### ISSUE TITLE
Standardise github labels

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1]
Using https://github.com/hadley/dplyr/labels as a template.

**Comment by jimhester** [comment]
Maybe we could think about incorporating the Difficulty and Effort labels from https://github.com/rich-iannone/DiagrammeR/labels?

I think they would be useful for potential contributors looking for a way to contribute, or for future planning for ourselves.

**Comment by hadley** [comment]
I really don't like how makes the issue page look — it's hard to see the issues themselves for all the labels.

**Comment by jimhester** [comment]
I think they went a little overboard with number of labels and you would need to choose quieter colors, but I think providing some guidance could be very beneficial to possible contributors

**Comment by hadley** [comment]
Implementation notes:

* Can use gh as it's now on CRAN (need to review other places where this could be used)
* API docs at <https://developer.github.com/v3/issues/labels/>
* Should create missing labels, and set colours
* Optionally delete default tags?
