### ISSUE TITLE
Allow forced pushes in pr_push

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/usethis#1007]
Would be nice...

**Comment by jennybc** [comment]
😨

**Comment by gaborcsardi** [comment]
Allowing a forced push would be great, because without that, if I do a rebase to master (which I guess people do quite often in PR branches) the branches will likely diverge, and then I am on my own at a miserable place. :(

**Comment by jimhester** [comment]
Ideally we would do a `--force-with-lease` rather than a `--force`, but I am not sure git2r supports the former.

**Comment by gaborcsardi** [comment]
There is no support for `--force-with-lease` in libgit2, either, AFAICT, so it will not be in libgit2 or gert anytime soon.

We could do it manually, though, i.e. get the remote refs, checks them, and/or ask the user, etc.

**Comment by jennybc** [comment]
We could create copy-pasteable git command to execute in the shell, as an initial step?

I'm not refusing to do this but it does make me a little queasy.

**Comment by jimhester** [comment]
I mean it is probably ok to just force push, it is just more dangerous. And yeah if we query the remote first and verify it is in the same state we could just do the check manually.

**Comment by hadley** [comment]
I think I'd rather leave this to the command line — our current workflow suggests avoiding rebases by using `pr_pull_upstream()` instead. I think rebasing PRs is now not great because we assuming that they're jointly editable by the PR author and the package maintainer.
