### ISSUE TITLE
use_lifecycle has a confusing instruction

### ISSUE THREAD

**Issue by jpritikin** [r-lib/usethis#1012]
When I run,

```r
use_lifecycle()
```
One of the instructions is:

```
Refer to functions with `lifecycle::fun()`
```

What does this mean? Functions in my package? So instead of `\link{foo}`, I should write `\link{experimental::foo}`??

**Comment by hadley** [comment]
This is just the standard boilerplate advice emitted whenever we add a package to `Import`.

To fix this we need some way to conditionally suppress the `how_to_use()` call when `use_package()` is called from another package. (And then inspect all calls to `use_package()` and verify whether or not this is needed)

**Comment by hadley** [comment]
Ooops that analysis was incorrect — we can just call `use_dependency()` instead.
