### ISSUE TITLE
pr_sitrep()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1013]
The new GitHub cli offers a pr status command. That seems like a good idea for both maintainer and contributor.

https://github.blog/2020-02-12-supercharge-your-command-line-experience-github-cli-is-now-in-beta/

**Comment by hadley** [comment]
Inlining the relevant image:

![](https://i1.wp.com/user-images.githubusercontent.com/10404068/74261502-34ae1380-4cb0-11ea-8baf-cf8248f1b222.png?ssl=1)

**Comment by jennybc** [comment]
I would definitely want to see local branches that I have previously worked with via `pr_*()`, on which I could use `pr_finish()` or a hypothetical `pr_resume()`.

We already label branches created by `pr_init()` and `pr_fetch()` with, e.g., `created-by = usethis::pr_init` in `.git/config`. So we can do this.

**Comment by hadley** [comment]
I'd particularly like to see all the branches with PRs and be able to close them en masse.

**Comment by jennybc** [comment]
I would say we have achieved the goals described here.

```
> pr_resume()
ℹ No branch specified ... looking up local branches and associated PRs
Which branch do you want to checkout? (0 to exit)
8 branches not listed: pr-resume-menu, foofy, holder, create-tidy, topepo-master, ... 

1:         github-diagnostics --> #1254 ('@jennybc'): GitHub diagnostics
2:                    linuxci --> #1236 ('@jeroen'): Test on multiple versions of Linux
3:   CorradoLanera-write_utf8 --> #1211 ('@CorradoLanera'): write_utf8()'s path
4:  cstepper-rstudio_snippets --> #1105 ('@cstepper'): edit_rstudio_snippets path
5: avalcarcel9-add_use_author --> #833 ('@avalcarcel9'): Add use author
6:                    pr-list
7:      testthat-improvements
8:            patch-for-withr
9:                   gitcreds

Selection: 
```
