### ISSUE TITLE
`use_*()` function for setting up rlang data pronoun

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/usethis#1016]
I'm not sure if this workflow is settled enough to encode it in usethis, but the [Using ggplot2 in packages](https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html) vignette suggests  using the `.data` pronoun from rlang for simple cases where you know the NSE variables you're going to reference. The vignette says:

> To avoid a similar note from the CMD check about `.data`, use `#' @importFrom rlang .data` in any roxygen code block (typically this should be in the package documentation as generated by `usethis::use_package_doc()`).

I think something like `use_data_pronoun()` that operates similarly to `use_tibble()` and `use_pipe()` (e.g. adding rlang as import, checking for a package doc, providing the roxygen code) would be helpful. Happy to make a PR if agreeable!

**Comment by hadley** [comment]
I think `use_tibble()` was probably a mistake; I don't think it's worth having a wrapper for importing a single fun. And `use_data_pronoun()` is very much in this vein, so I think I'd prefer not to add it — it creates a maintenance burden for us and saves very little effort.
