### ISSUE TITLE
Set RStudio defaults 

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1018]
https://blog.rstudio.com/2020/02/18/rstudio-1-3-preview-configuration/ — eg to not save/load workspace

**Comment by jennybc** [comment]
Yes, the day has finally arrived that we can do this 💥

**Comment by hadley** [comment]
```json
{
    "save_workspace": "never",
    "load_workspace": false,
}
```

**Comment by hadley** [comment]
And use in `use_blank_slate()`
