### ISSUE TITLE
FR: Return path from use_git_hook

### ISSUE THREAD

**Issue by csgillespie** [r-lib/usethis#1019]
It would be useful if `use_git_hook()` returned the hook path. This would require changing https://github.com/r-lib/usethis/blob/f53f0766af7da4ed234733fa6e218d97f2989020/R/git.R#L82 to
```
invisible(hook_path)
```
Happy to make a PR.

**Comment by hadley** [comment]
I think unfortunately this would make it inconsistent with other `use_` which should (generally speaking) return `TRUE` if they made some change and `FALSE` otherwise.
