### ISSUE TITLE
create_from_github() Error: New project '{repo name}' is nested inside an existing project 

### ISSUE THREAD

**Issue by jzadra** [r-lib/usethis#1020]
I'm getting this error when I try to `create_from_github()` and specify either my `~/Github` dir or '~/Github/repo_name`, where `repo_name` is a newly created, empty folder.

I previously forked this repo using Github, perhaps that is causing the error?  There is still a `github.com/myuser/repo_name` fork on github, could that be causing the issue?  I need to start from scratch because my fork is not syncing right after a PR I did, and the instructions for how to do PR's using RStudio are all years out of date and don't cover the fact that RStudio now has a branch feature. I'm about to start another PR for the same repo and have given up on fixing the fork I used previously.

**Comment by jennybc** [comment]
This error is about the local filesystem. And suggests that `~/` or `~/Github` looks like a project to usethis (so, really, to rprojroot). IME this means that some parent directory holds `.Rproj` file or a `.git/` directory.

Separately, I would go ahead and delete your existing fork, if you are hoping for a fresh start.

**Comment by jzadra** [comment]
Thanks Jenny!

Will `create_from_github()` attempt to create a fork with the same name as the original repo?

And also, while I have you here, will deleting my fork have any negative impact on the PR (that has been accepted) in terms of the linkages to commits / comments?

**Comment by jennybc** [comment]
> Will `create_from_github()` attempt to create a fork with the same name as the original repo on github?

usethis itself does not do any existence checking prior to the API call that says "make a fork". But, if memory serves, that command succeeds silently if you already have a fork and you are just left with your existing fork. However, in that case, at that moment, your fork isn't guaranteed to be synced up with the source repo the way that it is for a "fresh" fork. We do immediately `pull_upstream()` inside `create_from_github()` to hopefully guarantee that you are synced up, even if you have a pre-existing fork.

But given what you've said:

> because my fork is not syncing right after a PR I did

I would just blow it all away and start afresh. These problems are frequently seen when people do work on `master` of a fork, which is [basically never a good idea](https://happygitwithr.com/fork-and-clone.html#dont-touch-master).

This will not harm the content of an existing PR, as those commits actually live in a hidden branch on the target repo at this point. It probably does break some of the hyperlinks in the PR conversation.
