### ISSUE TITLE
use_github_actions() error

### ISSUE THREAD

**Issue by kevinushey** [r-lib/usethis#1023]
I saw this when trying to set up GitHub Actions on `renv`:

```
> usethis::use_github_actions()
✔ Setting active project to '/Users/kevinushey/r/pkg/renv'
✔ Creating '.github/workflows/'
✔ Writing '.github/workflows/R-CMD-check.yaml'
✔ Adding '^\\.github/workflows/R-CMD-check\\.yaml$' to '.Rbuildignore'
Warning: Package does not provide a GitHub URL.
Falling back to GitHub CRAN mirror
Error in names(res) <- c(attr(match, "capture.names"), ".text", ".match") : 
  'names' attribute [5] must be the same length as the vector [3]
```

Aside from the error, some other thoughts:

1. Should the requirement for a GitHub URL be documented? (Presumedly, it's expected to be found in the DESCRIPTION URL field?)

2. Assuming that's the case, it might be worth parsing the URL out of the BugReports field (since URL might be reserved for a pkgdown website, whereas BugReports often points to a GitHub issues page)

**Comment by hadley** [comment]
Does this still fail? If so, could you please provide a traceback?

**Comment by kevinushey** [comment]
I'm still seeing this:

```
> usethis::use_github_actions()
✔ Setting active project to '/Users/kevinushey/r/pkg/renv'
✔ Creating '.github/'
✔ Adding '^\\.github$' to '.Rbuildignore'
✔ Adding '*.html' to '.github/.gitignore'
✔ Creating '.github/workflows/'
✔ Writing '.github/workflows/R-CMD-check.yaml'
Warning: Package does not provide a GitHub URL.
Falling back to GitHub CRAN mirror
Error in names(res) <- c(attr(match, "capture.names"), ".text", ".match") :
  'names' attribute [5] must be the same length as the vector [3]
Traceback (most recent calls last):
11: usethis::use_github_actions()
10: use_github_action_check_release()
 9: use_github_actions_badge("R-CMD-check")
 8: glue("{github_home()}/workflows/{name}/badge.svg")
 7: glue_data(.x = NULL, ..., .sep = .sep, .envir = .envir, .open = .open,
        .close = .close, .na = .na, .transformer = .transformer,
        .trim = .trim)
 6: <condition-handler>(...)
 5: .transformer(expr, env)
 4: eval(parse(text = text, keep.source = FALSE), envir)
 3: eval(parse(text = text, keep.source = FALSE), envir)
 2: github_home()
 1: re_match_inline(gh_link, github_url_rx())
```

Looks like this is because `github_link()` fails:

```
> usethis:::github_link()
Warning: Package does not provide a GitHub URL.
Falling back to GitHub CRAN mirror

```

(note: `NULL` is returned above)

And this is because `github_home()` is invoked without the package argument here:

https://github.com/r-lib/usethis/blob/6522170d20c62d4d231631a4c379ba47b9421186/R/github-actions.R#L70-L71

**Comment by kevinushey** [comment]
`renv` does include a GitHub link in the DESCRIPTION, but not in the form that `usethis` seems to expect:

https://github.com/rstudio/renv/blob/f7db6478b34533d3f22213e5f3a3bc870df9dc3b/DESCRIPTION#L14-L15

**Comment by hadley** [comment]
Yeah, because we expect you to include the GitHub site after the pkgdown site. Looking in `BugReports` seems like a good idea. 

(Although I wonder here if we shouldn't be somehow be using the the git remote, but that probably requires some thought along the lines of #838 first; and is possibly related to #626)

**Comment by hadley** [comment]
Ok, took a stab at this in #1063 — now looks in remotes first (upstream, then origin), then falls back to BugReports then URLs.
