### ISSUE TITLE
Switch to travis-ci.com as default

### ISSUE THREAD

**Issue by riccardoporreca** [r-lib/usethis#1038]
With the [support for open source projects on travis-ci.com](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps), it is actually recommended to actually use travis-ci.com, especially for new repositories (https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/)

The suggestion here is to align the argument `ext` to `use_travis()` and friends to use `"com"` as default. Happy to contribute a PR.

**Comment by hadley** [comment]
Given that we're moving away from travis in favour of github actions, I think the only way we'd do this is through a PR 😄

**Comment by riccardoporreca** [comment]
@hadley: sure, the efforts towards github actions are highly appreciated ;)

PR coming soon...
