### ISSUE TITLE
create_from_github(): clone is successful but pulling changes fails due to authentication

### ISSUE THREAD

**Issue by jzadra** [r-lib/usethis#1045]
I'm following this guide: https://usethis.r-lib.org/articles/articles/pr-functions.html

I've successfully set up ssh (I think):

```
> libgit2_features()
$threads
[1] TRUE

$https
[1] TRUE

$ssh
[1] TRUE
```
```
> cred_ssh_key()
$publickey
[1] "/Users/u0982704/.ssh/id_rsa.pub"

$privatekey
[1] "/Users/u0982704/.ssh/id_rsa"

$passphrase
character(0)

attr(,"class")
[1] "cred_ssh_key"
```
```

> git_sitrep()
Git user
* Name: '***'
* Email: '***'
* Vaccinated: FALSE
usethis + git2r
* Default usethis protocol: 'ssh'
* git2r supports SSH: TRUE
* Credentials: '<usethis + git2r default behaviour>'
GitHub
* Personal access token: '<found in env var>'
* User: '***'
* Name: '***'
Repo
ℹ No active usethis project.
```

But when I call `create_from_github()` I get this error:

```
create_from_github("sfirke/janitor", destdir = "~/Github", credentials = cred)
✔ Creating '***/janitor/'
✔ Forking 'sfirke/janitor'
✔ Cloning repo from 'git@github.com:jzadra/janitor.git' into '***/Github/janitor'
✔ Setting active project to '***/Github/janitor'
✔ Adding 'upstream' remote: 'git@github.com:sfirke/janitor.git'
✔ Pulling changes from GitHub source repo 'upstream/master'
Error in git2r::fetch(repo, name = remref_remote(remote_branch), refspec = remref_branch(remote_branch),  : 
  Error in 'git2r_remote_fetch': error authenticating: 
✔ Setting active project to '<no active project>'
```

Versions:
R 3.6.0
git2r 0.26.1
usethis 1.5.1

**Comment by hadley** [comment]
You don't say what `cred` is, which I suspect might be the problem.

But we're planning to overhaul how usethis works with git in the neat future, and that's likely to resolve most problems, or at least provide more informative errors.

**Comment by jzadra** [comment]
I went through all the setup steps here: https://usethis.r-lib.org/articles/articles/pr-functions.html, including getting ssh set up and all the happy responses from `git_sitrep()` and other ssh checks.

The following solves the problem:

`use_git_credentials(git2r::cred_ssh_key())`

Is this expected behavior to have to run this every time?  GIven that there's no arguments given to run that, should it not be taken care of as the default if no credentials are provided explicitly?

**Comment by hadley** [comment]
No it's not. As I said, we are revamping this code and expect it to be better in the future.
