### ISSUE TITLE
create_project() does not follow Global Options Code Saving Setting

### ISSUE THREAD

**Issue by jimmyg3g** [r-lib/usethis#1077]
In RStudio, Tools > Global Options > Code > Saving, I do not check the `Strip trailing horizontal whitespace` when saving option. When I create a new project via `usethis::create_project()`, the global option is ignored and it is selected in the new project's Project Options.

**Comment by hadley** [comment]
The intent of usethis is to create projects that are as consistent as possible from one user to another, so I don't think we plan to respect your individual RStudio global options at this time.
