### ISSUE TITLE
Extend `use_test` to support writing tests for files in `src/`

### ISSUE THREAD

**Issue by rundel** [r-lib/usethis#1079]
It seems like a reasonable use case to support writing testthat tests for exported functions from `src/` and not restrict things just to scripts in `R/`. This is currently being handled by the `get_active_r_file` functions which supports only files in `R/` with `r` or `R` extensions.

**Comment by hadley** [comment]
@jimhester might have thoughts on this

**Comment by jimhester** [comment]
I am not opposed to this in principle, but if we decided to do this it would require changes in usethis and support in `devtools::test_file()` and `devtools::test_coverage_file()` as well.

I am unsure if it is worth the extra complexity or not...

**Comment by hadley** [comment]
It seems unlikely that this will ever rise to the top of our todo lists, so I'm going to close. But we're not fundamentally opposed, and we'd definitely review a PR.
