### ISSUE TITLE
Work draft PRs into the pr_*() flow

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1090]
Workflow described by @DavisVaughan:

- `pr_init()`
- Do some commits, get it working locally
- `pr_push()` and open a draft pr. This lets you see CI but doesnt notify anyone
- Continue work and routinely `pr_push()` to trigger CI
- Switch from draft pr to real pr *Jenny: maybe we facilitate this? also easy to do in browser*
- Now get a review from collaborators and merge
- `pr_finish()`

Context: he's not a big user of `pr_init()` and part of the reason is he wants to work on the branch more quietly until he's ready for review. So making an early WIP PR is not attractive, which `pr_push()` pushes you towards, but maybe draft PR is a good compromise.

**Comment by hadley** [comment]
That's also the workflow that I use. So I don't think it needs any new code?

**Comment by jennybc** [comment]
Yeah I just did an experiment. I thought we initiated the PR via an API call, but it's actually accomplished just by visiting a constructed URL. So we can't add something like `draft = TRUE`.

@DavisVaughan I think you should just take advantage of this drop down menu when creating the PR after `pr_push()`. Or decline to create the PR in the first place. `pr_push()` still does the push to a PR-able branch and the tell-tale annotations are still left behind in `.git/config` that will give you nicer clean up behaviour when you use `pr_finish()`.

<img width="475" alt="Screen Shot 2020-04-06 at 9 10 21 AM" src="https://user-images.githubusercontent.com/599454/78580117-ce90c900-77e6-11ea-979e-f63380eeeb77.png">

So, at most, this might be a documentation issue. But I'm going to close.
