### ISSUE TITLE
`use_data(..., internal = TRUE)` should consider an `add` option

### ISSUE THREAD

**Issue by CorradoLanera** [r-lib/usethis#1091]
Internal data are all stored in a single file `R/sysdata.rda`. For packages developed over time or which includes many datasets, it could be useful to include an option `add` to `use_data()` that can be activated (and have effect only) when `internal = TRUE`.

That would permit developers of the package to add internal data to the package as the package grown, without the needs to rerun all the setup scripts and without the need to include all of their code in single script with a single call of `use_data(..., internal = TRUE)` at its end.

```r
# 20200304-internal.R
# internal data that can be processed on 2020-03-04 only

20200304_data <- mtcars

usethis::use_data(20200304_data,
  internal = TRUE
)
```

```r
# 20200404-internal.R
# internal data that can be processed on 2020-04-04 only
# (without possibility to re-run 20200304-internal.R)
# (saving this code on its own file)

20200404_data <- iris

usethis::use_data(20200404_data ,
  internal = TRUE,
  add = TRUE
)
```

**Comment by CorradoLanera** [comment]
Or `usethis::use_data(..., internal = TRUE)` could check if `R/sysdata.rda` is already present. In that case (only), it could ask if you want to replace or add the current data with or to the current ones.

**Comment by jennybc** [comment]
I suppose this is technically possible, but I'm not sure we'd do it.

I think there are maintainer workflows that basically design this problem away and that might have some advantages. If there are, say, n scripts below `data-raw/`, each producing an object destined to be internal data, they should probably each write their discrete result somewhere (maybe as `.rds`). Then there could be one "marshalling" script that gathers all of those objects and writes `sysdata.rda`. This has the happy effect of leaving a very self-explaining situation behind and forces the holistic management of everything inside `sysdata.rda`.

**Comment by CorradoLanera** [comment]
Thanks for the suggesting workflow, I will adopt it (in the meanwhile :-) ) 👍 

(.buildignoring, but not .gitignoring, `data-raw.*\.rds`)

**Comment by jennybc** [comment]
Yeah, any package that uses the `data-raw/`strategy to keep track of how package data gets created/updated should Rbuildignore it. `use_data_raw()` always sets it up this way.

I'm going to close this as I really think managing internal data in a more explicit and holistic way is safer. I don't think you want to  keep adding to an existing `sysdata.rda` without being "gently encouraged" (forced?) to know where all of the contents are coming from and how they are created.
