### ISSUE TITLE
With un-pushed branch pr_sync() errors ungracefully

### ISSUE THREAD

**Issue by maurolepore** [r-lib/usethis#1097]
With a branch I didn't push, `pr_sync()` throws uninformative message. Instead I expected an error like:

```
x Can't find a remote branch to sync
* Did you forget to run `pr_push()` before `pr_sync()`?
```

(I often `pr_init("a-branch")`, then work for long enough to forget if I run or not `pr_push()`. So when I fail to `pr_sync()` and get the current error message I can't immediately see what the problem and solution might be. I fear this may discourage those who need the most help from the `pr_*` family.)

``` r
packageVersion("usethis")
#> [1] '1.5.1.9000'
usethis::pr_init("branch-i-didnt-push")
#> ✓ Setting active project to '/home/mauro/git/r2dii.match'
#> ✓ Checking that local branch 'master' has the changes in 'upstream/master'
#> ✓ Creating local PR branch 'branch-i-didnt-push'
#> ✓ Switching to branch 'branch-i-didnt-push'
#> ● Use `pr_push()` to create PR
usethis::pr_sync()
#> ✓ Pulling changes from GitHub PR
#> Error in git2r::fetch(repo, name = remref_remote(remote_branch), refspec = remref_branch(remote_branch), : Error in 'git2r_remote_fetch': 'name' must be a character vector of length one with non NA value
```

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
Yeah, that's ugly.
