### ISSUE TITLE
Support proprietary packages with new function use_file_license

### ISSUE THREAD

**Issue by antoine-sachet** [r-lib/usethis#1111]
Feature request: It would be nice to have a proprietary license option.

I know, I know, I wish I could only write open-source software but in reality most of my packages (e.g. internal shiny apps) are proprietary. I imagine this extends to the majority of R devs in the industry.

`usethis::use_file_license('Evil Corp')` would simply create:

DESCRIPTION
```
License: file LICENSE
```

LICENSE
```
YEAR: 2020
COPYRIGHT HOLDER: Evil Corp
```

**Comment by antoine-sachet** [comment]
On second thoughts, it should be more obvious that using only a file LICENSE results in a proprietary package. Perhaps `use_proprietary_license` is more appropriate.

The file LICENSE could also contain "All rights reserved". I am aware this disclaimer is superfluous but it has the advantage of avoiding any doubt.

```
YEAR: 2020
COPYRIGHT HOLDER: Evil Corp
All rights reserved.
```

**Comment by jennybc** [comment]
I'm going to close this and #1112, but in principle this is a good PR and this is something we want to do but we're going to track it in #1163.

If you're still game, will you please make a new PR against #1163 and specifically base it on:

https://unconj.ca/blog/copyright-in-closed-source-r-packages-the-right-way.html

Can you also look at the changes I made in #1112 and port them over when/if you make a new PR?
