### ISSUE TITLE
FR: `browse_package()`

### ISSUE THREAD

**Issue by pat-s** [r-lib/usethis#1113]
I often find myself in the situation wanting to browse the pkgdown site of a package rather than its GitHub or CRAN site.

I am currently using `browseURL(desc::desc_get_urls()[1])` for this which opens the pkgdown site if it exists in the URL field and comes first. If missing, the GitHub page is opened. If no URL field exists, it errors obviously.

Some pkgs do not have a URL field at all and while `usethis::browse_github()` already falls back to `usethis::browse_cran()`, I have the feeling that a wrapper function like `browse_package()` could be helpful.

Essentially it would try to look for a pkgdown page first, fall back to the GitHub page and last to the CRAN page.

**Comment by jennybc** [comment]
My usual workflow for this is to `browse_github()` and hope the maintainer has put the pkgdown site as the repo's URL. Adding this as another method for determining where to go.

**Comment by hadley** [comment]
I think you should just open the first url that is not a GitHub url — the first url should normally be the package url anyway.
