### ISSUE TITLE
`proj_line_ending()` breaks `write_utf8()` when executed outside of the target project

### ISSUE THREAD

**Issue by CorradoLanera** [r-lib/usethis#1125]
If you use `write_utf8()` (possibly through the `write_over()` exported function) to write programmatically from outside of any project (eg opening RStudio and selecting "close project", ie "Project: (none)" appear in the top-right corner) to a file which is into a project, the function possibly fails with the following error:

```r
Error: Path 'C:/Users/<user name>/Documents/' does not appear to be inside a project or package.
```
Note: if the call was run from inside a project which is not the one of the target file, it (re-)activate the current project.

The error is caused because of [here](https://github.com/r-lib/usethis/blob/master/R/write.R#L104) `write_utf8()` checks for `possibly_in_proj(path)` but in the following line ([here](https://github.com/r-lib/usethis/blob/master/R/write.R#L105)) it calls `proj_line_ending()` without passing that `path` to it.
In fact, `proj_line_ending()` does not have any arguments, but when [here](https://github.com/r-lib/usethis/blob/f5eb0e3240a50a9d757e1825b860475decae6dbf/R/line-ending.R#L3) it calls `project_name()` without any arguments, `project_name()` assign to its argument `base_path` the default value `proj_get()` ([here](https://github.com/r-lib/usethis/blob/1f4de552c8bd5238c6ec325f901ab9b546afe3d8/R/proj.R#L248)). Now, if we have called `write_utf8()` from inside a project, the returned name is that project name (which is the wrong one in this case), while if we are not in a project at all, it returns `proj_set(".")` ([here](https://github.com/r-lib/usethis/blob/1f4de552c8bd5238c6ec325f901ab9b546afe3d8/R/proj.R#L57)), which calls `proj_set(".")` ([here](https://github.com/r-lib/usethis/blob/1f4de552c8bd5238c6ec325f901ab9b546afe3d8/R/proj.R#L57)) because outside of a project, and possibly returns the mentioned error because (normally) outside of any project `"."` is `"~"`.

My purposed solution is to add the same default argument of `proj_name()` (ie `base_path = proj_get()`) to `proj_line_ending()`. Next, pass `base_path` into its call to `proj_name()`. Ie updating `proj_line_ending()` to

```r
proj_line_ending <- function(base_path = proj_get()) {
  # First look in .Rproj file
  proj_path <- proj_path(paste0(project_name(base_path), ".Rproj"))
  if (file_exists(proj_path)) {
    config <- read_utf8(proj_path)

    if (any(grepl("^LineEndingConversion: Posix", config))) {
      return("\n")
    } else if (any(grepl("^LineEndingConversion: Windows", config))) {
      return("\r\n")
    }
  }
```
This way every call to `proj_line_ending()` (ie without explicit arguments) should not change it previous behaviour.

Next, update `write_utf8` [here](https://github.com/r-lib/usethis/blob/400306aabedd01710559aa5f4984754191c28dde/R/write.R#L105) to

```r
write_utf8 <- function(path, lines, append = FALSE, line_ending = NULL) {
...
   if (possibly_in_proj(path)) {
      line_ending <- proj_line_ending(path)
    } else {
...
}
```

**Comment by jennybc** [comment]
I haven't digested all of the above because I'm holding a path problem in my head, but a quick comment.

It is with great reluctance that `write_over()` and the like are even exported. We do it to help people extend usethis for, e.g., a specific company or lab group. But that hypothetical domain-specific usethis still follows the main conventions of usethis.

I regard "working inside a project" as the main principle of usethis. So I'm not terribly concerned about making `write_over()` do the "right thing" outside a project or when project A is active but we address a file a project B.

There is a related section in the package principle doc:

https://github.com/r-lib/usethis/blob/master/principles.md#helper-functions

As I said above, I didn't digest your whole comment yet. But hopefully you can figure out if your proposal is consistent with these principles. My hunch is no. But if yes, this should help you figure out how to motivate it.

**Comment by CorradoLanera** [comment]
Thank you @jennybc and sorry if I reported the issue not clearly.
I have read helper-functions' principles and I think that the problem highlights exactly something against one of them: 
[Current mindset: helpers should not make direct use of the active project, i.e. project-based paths should be formed by the caller.](https://github.com/r-lib/usethis/blob/master/principles.md#helpers-and-the-active-project).

The main problem is that `write_utf8` check if `path` is a proj (hence, it suppose `path` could be not "the current project"...), but next it does not pass it to `proj_line_ending()`.

[current implementation:]
```r
write_utf8 <- function(path, lines, append = FALSE, line_ending = NULL) {
...
   if (possibly_in_proj(path)) {
      line_ending <- proj_line_ending()
    } else {
...
}
```

So, if "the current project" is not `path`,  `proj_line_ending()` possibly returns the wrong `line_ending` (because it returns the "current project" one and not the `path` project one), while if "the current project" is not a project, it returns an error.

That is the problem. Now, I can try to explain better its source and the purposed solution (which do not break things nor activate additional functionalities but fix the issue only)

This happens because `proj_line_ending()` calls in its first line `project_names()` without any arguments (and hence `project_names()` set its argument `base_path` to the default `proj_get()`, which by design return `proj_set(".")`, ie "the current project"!)

[current implementation:]
```r
proj_line_ending <- function() {
  proj_path <- proj_path(paste0(project_name(), ".Rproj"))
  ...
}
```


The solution consists only to make `write_utf8` works as I think it is designed to:

[purposed change:]
```r
write_utf8 <- function(path, lines, append = FALSE, line_ending = NULL) {
...
   if (possibly_in_proj(path)) {
      line_ending <- proj_line_ending(path) # adding this `path`
    } else {
...
}
```

to make it possible it is sufficient to 

[purposed change:]
```r
# add `base_path = proj_get()` do not change anything
# because it is already the default
proj_line_ending <- function(base_path = proj_get()) {
  # passing `base_path` to `project_name` solve the issue.
  # note: a call to `proj_line_ending()` (without arguments as before)
  # behave exactly as before (`base_path = proj_get()` is the default
  # in `project_name()`.
  proj_path <- proj_path(paste0(project_name(base_path), ".Rproj"))
  ...
}
```

PS: I get the error exactly from a call to `use_template()` ([here](https://github.com/CorradoLanera/devubesp/blob/master/R/create.R#L113)).

**Comment by hadley** [comment]
@CorradoLanera I don't understand the problem or solution either. I think the problem is that you're using text to attempt to explain the solution when a PR would be much easier to understand.

**Comment by jennybc** [comment]
I understand the problem now, because I've bumped up against it, while doing some other work.

But I think I will have a different solution than #1211. Stay tuned.
