### ISSUE TITLE
template.Rproj not consitent with RStudio

### ISSUE THREAD

**Issue by and3k** [r-lib/usethis#1130]
Hi!

when I use create_project()/create_package()/use_rstudio() it creates a Rproj file from https://github.com/r-lib/usethis/blob/master/inst/templates/template.Rproj. But when I then re-open the project, RStudio seems to update the Rproj file to include options that were not set in the template file. Here is a diff of the use_rstudio() output vs what RStudio updates it to.

```diff
@@ -5,8 +5,13 @@ SaveWorkspace: No
 AlwaysSaveHistory: Default
 
 EnableCodeIndexing: Yes
+UseSpacesForTab: Yes
+NumSpacesForTab: 2
 Encoding: UTF-8
 
+RnwWeave: Sweave
+LaTeX: pdfLaTeX
+
 AutoAppendNewline: Yes
 StripTrailingWhitespace: Yes
 LineEndingConversion: Posix
```
I am using a up to date RStudio on a fresh Ubuntu install.
 
Would be great if the template would already create a file that is not modified by RStudio again :)

Thanks!
Bela

**Comment by jennybc** [comment]
@jmcphers Do you have any advice for me? We (in the form of usethis) have a few opinions about the `.Rproj` file (specifically around line endings), but what I'd really like to do is merge/overlay them with some base `.Rproj` file. Is anything like that possible?

**Comment by hadley** [comment]
We could instead start with `rstudioapi::initializeProject()` and then overlay the usethis defaults. The problem is that we don't have any easy way to modify a DCF file while preserving existing formatting. So implementing this would be quite a lot of work, and TBH I quite like the fact that I can see the changes that RStudio makes to the standard template. All-in-all, I'm leaning towards saying that this change probably isn't worth the implementation cost.

**Comment by jennybc** [comment]
I just created a project with `create_project()`, which then opens in a fresh RStudio instance. Then I do `use_git()` and say "yes" to the offer to commit a bunch of files, including `.Rproj`.

I don't ever encounter this git diff that is the difference between our `.Rproj` template and what RStudio does to it upon first launch. Nor do I see it if I close that project and relaunch it.

I don't deny you see it @and3k but I suppose it comes about via a less-used workflow (?). In any case, it seems fairly harmless and the visibility of the change could even be regarded as a good thing.

I choose to leave things as is. Maybe one day we'll get a better API for manipulating `.Rproj` files, but for now, I'd like to do as little of it as possible.
