### ISSUE TITLE
Very confusing question to user: "not now" vs "absolutely not"

### ISSUE THREAD

**Issue by daattali** [r-lib/usethis#1132]
After running `usethis::use_git()` I got a message:

```
Is it ok to commit them?

1: Yeah
2: Not now
3: Absolutely not
```

I can't tell the difference between options 2 and 3. Is there a difference? This message is very confusing.

Using usethis v1.5.1

**Comment by daattali** [comment]
Update: after selecting "Yeah", I got an equally confusing message

```
Selection: 1
✔ Adding files
✔ Commit with message 'Initial commit'
● A restart of RStudio is required to activate the Git pane
Restart now?

1: I agree
2: No
3: Absolutely not
```

**Comment by jennybc** [comment]
These are deliberate speed bumps to keep people from cruising through such choices on auto-pilot, without giving it some thought.

I think in each case, if you know you want to answer YES or NO there's always an option that will clearly grant your wish. But yes, it is true that there are always 3 options, 2 forms of yes and 1 form of no (or *vice versa*).

**Comment by daattali** [comment]
Ah I see. IMO having multiple options that mean the same thing isn't as much a speed bump as it is confusing. I mean, by being confusing it *also* has the effect of slowing me down, but even after slowing down and thinking, I'm still left confused and not sure why there's two different "no" options and whether they have different meanings.

In my case, I was thinking maybe "not now" means "not right now, but ask me again" and "absolutely not" means "never ask me and put these in a .gitignore". That's obviously very far from correct :)

I should make a confession that I don't use `usethis` otherwise, so maybe this is a convention and anyone using `usethis` is familiar with this. But for a first time user of this, it left me thinking there's a bug in the message system -- do you you choose with this information :)

**Comment by jennybc** [comment]
I think we've worn most regular users of usethis down at this point, yes 😄

Refining the different forms of YES and NO is a recurring topic and we've done quite a bit of refining already over the years. For example, for reasons of decorum and professionalism, I was prevailed upon to remove "HELL NO", which still makes me a bit sad.
