### ISSUE TITLE
Error message from github_user() is concealed

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/usethis#1133]
`github_user()` catches and throws away all errors, and assumes that the problem is with your GH token, but that is not always the case, and then the error message about the token is very misleading. Maybe it could also show the actual error message?

**Comment by gaborcsardi** [comment]
The gh package failed to load for me, because of some broken dependency.

**Comment by jennybc** [comment]
Maybe we can take advantage of the fact that gh throws a classed error.

https://github.com/r-lib/gh/blob/master/R/gh_response.R#L42

**Comment by jennybc** [comment]
Existing relevant checks in `git_sitrep()`:

https://github.com/r-lib/usethis/blob/0144ea1044797604ca97997c7f4be964e2fec30c/R/git.R#L503-L520
