### ISSUE TITLE
use_make template query

### ISSUE THREAD

**Issue by tjtnew** [r-lib/usethis#1138]
Experimenting with `use_make` and I'm wondering if the `build:` line in the template should have `install_deps` as a dependency.  Currently the default will error if a build dependency is missing on the users system. `install_deps` can then be removed as a dependency from the `install` target.

**Comment by jennybc** [comment]
@ryapric Would you take a look at this, as the original contributor (and, I hope, continuing user) of the `use_make()` functionality? I do not use it myself.

**Comment by ryapric** [comment]
Sure!

@tjtnew can you provide a reprex showing what you mean? The `install_deps` currently runs before the `build` target when you call `make install`, so the full order when just calling `make install` is `install_deps -> build -> install`. Unless I'm misunderstanding?

The `build` target itself shouldn't need to worry about dependencies being installed, as it just (successfully) bundles the package source itself, for either distribution or `R CMD INSTALL`-ing. It's the `install` target that would then need to worry about deps on the target host.

However (as a separate, R issue), I *do* notice now that `R CMD INSTALL` seems to do nothing in the way of installing dependencies, which is confusing. It looks like CRAN handles that when you install *remotely* with `install.packages()`, not locally. Again, unless I'm mistaken. Hmm.

**Comment by tjtnew** [comment]
@ryapric I could definitely be wrong but by default`R CMD build` will try to build vignettes.  So when the build target runs if a package is missing that is used in a vignette then it will fail.  Tricky to describe a reprex:  Possibly use `pkgkitten` to generate a minimal package then alter the vignette to use a made up package.

**Comment by jennybc** [comment]
> Tricky to describe a reprex: Possibly use pkgkitten to generate a minimal package then alter the vignette to use a made up package.

Can you provide either code to create the scenario that troubles you or make a toy repo? If you are encountering this problem, you should be able to provide a concrete demo.

**Comment by tjtnew** [comment]
I say tricky as it would involve a verbal description and necessitate you deleting a possibly installed package from your system. I'm happy for you to close if the detail given is not enough.

**Comment by tjtnew** [comment]
The example below does install and uninstall packages to illustrate the issue.  Please check the code before you run to make sure you are happy with it.
```
install.packages(c("pkgKitten", "usethis", "dplyr"))

# create toy package that imports dplyr
pkgKitten::kitten()
setwd("anRpackage")
use_package("dplyr")

# add vignette with a call to load dplyr
use_vignette("example")
write(
"```{r}
library(dplyr)
````",
"vignettes/example.Rmd",
append = TRUE
)

# ensure dplyr is not installed to see the issue
remove.packages("dplyr")

# use makefile
usethis::use_make()

# run make without dplyr installed and it will fail
system2("make")

# install dplyr and it will run
install.packages("dplyr")
system2("make")
```

**Comment by ryapric** [comment]
Ah, I gotcha. Really what this outlines, though, is the difference between *build-time* dependencies and *install-time* dependencies.

However, now looking at the docs for `remotes::install_deps()`, I see there's space to instead add another target for just the build deps, and associate prereqs with the right targets. So let me see what I can do in a PR for that.

**Comment by hadley** [comment]
@ryapric @tjtnew could either of you please check my work in #1279?

**Comment by tjtnew** [comment]
@hadley lgtm

**Comment by ryapric** [comment]
That still doesn't solve the bigger issue I raised above, but it solves OP's directly, I suppose. I'll still try and find time to submit a more robust fix.

**Comment by hadley** [comment]
@ryapric ah sorry, I missed that. But I'm not sure there's a great deal of point distinguishing between build time and run time dependency in this scenario, since presumably anyone running the make file will be a developer?

**Comment by ryapric** [comment]
No that's a fair point, as well. Differentiating between build-time vs. run-time would just cover more personas, but the predominant user base for this Makefile would almost certiainly be developers.

If it comes up again somewhere else, I'll crack it open at that point. Thanks!
