### ISSUE TITLE
Unable to edit_r_profile("project") due to proj_active returning unexpected NULL value

### ISSUE THREAD

**Issue by leungi** [r-lib/usethis#1139]
As per subject, project is set up with an .Rproj, and its own .Rprofile.

However, `usethis` is unable to detect it.

Notes:

- actual .Rproj is located in a network drive (i.e., P:/)
- .Rproj used is located locally (i.e., C:/), with an .Rprofile such that it links to the project folder in network drive
- this set up is to reduce latency seen in .Rproj, if accessed directly via network drive

``` r
library(usethis)

edit_r_profile("project")
#> Error: [EPERM] Failed to realize 'P:/project/enersight_type_curve/.': operation not permitted

usethis:::proj_active()
#> [1] FALSE
```

<sup>Created on 2020-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
I think this is a problem being tracked at https://github.com/r-lib/fs/issues/147. usethis has a hard policy on using fs for all path handling. You might want to read through that thread and see if you can contribute any insights or instructions to make it easy for @jimhester to replicate and get a handle on. It looks like there might also be a proposed workaround that you could test and report back on.

**Comment by leungi** [comment]
Thanks for pointer and reference @jennybc; will heed your advice and study that issue.

**Comment by leungi** [comment]
This [suggestion](https://github.com/r-lib/fs/issues/147#issuecomment-532204081) and [patch](https://github.com/bjcairns/fs/wiki/Solving-network-drive-%22operation-not-permitted%22-errors-(r-lib-fs%23147)) from @bjcairns solves it 🙌🙏
