### ISSUE TITLE
create_from_github should not assume authentication.

### ISSUE THREAD

**Issue by cboettig** [r-lib/usethis#114]
Minor issue from #109

Currently, `create_from_github()` will throw an opaque error if the user has not put a valid `GITHUB_PAT` environmental variable, since without authentication the API will not return a `permissions` chunk.  If any behavior doesn't need auth, then it should work without this, otherwise, it should be documented that you should set `GITHUB_PAT` as an env var, and the function should probably have an argument to specify the token directly, consistent with `use_github()` etc.

**Comment by jennybc** [comment]
reprex

``` r
library(withr)
#> Warning: package 'withr' was built under R version 3.4.3
library(devtools)
library(usethis)

with_envvar(
  new = c(GITHUB_PAT = NA, GITHUB_TOKEN = NA),
  code = create_from_github("r-lib/usethis", path = tempdir())
)
#> Error in !repo_info$permissions$push: invalid argument type
```

Created on 2017-12-26 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by jennybc** [comment]
I think the idea is you are supposed to say `fork = FALSE` in this case, but I agree we have some flow/UI problems in this function.

``` r
library(withr)
#> Warning: package 'withr' was built under R version 3.4.3
library(devtools)
library(usethis)

with_envvar(
  new = c(GITHUB_PAT = NA, GITHUB_TOKEN = NA),
  code = create_from_github("r-lib/usethis", path = tempdir(), fork = FALSE)
)
#> ✔ Cloning repo
#> ✔ Opening project in new RStudio instance
```

Created on 2017-12-26 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by jennybc** [comment]
I renamed this issue to reflect what I can actually fix in this release. Everything else was moved into #214 (GitHub connectivity) and #215 (`create_from_github()` should share many arguments with `use_github()`).
