### ISSUE TITLE
Feature request: allow to add licenses to non-package projects

### ISSUE THREAD

**Issue by nuest** [r-lib/usethis#1140]
When setting up a (non-package) project, I repeatedly have to google for well formatted plain text versions of software licenses. It would be great if the `use_xx_license()` functions would not be limited to package projects, but allow to skip the [`check_is_package(..)` step](https://github.com/r-lib/usethis/blob/master/R/license.R#L42).

Current:

```r
> setwd(tempdir())
> usethis::use_mit_license(name = "Test")
Error: Path '/tmp/Rtmp7uX3Yq/' does not appear to be inside a project or package.
In addition: Warning message:
In path_file(base_path) : restarting interrupted promise evaluation
```

Desired:

```r
> setwd(tempdir())
> usethis::use_lgpl_license(name = "Test", check_project = FALSE)
File LICENSE.md created.
```

Alternatively, exposing the `use_license_template()` function and a list of allowed names, or some clever regexing on the names, could also be an option. However, this would prohibit special cases, such as the year-copyright file for MIT.

```r
# some ideas
usethis::list_templates(type = "license")
usethis::list_license_templates()

# with some magic
usethis::use_license_template("Apache")
```

**Comment by nuest** [comment]
Forgot to mention: I'm happy to contribute this feature, if you think it fits!

**Comment by hadley** [comment]
I did this as part of a general rewrite of the licensing functions — now if you're not in package they'll just create a `LICENSE.md` but won't attempt (and fail) to modify `DESCRIPTION`.

**Comment by nuest** [comment]
Thanks!
