### ISSUE TITLE
Behaviour of `pr_pull_upstream`

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#1146]
If I understood correctly `pr_pull_upstream` uses origin/master if there isn't a upstream remote on the repository:

https://github.com/r-lib/usethis/blob/be21e412498a6a47f6638a636d5eacf9e3531dd0/R/pr.R#L272 

This is convenient for the maintainers of packages but for contributors not much. From the perspective of a contributor I wanted to update my forked repository with the upstream changes but I hadn't set up the upstream repository (yet) so I needed to find out what happened and add the repository I wanted to contribute to.

I would expect a warning or a todo point to add the upstream repository. This could be ignored by maintainers of the repositories but useful for contributors.

**Comment by jennybc** [comment]
I am in the process of overhauling all things git and GitHub related.

That being said, the GitHub functions in usethis are definitely designed as a unit. For example `create_from_github()` will (1) fork-and-clone and (2) set up the `upstream` remote. So, to a certain extent, we  assume a specific setup.

I have found it's very hard to anticipate all possible initial conditions. But yes, as I renovate, I am trying to give better hints about how to fix a suboptimal or unsustainable setup.

**Comment by jennybc** [comment]
Once #1144 is merged, the `pr_*()` functions check explicitly for specific GitHub remote configurations and, if found lacking, suggest remedies.

**Comment by jennybc** [comment]
This function is also being renamed to `pr_merge_main()` (although the previous name `pr_pull_upstream()` still works for now).

**Comment by llrs** [comment]
Wow, huge PR! Hadn't had time to check it out (and not sure I'll be able) but if suggestions are made that solves the issue for me. Thanks for the heads up on the renaming.
