### ISSUE TITLE
Add edit_rstudio_prefs?

### ISSUE THREAD

**Issue by boshek** [r-lib/usethis#1148]
Would an `edit_rstudio_prefs` function be useful here?

Here is a minimal function that might be a start cribbed heavily from `edit_r_profile`:

```r
edit_rstudio_prefs <- function(){
  if( .Platform$OS.type == "windows") {
    path <- glue::glue("{Sys.getenv('APPDATA')}\\RStudio\\rstudio-prefs.json")
  }
  
  if( .Platform$OS.type == "unix") {
    path <- "~/.config/rstudio/rstudio-prefs.json"
  }
  
  usethis::edit_file(path)
  usethis::ui_todo("Restart RStudio for changes to take effect")
  invisible(path)
}

edit_rstudio_prefs()
```

Just trying to gauge whether there is interest in working on this to include into `usethis`.

**Comment by jennybc** [comment]
Yeah now that RStudio affords better control over all of this, we will definitely take advantage. I haven't given it any specific thought yet, personally.

Existing function that is also relevant: `use_blank_slate()`. In the past, we couldn't really do much exciting there -- which is to change this at the user level (vs. project) only -- but now I think we can.

**Comment by jennybc** [comment]
Note we would never want to hardwire any more path logic than we have to. I'd rather ask rstudioapi where it keeps it config file. Which is an existing request of mine:

https://github.com/rstudio/rstudioapi/issues/176

**Comment by jennybc** [comment]
Maybe we can use rappdirs to get around the path problem, since RStudio >= 1.3 complies with the XDG base directory standard for configuration data:

https://github.com/r-lib/rappdirs
