### ISSUE TITLE
Check licenses restrictions/compatibility on use_package

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#1151]
Some licenses have more restrictions than others, so they might end up blocking some uses. If a package with a more restrictive license is used by another package and is distributed there is a potential point of conflict (specially in commercial settings). Perhaps this could be checked on `use_package`?

I think it would help users if we got (at least) a warning if the licenses are incompatible and nothing if they are ok. This could be restricted to approved licenses as it is now and if there is a custom license a message should appear to make the user check if the license are compatible. 

This image ([from FOS](https://opensource.stackexchange.com/a/3)) can be helpful to determine if the code is compatible, together with the section [4.1.2 Dependencies in DESCRIPTION](https://thinkr-open.github.io/licensing-r/rlicense.html#4.12) of Licensing R from Colin Fay:
![](https://i.stack.imgur.com/k1G9Z.jpg)

**Comment by jennybc** [comment]
I'm afraid that sounds way too difficult for us to tackle in `use_package()`. We're going to stick with editing the file and doing some internal-to-DESCRIPTION sanity checks. I think even CRAN does all of its license vetting manually / human-ly.
