### ISSUE TITLE
[Feature request] Automate configuration of Rtools40 on Windows

### ISSUE THREAD

**Issue by GegznaV** [r-lib/usethis#1152]
Could **usethis** automate the configuration of RTools40 on Windows (described on https://cran.r-project.org/bin/windows/Rtools/)? The function should check if `"~/.Renviron"` file exists, if yes, should check if a line with the following code is present:

```r
PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"
```

If the file is missing or the line of code is missing, the line should be added **without removing** any content that is already present in `"~/.Renviron"`  file.

**Comment by hadley** [comment]
I don't believe this is necessary if you use devtools (which is what usethis is designed to be paired with). @jeroen can you confirm?

**Comment by jeroen** [comment]
Indeed, pkgbuild and rstudio will automatically find the toolchain. The config is only needed for vanilla base r.

**Comment by hadley** [comment]
So I think that makes it out of scope for usethis, because we generally believe it's better to just temporarily adjust the path as needed. That makes it easier to work with multiple versions of R.
