### ISSUE TITLE
Creating License files when filling from usethis.description option

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#1158]
I've stored in my .Rprofile an option for `usethis.description`:

```r
usethis.description = list(...,
		License = "MIT + file LICENSE",
        ...)
```
When I created a new package (via rstudio new project R package from devtools) I saw the description included it. However, I didn't see it populated with the LICENSE and LICENSE.md files I would get if I used `use_mit_license()`. 

Maybe it can be added that if there is an option of `usethis.description$License`, to run the appropriate `use_*_license()` (if possible) to create those files. It will make it easier to not forget them. 

Probably related to #159 but I don't have set up options for devtools, only for blogdown and Ncpus.

**Comment by hadley** [comment]
I think this is out of scope for usethis; if you always want this, I'd recommend create a small wrapper around `create_package()`.
