### ISSUE TITLE
Automatic replacing of the lifecycle badge

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#1159]
The `use_lifecycle_badge()` is intended to report the state of the package and it can change more often than other badges (thinking now on the move from travis to github actions...) .

Recently I have archived an experimental package and to my surprise the new badge was added instead of replacing the existing lifecycle badge. 

It would be nice if there was an option to override an existing badge with the new lifecycle stage. The default could be TRUE and if not found any badge to replace then add it.
 
This would mean finding if there is an old badge and then placing the new badge there. Perhaps it could be easily done with a couple of regex as much of the links (both for the image and to the stage) would be the same.

**Comment by hadley** [comment]
Thanks for filing this issue! However, I don't think the time it will take to implement is worth the payoff, especially given that you should be looking at the git diff, and will notice that only one line has been added and none have been deleted. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by llrs** [comment]
I don't understand your concerns:
1) I could try to implement it myself. The only time you'll spend is reviewing the issue and the PR. I understand that might be already too much, at the end of the day, you allocate your time and your team as you see fit. 
2) Why should I look at the git diff? If anything I would look at the README and remove the previous one or organize the badges differently (at least that's what I did). 
Don't worry I'll keep contributing while I have time :wink: and I think my contributions are valued and appreciated :smile:
