### ISSUE TITLE
Function to add proprietary license

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1163]
i.e. for internal packages that are definitely not open source. Can take model from https://r-pkgs.org/description.html#license

**Comment by ijlyttle** [comment]
Of course, nothing here you don't already know. 

I (used to) run into problems on `R CMD CHECK` as proprietary licenses are non-standard; someone (maybe @krlmlr) suggested I add these lines to `.Renviron`: 

```
# ignore non-standard license when checking locally
_R_CHECK_LICENSE_=FALSE
```

This disables the check for all the open source stuff, but it still gets checked on CI.

If this is the right way to go, perhaps this could be useful as feedback when the function is called?

**Comment by malcolmbarrett** [comment]
FWIW, here's an extended discussion on this issue, which centers around the example from R Packages: https://unconj.ca/blog/copyright-in-closed-source-r-packages-the-right-way.html

**Comment by jennybc** [comment]
Closing, explanation in issue.

**Comment by jennybc** [comment]
Function should be named `use_proprietary_license()`.
