### ISSUE TITLE
Reveal GitHub PAT's scopes in git_sitrep()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1174]
The group test drive revealed two surprises that were due to unexpected scopes:

* Some people couldn't see the emails associated with their GitHub accounts. That's because their PAT did not have the `"user:email"` scope. That is now included in the default scopes set for `create_github_token()`, but that was not always the case.
* One person had a PAT with **no** scopes. So that broke lots of things and, upon discussion, affected other packages as well, such as remotes.

In both cases, seeing explicit scopes would probably have helped us troubleshoot more quickly.

**Comment by krlmlr** [comment]
I used the following code in another project:

```r
attr(gh::gh("/user"), "response")$"x-oauth-scopes"
```

Any endpoint will do, `/user` seemed a good choice because it's always accessible (?) and doesn't return a ton of data (??).
