### ISSUE TITLE
Tutorials created with use_tutorial can't be found by learnr::run_tutorial

### ISSUE THREAD

**Issue by karaesmen** [r-lib/usethis#1178]
I'm currently working on a "tutorial package" for tidymodels called [learntidymodels](https://github.com/tidymodels/learntidymodels). 
We expect users to install this package and open their tutorial of choice locally by using `learnr::run_tutorial()` function.

When I use `usethis::use_tutorial` to add tutorials to the package, it adds the newly created tutorial `.Rmd` to `.Rbuildignore`. Consequently, `learnr::run_tutorial()` or `learnr::available_tutorials()` functions can't find the tutorial(s) and throw an error. 

For example:
```
library(usethis)
path <- file.path(tempdir(), "mypkg")
create_package(path)
use_tutorial("tutorial", "Some tutorial")
devtools::install()

learnr::run_tutorial("tutorial", "mypkg")
#> Error: No tutorials found for package: "mypkg"
```

I am not sure if there's a specific reason why these tutorial Rmds should be included in `.Rbuildignore`. 
But when these `.Rmd` files **are not** added to `.Rbuildignore` everything works fine and package still seems to pass all R CMD checks. On the other hand `use_tutoria()` adds the rendered html files to `.gitignore` and it may make sense to add these to `.Rbuildignore` as well?

**Comment by jennybc** [comment]
cc @angela-li @jules32 since they contributed this functionality and my head is elsewhere atm

**Comment by jules32** [comment]
Thanks Jenny – I'm unfortunately not up to date on this and can't dig into it atm. @angela-li do you have time to revisit this?

**Comment by apreshill** [comment]
Hi all,

Looking at the source code for `use_tutorial()`, `ignore` is set to TRUE:

https://github.com/r-lib/usethis/blob/master/R/tutorial.R#L41-L47

```
  new <- use_template(
    "tutorial-template.Rmd",
    save_as = path,
    data = data,
    ignore = TRUE,
    open = open
  )
```

But in `use_template()` has `ignore` set to FALSE by default:
https://github.com/r-lib/usethis/blob/a128f600103d5af1dfa0b4fbefc6764f5d998b55/R/template.R#L43

I wonder if setting it to FALSE in `use_tutorial()` would be safer and fix the problem we encountered? What do you all think? We can offer a PR with this change.

**Comment by jennybc** [comment]
I've never used a learnr tutorial, so am deferring to those of you who do.

But yes if this is meant to ship with a package, I'm not sure why `ignore = TRUE` was ever set in the `use_template()` call.

And therefore yes a PR sounds good.
