### ISSUE TITLE
create_from_github() + gert issue

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#1179]
I am using the usethis gert branch and tried `usethis::create_from_github("gagolews/stringi", "~/Desktop/")`

it works, and i end up with this config:

```
[remote "origin"]
	url = git@github.com:DavisVaughan/stringi.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = upstream
	merge = refs/heads/master
[remote "upstream"]
	url = git@github.com:gagolews/stringi.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
	created-by = usethis::create_from_github
```

however, when i then go to use the rstudio git pane to create a branch, it looks like the attached image. Notice that it says `upstream`! I think it always used to say `origin`. I accidentally created the `upstream` branch and obviously couldnt push to it, so that was unfortunate. switching this to `origin` fixes it, but it seems like a default has been set incorrectly by usethis?

here is what usethis says it did

```
> usethis::create_from_github("gagolews/stringi", "~/Desktop/")
✓ Creating '/Users/davis/Desktop/stringi/'
✓ Forking 'gagolews/stringi'
✓ Cloning repo from 'git@github.com:DavisVaughan/stringi.git' into '/Users/davis/Desktop/stringi'
Trying to authenticate 'git' using ssh-agent...
Transferred 20488 of 20488 objects...done!
Checked out 2131 of 2131 commits... done!
✓ Setting active project to '/Users/davis/Desktop/stringi'
✓ Adding 'upstream' remote: 'git@github.com:gagolews/stringi.git'
✓ Pulling in changes from the primary repo 'upstream/master'
Already up to date, nothing to merge
✓ Setting remote tracking branch for local 'master' branch to 'upstream/master'
✓ Writing 'stringi.Rproj'
✓ Adding '^stringi\\.Rproj$' to '.Rbuildignore'
✓ Opening '/Users/davis/Desktop/stringi/' in new RStudio session
✓ Setting active project to '<no active project>'
```

And when I compare to my vctrs fork created a while back, the git config for the master branch has a different remote

```
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

![Screen Shot 2020-07-08 at 9 44 00 AM](https://user-images.githubusercontent.com/19150088/86927328-336b0080-c101-11ea-8d30-150db4790579.png)

**Comment by DavisVaughan** [comment]
Ooof even CRAN usethis does this. So this is not a bug from gert changes

**Comment by jennybc** [comment]
We discussed elsewhere, but let me comment here too for others.

Yes, if `create_from_github()` creates a fork -- i.e. it's doing a full fork-and-clone setup -- it configures `upstream/master` as the tracking branch for `master`. This is one of the measures we take to discourage people committing on `master` in a fork and, eventually, making pull requests from `master` of a fork.

This means people get upstream development when they pull on `master`. They probably are refused when they try to push on `master`. And I think that's good. It encourages working in a feature branch when you're working in a fork.

**Comment by jennybc** [comment]
As for the default tracking situation for subsequent branches, usethis does this at the time of the first push, not at creation time. I've always found it rather odd that the IDE pushes the (empty) branch at the moment of creation. But in any case, `usethis::pr_push()` does push to `origin`, not `upstream`, and makes sure a local feature branch is tracking a branch on `origin`.
