### ISSUE TITLE
use_github needs option to switch repos

### ISSUE THREAD

**Issue by cboettig** [r-lib/usethis#118]
Followup from #109 

`use_github()` should be able to update the the git remote `origin` in an existing repository to point to the specified GitHub repository; creating said GitHub repository if necessary.  This would support the use case of cloning a template repo from GitHub and then establishing a new repository, with new name and potentially new org/user, on GitHub, as the remote.  

----

@hadley I think the above captures what you suggested in #109, but I'm not entirely sure.  There's clearly a couple of rather distinct patterns here and it's not obvious to me how best to divide or modularize them across the `usethis` API.  e.g. a partial list (cc @jennybc who also thinks about this more clearly than me!):

- Starting a new project from scratch / RStudio new->project menu and syncing to GitHub (compare to classic workflow of creating blank repo on GitHub first, then initializing project boilerplate).
- Starting a new project from a template repo, giving it a new name and syncing to new location on GitHub (Compare this to what GitHub Classroom does with template repos)
- Forking a project (identical to GitHub fork)
- Forking a project without registering as a Fork
- 

Clearly these are related to both `use_github` an `create_github_repo` functionality, but it's not clear if each is best done with it's own function or with a combination of modular functions.  Apologies if I'm getting derailed again in mixing issues.

**Comment by jennybc** [comment]
@cboettig I'm closing this in favour of #214.

It would be great if you could chime in there, using those diagrams to discuss what's missing. Some improvements will come to `create_from-github()` in the release that's imminent but no everything you're talking about. You seem to have goals around

  * Editing remotes
  * (Re-)Naming the local repo
