### ISSUE TITLE
Automatically use testthat 3e

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1185]
When creating a package and you have testthat 3.0.0 or later installed.

We may also want to provide `use_testthat_3e()` function.

**Comment by hadley** [comment]
(FWIW this isn't just for us, but is for everyone)

**Comment by jennybc** [comment]
I know but I was trying to find a label in addition to "feature" 😁

Seems like a good time to ask: Is this what the "code :desktop_computer:" label is for?

**Comment by hadley** [comment]
Should just add edition argument to use_testthat and default to 3 if appropriate version of testthat found.
