### ISSUE TITLE
Code blocks of the pr-functions vignette

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#1186]
Just that you are aware for the next release, the [PR vignette](https://usethis.r-lib.org/articles/articles/pr-functions.html)  doesn't show different colors for contributor and reviewer code blocks: 
![Screenshot from 2020-07-14 11-56-50](https://user-images.githubusercontent.com/6818218/87412266-1fc00e00-c5c9-11ea-94eb-7b96580cee24.png)

**Comment by jennybc** [comment]
@mine-cetinkaya-rundel Can you take a look at this?
