### ISSUE TITLE
rename_files needs to also rename snapshots

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1187]

**Comment by hadley** [comment]
i.e. `rename_files("foo", "bar")` should move `tests/testthat/_snaps/foo.md` to `tests/testthat/_snaps/bar.md`

**Comment by hadley** [comment]
I also wouldn't be opposed to removing the old code that moves `tests/testthat/test-old*.txt` to `tests/testthat/test-new*.txt` since we're generally moving away from that (and I'm probably the only person who knows that this behaviour exists)

**Comment by jennybc** [comment]
Re: package to practice on

Packages with `_snaps` include tibble, pillar, dbplyr, pkgdown, and testthat itself.
