### ISSUE TITLE
Change github actions template yaml to include the fix to the most recent bug in gh-actions when commiting

### ISSUE THREAD

**Issue by brunocarlin** [r-lib/usethis#1189]
The issue can be found here https://github.com/r-lib/pkgdown/issues/1329

The current fix seems to be adding

         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"

To the yaml responsible for the pkgdown implementation

This issue affected both my pkdown and styler workflows

**Comment by jennybc** [comment]
The necessary changes have already been made in https://github.com/r-lib/actions.

Run `usethis::use_github_action("pkgdown")` to update your package. usethis just helps to write workflow files. It does not "own" the workflows.

**Comment by brunocarlin** [comment]
ops sorry about that, thought it was usethis that implemented this function
