### ISSUE TITLE
Q: How to fake package/project home? (to protect when running revdepcheck)

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/usethis#1197]
As described in https://github.com/r-lib/lifecycle/issues/52, when running revdepcheck on your package and one of the packages tested calls `usethis::use_lifecycle()`, then that call will update several files in your package, not the package being tested.

I'd like to protect against this by faking a package/project home in `my.package/revdepcheck/` to prevent `usethis::use_lifecycle()` (and other similar calls) from hitting my package.  What do I need to add?  Is it sufficient with a dummy `my.package/revdepcheck/DESCRIPTION` file?

**Comment by jennybc** [comment]
The lightest-weight thing to do is `touch .here` in revdepcheck. That will halt (and initially satisfy) the search for project root.  Then presumably an immediate error will be thrown by `use_lifecycle()` because it won't be in a project that is a package.

But as we discussed in https://github.com/r-lib/lifecycle/issues/52, this is really an error in the revdep, in the same way it would be if a package called `package.skeleton()` or `install.packages()`.

**Comment by HenrikBengtsson** [comment]
Thanks.  I've just re-launched a big, otherwise-problematic revdepcheck run to verify that this works.

Regard who's responsible to protect against this: I'm happy to add `revdep/.here` in my projects.  I agree that sending bug reports to the maintainers helps but that is a very slow process and the cost of letting these types of mistakes propagate up to my code base is just too high.  There's definitely a risk that I commit these unintended rewrites of my code base and not noticing them.  Also, I often have to run several rounds of revdepcheck:s to complete the checks of all revdep packages, e.g. some packages have false errors due to [random port clashes](https://github.com/r-lib/revdepcheck/issues/95), some require internet access so those I cannot run on our sandboxed HPC environment and need to re-run those interactively, etc.  I also keep forgetting to look for https://github.com/r-lib/lifecycle/issues/52 mistakes, so I've found myself having to start over from scratch a few times already.  So this fairly simple mistake, adds lots of friction for me.

One could argue that revdepcheck c/should protect against this, especially if all it takes is to add a `./revdep/.here`.  I might send that feature request later.

**Comment by HenrikBengtsson** [comment]
Update: It looks like `./revdep/.here` is _not_ enough.  Although the 'lifecycle' Rd figures were written to `./revdep/man/figures/`, it still ended up updating my `./DESCRIPTION` file.  I will now re-try with a dummy `./revdep/DESCRIPTION` instead of `./revdep/.here`.

**Comment by jennybc** [comment]
Are we talking about more than 1 package here? Who all is calling `use_lifecycle()` in their package code?

**Comment by HenrikBengtsson** [comment]
No, this far only one package that does this AFAIK.  But I've tested my updates to my package 3-4 times since this was discovered and each time I forgot about this problem.  After the problematic pkg has been fixed an submitted to CRAN, it might be years since it hits me again.  This hits me when I revdep check [SpaDES.core](https://cran.r-project.org/package=SpaDES.core) but if I understood it correctly the problematic package is [reproducible](https://cran.r-project.org/package=reproducible).  Until fixed, I think the following CRAN packages will run into this problem if/when they run their revdepcheck:s;
```r
> setdiff(unique(sort(unlist(lapply(revdepcheck:::cran_revdeps("reproducible"), FUN=tools::package_dependencies), use.names=FALSE))), revdepcheck:::base_packages())
 [1] "backports"     "checkmate"     "CircStats"     "crayon"        "data.table"    "DBI"           "devtools"     
 [8] "digest"        "dplyr"         "fastdigest"    "fastmatch"     "fpCompare"     "glue"          "googledrive"  
[15] "httr"          "igraph"        "lifecycle"     "lubridate"     "magrittr"      "memoise"       "miniUI"       
[22] "qs"            "quickPlot"     "R.utils"       "raster"        "Rcpp"          "RCurl"         "remotes"      
[29] "reproducible"  "rgeos"         "rlang"         "RSQLite"       "rstudioapi"    "sf"            "shiny"        
[36] "sp"            "SpaDES.addins" "SpaDES.core"   "SpaDES.tools"  "stringi"       "testthat"      "usethis"      
[43] "versions"      "whisker"
```

BTW, adding a `./revdep/DESCRIPTION`:
```
Package: dummy
Version: 0.1
Title: A Dummy Package
Description: A package placeholder to trick 'usethis' to stop at the folder where this DESCRIPTION file lives rather
 than traversing higher up in the directory structure. This protects against bugs such as the one described in https
://github.com/r-lib/lifecycle/issues/52.
Authors@R: person("Dummy", "Dummyson", role="aut", email = "dummy@dummy.org")
License: GPL (>= 3)
```
seems to have done the trick for me (so closing).  Thxs.
