### ISSUE TITLE
use_gpl3_license() modifies GPL-3 license text

### ISSUE THREAD

**Issue by fweber144** [r-lib/usethis#1198]
Calling `usethis::use_gpl3_license("My name")` produces a modified `LICENSE.md` file, with "modified" denoting modifications compared to the [original license text](https://www.gnu.org/licenses/gpl-3.0.md). In particular, the name of the R package and the text passed to `usethis::use_gpl3_license()`'s argument `name` (`"My name"` in the example above) are used in section "How to Apply These Terms to Your New Programs" of the license text. However, it seems like modifying the GPL-3 license text is not allowed (not even for section "How to Apply These Terms to Your New Programs"), see for example [here](https://softwareengineering.stackexchange.com/questions/281949/how-to-properly-apply-a-license). I'm not an expert for legal affairs (and I also don't know if the person who answered in that Stack Exchange thread is one), but it makes sense to me that this section "How to Apply These Terms to Your New Programs" is intentioned to be a template and therefore must be included unmodified.

**Comment by jennybc** [comment]
Would you like to make a PR showing how you think it should be? I don't think we're intentionally doing anything creative here.

**Comment by fweber144** [comment]
Done: [https://github.com/r-lib/usethis/pull/1199](https://github.com/r-lib/usethis/pull/1199). However, in that PR, I just demonstrated my suggestion for `use_gpl3_license()`. You will probably have to adopt it for the other GPL-like licenses, too.
