### ISSUE TITLE
Allow `use_package` to change dependencies

### ISSUE THREAD

**Issue by TylerGrantSmith** [r-lib/usethis#1201]
Why does `use_package` not give an option to change the dependency type of an already added package?  Could this be changed to either allow the change as requested, warning that it already exists, or add an optional argument to force the change? Or perhaps add a new `type` `"remove"` so that I can at least remove the package before updating the dependency.

````
> usethis::use_package("ggplot2")
✔ Adding 'ggplot2' to Imports field in DESCRIPTION
● Refer to functions with `ggplot2::fun()`
> usethis::use_package("ggplot2", "suggests")
● Use `requireNamespace("ggplot2", quietly = TRUE)` to test if package is installed
● Then use `ggplot2::fun()` to refer to functions.
Warning message:
Package 'ggplot2' is already listed in 'Imports' in DESCRIPTION, no change made. 
```

**Comment by jennybc** [comment]
> Why does use_package not give an option to change the dependency type of an already added package?

Based on my recollection the last time I worked on it: it's already borders on over-complicated, given how easy it is to manually edit DESCRIPTION. That doesn't mean there's no room for improvement, but that's my initial hunch.

**Comment by TylerGrantSmith** [comment]
You know, i know its easy, but I still use it!  If nothing else, maybe the suggestion on how to reference the package shouldn't print for the replacement if it ultimately doesn't make the change.

**Comment by hadley** [comment]
Totally agreed, but it's already a very complicated function, and I don't think the development time needed to fix it is worthwhile, given the mild expected pay off.
