### ISSUE TITLE
edit_rstudio_snippets() works incorrectly due to changes in RStudio 1.3

### ISSUE THREAD

**Issue by GegznaV** [r-lib/usethis#1204]
The default directory where user-defined RStudio settings (including code snippets) reside has changed in RStudio 1.3 (I do not know in which exact version). So `edit_rstudio_snippets()` creates and opens a file in a wrong directory.

**Comment by batpigandme** [comment]
Hmm, it still works in the daily builds (currently 1.4.746)

```r
usethis::edit_rstudio_snippets()
# ● Modify '/Users/maraaverick/.R/snippets/r.snippets'
```
What path are you getting when you run this command? What is your expected path?

**Comment by GegznaV** [comment]
> What is your expected path?

I expect the same path that is used in RStudio by default. I.e., the same path that is opened when point-and-click way modify snippets is used. It is described here: https://blog.rstudio.com/2020/02/18/rstudio-1-3-preview-configuration/

For RStudio 1.3 < on Windows it is
```r
fs::path(Sys.getenv("APPDATA"), "RStudio", "snippets")
```
e.g., `C:/Users/User/AppData/Roaming/RStudio/snippets`

For RStudio 1.3 < on other OS'es:
```r
fs::path_expand_r("~/.config/snippets/")
```

For RStudio < 1.3 (e.g., 1.2) it was
```r
fs::path_expand_r("~/.R/snippets/")
```
