### ISSUE TITLE
tidyeval template: import .env from rlang

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#122]
I don't have a strong opinion on this but I notice that (as of today) rlang does not export `.env` - so I think (as of today) the template should not import it.

I gather that this remains an open question (tidyverse/rlang#269), just going for consistency now.

Also making a PR for this.

**Comment by ijlyttle** [comment]
Just saw the CRAN release - I should have also pointed out that the backquotes around `:=` appear to cause a warning - this is fixed in the PR.

This is using the CRAN version (1.1.0) of usethis.

Also noting I get this `template.Rproj` error, but this may be because I have (by habit) already created the directory and RStudio project. Can open separate issue if need be.  

```
> create_package(".")
Changing active project to tempusethis
✔ Creating 'R/'
✔ Creating 'man/'
✔ Writing 'DESCRIPTION'
✔ Writing 'NAMESPACE'
Error: Could not find template 'template.Rproj'

> use_roxygen_md()
✔ Setting Roxygen field in DESCRIPTION to 'list(markdown = TRUE)'
✔ Setting RoxygenNote field in DESCRIPTION to '6.0.1'
● Re-document

> document()
Updating tempusethis documentation
Loading tempusethis
Writing NAMESPACE

> use_tidy_eval()
✔ Adding 'rlang' to Imports field in DESCRIPTION
✔ Writing 'R/utils-tidy-eval.R'
● Run document()

> document()
Updating tempusethis documentation
Loading tempusethis
Writing NAMESPACE
Writing tidyeval.Rd

> load_all()
Loading tempusethis
Warning messages:
1: object ‘`:=`’ is not exported by 'namespace:rlang' 
2: object ‘.env’ is not exported by 'namespace:rlang' 
```

**Comment by alexholcombe** [comment]
I also get the below template.Rproj error (and I don't know what to do about it) from create_package, e.g. when following the get started instructions at https://www.tidyverse.org/articles/2017/11/usethis-1.0.0/

`Error: Could not find template 'template.Rproj'`

**Comment by ijlyttle** [comment]
It looks like you have identified the `create_package()` behaviour in #127

**Comment by jennybc** [comment]
Yes, I confirm that the error re: `template.Rproj` has been resolved in dev version.
