### ISSUE TITLE
Use bullet character in kv_line()

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#1220]
In https://github.com/r-lib/devtools/issues/2269 it was mentioned that the bullet types in the devtools sitrep function are inconsistent. This seems to be because `ui_todo()` uses a unicode bullet, but `kv_line()` uses a simple `*`. Ideally these would both use the unicode bullet.

**Comment by jennybc** [comment]
Fixed (although I picked a different symbol) for `kv_line()`: `cli::symbol$star` ٭ .

Let me know if that's a problem and I really should use the bullet.

**Comment by jimhester** [comment]
That is a problem, the whole purpose of this is to be consistent with the bullets of `ui_todo()`.

**Comment by jennybc** [comment]
OK I can use the bullet.

In usethis `kv_line()` is only used inside `git_sitrep()`-type of functions, so it's not really set up to be parallel with todo's and done's.
