### ISSUE TITLE
Adding VignetteBuilder to DESCRIPTION results in to Github Action failure

### ISSUE THREAD

**Issue by dmenne** [r-lib/usethis#1228]
My [R-Package ](https://github.com/dmenne/gastempt) errors when the DESCRIPTION has the line
`VignetteBuilder: knitr`. Default yml from `usethis`. Local check/build works ok.

### With VignetteBuilder: knitr

```
Run rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
  shell: /usr/local/bin/Rscript {0}
  env:
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    NOT_CRAN: true
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘.../DESCRIPTION’ ... OK
* preparing ‘gastempt’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘gastempt’ ...
** using staged installation
ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'
* removing ‘/tmp/Rtmp1wTKwa/Rinst341f34f303e2/gastempt’
      -----------------------------------
ERROR: package installation failed
Error: Error in proc$get_built_file() : Build process failed
Calls: <Anonymous> ... build_package -> with_envvar -> force -> <Anonymous>
```

### Without VignetteBuilder

```
Run rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
  rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
  shell: /usr/local/bin/Rscript {0}
  env:
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    NOT_CRAN: true
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘.../DESCRIPTION’ ... OK
* preparing ‘gastempt’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘gastempt_0.5.1.tar.gz’
Warning: Warning: file 'gastempt/configure' did not have execute permissions: corrected
```

**Comment by jennybc** [comment]
The exact presentation of the error varies a bit in the two scenarios above, but the real problem looks to be related to:

```
ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'
* removing ‘/tmp/Rtmp1wTKwa/Rinst341f34f303e2/gastempt’
...
* building ‘gastempt_0.5.1.tar.gz’
Warning: Warning: file 'gastempt/configure' did not have execute permissions: corrected
```

If you really think this is usethis problem, we will need to see a reprex with full code to create the problematic package with usethis:

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks!

**Comment by dmenne** [comment]
Hi, Jenny, I know how to use reprex, but this is not a use-case (sic!).

The error does not occur when I apply the `usethis` function, but when the action is run on github with the same default yaml-file in both cases. The only difference between the two versions shown in this [diff ](https://github.com/dmenne/gastempt/commit/246563ecdd42f34d6342d83322c4910500c04202)

The "did not have execute permission" always turns up when source is developed under Windows and is normally corrected without problems.

**Comment by dmenne** [comment]
Thinking it over, this might be better suited for https://github.com/r-lib/usethis. I will post a link there and close this thread when it has been accepted there.
