### ISSUE TITLE
Problem with Rstudio restart in usethis::use_git() when project path contains accents

### ISSUE THREAD

**Issue by andrader** [r-lib/usethis#1231]
It seems to be a problem when there are accents in the full path of the project.

reprex:
```r
usethis::create_project("C:\\test_ãccêntsí")
```
In the new project session:
```r
usethis::use_git()
```
The answering Yes to "Restart Rstudio?"

Will produce an error similar to these:
![image](https://user-images.githubusercontent.com/38709237/94458158-ef314e80-018b-11eb-84b8-108681755566.png)

**Comment by jennybc** [comment]
Can you show the output of these commands?

``` r
rstudioapi::versionInfo()
packageVersion("rstudioapi")
```

**Comment by andrader** [comment]
```
> rstudioapi::versionInfo()
$citation

To cite RStudio in publications use:

  RStudio Team (2020). RStudio: Integrated Development
  Environment for R. RStudio, PBC, Boston, MA URL
  http://www.rstudio.com/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, PBC},
    address = {Boston, MA},
    year = {2020},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] ‘1.3.1056’

$release_name
[1] "Water Lily"

> packageVersion("rstudioapi")
[1] ‘0.11’
```

**Comment by jennybc** [comment]
Are you able to open such an RStudio project (accents in the path) through other means? If so, which methods work for you?

**Comment by andrader** [comment]
I am able to open through File > Open Project...
But when I try to use git:
`usethis::use_git()`
This is what I get:
![image](https://user-images.githubusercontent.com/38709237/97609815-d6b68d00-19f2-11eb-8fd6-fd593783b356.png)


Also, if I try openning the project through the file .Rproj it gives me the error:
![image](https://user-images.githubusercontent.com/38709237/97609990-141b1a80-19f3-11eb-85e2-c8105be6410b.png)

**Comment by jennybc** [comment]
This is problem with RStudio and thus where the fix must happen (which is in process, see links to issue & PR above). So nothing to be done here in usethis. Thanks for the report!
