### ISSUE TITLE
Refresh "pull request helpers" vignette

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1234]
Has lots of pre-rendered content that has undoubtedly changed

**Comment by jennybc** [comment]
@mine-cetinkaya-rundel Does this work nicely into anything you are doing anyway? Or would you prefer to not be involved?

**Comment by mine-cetinkaya-rundel** [comment]
I'd be happy to update it. Are you ok with pre-rendered content again?

**Comment by jennybc** [comment]
> Are you ok with pre-rendered content again?

Absolutely. I think we have no choice in this case.

**Comment by mine-cetinkaya-rundel** [comment]
Sounds good, I'll work on updating it.

**Comment by jennybc** [comment]
Is this still on the horizon @mine-cetinkaya-rundel?
