### ISSUE TITLE
create_package() should complete license when possible

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#124]
If you have options configured such that all new packages use, e.g., the MIT license, a freshly-created package will throw this warning:

``` R
W  checking DESCRIPTION meta-information
   Invalid license file pointers: LICENSE
```

It would be nice if `create_package()` checked the license and called, e.g., `use_mit_license()`, to close the deal.

**Comment by hadley** [comment]
If you want to customise your description in that way, it's up to you to call `use_mit_license()` etc. (And you'd be better writing a wrapper around `create_package()`)
