### ISSUE TITLE
`ui_code()` output difficult to read with dark editor themes

### ISSUE THREAD

**Issue by mrcaseb** [r-lib/usethis#1240]
Is it possible to make the output of `ui_code()` change it's color depending on the editor theme?
It looks like all other inline styles can do this but the `ui_code()` is always very dark. Since the reprex can't demonstrate this I have provided additional screenshots from my R Console with different RStudio editor themes.

```r
library(usethis)
ui_line("Normal text, {ui_field('field')}, {ui_value('value')}, {ui_path('path')}, {ui_code('code')}")
#> Normal text, field, 'value', 'path', `code`
```

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### Default RStudio theme "Textmate"

![grafik](https://user-images.githubusercontent.com/38586519/95226501-4fb03380-07fd-11eb-8e34-5fd4cb048804.png)

### RStudio theme "Dracula"

![grafik](https://user-images.githubusercontent.com/38586519/95227096-fbf21a00-07fd-11eb-8e83-4c5496294931.png)

### RStudio theme "Cobalt"

![grafik](https://user-images.githubusercontent.com/38586519/95226560-60f94000-07fd-11eb-9dc2-ba5cdfe088e7.png)

**Comment by jennybc** [comment]
Oh I feel you. Last time I looked into this, solving it well required something to change in RStudio, as I recall.

@jimhester Do you remember more or just generally have insights?

**Comment by jimhester** [comment]
This is a bug in the RStudio themes, https://github.com/rstudio/rstudio/issues/1959, their ANSI color values are not adjusted from the defaults for anything but the Dracula theme.

**Comment by mrcaseb** [comment]
Oh my god. I wanted to chose a random theme for comparison and really randomly clicked on Dracula which obviously the only theme that's changing the colors. 

Thanks for the answer @jimhester!

**Comment by jennybc** [comment]
Being sent to https://github.com/rstudio/rstudio/issues/1959 enabled me to find the previous incarnation of this issue here (#546) where we concluded this is a matter that has to be fixed in RStudio.
