### ISSUE TITLE
Detect if `master` --> `main`

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1243]
Can we help people discover that the source repo has switched from master to main?

**Comment by hadley** [comment]
It looks like GitHub is planning to do this on their end: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

**Comment by jennybc** [comment]
I'm not sure the usethis user will benefit much from what GitHub is planning there. That is, I'm not sure any of that will clearly surface the `master` --> `main` switch for someone with a "mature" fork & local clone that resumes work after a period of inactivity. Only a notify-on-fetch might help, but I wonder if that will get surfaced for a fetch done via libgit2?

I suspect there may still be some role usethis can play, at least in a health check function like `git_sitrep()`.

**Comment by hadley** [comment]
I think this will be the bit that's most helpful:

>  And, we’re also looking into redirecting users who git fetch or git clone the old branch name to the new branch name (with a warning and instructions to update their local clone), so it’s easy for your contributors to move.

**Comment by jennybc** [comment]
Yeah, I just don't understand what effect that will have on a fetch or clone that happens via libgit2. I don't see how any such helpful message is going to get surfaced to the R user.

**Comment by davidkane9** [comment]
Here is an example of how this fails now, using this test repo: https://github.com/PPBDS/test-create_from_github

``` r
library(usethis)
create_from_github("PPBDS/test-create_from_github", 
                   fork = TRUE, 
                   protocol = "https")
#> ✓ Creating '/Users/davidkane/Desktop/test-create_from_github/'
#> ✓ Forking 'PPBDS/test-create_from_github'
#> ✓ Cloning repo from 'https://github.com/davidkane9/test-create_from_github.git' into '/Users/davidkane/Desktop/test-create_from_github'
#> ✓ Setting active project to '/Users/davidkane/Desktop/test-create_from_github'
#> ✓ Adding 'upstream' remote: 'https://github.com/PPBDS/test-create_from_github.git'
#> ✓ Pulling changes from GitHub source repo 'upstream/master'
#> Error in b[vapply(b, "[[", character(1), "name") == y][[1]]: subscript out of bounds
#> ✓ Setting active project to '<no active project>'
```

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The repo, because it is new, has a main branch. create_from_github() does not seem to handle that correctly.

**Comment by jennybc** [comment]
@davidkane9 What version of usethis do you have?

**Comment by davidkane9** [comment]
usethis_1.6.1

**Comment by jennybc** [comment]
This works for me with the dev version (I just did it). This level of support has been introduced already in the dev version.

 This issue is about something else: when an existing, fully configured repo changes its branches.

**Comment by davidkane9** [comment]
Thanks! I will switch to the dev version. And apologies for putting this in the wrong place. I can delete my comments here, if that would be helpful to keep the thread clean.

**Comment by jennybc** [comment]
No worries, hiding is fine (which I'll do).

**Comment by jennybc** [comment]
Notes from @jimhester's recent `master` --> `main` experience in brio:

> The GitHub side of it was easy, but the instructions on renaming the branch locally and having it track the right remote branch are kind of awkward:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

> It might be worth having a usethis helper to do the renaming for us, if we don't already
> And maybe something we that would even do the GH part of it as well, assuming there is a API endpoint we can use

**Comment by jennybc** [comment]
Think about forks too
