### ISSUE TITLE
Add `setwd` argument to `with_project()` and `local_project()`

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1244]
I find that you usually want to change working directory to the temporarily active project. I think there should be an argument `setwd = TRUE` that does that, by default. And when it's `TRUE`, then cleanup would obviously restore original working directory, as well as the original active project.

@jimhester I know I talked you into using one of these functions recently in devtools. Would this have any downside for you?

**Comment by jimhester** [comment]
I think all the devtools examples should still work with this change
