### ISSUE TITLE
Default to "main" in github actions

### ISSUE THREAD

**Issue by friep** [r-lib/usethis#1245]
Brief description of the problem

This issue is inspired by my own experience using usethis' github actions in [newsanchor](https://github.com/CorrelAid/newsanchor) and [pocketapi](https://github.com/CorrelAid/pocketapi) and [this tweet](https://twitter.com/coolbutuseless/status/1314465384276389888?s=20) by @coolbutuseless. 

New GitHub repos are now using `main` as default branch by default, see [here](https://github.com/github/renaming) unless a different default branch is set in user / organization settings. Hence, more and more repositories will have main as default branch. For those repos, the github actions provided via `usethis` do not work out of the box and have to be adapted (for example, see [this commit](https://github.com/CorrelAid/newsanchor/commit/cab71fea43d769071714b8edf924a95705df954a)). 

I understand that there is a trade-off between supporting existing repositories still running on `master` with default branch. However, given that the R community is not afraid to adapt / move forward and that in the future, a lot more `main` repos will be there because of GitHub's new defaults, I think there is definitely a case to change the defaults in `usethis` GitHub actions as well. :)

**Comment by friep** [comment]
as i found out the actions themselves are stored in https://github.com/r-lib/actions  so this issue does not make sense here :)

**Comment by jennybc** [comment]
Yes, usethis and adjacent packages have been tracking the "default branch" situation in the Git world for quite a while (e.g. #1156) and we are all expanding support for a default branch that is not `master`. We are aware.
