### ISSUE TITLE
use_tidy_style should skip renv library

### ISSUE THREAD

**Issue by jamesmyatt** [r-lib/usethis#1251]
When I am using renv and I try to use_tidy_style,

```r
usethis::use_tidy_style()
```

then it starts to style files in the renv library

```
Styling  510  files:
 .Rprofile                                                                        v
 renv/library/R-4.0/x86_64-w64-mingw32/arrow/doc/dataset.R                        v
 renv/library/R-4.0/x86_64-w64-mingw32/bit/doc/bit-demo.R                         v
 renv/library/R-4.0/x86_64-w64-mingw32/bit/doc/bit-performance.R                  v
 renv/library/R-4.0/x86_64-w64-mingw32/bit/doc/bit-usage.R
....
```

This seems wrong, and it should skip the renv library (etc) entirely by default.

usethis 1.6.3
styler 1.3.2

**Comment by jennybc** [comment]
I think you need to upgrade styler, as it appears the renv issue has already been handled with reasonable defaults from at least v1.3.0.
