### ISSUE TITLE
Re-licensing usethis 2/2

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1253]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/usethis/graphs/contributors). @angela-li, @antoine-sachet, @bfgray3, @boshek, @cboettig, @Cervangirard, @Chris-Engelhardt, @coatless, @craigcitro, @cwickham, @davechilders, would you permit us to re-license usethis with the MIT license? If so, please comment "I agree" below.

* [x] [@angela-li](https://github.com/r-lib/usethis/commits?author=angela-li)  
* [x] [@antoine-sachet](https://github.com/r-lib/usethis/commits?author=antoine-sachet)  
* [x] [@bfgray3](https://github.com/r-lib/usethis/commits?author=bfgray3)  
* [x] [@boshek](https://github.com/r-lib/usethis/commits?author=boshek)  
* [x] [@cboettig](https://github.com/r-lib/usethis/commits?author=cboettig)  
* [x] [@Cervangirard](https://github.com/r-lib/usethis/commits?author=Cervangirard)  
* [x] [@Chris-Engelhardt](https://github.com/r-lib/usethis/commits?author=Chris-Engelhardt)  
* [x] [@coatless](https://github.com/r-lib/usethis/commits?author=coatless)  
* [x] [@craigcitro](https://github.com/r-lib/usethis/commits?author=craigcitro)  
* [x] [@cwickham](https://github.com/r-lib/usethis/commits?author=cwickham)  
* [x] [@davechilders](https://github.com/r-lib/usethis/commits?author=davechilders)

**Comment by craigcitro** [comment]
I agree.

**Comment by coatless** [comment]
I agree.

**Comment by cboettig** [comment]
I agree.

**Comment by Chris-Engelhardt** [comment]
I agree.

**Comment by cwickham** [comment]
I agree

**Comment by antoine-sachet** [comment]
I agree!

**Comment by davechilders** [comment]
I agree

**Comment by boshek** [comment]
I agree

**Comment by bfgray3** [comment]
I agree.

**Comment by angela-li** [comment]
I agree!

**Comment by batpigandme** [comment]
Hi @Cervangirard,
We'd love to get your agreement please, if you could take a look when you have a chance. 🙂
Thanks!

**Comment by Cervangirard** [comment]
I agree

**Comment by Cervangirard** [comment]
Sorry :)

**Comment by jennybc** [comment]
Closing, since everyone here has given explicit agreement.
