### ISSUE TITLE
Export style functions like todo(), done()?

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#126]
Following the motivation for #120, I am seeing if I can put together a package that uses "usethis" templates. (https://github.com/ijlyttle/ghentr)

I think it could be useful to be able to replicate this feedback style in my package.

The most expedient thing would be to for me to use the code in `style.R` as inspiration, but I was wondering if others might want to do the same. In this case, I could make a PR that exports these functions. 

If so, are there other such functions that should be considered, like `field()`, `value()`, `code()`, `code_block()`?

**Comment by boshek** [comment]
Was heading over here to make this exact suggestion so I would bump this. I would also advocate for two functions like this:

A function for when things haven't gone well:
```
not_done <- function(...) {
  usethis:::bullet(paste0(...), bullet = crayon::red(clisymbols::symbol$cross))
}
```
And then `congrats` as something to use when everything has happened successfully.
```
congrats <- function(...) {
  usethis:::bullet(paste0(...), bullet = crayon::yellow(clisymbols::symbol$star))
}
```
I'd be able to submit a PR on this as well including export `done` with appropriate documentation.

**Comment by jennybc** [comment]
Good idea, @ijlyttle. I think the tidyverse/r-lib team would also like to reuse these functions elsewhere. I think they will migrate to a UI-focused package and, once there, would be exported. The flip side of this is that we aren't willing to export them here and have others depending on usethis for such functionality.

So, the short-term advice, is to just re-implement what you need and keep your ears open for further developments.

**Comment by ijlyttle** [comment]
Sounds good. Thanks!
