### ISSUE TITLE
test-utils-git.R:12 failure

### ISSUE THREAD

**Issue by jeroen** [r-lib/usethis#1268]
I noticed usethis if failing one unit test on r-universe. See: https://github.com/r-universe/r-lib/runs/1344834004

This may very well be a bug on the r-universe end, but I would like to rule out that there is a bug in gert. On both Windows and MacOS, we see this:

```
  ── Skipped tests  ──────────────────────────────────────────────────────────────
  ● No Git user configured (21)
  ● On CRAN (5)
  ● On CRAN and on macOS (1)
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  ERROR (test-utils-git.R:12:3): git_branch() works
  
  [ FAIL 1 | WARN 0 | SKIP 27 | PASS 550 ]
```

The build script just runs `R CMD build` + `R CMD check` on a pretty standard setup.

**Comment by jennybc** [comment]
Thanks! I'm pretty sure the skip I added should solve things. Will you let me know if the problem persists?

**Comment by jeroen** [comment]
Thanks that fixed it.
