### ISSUE TITLE
Fill placeholder in new "Code of Conduct" template

### ISSUE THREAD

**Issue by krlmlr** [r-lib/usethis#1269]
See https://github.com/r-lib/usethis/commit/3b2998d1480f182ebca9bf43b2a8299d04c77e43#diff-b2396aff8b9801c5504d37c25f47f8614ff68ad547f8993ca66c333310c8ee4dR62-R63.

What's a good value for the "INSERT CONTACT METHOD" placeholder?

CC @batpigandme.

**Comment by batpigandme** [comment]
Like a default value, or the name for the placeholder? If the latter, I like INSERT CONTACT METHOD.

**Comment by jennybc** [comment]
At the very least, for all of our repos, we should be populating that placeholder. Should we "contact the maintainer"? Then we'd also need some sort of fall back if the complaint involves the maintainer.

In general, we should either expose an argument in `use_code_of_conduct()` to populate this or I should be messaging, alerting people to the fact that the template requires some manual modification.

So I'm seeking your advice about:

1. Is the maintainer the best blanket recommendation?
2. For tidyverse/r-lib org-owned packages, at least, what's the fall back beyond maintainer?

**Comment by hadley** [comment]
I think we should add an argument, and for our repos make it an email address (maybe me + Mara?).
