### ISSUE TITLE
Silence some gert messages

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1275]
Specifically, I'm thinking about this one:

```
#> ✓ Pulling in changes from default branch of the source repo 'upstream/master'
#> Already up to date, nothing to merge
```

**Comment by jennybc** [comment]
Maybe also this one:

```
#> ✓ Pulling from 'origin/formidable'
 #> Performing fast-forward merge, no commit needed
```

**Comment by malcolmbarrett** [comment]
FWIW I have really noticed these two messages using the dev version, and to my eye, they look a little weird compared to how usethis normally speaks

**Comment by jennybc** [comment]
They are literally not coming from usethis, so yes, they aren't styled like all our other messages.

I don't want to silence gert entirely, because if things go really wrong, we want to know. But these content-free messages are potentially worth suppressing entirely. It's just sort of fiddly.

**Comment by malcolmbarrett** [comment]
Oh yes, I am aware; I guess what I mean is that usethis is so chatty and has a specific way of speaking that it's been a little unusual to see something else a little chatty speaking slightly differently. Probably wouldn't much notice in another package! I do like some of the gert messages, though.
