### ISSUE TITLE
When do we invite user to commit?

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1282]
I can't remember or infer if there's a general principle about this. When do we ask the user if they'd like to commit files X, Y, and Z?

Example: `use_readme_md()` does NOT ask. `use_new_md()` does. Why?

**Comment by hadley** [comment]
I vaguely remember some discussion with @gaborcsardi (?) about this, but I don't remember the conclusion.

**Comment by gaborcsardi** [comment]
I don't even remember the discussion. :( 

Re the original question, I don't really have a very strong opinion. I probably would not want to _commit_ newly added files, but _adding_ them would be nice, I think. YMMV.
