### ISSUE TITLE
Figure out how to switch projects on RStudio server

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#129]
As opening the file doesn't seem to work.

**Comment by hadley** [comment]
Duplicate of #115

**Comment by hadley** [comment]
`rstudioapi::openProject(path, newSession = TRUE)` should be adequate

**Comment by jennybc** [comment]
@cboettig Would you be willing to install usethis from GitHub and confirm `create_project()` and `create_package()` behave themselves now re: opening the new project? *Still working on the stuff that's very specific to creating projects from GitHub ...*

**Comment by cboettig** [comment]
@jennybc Yup, they behave correctly in RStudio server now.

**Comment by jennybc** [comment]
Yay! Thanks for checking.
