### ISSUE TITLE
user_config_dir for Windows 10

### ISSUE THREAD

**Issue by cstepper** [r-lib/usethis#1293]
Hi,

just installed the latest version of `usethis`, and checked if I can edit my Rstudio snippets with `usethis::edit_rstudio_snippets`.

As mentioned in https://github.com/r-lib/usethis/pull/1278/, you use `rappdirs::user_config_dir("Rstudio")` now to find the correct location for the snippets file.

However, to me it looks like with windows 10 the "appauthor" part for the the directory path became obsolete.
https://github.com/r-lib/rappdirs/blob/71017d8f921967025c9e8ba43791af2e5162e165/R/data.r#L101

Please see my little reprex below.

Seems like a similar issue was already created in the past: r-lib/rappdirs#23 

Thanks for checking this, 
Christoph

``` r
# get OS
osVersion
#> [1] "Windows 10 x64 (build 18363)"

# Rstudio version
rstudioapi::versionInfo()$version
#> '1.4.1047'

# content of user config directory for RStudio
fs::dir_ls(fs::path(Sys.getenv("appdata"), "Rstudio"))
#> C:/Users/christoph.stepper/AppData/Roaming/Rstudio/crash-handler.conf
#> C:/Users/christoph.stepper/AppData/Roaming/Rstudio/desktop.ini
#> C:/Users/christoph.stepper/AppData/Roaming/Rstudio/desktop.ini.rYWFSf
#> C:/Users/christoph.stepper/AppData/Roaming/Rstudio/dictionaries
#> C:/Users/christoph.stepper/AppData/Roaming/Rstudio/keybindings
#> C:/Users/christoph.stepper/AppData/Roaming/Rstudio/rstudio-prefs.json
#> C:/Users/christoph.stepper/AppData/Roaming/Rstudio/snippets
#> C:/Users/christoph.stepper/AppData/Roaming/Rstudio/templates
#> C:/Users/christoph.stepper/AppData/Roaming/Rstudio/themes


# rappdirs
fs::dir_ls(rappdirs::user_config_dir("RStudio"))
#> Error: [ENOENT] Failed to search directory 'C:/Users/CHRIST~1.STE/AppData/Roaming/RStudio/RStudio': no such file or directory
```

<sup>Created on 2020-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
@Hadley If you still have this matter loaded into your brain, do you have opinion? Otherwise I will load it into mine and sort this out.

**Comment by gaborcsardi** [comment]
Application directories have different practices on Unix and Windows. On Windows, most apps have their files within a vendor or app author directory, e.g. `.../Microsoft/Internet Explorer/...`. On Unix, the vendor is usually not part of the path. This is why rappdirs by default uses `appauthor` on Windows.

OTOH RStudio does not seem to use the vendor name in the path. So you need to specify `appauthor = NULL`:

```r
rappdirs::user_config_dir("Rstudio", NULL)
```

**Comment by hadley** [comment]
@jennybc I would just do what @gaborcsardi suggests.

**Comment by jennybc** [comment]
I seem to have both of these directories on my fairly-newly-setup Windows VM. Not sure why.

I just made a change to my global options via the GUI and we can see which RStudio prefs file was affected = the one in `RStudio`, not the one in `RStudio/RStudio`.

``` r
library(tidyverse)
library(fs)

osVersion
#> [1] "Windows 10 x64 (build 19042)"

# Rstudio version
rstudioapi::versionInfo()$version
#> Error: RStudio not running


path(Sys.getenv("appdata"))
#> C:/Users/jenny/AppData/Roaming
rappdirs::user_config_dir()
#> [1] "C:\\Users\\jenny\\AppData\\Roaming"

(no_appauthor <- rappdirs::user_config_dir("RStudio", appauthor = NULL))
#> [1] "C:\\Users\\jenny\\AppData\\Roaming\\RStudio"

dir_ls(no_appauthor)
#> C:/Users/jenny/AppData/Roaming/RStudio/crash-handler.conf
#> C:/Users/jenny/AppData/Roaming/RStudio/desktop.ini
#> C:/Users/jenny/AppData/Roaming/RStudio/dictionaries
#> C:/Users/jenny/AppData/Roaming/RStudio/RStudio
#> C:/Users/jenny/AppData/Roaming/RStudio/rstudio-prefs.json

(appname_is_appauthor <- rappdirs::user_config_dir("RStudio"))
#> [1] "C:\\Users\\jenny\\AppData\\Roaming\\RStudio\\RStudio"

dir_ls(appname_is_appauthor)
#> C:/Users/jenny/AppData/Roaming/RStudio/RStudio/rstudio-prefs.json
#> C:/Users/jenny/AppData/Roaming/RStudio/RStudio/snippets

x <- file_info(c(
  path(no_appauthor, "rstudio-prefs.json"),
  path(appname_is_appauthor, "rstudio-prefs.json")
)) %>%
  select(path, ends_with("time")) %>% 
  mutate(path = path_rel(path, rappdirs::user_config_dir()))
as.data.frame(x)
#>                                 path   modification_time         access_time
#> 1         RStudio/rstudio-prefs.json 2020-12-04 12:57:24 2020-12-04 12:57:24
#> 2 RStudio/RStudio/rstudio-prefs.json 2020-12-04 12:06:19 2020-12-04 12:06:19
#>           change_time          birth_time
#> 1 2020-12-04 12:57:24 2020-10-29 18:31:53
#> 2 2020-12-04 12:06:19 2020-11-24 10:49:35
```

<sup>Created on 2020-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@jmcphers do you have any thoughts? Do you think I have this `RStudio/RStudio` directory *because* of this bug in usethis? Maybe I've executed some of our snippet- and RStudio-related code in this VM. Unless you say otherwise, that's going to be my assumption.

**Comment by jennybc** [comment]
I've de-installed and re-installed RStudio and then executed `use_blank_slate()` and am convinced this is a self-goal. Will fix in usethis.
