### ISSUE TITLE
Does use_tidy_pkgdown() have the wrong name?

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1308]
Discussion from review of usethis v2.0.0 blog post:

@hadley 
Probably shouldn't promote `use_tidy_pkgdown()` because it's our workflow?
 
 @jennybc 
In this case, `use_tidy_pkgdown()` is both our workflow AND what I would recommend for other maintainers as well. `use_tidy_pkgdown()` is `use_pkgdown() + use_github_pages() + use_github_action("pkgdown") + use_pkgdown_url()`.

Not sure what to do about that, if anything. I see your point, i.e. where other "tidy" functions often do something that is overkill or inappropriate for others. But it's not the case here.
 
 @jennybc
In any case, it's not really a blog post problem but potentially a function naming problem.
 
 @hadley 
Yeah, feels like we might've given the wrong name. Maybe should be `use_github_pkgdown()` or similar?

**Comment by jennybc** [comment]
Or `use_pkgdown_github_pages()`. Long but descriptive!

**Comment by hadley** [comment]
Yeah, and has the advantage that you'll see it with autocomplete.
