### ISSUE TITLE
Latest usethis update doesn't compile with old versions of libgit2

### ISSUE THREAD

**Issue by andresrcs** [r-lib/usethis#1310]
With old versions of `libgit2`, when compiling the `gert` package dependency, you are going to get a warning message telling you that your libgit2 version is too old, followed by a compilation error caused by a missing file (Sorry I didn't take note of the specific file before fixing the issue).

This is not exactly a bug but for anyone else trying to install `usethis` on systems whit no up to date versions of `libgit2` available, like in my case Raspbian Stretch only has `libgit2` 0.25.1 and you can't simply install a .deb package since it is an armhf architecture, you have to compile the package from source to get an update.

```
git clone https://github.com/libgit2/libgit2
cd libgit2
mkdir build && cd build
sudo su
cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
cmake --build . --target install
cd ..
rm -rf libgit2
exit
```
I'm aware this is not a proper bug report but I was told to post it here instead of replying to the publication on Community RStudio

**Comment by jennybc** [comment]
I suspect the answers you seek are in the gert repo:

https://github.com/r-lib/gert/issues

https://docs.ropensci.org/gert/#installation

**Comment by andresrcs** [comment]
Thanks, but those threads are related to x86 Linux distros where is much easier to just find a repo and update the dependency with apt or yum.
I just wanted to leave this message somewhere (findable) for those lost souls like me that need to work with armhf systems.
Feel free to close this issue if it's too much of a misfit.

**Comment by jennybc** [comment]
I'm sorry you're having trouble. But yes if the struggle is to install ?gert? we should have or continue the conversation there. If you agree that's the root case, let's close this, link, and open a new issue on gert.

**Comment by andresrcs** [comment]
Actually I don't have any issue, I solved my problem by compiling the system dependency from source. I understand that, if this was an actual issue, I should file it on the `gert` repo but my intention with this was to help anyone having the same problem with the latest `usethis` update announced on Community RStudio.
I thought a reply there would be more appropriate for this but I was told Mara requested redirecting feedback here instead, which honestly feels weird.

**Comment by jennybc** [comment]
Sure, it's often helpful for those that come later to find an issue trail. Glad it is sorted.
