### ISSUE TITLE
Use upstream repository in README development installation

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#1312]
when creating a README (I think both Rmd and .md) there are some automatic instructions to install a package from the development repository. 
Currently origin remote is used, but in a fork I think it should use upstream. If not a question about which one to use as in `use_github_links()` might be helpful to avoid later a potentially merge conflict.

**Comment by jennybc** [comment]
Yes good point.

**Comment by llrs** [comment]
Thanks, that was quick but more complicated than I though.
I was about to look into this and create a PR, glad you closed it first :)
