### ISSUE TITLE
use_course()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#132]
Grabs a course's-worth of material from DropBox or GitHub (as zip archive), saves to a reasonable place, unpacks it, ~opens RStudio Project in that place~ opens directory.

cc @jaredlander

**Comment by hadley** [comment]
I think this is fairly straightforward:

1. Download with `download.file()`
2. Unzip to desktop (?) with `unzip()` and print message
3. `browseUrl()` on the downloaded directory, so that it opens in finder/explorer.

**Comment by hadley** [comment]
Oh this will be more complicated than I was thinking because you need to figure out how to go from dropbox directory to zip file download (or from github page to equivalent)

**Comment by jaredlander** [comment]
Another complicating factor is that a lot of companies now use Box or Dropbox as their Documents folder which is often the only directory to which users have write access. And I've seen Box/Dropbox not play well with RStudio projects and with Git.

**Comment by jennybc** [comment]
We will definitely separate the acquisition + unpacking of files from making the folder into an RStudio Project and/or a Git repo. This has pedagogical value (to do those things explicitly) and, as you @jaredlander point out, it may also be very pragmatic.
