### ISSUE TITLE
use_freshstarts()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#133]
Re: https://github.com/tidyverse/tidyverse.org/pull/64#discussion_r156173690

Have a function to report or change behaviour around saving/loading `.RData`?

**Comment by jennybc** [comment]
This *could* be default behaviour for RStudio Projects created by usethis 🤔.

**Comment by hadley** [comment]
Do you want to have a go at this? 

I'd start by figuring out where the global settings live and then what R package is needed to parse/modify.

**Comment by jennybc** [comment]
Sure I will get the ball rolling.

**Comment by jennybc** [comment]
First pass will implement `scope = "project"`, but not `scope = "user"`. Why? (thx to @jmcphers for all this info):

Storage of user-level setting varies by OS. Some of the settings there can cause catastrophe if manipulated inappropriately, so it's not a file to edit lightly and there is currently no official API. There is interest in providing users better access to these settings (Store RStudio user preferences in a user-accessible location, https://github.com/rstudio/rstudio/issues/1607).

Example of user settings on a Mac: settings are in `~/.rstudio-desktop/monitored/user-settings/user-settings`. "freshstarts" behaviour corresponds to setting `saveAction="0"` and `loadRData="0"`. Values for `saveAction` are enumerated [here](https://github.com/rstudio/rstudio/blob/26ff5429aec42ba83bb26073388c778dbcab06af/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java#L245-L257).
