### ISSUE TITLE
proj_activates(".") reopoens the project 

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#1335]
I recently created a new project with `create_package(path)` on the new Rstudio instance I used `proj_activate(".")` which resulted in opening a new instance of the same project .

Maybe exclude opening the project if it is already opened by Rstudio?

Using usethis2.0.0

----
Not sure if https://github.com/r-lib/usethis/issues/905 is related

**Comment by jennybc** [comment]
This is doing exactly what `proj_activate()` is designed for and as documented:

https://usethis.r-lib.org/reference/proj_activate.html
