### ISSUE TITLE
create_project not writing to .Rproj file

### ISSUE THREAD

**Issue by ldecicco-USGS** [r-lib/usethis#1336]
I cannot get `create_project` to write to the .Rproj file to my working directory. I've set my wd to a folder that has no .Rproj file and run:

```r
> usethis::create_project(here::here(), 
+                         open = FALSE)
√ Setting active project to 'C:/Users/ldecicco/Documents'
√ Writing 'Documents.Rproj'
Error in file(con, "rb") : cannot open the connection
√ Setting active project to '<no active project>'
```
When that is run, there's a "Documents.Rproj" file created on my system, but it's empty (0 bits).

If I specify a new or existing folder, then it works. In this example, I already have a folder called Workflows on my computer, but there is no Rproj within that folder:
```r
usethis::create_project(here::here("Workflows"), 
+                         open = FALSE)
√ Setting active project to 'C:/Users/ldecicco/Documents/Workflows'
√ Creating 'R/'
√ Writing 'Workflows.Rproj'
√ Adding '.Rproj.user' to '.gitignore'
√ Setting active project to '<no active project>'
```

Side question, should `create_project` necessarily create an "R" folder? In my use case, I'd rather it didn't. 

```r
> devtools::session_info()
- Session info -----------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Chicago             
 date     2021-01-21                  

- Packages ---------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.3)
 callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.3)
 cli           2.2.0   2020-11-20 [1] CRAN (R 4.0.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.3)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.3)
 devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.3)
 digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.3)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.3)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.3)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.3)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.3)
 here          1.0.1   2020-12-13 [1] CRAN (R 4.0.2)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.3)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.3)
 pillar        1.4.7   2020-11-20 [1] CRAN (R 4.0.3)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.2)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.3)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.3)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.3)
 processx      3.4.5   2020-11-30 [1] CRAN (R 4.0.3)
 ps            1.5.0   2020-12-05 [1] CRAN (R 4.0.3)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.3)
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.3)
 rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.3)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.3)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)
 testthat      3.0.1   2020-12-17 [1] CRAN (R 4.0.3)
 tibble        3.0.4   2020-10-12 [1] CRAN (R 4.0.3)
 usethis       2.0.0   2020-12-10 [1] CRAN (R 4.0.3)
 vctrs         0.3.6   2020-12-17 [1] CRAN (R 4.0.3)
 whisker       0.4     2019-08-28 [1] CRAN (R 4.0.3)
 withr         2.4.0   2021-01-16 [1] CRAN (R 4.0.3)

[1] C:/Users/ldecicco/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.3/library
```

**Comment by jennybc** [comment]
I haven't tried to replicate or explore this myself yet, but I already have 2 questions:

1. Do you really want to put an `.Rproj` file in `Documents/`? usethis is going to fight you really hard re: not nesting projects within project, so this will get triggered for any folder below `Documents/` that meets one of the "project" criteria (git repo, RStudio project, etc.).
2. Is the behaviour you're seeing somehow unique to `Documents/`? (which is a rather special folder)

**Comment by jennybc** [comment]
And a third question / observation: `here::here()` is looking for a "project", in order to find its top-level directory. So in terms of workflow and mental model, the above seems somewhat circular to me, i.e. "create me a new project here in this here project". This is not to say that this code shouldn't execute or fail in a better way. But it feels like a weird thing to do FWIW.

**Comment by ldecicco-USGS** [comment]
You are right, it's unique to Documents! I picked that because I didn't have an .Rproj file there already. If I move to another folder without a project, it's fine.

The use case for the record is I've been following the pattern for an R package as described here:
https://sharla.party/post/usethis-for-reporting/
And mostly it's super duper awesome. My problem lately is that users are trying to use the package without creating a new RStudio project, and then the whole thing breaks down since all the guts of the package use `usethis` functions which assume there's a project. I've been adding directions that include "Step 1, make a new project" (with a screenshot and arrows and everything), but it still seems to be the new-user-main-hurdle. So, I was thinking I could check for a .Rproj file, and if it's not there create it. I could do that with base-R, but I'm trying to stick with Sharla's theme and try to use `usethis` when I can.

I'll close the issue, but if you have any suggestions on the workflow described, I'm all ears.

**Comment by jennybc** [comment]
Ooh boy, this is a weird one. I can replicate the error and have various changes planned as a response.

But the first observation I'll make is that, if you start to make `Documents/` a project, in the `create_project()` sense, the `R/` directory is assumed to play the role of a "normal" `R/` directory in a project (package or not). So, it's assumed to hold the project's R scripts.

Except, in the case of `Documents/`, on Windows, most of us have our main R package library at `C:/Users/jenny/Documents/R/win-library` 😱 So needless to say, this creates problems, which ultimately lead to this error message.

@ldecicco-USGS Let's consider the special weirdness of trying to turn `Documents/` into a project to be its own story and set that aside for now.

Can you restate your problem, making no reference to that specific weird situation?

**Comment by jennybc** [comment]
As for this:

> Side question, should create_project necessarily create an "R" folder? In my use case, I'd rather it didn't.

That's sort of a vestigial early effort at conceiving what a non-package project would look like. I take your point, but we aren't going to solve that (or remove it) in this thread.

**Comment by ldecicco-USGS** [comment]
I think I only stumbled on the "Documents" weirdness because I was being lazy navigating to a folder that didn't currently have an Rproj (of course....95% of my folders are already R projects 😁). I've tried a few scenarios and it's only "Documents".

In case someone else is looking for a "check for project, create one if not", here's what I'm using:
```
check_project <- function(){
  has_package <- tryCatch(
    usethis::proj_get(),
    error = function(cond) FALSE)
  
  if(!isTRUE(has_package)){
    message("The foo package is required to be run within an R Project.")
    
    where <- getwd()
    create_one <- usethis::ui_yeah(paste0("Would you like to create an R project here: ",
                                          where, "?"))
    
    if(create_one){
      usethis::create_project(".",
                              open = TRUE)
    } else {
      stop("Please create an R project.")
    }
  }
}
```
