### ISSUE TITLE
Proposed feature: use_custom_build()

### ISSUE THREAD

**Issue by petrbouchal** [r-lib/usethis#1337]
I often repeat this pattern to get the Build All button for a custom build script and the Ctrl/Cmd+B shorcut linked to it:

1. create build script, like `build.R`, with the right shebang
2. open terminal, set permissions on build script
3. open project preferences to set custom build + point Rstudio to the script file

A  new `use_custom_build()` (or so) function would be useful. It could take a file name as input, then

1. if the file does not exist, create it from a template (shebang etc.) for common types (shell, R)
2. add execute permissions on Unix systems
3. set the `BuildType` and `CustomScriptPath` fields in *.Rproj, or stop and print a hint if there already is a BuildType field in *.Rproj

This could then be reused by more specialised workflow packages, which could wrap it with defaults set to their own build script templates, e.g. https://github.com/toddgrabowsky/tarflow/ (see https://github.com/toddgrabowsky/tarflow/issues/1)

A caveat is that shebangs may vary across systems and users, but this could be handled with a message prompting the user to review the script, or even opening it upon completion, adding a message or a comment in the file.

I'd be happy to do a PR if you think this fits into {usethis}. The only thing I am not sure about is what the most sensible way is to manipulate .Rproj files, as per https://github.com/r-lib/usethis/issues/1130#issuecomment-733927026.

**Comment by malcolmbarrett** [comment]
We just implemented a helper function in our internal pkg to do this for our targets template (similar to the link above). I haven't used it a lot in practice yet, but I really like the idea. Here's a sort of generalized version: https://gist.github.com/malcolmbarrett/3e4311daa26f327af1d4e5fb0ffb248c

I'm not happy with how I've handled checking and writing the Rproj file, though. I'm worried I'm going to mangle an unusual pre-existing setup. In the process of trying to get that right, I did accidentally discover that `rstudioapi::executeCommand("buildToolsProjectSetup")` opens up the relevant menu, though.

**Comment by petrbouchal** [comment]
Thanks, wonderful! So I wonder if @jennybc 

- knows of a safer way to manipulate the Rproj file (I've looked at `readDCF()` but didn't see an immediate way to make it work)
- would like this in {usethis}?

**Comment by jennybc** [comment]
Re: what's considered in scope for usethis vs not: frankly it often comes down to what our team personally uses intensely and can, therefore, design well, test often, and motivate ourselves to maintain. A somewhat involved or fiddly task that is _not_ shared by us ... is a tough sell. And I'm afraid that probably applies here.

> safer way to manipulate the Rproj file

Yeah I believe there is no official API or DSL for this. You'll see that inside usethis we also do this in a fairly primitive way.

**Comment by malcolmbarrett** [comment]
And my current implementation feels VERY fiddly. Even after reading the IDE source code a bit, I really don't have a good sense of how, when, and with what consequences the IDE uses these build-related fields. I'm worried it's going to come back to haunt me 😅.

**Comment by hadley** [comment]
To echo @jennybc, in the past we have tried to accept code that we only weakly care about it, but we haven't been able to make it work.
