### ISSUE TITLE
Feature Request: Write a .zenodo.json file based on fields from DESCRIPTION

### ISSUE THREAD

**Issue by ha0ye** [r-lib/usethis#1339]
I am coming back to a previous issue I had pondered - https://github.com/r-lib/devtools/issues/1673, which was to generate (or modify) `.zenodo.json` based on corresponding fields in a `DESCRIPTION` file.

I think a MVP would be pretty quick to whip up, using `desc::desc_get()` to retrieve values for "Title", "Description", and "License", as well as `desc::desc_get_authors()` to retrieve an author list, and then using functions in `jsonlite::` to generate a `.zenodo.json` file (or modify an existing one).

**Comment by hadley** [comment]
I think this is out of scope for usethis; it feels like it would be better suited for a package built around zenodo.
