### ISSUE TITLE
Repo already exists on 'github.com' when run use_github()

### ISSUE THREAD

**Issue by qiangxyz** [r-lib/usethis#1340]
I created a repository, say "abc123", and then deleted it in the web of GitHub. Yet I can not create a new repository named "abc123" any more when I run use_github(use_github(protocol = 'https'):

`√ Checking that current branch is default branch ('master')

Error: Repo 'qiangxyz/abc123' already exists on 'github.com'`

**Comment by jennybc** [comment]
I suspect it's a latency problem, i.e. the deletion hasn't fully propagated throughout GitHub's infrastructure.

If I create a local repo, then call `use_git()` and `use_github()`, it works. If I then delete the repo through the GitHub browser UI and try `use_github()` again, I see this, as expected:

```
> use_github(private = TRUE)
✓ Checking that current branch is default branch ('main')
Error: This repo already has an 'origin' remote, with value 'https://github.com/jennybc/jkl.git'.
You can remove this setting with:
`usethis::use_git_remote("origin", url = NULL, overwrite = TRUE)`
```

If I do as it says and try again, it works, again:

```
> usethis::use_git_remote("origin", url = NULL, overwrite = TRUE)
> use_github(private = TRUE)
✓ Checking that current branch is default branch ('main')
✓ Creating private GitHub repository 'jennybc/jkl'
✓ Setting remote 'origin' to 'https://github.com/jennybc/jkl.git'
✓ Pushing 'main' branch to GitHub and setting 'origin/main' as upstream branch
✓ Opening URL 'https://github.com/jennybc/jkl'
```
