### ISSUE TITLE
Switch default branch to main

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1341]
We're going to pilot this in usethis, which is very meta.

GitHub has reached a new milestone in its work:

https://github.com/github/renaming#renaming-existing-branches

Will motivate me to deal with #1243

**Comment by jstevens5** [comment]
I'm happy to see this. Is it possible to set the default branch name with `use_git()`? Or is the plan just to move to defaulting to main?

**Comment by jennybc** [comment]
@jstevens5 usethis and its dependency gert already honour your Git config. So if you've expressed that you want `main` to be the default branch, this whole stack should already be honouring that.

This issue is about the usethis GitHub repo itself (so I'm going to hide this conversation as off-topic).

**Comment by hadley** [comment]
To make it even more meta, we could implement #1371, and then `use_git_main_branch()` on usethis.

**Comment by jennybc** [comment]
Superseded by #1480, which is the official issue I created as part of my mass branch renaming activities.
