### ISSUE TITLE
use_github to check if the name is used on CRAN

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/usethis#1342]
I recently made the blunder of publishing on github a package called {boom}, overlooking that there was already a cran package called {Boom}. 

I could have avoided it by being more careful on my own but since use_github is connecting to Internet anyway I thought that you might add a question if the name is taken on CRAN, something like: 

> A package named 'Boom' was found on CRAN, are you sure you want to create a new repository named 'boom' ?

Thanks!

**Comment by malcolmbarrett** [comment]
Are you aware of the [available](https://github.com/r-lib/available) package?

**Comment by moodymudskipper** [comment]
Thanks, I have seen it around, but I never remember it's name (though probably from now on I will!) .

Given that {usethis} eases steps of package development and that {available} tackles one of those maybe it could be integrated in {usethis}?
Some of its features might be out of scope but I think it's really rarely a good idea to publish on github a package named as an existing CRAN package so this sanity check wouldn't hurt.

**Comment by jennybc** [comment]
We have had this exact conversation before and I don't think anything has changed:

https://github.com/r-lib/usethis/issues/808

I still suspect the vast majority of `create_package()` calls do *not* lead to CRAN submissions, so we'd never check this by default. And I continue to doubt that many people would bother to set an argument to a non-default value. And those few people are the ones who would probably check `available::available()` themselves.
