### ISSUE TITLE
A function to rename a package? 

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/usethis#1343]
Renaming a package is a somewhat tedious multi step process that I believe fits well the scope of usethis.

NJ Tierney wrote a great post about it that I often come back to:  

https://www.njtierney.com/post/2017/10/27/change-pkg-name/

It would be awesome to have these steps implemented in usethis, automatically when possible and with guidance on which manual steps need to be followed when necessary.

Thanks!

**Comment by hadley** [comment]
Duplicate of #858
