### ISSUE TITLE
Using package data at "install time" causes an error

### ISSUE THREAD

**Issue by Vincent-Toups** [r-lib/usethis#1357]
I've created a minimal reproduction of the issue here:

https://github.com/Vincent-Toups/packagebugex

This package should build fine but fail on install.

The install fails because there is a function in `example.R` which depends on the package data directly, not indirectly.

```
mean_of_data <- function(continuation){
    m <- mean(some_data);
    continuation(m);
}

#' static_mean - returns the mean of some_data
#' @return - the mean
#' @export 
static_mean <- mean_of_data(function(m){
    function(){
        m;
    }
});
```

Here the function `static_mean` depends on running the function `mean_of_data`, which refers to `some_data`. I believe the issue here is that "mean_of_data" is invoked during the installation of the package (to create static_mean) but at that time `some_data` is not loaded.

I have tried disabling LazyData and that does not resolve the problem.

Context: I'm writing a large parsing/validating library which is based on combinators, many of which rely on a specification document which I am treating as package data. Since many of the high level validators (themselves functions) depend on low level validators, I need to access the package data in this way.

I don't have the problem if I use `pkgload::load_all` nor during tests.

**Comment by Vincent-Toups** [comment]
What about separating the data out into its own package? Would that maybe do the trick? Can one package reference another package's data at "install time"?

**Comment by hadley** [comment]
Doing anything at install time is risky because it's really build time, and if your package is CRAN build time and install time might be a large distance apart.
