### ISSUE TITLE
Lifecycle badge URL rejected by CRAN

### ISSUE THREAD

**Issue by MattCowgill** [r-lib/usethis#1360]
I am the maintainer of a CRAN package (`{readabs}`) that uses a Tidyverse lifecycle badge in README.md. 

On submitting an update to CRAN I received the following: 

```
Thanks, we see:

   Found the following (possibly) invalid URLs:
     URL: https://www.tidyverse.org/lifecycle/#stable (moved to 
https://lifecycle.r-lib.org/articles/stages.html)
       From: README.md
       Status: 200
       Message: OK

Please change http --> https, add trailing slashes, or follow moved 
content as appropriate.

Please fix and resubmit.
```

The tidyverse.org URL is added when users invoke `usethis::use_lifecycle_badge()`. It would be good to ensure that the badge points to the lifecycle.r-lib.org address without redirects, to avoid CRAN rejections.

**Comment by MattCowgill** [comment]
PS thanks for a great package!

**Comment by jennybc** [comment]
I believe this to be addressed in the dev version already:

23300fcb854a14d50007c20ef6f9dc5038dd33af

30bc851a103dfec03ecac0cb5e419090b4c4038f

**Comment by MattCowgill** [comment]
Ah, thank you! Sorry, I didn't realise.

**Comment by jennybc** [comment]
A small usethis release is coming soon
