### ISSUE TITLE
Generalizing `use_tibble()` and `use_data_table()`

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/usethis#1361]
`use_tibble()` and `use_data_table()` were marked as questioning in #1046 because:

> [they] don't do that much, and [they suggest] hundreds of other similar functions that might be added to usethis

Which is think is reasonable. I'm opening this issue to discuss if a generalized version of these functions is a good fit for usethis. I'm thinking something like `use_import(package, function = NULL)`. So, these functions would simply be replaced by these actions: `use_import("tibble", "tibble")` and `use_import("data.table")` or something to that effect. This generalization would primarily address the second reason above, but with respect to the first reason, I think usethis brings a consistency to roxygen imports that is very useful.

The reason I'm interested in this workflow is because, even though usethis is just adding a little roxygen, I like that it adds it to a consistent place and automates away that little bit of tedium, much like `use_package()`. Putting it in the package doc if it exists or using `ui_code_block()` otherwise is very nice to me. It has the added benefit of making such imports more consistent; they can be hard to find without digging around the docs or namespace, and if usethis has an opinion about where to put them, then I can start checking in one location to start.

**Comment by hadley** [comment]
I think this is good idea since I've started noticing many unusually patterns of `@importFrom` usage in the wild. 

Would you be interested in proving a PR? I think it would be worth also automatically running `devtools::document(roclets = "namespace")` to update the namespace, and it's worth at least considering if it should re-run `pkgload::load_all()`.

I think it's also worth considering if the `function` argument should be required, since it's very easy to use `@import` incorrectly.

**Comment by hadley** [comment]
We might also consider more aggressively steering people towards using `use_package_doc()` first. I'd be fine requiring it for a first pass at this function.

**Comment by malcolmbarrett** [comment]
Happy to! I think requiring a package doc makes since, since IMO that's one of the bigger benefits of this approach. Maybe using `@import` should produce a poke the way `use_package(..., type = "Depends")` does?

Should the pkgload/devtools commands be `ui_todo()`s instead since usethis doesn't depend on them (and devtools depends on usethis), or is there a safe way to call devtools with that arrangement?

**Comment by hadley** [comment]
I'd prefer to just not facilitate any use of `@import` to start with.

I think it's worth trying `pkgload::load_all()` for the first pass — add it to suggests and then check it's installed with `check_installed()`

**Comment by hadley** [comment]
BTW I don't follow this repo, so feel free to ping me (`@hadley`) when you submit a PR.
