### ISSUE TITLE
Changes to default package doc template

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1372]
* Drop `@keywords internal`
* Add `@includeRmd ../README.md` (or whatever the correct path is)

This would provide a convenient way to access the README from within the package — it looks the package doc itself is listed at the top of (e.g.) `help(package = rtweet)`

**Comment by hadley** [comment]
Hmmm, tried this with usethis itself — the correct path is `@includeRmd README.md` but then I get

```
Updating usethis documentation
ℹ Loading usethis
File man/figures/logo.png not found in resource path
Error: pandoc document conversion failed with error 99
Execution halted
```

So some path isn't set correctly

**Comment by jennybc** [comment]
> Add `@includeRmd ../README.md` (or whatever the correct path is)

Ooh, this is an interesting idea!

**Comment by hadley** [comment]
I'm no longer convinced that this is worthwhile.
