### ISSUE TITLE
Feature request: browse_rseek()

### ISSUE THREAD

**Issue by rossellhayes** [r-lib/usethis#1386]
A common workflow I go through in R is to encounter an issue, open a browser window, search the issue on [rseek](https://rseek.org), then return to R. I love the speed that `usethis` brings with functions like `browse_github()`, and think `browse_rseek()` could be a great addition. While it moves further from the `browse_` family's focus on packages, I think it would be helpful for day-to-day R use.

I'd be happy to submit a pull request if this feature would be useful. This could also include `browse_google()`/`browse_duckduckgo()`/etc. if that would be beneficial.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package:  developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
