### ISSUE TITLE
pkgdown bug: `use_tidy_github_actions` hyperlink points to wrong page and 404s

### ISSUE THREAD

**Issue by russHyde** [r-lib/usethis#1392]
Observed Behaviour:
- On the pkgdown website for usethis,
- On the page for [use_github_actions()](https://usethis.r-lib.org/reference/github_actions.html)
- The hyperlink for "use_tidy_github_actions()" that is presented in the "see also" section goes to `https://usethis.r-lib.org/reference/use_tidy_github_actions.html` and 404s.

Expected behaviour:
It should go to `https://usethis.r-lib.org/reference/tidyverse.html`, where the description for `use_tidy_github_actions()` is defined.

**Comment by jennybc** [comment]
This actually looks like a pkgdown problem.

@maelle Will you see if you agree?

**Comment by maelle** [comment]
I'll explore further, I notice downlit finds the right link.

``` r
downlit::highlight("usethis::use_tidy_github_actions()")
#> [1] "<span class='nf'>usethis</span><span class='nf'>::</span><span class='nf'><a href='https://usethis.r-lib.org/reference/tidyverse.html'>use_tidy_github_actions</a></span><span class='o'>(</span><span class='o'>)</span>"
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9001)</sup>

**Comment by maelle** [comment]
Fixed in pkgdown via https://github.com/r-lib/pkgdown/pull/1586

**Comment by jennybc** [comment]
Thanks @maelle.
