### ISSUE TITLE
add helper browse_github_labels() to open labels page on Github ? 

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#1393]
I often use **usethis** to quickly open a page on Github with one of the repo. 

There already are a few but not `browse_github_labels()` , which I was looking for. Not useful very often I recognize. but this could be added at the end of `usethis::use_github_labels()` to open the labels page on github (which is useful to see the change, and delete what should be deleted manually)

What about adding this small helper ? 
```r
browse_github_labels = function (package = NULL) {
  view_url(github_url(package), "labels")
}
```

or more maybe make `browse_github()` more customizable so that `browse_github(path = "labels")` is possible ? 
```r
browse_github <- function(package = NULL, path = NULL) {
  view_url(github_url(package), path))
}
```

Asking in an issue before doing any PR.

**Comment by jennybc** [comment]
I think this is too special case-y. I think I would just `browse_github_issues()` and click on "Labels".
