### ISSUE TITLE
Site created with use_tidy_pkgdown() takes time to take effect (initially indicates index.html is not found)

### ISSUE THREAD

**Issue by billdenney** [r-lib/usethis#1397]
I just started trying to use a pkgdown site for one of my repositories (https://github.com/billdenney/pknca) with `usethis::use_tidy_pkgdown()`.

It successfully created the `gh-pages` remote branch, and the GitHub actions built the site in the gh-pages branch, but the site is not showing up (http://billdenney.github.io/pknca/).

`index.html` is in the gh-pages branch, but some aspect of `use_tidy_pkgdown()` did not get a fully-functional site running as I expected it to.

As an aside:
I found [here](https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site) that "It can take up to 20 minutes for changes to your site to publish after you push the changes" which I think would be useful to notify the user because I just pushed a site, and it is not showing up about 20 minutes later.

**Comment by billdenney** [comment]
I have an update the next morning.  When I checked today, the site was active with no additional changes from me.  I think that the "aside" above is the accurate summary of the issue:  GitHub sometimes takes a bit of time for changes to propagate.

I think that providing the fact that it may take some time for the site to become active due to GitHub time to publish changes could be useful to users (i.e. it would have saved me some attempted troubleshooting time rather than just waiting ~6 hours).

So, could `use_github_pages()` add a message indicating that "Settings changes for GitHub pages may take >1 hour to become effective"

**Comment by jennybc** [comment]
I'm not keen to (re-)document the behaviour of an external service and I've also found that adding more messaging and docs is a double-edged sword.

You did find:

> I found here that "It can take up to 20 minutes for changes to your site to publish after you push the changes"

which I think is the right / best outcome.
