### ISSUE TITLE
Make git config key comparison/search case insensitive

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1401]
Here, at the very least:

https://github.com/r-lib/usethis/blob/29192cf7e485c7bb29b64d6394aac13909a30880/R/utils-git.R#L63

For background, see https://github.com/r-lib/gert/issues/133

**Comment by malcolmbarrett** [comment]
Ohhh, this explains a lot. I bumped into/was confused about that issue when thinking through #1371.
