### ISSUE TITLE
Generalizing `use_github_action()` with `use_github_file()`

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/usethis#1407]
I'm very interested in the pattern used by `use_github_action()` as an alternative to `use_template()` when it makes sense to host files somewhere else (e.g. we want to make it easier to grab a file from R but don't necessarily want to host it in the package itself because it's useful for other purposes). 

I think it would be nice to refactor that internal code to a new exported function, e.g. `use_github_file()`, which could then be called by `use_github_action()`. The pattern for reading a file from GitHub is, thankfully, not that complex, but it's very useful. 

Happy to prepare a PR if it seems like it's worth exporting that code

**Comment by hadley** [comment]
Yeah, a PR would be appreciated thanks.

**Comment by jennybc** [comment]
Very related to #1483
