### ISSUE TITLE
How to develop with `withr::defer()`

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#141]
@hadley added this function, presumably because it's handy in the tests:

``` r
scoped_temporary_package <- function(dir = tempfile(), env = parent.frame()) {
  old <- proj$cur
  withr::defer(proj_set(old), envir = env)

  utils::capture.output(create_package(dir, rstudio = FALSE, open = FALSE))
  invisible(dir)
}
```

But when you're *developing* the test, you can't actually call `scoped_temporary_package()`. You get this:

```
 Error in withr::defer(proj_set(old), envir = env) : 
  attempt to defer event on global environment 
```

Which makes life rather difficult. I think I've run up against this in some other recent experiment with `withr::defer()`. What to do? Is there something that could or should be different about `withr::defer()`? Or should I finesse this inside `scoped_temporary_package()`?

cc @jimhester

**Comment by jennybc** [comment]
Related Q: should I move `scoped_temporary_package()` into `tests/testthat/helper.R`? It is only used in tests. It is currently in `R/proj.R` which seems a bit odd to me.

**Comment by jimhester** [comment]
That is why I added a conditional for the global environment in a similar function in [pkginstall](https://github.com/r-lib/pkginstall/blob/a4819e5580c7e76c8ed8943a2312531b6ec3263d/tests/testthat/helper.R#L21-L26)
```r
  # We do not want to unlink files if we are calling this from the R console,
  # useful when debugging.
  is_globalenv <- identical(envir, globalenv())
  if (!is_globalenv) {
    defer(unlink(d, recursive = TRUE), envir = envir)
  }
```

I would probably move it to helper.

**Comment by jennybc** [comment]
Thanks @jimhester. I was thinking of just such an escape hatch to ease development, so glad to see this.
