### ISSUE TITLE
I copy and Paste my CAP but it keeps stating 

### ISSUE THREAD

**Issue by derekholste** [r-lib/usethis#1411]
![Capture](https://user-images.githubusercontent.com/81579243/113461208-8479fd80-93d0-11eb-8365-28b4064ad6ef.JPG)

**Comment by jennybc** [comment]
Please update the gh package.

`install.packages("gh")`

https://github.com/r-lib/gh/issues/148

**Comment by derekholste** [comment]
Thank you so much it worked!
