### ISSUE TITLE
Should `gh_token_help()` report bad credentials (401)?

### ISSUE THREAD

**Issue by zkamvar** [r-lib/usethis#1413]
I know this is covered in `git_sitrep()`, but I'm wondering if `gh_token_help()` should report if a discovered token throws a 401 error.

For example, I have a token whose access I just revoked, but `gh_token_help()` does not report any errors:

``` r
usethis::gh_token_help()
#> ● GitHub host: 'https://github.com'
#> ● Host online: TRUE
#> ● Personal access token for 'https://github.com': '<discovered>'
#> ℹ Call `gh::gh_whoami()` to see info about your token, e.g. the associated user
#> ℹ To see or update the token, call `gitcreds::gitcreds_set()`
#> ✔ If those results are OK, you are good go to!
#> ℹ Read more in the 'Managing Git(Hub) Credentials' article:
#>   https://usethis.r-lib.org/articles/articles/git-credentials.html
gh::gh_whoami()
#> Error in gh_process_response(raw): 
#> GitHub API error (401): 
#> Message: Bad credentials
#> Read more at https://docs.github.com/rest
```

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jennybc** [comment]
Note to self: Just did some troubleshooting with Tareef, who had an invalid PAT in `.Renviron` and had set a good PAT via gitcreds. I need to recreate this situation and see what help `git_sitrep()` and `gh_token()` offers (or not). And also make sure Happy Git is sending people to these functions for troubleshooting.

**Comment by DataStrategist** [comment]
Just leaving a note here as a concise list to check in case nothing seems to be working:

The PAT could be saved in multiple places on a Windows computer. The following should be checked:
 - the `.Renviron` in the User's `HOME`. By default that's in "Documents"
 - Project specific `.Renviron`s, which would be in the root of project folders
 - The Windows Credential Manager. Find it by typing "Credential Manager" into the Windows search. Switch to "Windows Credential" and delete anything that says GitHub on it
 - The Windows Environment Variables. Make sure you check both the user and system locations.

I somehow managed to have random PATs saved in each one of these categories. Deleting everything let me follow normal instructions.
