### ISSUE TITLE
`use_tidy_upkeep_issue()`

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1416]
Create an issue to bring your package up to spec with latest changes. Would divide into sections with dates (maybe just years?) so you can choose how far to go back (and some should be re-run regularly).

Initial ideas:

* `use_tidy_description()` + `devtools::document()`
* `use_tidy_github_actions()`
* Remove check environments from `cran-comments.md`
* start with `devtools::document()` for very old. Maybe check that uses md?
* Update R dependency to match GitHub actions

**Comment by jennybc** [comment]
Use test that 3e?

**Comment by hadley** [comment]
What do you think of this presentation? I always lean towards minimal, but maybe it's worth being more verbose?

## Pre-history

* [ ] `use_readme_rmd()`
* [ ] `use_roxygen_md()`
* [ ] `use_pkgdown_github_pages()` / `use_github_links()`
* [ ] `urlchecker::url_check()`
 
## 2020

* [ ] `use_testhat()` and upgrade to 3e
* [ ] `use_package_doc()`

## 2021

* [ ] Remove check environments from `cran-comments.md`

## Evergreen

* [ ] `devtools::document()`
* [ ] `use_tidy_description()`
* [ ] `use_tidy_github_actions()`; check R version in DESCRIPTION

**Comment by jennybc** [comment]
I like this proposed organisation.

Should we add something about spelling? I confess I'm pretty foggy on what exactly maintaining WORDLIST buys for us and yet I keep doing it in many packages and I don't get bugged about spelling by CRAN 🤷‍♀️

**Comment by jennybc** [comment]
Another change I make when I return to something is renaming `.R` and test files so that `use_r()` / `use_test()` is happy to do my bidding.

**Comment by hadley** [comment]
I think spelling needs to emerge of more a standard; I've added `use_r`/`use_test()` alignment above. We might want to add a little helper to facilitate? (But not sure what it would be called since it could only report, not take action)

**Comment by hadley** [comment]
Maybe call this something like `use_spring_clean_issue()`? I like the idea of getting spring cleaning into the name somehow since that implies an annual cadence (which feels about right to me).

**Comment by DavisVaughan** [comment]
`use_annual_upkeep_issue()` matches our new "upkeep" issue label

**Comment by hfrick** [comment]
another checkbox could be to update artisanal deprecation messages to use `lifecycle`

**Comment by hadley** [comment]
I think we should try and get this into this release. I’m happy to take a first pass when I’m back.
