### ISSUE TITLE
Why doesn't `use_lifecycle()` import 1 function from lifecycle?

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1419]
Looking at #1418, I wondered:

Why doesn't `use_lifecycle()` also do `roxygen_ns_append("@importFrom lifecycle deprecated")` (or, now that it exists, `use_import_from("lifecycle", "deprecated")`)?

I'm pretty sure it should.

**Comment by hadley** [comment]
What should happen if `package-doc.R` doesn't exist?

**Comment by hadley** [comment]
It prompts you to create it; which seems fine to me.
