### ISSUE TITLE
Should `use_tidy_github_actions()` also set R version?

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1421]
We could either figure out what version we official support with a little code, or we could remember to update it once a year.

**Comment by jennybc** [comment]
I assume you mean in DESCRIPTION?

It sort of feels weird for `use_tidy_github_actions()` to touch DESCRIPTION, but maybe it's OK.

Maybe `use_tidy_description()` is a better (or equally bad) place to hang this?

**Comment by hadley** [comment]
I encounter this when I run `use_tidy_github_action()` because that's what sets up the range of R versions to test, so it feels fairly natural to me.

**Comment by jennybc** [comment]
Oh, true. The GitHub Actions do effectively determine which versions of R are supported.

**Comment by hadley** [comment]
`use_tidy_github_action()` now uses relative version numbers, so this idea doesn't feel right to me any more. Moving to #1416 instead.
