### ISSUE TITLE
CodeCov requires a CODECOV_TOKEN

### ISSUE THREAD

**Issue by statnmap** [r-lib/usethis#1435]
I set up codecov for my package but the report would not be created without the `CODECOV_TOKEN` set in the environment variable of my GitHub Action.   
Maybe one of the two function I used below to set up the action could add a message to set up this Token to be able to use it on a CI. I think `use_coverage()` is the place because this token will be necessary for other CI than Actions.   
You can use the link of the Badge created to inform the developers to follow this link a get the Token that will be shown on the page.  

```
usethis::use_coverage()
usethis::use_github_action("test-coverage")
```

**Comment by malcolmbarrett** [comment]
I was under the impression that public repositories didn't need a token (and I don't recall setting one up any time recently); likewise, the actions template does not use a token (https://github.com/r-lib/actions/blob/master/examples/test-coverage.yaml). I'm now having issues as well, however: https://github.com/malcolmbarrett/code.cov.test/runs/2421122388?check_suite_focus=true.

A little issue surfing suggests that the uploader might have changed very recently to address similar issues: https://community.codecov.io/t/add-support-of-uploading-from-cirrus-ci-without-token/1028/32

@jimhester might have a better sense of what's happening here.

**Comment by jimhester** [comment]
Yes @malcolmbarrett that is correct, public repositories don't need a token, it is possible this was a temporary regression in the codecov.io service, it seems to be resolved now.

**Comment by jennybc** [comment]
I'm going to close, assuming this was part of the dust settling while Codecov responded to their breach. We can reopen if I'm wrong.

**Comment by Moohan** [comment]
Could this be related to [caveat b](https://github.com/codecov/example-r#caveats), i.e. non-travis CI needs a token ?

**Comment by privefl** [comment]
I get this error "Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue." (cf. https://github.com/privefl/bigstatsr/actions/runs/3224863943/jobs/5276476155#step:5:5054).

Is it related?
If so, how to get the token, and where to put it?

**Comment by statnmap** [comment]
You need to go to CodeCov.io and get your TOKEN from there.  
In your case, I guess this is: 
https://app.codecov.io/gh/privefl/bigstatsr/settings
And add it to the secrets variables for GitHub Actions with `CODECOV_TOKEN`

**Comment by statnmap** [comment]
Codecov says that if you use their GitHub Action, you should not need token for public repositories: https://github.com/codecov/codecov-action#usage  

Can you start by updating the "test-coverage" action. I think it was fixed.
```r
usethis::use_github_action("test-coverage")
```

**Comment by privefl** [comment]
Using a global `CODECOV_TOKEN` seems to have solved my problem.
Thanks for the tip
