### ISSUE TITLE
use_data Error in if (any(mismatch <- res != res2))

### ISSUE THREAD

**Issue by igordot** [r-lib/usethis#1436]
This started as a bug report, but the solution is provided, so it's probably a feature request.

I used `use_data()` in the past without issues. I ran it today and am suddenly getting an error:

```
> usethis::use_data(iris, internal = TRUE)
✓ Setting active project to '/path/project'
Error in if (any(mismatch <- res != res2)) { : 
  missing value where TRUE/FALSE needed
> usethis::use_data(iris, internal = FALSE)
Error in if (any(mismatch <- res != res2)) { : 
  missing value where TRUE/FALSE needed
```

This is the `reprex` version:

``` r
usethis::use_data(iris, internal = TRUE)
#> Warning in path_file(base_path): restarting interrupted promise evaluation
#> Error: Path '/private/var/folders/lj/80zz6n91631_lb6h3l2m3hq4f503zw/T/RtmpxGe7oy/reprex-1263e29e32f61-pure-tayra/' does not appear to be inside a project or package.
```

It turns out the problem was a blank line in `DESCRIPTION`. It wasn't very obvious from the error message. It might be outside the scope of `usethis`, but perhaps there is a way to catch those errors more elegantly.

**Comment by malcolmbarrett** [comment]
What did the `DESCRIPTION` file look like? Is there a minimum version that produces this error?

**Comment by igordot** [comment]
You can just add a blank line to `DESCRIPTION`.

For example, from:

```
Description: More about what it does (maybe more than one line)
    Use four spaces when indenting paragraphs within the Description.
License: MIT + file LICENSE
```

To:

```
Description: More about what it does (maybe more than one line)
    Use four spaces when indenting paragraphs within the Description.

License: MIT + file LICENSE
```

**Comment by malcolmbarrett** [comment]
Thanks! This is actually an issue in desc, which reads the `DESCRIPTION` file in `use_data()`. Any attempt to read a file like that with desc fails. Because it's not a usethis issue, I'm going to close this in favor of resolving it in desc

**Comment by igordot** [comment]
Thank you for following up.
