### ISSUE TITLE
actions having trouble with pandoc

### ISSUE THREAD

**Issue by mkoohafkan** [r-lib/usethis#1439]
For some reason, one of my packages (out of more than 10) is having trouble with finding/installing a recent pandoc version. The action was created using the default `usethis::usegithub_actions()`. Package builds fine locally.

relevant parts of description:
```
Depends: R (>= 3.5)
Imports: stats
Suggests:
    knitr (>= 1.33),
    rmarkdown (>= 2.7),
    tidyverse,
    lubridate,
    testthat
VignetteBuilder: knitr
```

Vignette header:
```
---
title: "Decision Support Curves"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Decision Support Curves}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

GitHub Actions error log:

```
* installing the package to build vignettes
* creating vignettes ... ERROR
Error: --- re-building ‘curve-creation.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.
Error: Error: processing vignette 'curve-creation.Rmd' failed with diagnostics:
The 'markdown' package should be installed and declared as a dependency of the 'culvrt' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
--- failed re-building ‘curve-creation.Rmd’
```

**Comment by malcolmbarrett** [comment]
Likely you need to add `- uses: r-lib/actions/setup-pandoc@v1` to your `step` field, as in some of the other actions scripts (e.g. https://github.com/r-lib/actions/blob/0d6c4b3efe82090bc03e99c585d9e89003117931/examples/check-standard.yaml#L42)

**Comment by mkoohafkan** [comment]
Thanks, that did it! I guess with all my other packages I had used `use_tidy_github_actions()` which includes that step by default.
