### ISSUE TITLE
usethis for "Non-R scripts in packages"

### ISSUE THREAD

**Issue by Shicheng-Guo** [r-lib/usethis#1444]
How usethis to handle "Non-R scripts in packages" situation? for example, I have perl script in my R package. 

`If your package requires one of these interpreters or an extension then this should be declared in the ‘SystemRequirements’ field of its DESCRIPTION file. (Users of Java most often do so via rJava, when depending on/importing that suffices unless there is a version requirement on Java code in the package.)
`
Thanks.

**Comment by malcolmbarrett** [comment]
I'm not sure I totally understand your question. Are you wondering where to put the perl script or how to document it in the `DESCRIPTION` file? If you are calling the script via `system()` or something similar, putting it in `inst/` is a reasonable place, then get the path with `system.file()` or `fs::path_package()`. 

usethis doesn't have have an opinion about handling or documenting perl, though. Other languages, like C and C++, have more opinionated approaches via the R packages that support them, and usethis supports them with `use_*()` functions like `use_cpp11()`. Nothing like that exists for perl, so it depends on how you're using it.

**Comment by Shicheng-Guo** [comment]
So if we have `Perl/Java` script in our R package, for example in `inst/`, we should manually handle the `DESCRIPTION` requirement.

**Comment by malcolmbarrett** [comment]
Yes, that's right; usethis doesn't have any templates for those languages, although it does support automatically updating `SystemRequirements` for other languages (C/C++). Basically, usethis wraps `desc::desc_set("SystemRequirements", ...)` to set requirements for a few cases, if you want to know how to do it programmatically

**Comment by malcolmbarrett** [comment]
This seems like it addressed your question, so I'm going to close this. If you have more questions, I think StackOverflow or RStudio Community would be the right place
