### ISSUE TITLE
Feature request: Add environment variables to .Renviron

### ISSUE THREAD

**Issue by muschellij2** [r-lib/usethis#1448]
I would like to add environment variables to `.Renviron` programmatically.  This behavior seems less dangerous than injecting code via `.Rprofile`.  The use case that I'm envisioning is if a JSON for authorization exists, then you can add it to the `.Renviron` so that be loaded for auto-authorization.

For example, google* set of package from @MarkEdmondson1234's work https://github.com/cloudyr/googleComputeEngineR/blob/d62f8989571cfe9cfbeb97250808aee6e29f9cb4/R/options.R#L4have the ability to have a auth file specified (e.g. `GCE_AUTH_FILE`).

If this already exists (including outside `usethis`) I couldn't find it.  I'm envisioning something like:

```r
add_variable_r_environ = function(
  scope = c("user", "project"),
  envvar,
  value,
  overwrite = FALSE) {
  
  env = Sys.getenv()
  if (!envvar %in% names(env)) {
    if (!overwrite) {
      stop(envvar, " is already set and overwrite = FALSE. ",
           "If you set these in R, please Restart R.")
    } else {
      warning(envvar, " is already set, we are appending definition to ", 
              ".Renviron, so you may need to tidy .Renviron file")
    }
  }  
  
  # taken from usethis::edit_r_environ
  path <- r_environ_path(scope = scope)
  
  if (!readRenviron(path)) {
    stop("Renviron file is malformed according to base::readRenviron")
  }
  values = readLines(path, warn = FALSE)
  out_value = c(
    paste0("# Added at ", Sys.time(),  " from add_variable_r_environ"),
    paste0(envvar, ' = "', value, '"')
  )
  values = c(values, out_value)
  writeLines(values, path, sep = "\n")
  return(readRenviron(path))
}
```

This allows you set up a project with certain environment variables as opposed to something like:
```r
if (file.exists(json)) {
   Sys.setenv(GCE_AUTH_FILE = json)
}
```

There are other use cases, but this was the most direct I had on hand.

**Comment by jennybc** [comment]
It's a deliberate choice that we don't edit `.Renviron` here in usethis (and I also don't do it in, say, gargle). To me, this feels like overstepping a bound and I don't want the responsibility. `.Renviron` can contain some rather powerful secrets, which often aren't backed up anywhere, and I prefer that the user do such an edit for themselves.

(BTW you don't have to restart R after editing `.Renviron`, though it's probably a good idea. You can also call `readRenviron(path)`.)

**Comment by MarkEdmondson1234** [comment]
This is in `googleAuthR` (and so available to `googleComputeEngineR`) via `gar_setup_edit_renviron()` - the setup functions example similar to yours:

https://github.com/MarkEdmondson1234/googleAuthR/blob/73221f3cf5a561cbb17fe04943ce85e2130204ff/R/setup_wizard.R#L198-L217

I am now of course more nervous about it given Jenny's reasons to not include it, but its certainly helped in my day to day.  Perhaps I'll add a warning or similar, but the tip on `readRenviron()` is appreciated. 

I do extensively use environment arguments mostly as its an agnostic, non-R way to point to configuration files, and in GCE's example can then be used on the VM startup to pass through configuration to R.

**Comment by muschellij2** [comment]
Thanks @jennybc - wasn't sure if it was intentional or not.  Makes sense.  @MarkEdmondson1234 - I'll check out `add_renviron`.  The one thing I like is that you can specify `scope`, but you have to pass in the non-exported `usethis:::scoped_path_r` function.

My use case is to have a package/set of scripts strictly control and check the `.Renviron` for a tightly controlled set of environment variables inside of small projects, but I think this is too narrow to expose a function.

**Comment by jennybc** [comment]
I've always decided to stop at perhaps emitting exactly what they need to put in `.Renviron`, maybe putting this on the clipboard even, maybe opening the file for them to edit. But I don't actually make changes myself.

Also, I tend to think this sort of config is for a user who isn't accepting default behaviour and therefore is more advanced and/or motivated. And they can edit `.Renviron` themselves!

I think if it's really important to do stuff automagically, you should probably create and consult a config file that your package totally "owns" and then it's less scary to edit it.
