### ISSUE TITLE
Default README mentioning installing from CRAN is potentially confusing for new package authors

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#1451]
The default README issue template mentions the package can be installed from CRAN.
This can be confusing to first time package authors, and also users who encounter the readme without having the package actually submitted and approved.

It makes it seem like the package is (somehow) already on CRAN, just by adding the readme. Particularly if this step was done in combination with doing other things, like setting up CI, a package author could get a mistaken impression about the CRAN status of their package.

It will always be wrong for packages which are never submitted to CRAN (which may very well be the majority). It will also be incorrect at least temporarily when a package is first being developed and not yet on CRAN.

The alternative (just showing the devel installation instructions) is also problematic if the instructions are not changed when the package is submitted to CRAN.

But I think generally the authors who submit to CRAN are more capable of changing the installation instructions appropriately than first time R package authors many of whom many never submit a package to CRAN.

**Comment by jennybc** [comment]
In other README ruminations, we've also argued the other way 'round, i.e. that very few READMEs should offer instructions for installing the dev version. Because very few people should be installing a dev version. But perhaps that mostly applies to tidyverse / r-lib packages.

But yeah it would make sense to figure out how to help more packages get installation instructions appropriate to their situation.

**Comment by jimhester** [comment]
Yeah, but I am pretty sure the number of packages which at some point `use_readme()` and are never put on CRAN is higher than the reverse.

I agree the current default is probably best for tidyverse packages, but we are also the group of developers who could most easily change the installation instructions as needed.

Perhaps usethis could query to see if the package is on CRAN and use the appropriate installation method? Though we would have to have some way to update the instructions, maybe in a sitrep function?

**Comment by hadley** [comment]
What if we change the default to use `install_github()` and then in `use_release_issue()` add a bullet point (only shown on first release) to update the install instructions in the README?

**Comment by hadley** [comment]
Also related: https://github.com/r-lib/pkgdown/issues/1299#issuecomment-905508921 — pkgdown is likely to add support for a div that's only shown on the dev version of the site.

**Comment by jimhester** [comment]
Yeah I think that is a good solution @hadley
