### ISSUE TITLE
Update Suggests section of DESCRIPTION file after adding vignette using use_vignette()

### ISSUE THREAD

**Issue by Rishi0812** [r-lib/usethis#1456]
Can we add "markdown" to Suggests section of the DESCRIPTION file as we will get an error in the build without it in the github r-CMD-check build checker.

I think this error is caused as the author of knitr updated few parameters recently. You can check the link below for more information,

https://github.com/yihui/knitr/issues/1864

The example of the change in description file to be created as default by use_this can be considered like:
```r
Suggests: 
    knitr,
    rmarkdown,
    markdown
```

**Comment by Rishi0812** [comment]
I have created a PR to address this issue,
https://github.com/r-lib/usethis/pull/1457
Hope this works!

**Comment by malcolmbarrett** [comment]
In that post, Yihui says:

> [This is for] package authors who use R Markdown vignettes based on the vignette engine `knitr::knitr`

In usethis, we use `knitr::rmarkdown` in the vignette template:

https://github.com/r-lib/usethis/blob/0d6522474e35c78391a0b54dc12d63a63a5ce05a/inst/templates/vignette.Rmd#L6

Yihui also says:

> Similarly, if your vignette is based on the vignette engine knitr::rmarkdown, you have to declare the dependency on rmarkdown

Which we already do:

https://github.com/r-lib/usethis/blob/3ce70d7480095d6a6a4a1263485917f1f93a853c/R/vignette.R#L56

So, based on that info, it doesn't seem like this is necessary. The markdown package is essentially retired (it's in maintenance mode only), so we probably wouldn't want to be in a situation where we're adding it to all packages, even if it's a soft dependency

**Comment by malcolmbarrett** [comment]
By the way, are you actually seeing an error on a project because of this?

**Comment by Rishi0812** [comment]
> By the way, are you actually seeing an error on a project because of this?

YES, I did get an error in r-CMD-check build tool in GitHub to include markdown in suggest

**Comment by malcolmbarrett** [comment]
Are you able to share it? Are you using `knitr::knitr` in your vignette?

**Comment by Rishi0812** [comment]
> Are you able to share it? Are you using `knitr::knitr` in your vignette?

Yes Sure, I'll attach a ss below, No I'm not using the `knitr::knitr`, I'm using the default function, which is the `knitr::rmarkdown`
![Screenshot_20210625-004952](https://user-images.githubusercontent.com/56316487/123320598-97bfe380-d54f-11eb-99b9-cc5659ba6bcf.jpg)

**Comment by malcolmbarrett** [comment]
I think your issue is actually because you don't have pandoc installed, e.g. 

https://github.com/r-lib/usethis/blob/3ce70d7480095d6a6a4a1263485917f1f93a853c/.github/workflows/R-CMD-check.yaml#L54

**Comment by Rishi0812** [comment]
> I think your issue is actually because you don't have pandoc installed, e.g.
> 
> https://github.com/r-lib/usethis/blob/3ce70d7480095d6a6a4a1263485917f1f93a853c/.github/workflows/R-CMD-check.yaml#L54

This might be the problem, Thank you, I'll be closing this issue then
