### ISSUE TITLE
`pr_finish()` could return to the PR's base branch

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/usethis#1459]
In some workflows where [feature and dev branches are used](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows), pull requests may be based against non-default branches, e.g. a PR to `dev` rather than `main`. It would be very helpful if `pr_finish()` could detect this using the `base` item in the PR info from the GitHub API response and move back to the base branch, if available locally, rather than the default branch.

**Comment by jennybc** [comment]
With the coming default branch support, the `pr_*()` functions are poised to lean much harder on the idea of default branch. This is all in the name of helping people detect a change in default branch and to adapt ASAP, with as little pain as possible.

Honestly I don't have the appetite to introduce even more complexity about what branch which should switching back to, pulling from etc.

Sorry but this is a #wontfix 😬
