### ISSUE TITLE
`~/.gitignore` is ignored

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#1461]
I realize that I can't provide a reproducible example; I need to tell a story (sorry).

I recently upgraded my Mac to Big Sur. Of course, one of the first things I did was `install.packages("usethis")`, then `usethis::git_vaccinate()`.

I kept on seeing `.DS_Store` wanting to be committed, which was odd, so I kept adding it to local `.gitignore`. Finally, this morning, I said "enough" and started digging into it.

Of course, my `~/.gitignore` file looked OK, so a little investigation brought me to this [SO answer](https://stackoverflow.com/a/32487076), and sure enough, I did not have git's `core.excludesfile` set.

So I set `core.excludesfile`, and `.DS_Store` "went away".

I see that in [`edit_git_ignore()`](https://github.com/r-lib/usethis/blob/0d181f6905392b0c543a490d6047613334404bad/R/edit.R#L222-L227), if there is no global gitignore file: you set `core.excludesfile`, then call `git_vaccinate()`.

However, if you just call [`git_vaccinate()`](https://github.com/r-lib/usethis/blob/b3de0d7c18fdc1d0de0dc7616cbb85e823db9dac/R/git.R#L565-L568), I don't see that `core.excludesfile` gets set. I think this is how I got here.

As well [`git_vaccinated()`](https://github.com/r-lib/usethis/blob/b3de0d7c18fdc1d0de0dc7616cbb85e823db9dac/R/git.R#L570-L574) does not check that `core.excludesfile` is set.

I have a few ideas on some solutions, and will be happy to contribute, but I figure I'd let you react first.

Thanks!

**Comment by malcolmbarrett** [comment]
Ah, by a lucky coincidence, I just got a new computer and ran `git_vaccinated()` a couple of days ago, and it resulted in the same problem for me. Consider it reproduced!

**Comment by ijlyttle** [comment]
I'm glad (?) it is reproducible!

My thought is that [`git_ignore_path()`](https://github.com/r-lib/usethis/blob/0d181f6905392b0c543a490d6047613334404bad/R/edit.R#L232-L251) is used by [`edit_git_ignore()`](https://github.com/r-lib/usethis/blob/0d181f6905392b0c543a490d6047613334404bad/R/edit.R#L222-L227), [`git_vaccinate()`](git_vaccinate()) and [`git_vaccinated()`](https://github.com/r-lib/usethis/blob/b3de0d7c18fdc1d0de0dc7616cbb85e823db9dac/R/git.R#L570-L574).

Perhaps it could contain the logic for `core.excludesfile`, moving some of the logic out of `edit_git_ignore()`:

If `scope == "user"`, it could:

- consult `core.excludesfile`
  
- if `core.excludesfile` not set:
  - check if files `"~/.gitignore"` or `"~/.gitignore_global"` exist (in that order):
      - if either files exists, use that value.
      - if neither file exists, use (and create) `"~/.gitignore"`, tell user via `ui_done()`. 
  - set `core.excludesfile`, tell user via `ui_done()`
        
- return value of `core.excludesfile`

**Comment by jennybc** [comment]
This all seems reasonable to me 👍
