### ISSUE TITLE
usethis::use_version(which = "minor") fails in non-interactive session when there are uncommitted changes in the repo

### ISSUE THREAD

**Issue by JamieCranston** [r-lib/usethis#1462]
usethis::use_version(which = "minor") fails in non-interactive session when there are uncommitted changes in the repo.

Would it be possible to add an option for this function to suppress interactive behaviour to get around this?

```r
usethis::use_version(which = "minor")
✔ Setting active project to '/home/jupyter/x/y'

Error: User input required, but session is not interactive.
Query: There are uncommitted changes and you're about to bump version
Do you want to proceed anyway?
Traceback:

1. usethis::use_version("minor")
2. challenge_uncommitted_changes(msg = "There are uncommitted changes and you're about to bump version")
3. ui_yeah("{msg}\nDo you want to proceed anyway?")
4. ui_stop(c("User input required, but session is not interactive.", 
 .     "Query: {x}"))
```

https://stackoverflow.com/questions/68443898/how-can-i-use-usethis-to-increase-version-of-my-r-package-on-google-cloud-platfo/68452631#68452631

**Comment by jennybc** [comment]
I suspect this is a road we don't want to go down (adding arguments and *ad hoc* tweaks like this). `use_version()` (and, basically, the whole package) is designed with interactive use as the primary use case.
