### ISSUE TITLE
Use use_tidy_style() within Rmarkdown?

### ISSUE THREAD

**Issue by davidgibsonp** [r-lib/usethis#1471]
Is it possible to apply `use_tidy_style()` to R chunks with a R Markdown/Notebook file?

**Comment by jennybc** [comment]
usethis gets its tidy styling from the styler package, so I think you should pursue this question by doing some research via styler and/or rmarkdown. I don't know the answer off the top of my head.

This issue doesn't appear to be a bug report or a specific feature request, so it's more suitable for [RStudio Community](https://community.rstudio.com).
