### ISSUE TITLE
Factor out usethis::ui_* functions

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/usethis#1479]
I recently wanted to cut down the dependency graph of one of my packages and then I realised `usethis::ui_info()` and friends are the only functions I use from {usethis}, but they have the following recursive dependencies:

```
# output from renv::snapshot(type = 'explicit', packages = 'usethis')
# CRAN ===============================
- curl          
- R6            [* -> 2.5.1]
- askpass       [* -> 1.1]
- cli           [* -> 3.0.1]
- clipr         [* -> 0.7.1]
- crayon        [* -> 1.4.1]
- credentials   [* -> 1.3.1]
- desc          [* -> 1.3.0]
- fs            [* -> 1.5.0]
- gert          [* -> 1.3.2]
- gh            [* -> 1.3.0]
- gitcreds      [* -> 0.1.1]
- glue          [* -> 1.4.2]
- httr          [* -> 1.4.2]
- ini           [* -> 0.3.1]
- jsonlite      [* -> 1.7.2]
- lifecycle     [* -> 1.0.0]
- magrittr      [* -> 2.0.1]
- mime          [* -> 0.11]
- openssl       [* -> 1.4.4]
- purrr         [* -> 0.3.4]
- rappdirs      [* -> 0.3.3]
- rlang         [* -> 0.4.11]
- rprojroot     [* -> 2.0.2]
- rstudioapi    [* -> 0.13]
- sys           [* -> 3.4]
- usethis       [* -> 2.0.1]
- whisker       [* -> 0.4]
- withr         [* -> 2.4.2]
- yaml          [* -> 2.2.1]
- zip           [* -> 2.2.0]
```

In particular, they also have system dependencies (git2r/gert -> libgit2, openssl -> openssl,  curl -> curl, fs -> GNU make etc.). Would it make sense to give these UI functions another home and re-export in {usethis}?

This seems quite a lot for printing text to the console. {crayon} and {cli} and {glue} would be the recursive dependencies required here I think.

**Comment by malcolmbarrett** [comment]
I think you'll likely want to review this vignette from cli: https://cli.r-lib.org/articles/usethis-ui.html

**Comment by lorenzwalthert** [comment]
Thanks @malcolmbarrett, indeed that's exactly what I need 😄. Wondering if there should be a note in the docs of these usethis functions that point to that vignette.

**Comment by assignUser** [comment]
@lorenzwalthert that's exactly what we needed, I think you can close this 🙂👍
