### ISSUE TITLE
Check for newest CoC at release

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r-lib/usethis#1484]
First, thank you for all of your hard work on `usethis`, it is a great package.

### Brief description of the problem

I noticed that the [Code of Conduct](inst/templates/CODE_OF_CONDUCT.md) that is stored in the [templates directory](https://github.com/r-lib/usethis/tree/master/inst/templates) is not up to date with the latest version, i.e., version 2.0 instead of version 2.1. The [latest version available from EthicalSource](https://github.com/EthicalSource/contributor_covenant/blob/release/CODE_OF_CONDUCT.md) is always available on their GitHub site. 

### Potential solution

Instead of https://github.com/r-lib/usethis/blob/3385e148c06b13a34406a455d7a7ab0785993201/R/code-of-conduct.R#L36-L41 you could read the text directly from the following link
```
https://github.com/EthicalSource/contributor_covenant/blob/release/CODE_OF_CONDUCT.md
```
which always has the latest version.

I think that it might also be a good idea to create a test in `usethis` that would alert `usethis` developers when the version has changed. I am not sure how often users of `usethis`  should update their Code of Conduct within their package or project. I looked on the [issue list](https://github.com/EthicalSource/contributor_covenant/issues) for Contributor Covenant and found a few requests, e.g., [871](https://github.com/EthicalSource/contributor_covenant/issues/871) and [167](https://github.com/EthicalSource/contributor_covenant/issues/167), to facilitate updating to the newest version upon release but I don't know if that is a good idea or not. 

Thank you for implementing a Code of Conduct and facilitating others to do so as well.

**Comment by jennybc** [comment]
Interesting idea. I am somewhat hesitant to have live download of something we don't control, as it also means that if the content disappears or moves, now our function doesn't work. I'm pretty sure we have had to fiddle with this link in the past for these reasons.

One alternative that partially mitigates the original problem is to add a custom release bullet reminding us to check for CoC updates every time we release. This might be the right compromise.

**Comment by kellijohnson-NOAA** [comment]
Thanks @jennybc for the alternative. Would there be a way for others to easily add the check as well? I find that I have good intentions of keeping things up to date but just don't have the bandwidth to do things by memory.

**Comment by jennybc** [comment]
The general mechanism for leaving yourself reminders like this, in the devtools world, is to have an unexported function that returns the nudges:

https://devtools.r-lib.org/reference/release.html#details

> You can add arbitrary extra questions by defining an (un-exported) function called `release_questions()` that returns a character vector of additional questions to ask.

If you do that, both `devtools::release()` and `usethis::use_release_issue()` will include your custom release checks along with the standard ones.

**Comment by kellijohnson-NOAA** [comment]
Brilliant. Thanks for sharing and for the discussion regarding updating the Code of Conduct.

**Comment by jennybc** [comment]
I think we should add a release bullet to check for latest CoC, if project has a CoC. Or maybe just a nudge to rerun `use_code_of_conduct()`?

**Comment by hadley** [comment]
I think usethis itself should gain a bullet that remind us to update the CoC, but for other packages I think this is better to do as part of spring cleaning, not routinely with every release.
