### ISSUE TITLE
make usethis::use_*_license() friendly with github's license overview

### ISSUE THREAD

**Issue by brshallo** [r-lib/usethis#1494]
For example, running `usethis::use_mit_license()` creates both a LICENSE and a LICENSE.md file. Github seems to look to the LICENSE file to generate it's overview of the rights associated with the repo (therefore github thinks the repo is using an 'other' license type and doesn't give an overview of the LICENSE).

# Example

In [brshallo/pwiser](https://github.com/brshallo/pwiser) I have just a LICENSE file and github knows which license I'm using (MIT): 
![image](https://user-images.githubusercontent.com/30487784/134727603-52f153c7-7589-4e57-b00e-3ddd8cdd10f4.png)

and shares a helpful overview of the rights when viewing the LICENSE
![image](https://user-images.githubusercontent.com/30487784/134727630-b58e4ae2-1304-48dd-a36a-79b2772a866b.png)

However in [brshallo/piececor](https://github.com/brshallo/piececor) I have both a LICENSE and LICENSE.md file and github does not know which license I am using (though again I'm using MIT):
![image](https://user-images.githubusercontent.com/30487784/134727670-2b5dbab3-b0b6-4327-9f2d-b3cac38cf05f.png)

And does not offer a helpful overview of rights when viewing either LICENSE or LICENSE.md:
![image](https://user-images.githubusercontent.com/30487784/134727687-708c9dac-5bed-4b47-88d1-833b1d3a45ad.png)

Given that most new R packages are on github, it would be nice if `usethis::use_*_license()` produced file(s) in a way that made them friendly to github's rights overview. 

(Though could be better to open with github to suggest that their license overview identifies the file containing the actual license type...)

**Comment by jennybc** [comment]
I believe the current arrangements do what's necessary to **satisfy CRAN** and, as much as possible, GitHub at the same time. This part of usethis was updated rather recently.

**Comment by jennybc** [comment]
I'm closing this as I believe doing what's optimal for GitHub implies doing something that's unacceptable to CRAN.

https://r-pkgs.org/license.html#key-files

https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Licensing

**Comment by malcolmbarrett** [comment]
@brshallo FWIW, I've seen others who'd like this, so it may be worth following up with GitHub directly to better support the structure we have to use

**Comment by brshallo** [comment]
Just opened [topic](https://github.community/t/including-a-license-and-a-license-md-file-has-github-not-provide-license-overview-impacts-r-packages/203480) with github support community.
