### ISSUE TITLE
quiet local project?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#1498]
I wonder how to make usethis quiet when using a local project. Apologies if I missed something obvious!

``` r
tmpdir <- withr::local_tempdir()
#> Setting deferred event(s) on global environment.
#>   * Execute (and clear) with `withr::deferred_run()`.
#>   * Clear (without executing) with `withr::deferred_clear()`.
usethis::with_project(
  path = tmpdir,
  {
    usethis::ui_done("yeah")
    print(getOption("usethis.quiet"))
  },
  quiet = TRUE,
  force = TRUE,
  setwd = FALSE
)
#> ✓ yeah
#> NULL
#> ✓ Setting active project to '<no active project>'
usethis::local_project(path = tmpdir, quiet = TRUE, force = TRUE, setwd = FALSE)
usethis::ui_done("yeah")
#> ✓ yeah
getOption("usethis.quiet")
#> NULL
```

<sup>Created on 2021-09-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

For `with_project()` I was able to get the result I expected by adding a line `withr::local_options(usethis.quiet = quiet)` right before `force(code)`.

**Comment by maelle** [comment]
Or maybe the current behaviour is the expected one?

I would have expected not to get the "yeah" but that might be my misunderstanding the docs. I can get the behaviour I expected by adding `.local_envir = .local_envir` to https://github.com/r-lib/usethis/blob/5fd76ed12fdc1c36c63033cae711d6358ee2556d/R/proj.R#L131

Very useful functions in any case. :ok_hand:

**Comment by jennybc** [comment]
Thanks for the great example and the solution!
