### ISSUE TITLE
use_options ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/usethis#1500]
I find myself always going back to Hadley's book when I want to use options in packages, so I can copy paste and edit the below code:

```
.onLoad <- function(libname, pkgname) {
  op <- options()
  op.devtools <- list(
    devtools.path = "~/R-dev",
    devtools.install.args = "",
    devtools.name = "Your name goes here",
    devtools.desc.author = "First Last <first.last@example.com> [aut, cre]",
    devtools.desc.license = "What license is it under?",
    devtools.desc.suggests = NULL,
    devtools.desc = list()
  )
  toset <- !(names(op.devtools) %in% names(op))
  if(any(toset)) options(op.devtools[toset])
  
  invisible()
} 
```

A `use_options()` function might : 

* create a "zzz.R" file if there is none yet and no `.onLoad` function is defined anywhere
* write a `.onLoad`  function in "zzz.R" if none is defined anywhere
* have the body of `.onLoad` start with the code below if no usethis comments are found:

```
  ## usethis options: start
  op <- options()
  op.PKGNAME <- list(
   # edit and add options below
    PKGNAME.your_option = "your_default"
  )
  toset <- !(names(op.PKGNAME ) %in% names(op))
  if(any(toset)) options(op.PKGNAME[toset])
  ## usethis options: end ​
```

I'd use it often! Happy to contribute a PR  if it helps.

Thanks for the great work.

PS: Does it make sense to have `use_onload()` and `use_onattach` too to just create "zzz.R" and the empty function ?

**Comment by jennybc** [comment]
Very related to #1136

**Comment by hadley** [comment]
I no longer believe that this is the right approach for options, so I don't think we should implement. There's some discussion in https://github.com/tidyverse/style/issues/111, but I'm likely to write up a more formal proposal in the next few weeks/months.
