### ISSUE TITLE
Consistent Default for `copyright_holder` Parameter?

### ISSUE THREAD

**Issue by GregYannes** [r-lib/usethis#1503]
I'm not certain this is either a bug report or a feature request, as this issue might simply reflect a deliberate choice by the authors to follow a legal convention of which I am unaware.

-----

Regarding the `copyright_holder` parameter, its (nonexistent) [default behavior](https://github.com/r-lib/usethis/blob/0d6522474e35c78391a0b54dc12d63a63a5ce05a/R/license.R#L141) in `use_proprietary_license()`
```
use_proprietary_license <- function(copyright_holder) {
  # ...
    copyright_holder = copyright_holder
  #...
}
```
seems inconsistent with its [default behavior](https://github.com/r-lib/usethis/blob/0d6522474e35c78391a0b54dc12d63a63a5ce05a/R/license.R#L60) in `use_mit_license()`
```
use_mit_license <- function(copyright_holder = NULL) {
  # ...
    copyright_holder = copyright_holder %||% glue("{project_name()} authors")
  #...
}
```
and (possibly) with its own [documentation](https://usethis.r-lib.org/reference/licenses.html#arguments):

> Name of the copyright holder or holders. This **defaults to "package name authors"**; you should only change this if you use a CLA to assign copyright to a single entity.

-----

As it stands, the call
```
use_proprietary_license()
```
throws the following error:
```
Error in use_proprietary_license() : 
  argument "copyright_holder" is missing, with no default
```
In contrast to the seamless call
```
use_mit_license()
```
the former seems a bit of a hiccup in the workflow.

# Question #

Should the convention ("package name authors") apply by default to a proprietary license

> Copyright 2021 `<package-name>` authors. All rights reserved.

just as it does to the MIT license?

> YEAR: 2021
> COPYRIGHT HOLDER: `<package-name>` authors

**Comment by hadley** [comment]
I think the current behaviour is correct:

* If you're using `use_ proprietary_license()` your company probably owns the copyright, so you really need to supply it explicitly.
* `use_mit_license()` makes no claim about which specific individuals hold the copyright, which is the most sensible default.
