### ISSUE TITLE
Append new internal data to existing `R/sysdata.rda` file

### ISSUE THREAD

**Issue by kiernann** [r-lib/usethis#1512]
Currently, you can save multiple objects in `R/sysdata.rda` using the `...` argument.

 ```r
use_data(obj1, obj2, internal = TRUE)
```

However, if you are trying to _add_ a new object to an existing `R/sysdata.rda` file, you have to first manually read the objects and then write them together along with the new one.

It would be nice if there were some kind of `append` argument to automate this process.

**Comment by msberends** [comment]
It's a pity to learn that an `add` or `append` argument will not be supported.

For those coming here for a solution (as I did), check here on StackOverflow: https://stackoverflow.com/a/73426349/4575331. Basically comes down to this simple flow:

```r
# create new environment
my_new_env <- new.env(hash = FALSE)

# load current internal data into this new environment
load("R/sysdata.rda", envir = my_new_env)

# add or replace some objects
my_new_env$dataset123 <- data.frame(a = 1, b = 2)

# save the environment as internal package data
save(list = names(my_new_env),
     file = "R/sysdata.rda",
     envir = my_new_env)
```
