### ISSUE TITLE
Formatting of packages listed in `Config/Needs/website`

### ISSUE THREAD

**Issue by hfrick** [r-lib/usethis#1533]
I have a DESCRIPTION which contains

```
Config/Needs/website:
    tidymodels,
    tidymodels/parsnip,
    tidyverse/tidytemplate
```

and when I run `use_tidy_description()`, it gets changed to 

```
Config/Needs/website:tidymodels, tidymodels/parsnip,
    tidyverse/tidytemplate
```

I find the first version easier to read, similar to how the packages in Depends, Imports, etc are listed. Is that something that might get changed?

**Comment by jennybc** [comment]
This is really https://github.com/r-lib/desc/issues/117
