### ISSUE TITLE
Give helpful error message when issue number is passed instead of pr number in `pr_fetch`

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#1538]
Sometimes I happen to enter the issue number associated to a PR that fixes it instead of the actual PR number. 
Obviously this does not work but the issue is not quite helpful on the why 

```r
> usethis::pr_fetch(424)
Error in gh_process_response(raw) : 
GitHub API error (404): 
Message: Not Found
Read more at https://docs.github.com/rest/reference/pulls#get-a-pull-request

URL not found: https://api.github.com/repos/rstudio/distill/pulls/424
Type .Last.error.trace to see where the error occurred
```

Correct number was 426... 

an idea would be to give a helpful error like 

* This does not seem to be a PR  number in rstudio/distill - did you enter an issue number instead ? 

Or if we can do clever thanks to Github API ? not sure it is worth it - a message reminding to check if the number was PR and not issue would already help not remember what is happening each time. 

Just an idea - feel free to discard.

**Comment by jennybc** [comment]
I am OK with this error message. It's not clear that more wrapping is a net positive.
