### ISSUE TITLE
Make sure all new projects meet one project criterion

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#154]
Re: self-consistency.

Should all new projects meet at least one of the criteria usethis uses to recognize a project?

https://github.com/r-lib/usethis/blob/973bcabceb36a73094d6a96094006b2a57fe0865/R/proj.R#L3-L9

In practice, I think this means creating a `.here` file whenever `rstudio = FALSE`.

cc @hadley

**Comment by hadley** [comment]
Yes! I just encountered this too.
