### ISSUE TITLE
Feature request: configure build tools

### ISSUE THREAD

**Issue by daynefiler** [r-lib/usethis#1540]
I would appreciate functionality to automatically configure the build tools when creating a new package. I can see the settings are stored in `.Rproj.user/[hash]/build_options`. I initially guessed the `[hash]` comes from the RStudio version, but it doesn't appear to. Now I think it might be user-specific? 

Anyway, this might be more appropriate for the rstudioapi, then usethis could simply call it? Happy to work on it with a little direction.

**Comment by jennybc** [comment]
I'm not sure I understand what you mean by "build tools" here.

Are you talking about this?

<img width="674" alt="Screen Shot 2021-12-01 at 4 11 27 PM" src="https://user-images.githubusercontent.com/599454/144334458-b0c84247-d93d-4b1a-a3db-3aee036d4782.png">

**Comment by daynefiler** [comment]
Yes, the specific thing I ran into today after creating a new package with usethis was having to manually go in and configure Roxygen to roxygenize on build & restart. Checking the box, I believe, edits `.Rproj.user/[hash??]/build_options` to include:

`auto_roxygenize_for_build_and_reload="1"`

**Comment by jennybc** [comment]
We do have code in usethis for programmatically editing `foo.Rproj`, as that is what powers `use_blank_slate(scope = "project")`.

I'm pretty sure edits in that file are as far as usethis will ever go re: project config. I don't view `.Rproj.user/*` as something tools other than the IDE should be touching.

My main takeaway is wondering why that particular piece of config (`auto_roxygenize_for_build_and_reload="1"`) does not also reside in the `.Rproj` file 🤔

(Even if it were in the `.Rproj` file, I'm not convinced this feature would see broad enough use to justify a function in usethis.)

**Comment by daynefiler** [comment]
Those are all fair points. I would argue that changing the to blank slate is not functionally different from configuring when to roxygenize in a project. If the goal of including functionality like `use_blank_slate` is to automate setting up a new project, ***for me***, setting when to roxygenize is a crucial part of configuring a project.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, given the discussion above I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
