### ISSUE TITLE
Versioning GH actions

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/usethis#1541]
It seems like usethis always uses the `v1` tag of the actions repo, which was fine until now, but I am about to update the `setup-r-dependencies` action and the related example workflows that use it in a way that might not be backwards compatible. 

So I would create a new branch for this (or just use `main`?). For a short time this branch would live as the "devel" workflow, and then we will make it the default, and then `r-lib/actions` will receive a `v2` tag. 

So it seems like it would make sense to support multiple tags/branches in usethis as well. usethis could  pick up the latest release / tag from the `r-lib/actions` repo, this could be the default.

**Comment by jennybc** [comment]
How do you envision usethis discovering the default ref from `r-lib/actions`?

This will be a fairly easy adjustment, since all the workflow-downloading functions now route through `use_github_file()`, which already has a `ref` argument.

**Comment by gaborcsardi** [comment]
usethis could pick up the latest release / tag from the `r-lib/actions` repo.

**Comment by jennybc** [comment]
Yeah I meant ... latest in terms of the date modified? Or latest in an alpha/numerical sense?

**Comment by gaborcsardi** [comment]
Sorry, yes, we would order the numbers. I don't think we would have version numbers, so just removing the `v` and then ordering the rest numerically seems good?

**Comment by jennybc** [comment]
OK, sounds good.

**Comment by jennybc** [comment]
I'm beginning to question defaulting to the latest tag in `r-lib/actions`, in a version number sense.

Because, for example, right now that might deliver the not-yet-quite-official `v2` to people who probably want `v1`. And you can imagine the same cycle repeating itself in the future whenever there's a need to start experimenting with `v3`.

@gaborcsardi Do you think there should be some other mechanism (tag, probably) for designating the version that's currently considered the best for more users?

**Comment by gaborcsardi** [comment]
Aren't pre-releases marked in the API?

**Comment by gaborcsardi** [comment]
```
gh::gh("/repos/r-lib/actions/releases")
```

```
...
    "node_id": "RE_kwDODMSrZM4DSp0x",
    "tag_name": "v1",
    "target_commitish": "master",
    "name": "v1",
    "draft": false,
    "prerelease": false,
...
    "node_id": "RE_kwDODMSrZM4DSVjI",
    "tag_name": "v2",
    "target_commitish": "master",
    "name": "v2 ",
    "draft": false,
    "prerelease": true,
...
```

So we can choose the latest release that is not a pre-release.

**Comment by jennybc** [comment]
Also, do you think the `.yaml` should contain a comment re: which `r-lib/action` ref was used? Either baked into it on the `r-lib/action` side or incorporated by `use_github_action_*()`. My motivation is to help people know which version they currently are using.

**Comment by jennybc** [comment]
> Aren't pre-releases marked in the API?

I thought we were going to consult a generic tag. But OK yes if we're talking about releases, I see how it will work.

**Comment by gaborcsardi** [comment]
Yeah, it would be nice to include the source, sure. If you want a proper reference, that would be the sha, because the tag will change. But maybe the tag is enough.

**Comment by jennybc** [comment]
Just FYI I think part of my confusion with how this is going to work in practice stems from the fact that, I think, the `v1` tag in `r-lib/actions` has previously just been a tag, not a release.

Re: including the source, I suppose it might make sense to record the ref and, assuming it's not already a SHA, also the SHA.
