### ISSUE TITLE
`proj_activate()` fails with tilde shortcut (`~/`)

### ISSUE THREAD

**Issue by arisp99** [r-lib/usethis#1543]
Up until recently, I have been able to specify paths when activating RStudio projects using the tilde shortcut (`~/`) for home. For some reason, this no longer works. I believe this issue arose from my recent update to `usethis`.

```r
# Home path shortcut no longer works
proj_activate("~/path/to/directory/")
#> Error: Directory '~/path/to/directory/' does not exist.

# Full path specification works
proj_activate("/Users/user/path/to/directory/")
#> ✓ Opening '/Users/user/path/to/directory/' in new RStudio session
```

**Comment by jennybc** [comment]
I don't think anything has changed re: path handling in the recent release of usethis (2.1.0, which had 2 patches, 2.1.2 and 2.1.3; all released in October 2021).

Other possible explanations include the recent fs release and (waves hands) Windows.

If you are motivated to gather data re: fs, you could install fs at versions 1.5.0 and at 1.5.1 and see if that's the difference. usethis has long used fs for all filesystem work, so a breaking change in fs could easily be transmitted via usethis. FWIW I think fs will have a small release soon, as there is at least one known regression (https://github.com/r-lib/fs/issues/325). However, I don't see an obvious connection between what you're reporting and that specific fs issue.

fs takes a very specific stance re: what home directory is, which is sadly not a simple matter on Windows.

https://fs.r-lib.org/reference/path_expand.html

So if you're on Windows, changes in the USERPROFILE, HOMEDRIVE, HOMEPATH, or R_FS_HOME environment variables could also have an effect.

**Comment by arisp99** [comment]
Thanks for the detailed response. I did a bit more digging into the issue following your advice. I am on macOS so this is not an issue with Windows home directory shenanigans. This issue is indeed a result of https://github.com/r-lib/fs/issues/325 and arises with `{fs}` v1.5.1 (the tilde shortcut works for `{fs}` v1.5.0). 

`proj_activate()` calls `check_path_is_directory()` which then calls `fs::file_exists()`. As per the `{fs}` issue, `fs::file_exists()` no longer performs path expansion and, therefore, `proj_activate()` fails. As you mentioned, the authors of `{fs}` will make a new release in a couple of days, which should solve this issue. 

As this is not a problem with `{usethis}`, I will close this issue. Thanks for your help!
