### ISSUE TITLE
Consider adding `devtools::check_mac_release()` to the release issue checklist

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1546]
Definitely needs to wait a while, for the new macOS builder (https://mac.r-project.org/macbuilder/submit.html) to accumulate some usage.

Even then, it's not completely clear we (tidyverse) want or need this, given that we mostly develop on macOS and, increasingly, on M1.

It could be an item we only add to the checklist if there's a `src/` directory.

**Comment by hadley** [comment]
I think it's probably less likely we need this because the mac CRAN builder doesn't set any special check env vars (and is unlikely to in the future), and hence tends to be very close to our GHA mac checks.
