### ISSUE TITLE
git_default_branch_rename() does not always change local branch

### ISSUE THREAD

**Issue by jesse-ross** [r-lib/usethis#1550]
My organization has changed our default branch name, but we still have a lot of old-fashioned repositories which need to be changed. While testing the git_default_branch_rename() workflow, I noticed that results can be inconsistent with respect to renaming of local branches.

Here is the same reprex giving inconsistent results. In the first run, the local branch is correctly changed, while in the second it is not. The two outcomes appear to happen roughly equally often.

*Warning: the reprex will create a repository on your github each time it is run!*

``` r
# Create an empty repo in temp directory
repo_name <- file.path(tempdir(), uuid::UUIDgenerate())
retval = dir.create(repo_name)
if (! retval) {
  stop(paste("could not create directory", repo_name))
} 

# Initialize the repo and cause it to have default branch master,
# no matter what user has for their git config init.defaultBranch
gert::git_init(path = repo_name)
gert::git_branch_checkout("master", repo = repo_name, orphan = TRUE)
#> [1] "refs/heads/master"
writeLines("Here is a repo with default branch master.",
           file.path(repo_name, "README.md"))
gert::git_add("README.md", repo = repo_name)
#> # A tibble: 1 x 3
#>   file      status staged
#>   <chr>     <chr>  <lgl> 
#> 1 README.md new    TRUE
gert::git_commit("initial commit", repo = repo_name)
#> [1] "e92a83bc79b9bad7683ec74e4ebe73ca3e748b28"

# Set project to the new repo location
usethis::proj_set(repo_name)
#> v Setting active project to 'C:/Users/jross/AppData/Local/Temp/1/RtmpmGvG5X/3574e8ec-a0e3-4146-bd47-354f0663c49e'
usethis::use_github(private = TRUE)
#> i Defaulting to 'https' Git protocol
#> v Creating private GitHub repository 'jesse-ross/3574e8ec-a0e3-4146-bd47-354f0663c49e'
#> v Setting remote 'origin' to 'https://github.com/jesse-ross/3574e8ec-a0e3-4146-bd47-354f0663c49e.git'
#> v Pushing 'master' branch to GitHub and setting 'origin/master' as upstream branch
#> * Open URL 'https://github.com/jesse-ross/3574e8ec-a0e3-4146-bd47-354f0663c49e'

# Change default branch remotely and locally
usethis::git_default_branch_rename()
#> v Default branch of the source repo 'jesse-ross/3574e8ec-a0e3-4146-bd47-354f0663c49e' has moved: 'master' --> 'main'
#> * Be sure to update files that refer to the default branch by name.
#>   Consider searching within your project for 'master'.
#> v Default branch of local repo has moved: 'master' --> 'main'
```

<sup>Created on 2021-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

``` r
# Create an empty repo in temp directory
repo_name <- file.path(tempdir(), uuid::UUIDgenerate())
retval = dir.create(repo_name)
if (! retval) {
  stop(paste("could not create directory", repo_name))
} 

# Initialize the repo and cause it to have default branch master,
# no matter what user has for their git config init.defaultBranch
gert::git_init(path = repo_name)
gert::git_branch_checkout("master", repo = repo_name, orphan = TRUE)
#> [1] "refs/heads/master"
writeLines("Here is a repo with default branch master.",
           file.path(repo_name, "README.md"))
gert::git_add("README.md", repo = repo_name)
#> # A tibble: 1 x 3
#>   file      status staged
#>   <chr>     <chr>  <lgl> 
#> 1 README.md new    TRUE
gert::git_commit("initial commit", repo = repo_name)
#> [1] "bf1c2b8635af16c42ba4ce17337edaadb9b78593"

# Set project to the new repo location
usethis::proj_set(repo_name)
#> v Setting active project to 'C:/Users/jross/AppData/Local/Temp/1/RtmpADmNbU/f6b9d0d1-99db-4525-a819-af9dfafdf7c3'
usethis::use_github(private = TRUE)
#> i Defaulting to 'https' Git protocol
#> v Creating private GitHub repository 'jesse-ross/f6b9d0d1-99db-4525-a819-af9dfafdf7c3'
#> v Setting remote 'origin' to 'https://github.com/jesse-ross/f6b9d0d1-99db-4525-a819-af9dfafdf7c3.git'
#> v Pushing 'master' branch to GitHub and setting 'origin/master' as upstream branch
#> * Open URL 'https://github.com/jesse-ross/f6b9d0d1-99db-4525-a819-af9dfafdf7c3'

# Change default branch remotely and locally
usethis::git_default_branch_rename()
#> v Default branch of the source repo 'jesse-ross/f6b9d0d1-99db-4525-a819-af9dfafdf7c3' has moved: 'master' --> 'main'
#> * Be sure to update files that refer to the default branch by name.
#>   Consider searching within your project for 'master'.
#> v Default branch of local repo is 'master'. Nothing to be done.
```

<sup>Created on 2021-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jennybc** [comment]
First, let me thank you for providing complete runnable code!

I ran the exact code above and saw the expected, desirable behaviour both times. So I couldn't reproduce the problem you're experiencing.

The only thing that comes to mind is that maybe we need to add some `Sys.sleep()` in between renaming the default branch of the source repo and syncing the local default branch with the remote.

The easiest workaround that sort of tests my hypothesis is for you to call `git_default_branch_rediscover()` after `git_default_branch_rename()`. If you are doing this programmatically, add a bit of sleep in between. This should catch un-done local work, when "the bad thing" happens and is a no-op otherwise.

Is there any additional colour here? Are you running GitHub Enterprise? Do you experience other operations via the GitHub API that feel like there is some lag?

**Comment by jesse-ross** [comment]
Hi! Thanks for this quick and helpful response. I made the change you suggested, and it caught the un-done work.


``` r
# Create an empty repo in temp directory
repo_name <- file.path(tempdir(), uuid::UUIDgenerate())
retval = dir.create(repo_name)
if (! retval) {
  stop(paste("could not create directory", repo_name))
} 

# Initialize the repo and cause it to have default branch master,
# no matter what user has for their git config init.defaultBranch
gert::git_init(path = repo_name)
gert::git_branch_checkout("master", repo = repo_name, orphan = TRUE)
#> [1] "refs/heads/master"
writeLines("Here is a repo with default branch master.",
           file.path(repo_name, "README.md"))
gert::git_add("README.md", repo = repo_name)
#> # A tibble: 1 x 3
#>   file      status staged
#>   <chr>     <chr>  <lgl> 
#> 1 README.md new    TRUE
gert::git_commit("initial commit", repo = repo_name)
#> [1] "29dfa745c31b33451ff7d441e9dfd61b493886dc"

# Set project to the new repo location
usethis::proj_set(repo_name)
#> v Setting active project to 'C:/Users/jross/AppData/Local/Temp/1/RtmpSoRcI1/8e899cae-389f-4897-b631-c998efadfe88'
usethis::use_github(private = TRUE)
#> i Defaulting to 'https' Git protocol
#> v Creating private GitHub repository 'jesse-ross/8e899cae-389f-4897-b631-c998efadfe88'
#> v Setting remote 'origin' to 'https://github.com/jesse-ross/8e899cae-389f-4897-b631-c998efadfe88.git'
#> v Pushing 'master' branch to GitHub and setting 'origin/master' as upstream branch
#> * Open URL 'https://github.com/jesse-ross/8e899cae-389f-4897-b631-c998efadfe88'

# Change default branch remotely and locally
usethis::git_default_branch_rename()
#> v Default branch of the source repo 'jesse-ross/8e899cae-389f-4897-b631-c998efadfe88' has moved: 'master' --> 'main'
#> * Be sure to update files that refer to the default branch by name.
#>   Consider searching within your project for 'master'.
#> v Default branch of local repo is 'master'. Nothing to be done.

# Rest a little while to let GitHub get its head together,
# and then test for un-done local work
Sys.sleep(5)
usethis::git_default_branch_rediscover()
#> i Default branch of the source repo 'jesse-ross/8e899cae-389f-4897-b631-c998efadfe88': 'main'
#> v Default branch of local repo has moved: 'master' --> 'main'
```

<sup>Created on 2021-12-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


As for additional color, our organization is just an organization on GitHub, and the reprex just uses my personal account.

The reason that I am looking into this was because `git_default_branch_rename()` didn't do all of the work for another user in the organization. However, their setup was fundamentally different from my reprex: they had a bit of an odd ["Fork (of ours)"](https://happygitwithr.com/common-remote-setups.html) setup where they had already created the `main` branch locally (but not deleted `master`), and configured it to push to `main` on their origin repo (where they also hadn't deleted `master`). They were then doing pull requests from `origin:main` to `upstream:master`.

In this case the upstream repo had its default branch changed correctly, but it seems that `git_default_branch_rename()` got confused and didn't change the local repo or origin. I would be happy to try to create a reprex for this case if that would be useful. In any case, here is their output from that operation:

```r
usethis::git_default_branch_rename()
✓ Setting active project to '/Users/XXXXXX/Documents/R/lake-temperature-model-prep'
✓ Default branch of the source repo 'USGS-R/lake-temperature-model-prep' has moved: 'master' --> 'main'
• Be sure to update files that refer to the default branch by name.
  Consider searching within your project for 'master'.
Error in libgit2::git_branch_move : 
  failed to write reference 'refs/heads/main': a reference with that name already exists.
```

**Comment by jennybc** [comment]
> they had a bit of an odd "Fork (of ours)" setup where they had already created the `main` branch locally (but not deleted `master`), and configured it to push to `main` on their origin repo (where they also hadn't deleted `master`). They were then doing pull requests from `origin:main` to `upstream:master`.

Well, I'm glad to know something unusual was going on. I'm going to let this particular sleeping dog lie. Our determination of the local default branch, by necessity, involves some heuristics, and the situation described above basically is not accounted for. But I don't think this comes up often enough for me make the code even more complicated. My goal is to facilitate the canonical "move `master` to `main`" and I'm OK accepting the partial failure here.

**Comment by jesse-ross** [comment]
OK; thanks for having a look!
