### ISSUE TITLE
allow to pipe use_test and use_r

### ISSUE THREAD

**Issue by CorradoLanera** [r-lib/usethis#1552]
Quite often, I write 
``` r
use_test("fun_name")
use_r("fun_name")
```

So, I have to repeat the function's name twice every time for each function.

I have noticed that `use_r` returns `TRUE`, while `use_test` returns the path to `test-fun_name.R`. So I started to 

``` r
basename(use_test("fun_name")) |>
  use_r()
```

Have you some suggestions to implement that in a "nicer" way? It could be of interest to provide, e.g., something like

``` r
# use_tdd <- 
# use_r_test <-
# use_testr <-
# ...
function(name = NULL, open = rlang::is_interactive()) {
  use_test(name = name, open = open)
  use_r(name = name, open = open)
}
```

Or, can `use_r` and `use_test` both return their input (i.e., `name`) so that they would be _pipable_ directly?

**Comment by SERTwitter** [comment]
I'm not sure how consistent we are about the type of information we return, but are you aware that if have `fun_name.R` open, `use_test()` (without any arguments) will create/open a matching test file? That seems like it captures your workflow. Similarly, running `use_r()` with a test file open will open the matching R file

**Comment by malcolmbarrett** [comment]
I'm not sure how consistent we are about the type of information we return, but are you aware that if have fun_name.R open, use_test() (without any arguments) will create/open a matching test file? That seems like it captures your workflow. Similarly, running use_r() with a test file open will open the matching R file

**Comment by CorradoLanera** [comment]
Yes, it is very useful. Anyway, I track the project's development in a file (e. g., `here("dev/00-setup.R")`). So, I don't use `use_r` and `use_test` interactively that often for the creation of the related files, but more to open "the other" quickly.

The present issue is mainly related on the creation of those development files. The main concern is in the logic: when I create a function (tracking it's creation) I would like the command executed is "one" for the script and it's test. That to be able to run it with a single `CTRL/CMD + RETURN`. Anyway, if I create an explicit function for that I have to re-create that quite every new function, and every new session when I open the project again. with the pipe, if I have a new function to create, I would simply add in `00-setup.R`

``` r
use_test("new_fun") |> use_r() 
```

execute it, and start coding it. Tracking everything, including the idea that it is a single step for me, for that function, the creation of the function itself and its test.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package because we're not prepared to support this way of using these functions. Re-thinking how data flows through these functions would be a lot of work, and you can already program up your own custom solution if needed. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
