### ISSUE TITLE
"Pull Request Helpers" vignette css broken

### ISSUE THREAD

**Issue by tanho63** [r-lib/usethis#1555]
It seems like there is meant to be some sort of CSS applied here to make the vignette code easier to understand:

> To make it more clear who runs which code, the code chunks in this article are color coded: code executed by the contributor appears in chunks with light gray background and code executed by the reviewer appears in chunks with beige background.

but it looks the two subsequent chunks have the same colours to me:

![image](https://user-images.githubusercontent.com/38083823/147859788-809170dc-6417-4b78-8d9e-4b86d6339494.png)

**Comment by hadley** [comment]
Link to rendered article: https://usethis.r-lib.org/articles/pr-functions.html#whats-a-pull-request
