### ISSUE TITLE
Bug: use_package() inserts an invalid version specification for integers

### ISSUE THREAD

**Issue by jzadra** [r-lib/usethis#1556]
`use_package("tidyselect", min_version = 1.0)` adds a line to the description that drops the `.0`, ie:

```
Imports:
   tidyselect (>= 1)
```

Which then causes the error `Error: invalid version specification ‘1’`

**Comment by ijlyttle** [comment]
I find it useful to think of a version "number" as a string rather than as a number, e.g. `2.0.0` is not a number.

When I provide the arg as a string, it works well:

```r
use_package("tidyselect", min_version = "1.0") 
```

**Comment by jzadra** [comment]
Yes great point.

**Comment by jennybc** [comment]
Yes, I consider this function to be working properly. Version numbers are really strings.
