### ISSUE TITLE
Using REUSE licensing specs with use_<license> functions

### ISSUE THREAD

**Issue by RichardJActon** [r-lib/usethis#1563]
As a long-term goal for the use license features in this package it would be nice to integrate with the REUSE license spec / tools: https://reuse.software/. They have some nice tooling and useful recommendations and utilities for including license information in each file e.g. if you are using APACHE or MIT code in a GPL project, and generally making it easier to manage multi-licensed projects.

**Comment by hadley** [comment]
This seems like a great idea, but I think it's out of scope for usethis. It would be a great idea for a new package though!
