### ISSUE TITLE
Order of fields in Authors@R in `use_description` / `create_package`

### ISSUE THREAD

**Issue by jtr13** [r-lib/usethis#1564]
I find this line perplexing:
https://github.com/r-lib/usethis/blob/d1c516d7b28eabcbaac8de4715fb351a73a4cbdc/R/description.R#L95

It's tempting to delete what appears to be an extra comma which of course is not a wise choice. Why not put role before email so the comma isn't necessary?

**Comment by hadley** [comment]
The third argument, which the comma skips, is `middle`

**Comment by jtr13** [comment]
Oh, that's what that is! In the wild it is causing problems for people creating their first packages. Could perhaps `email = ` and `role =` be added so the seemingly extra comma isn't necessary?
