### ISSUE TITLE
usethis contributing guide needs gert in a non-obvious way

### ISSUE THREAD

**Issue by nikosbosse** [r-lib/usethis#1565]
Not sure this qualifies for an issue, so please feel free to delete immediately. 
I was adding a CONTRIBUTING guide using usethis::use_tidy_contributing() which failed with a rather cryptic message about libgit2.so missing. 
This could easily be solved by installing the `gert` package. However, it was not immediately clear that this was the issue. Maybe it would be a good idea to check for the presence of the package and give a warning? 
Thank you very much for your efforts!

**Comment by jennybc** [comment]
gert is a formal dependency of usethis, listed in Imports, so it should not be possible to install usethis without also having gert installed, at an appropriate version.

So I'm not sure I follow what this is about. I.e. maybe something got wonky with your system?

**Comment by nikosbosse** [comment]
Potentially, Arch linux sometimes does funny things. But usethis definitely was installed (maybe it got installed as a dependency, not sure I actively installed it myself) and gert was not installed. 
I also called the function using `::` without having loaded `usethis` - not sure that made a difference. 

We could also just close this for now and I see if I can make a reprex using Docker. 
Thank you for your quick response!
