### ISSUE TITLE
`create_package()` should check if `.Rproj.user` is already in `.gitignore`

### ISSUE THREAD

**Issue by kalaschnik** [r-lib/usethis#1568]
Note that this feature suggestion applies only to existing git-enabled projects, where a `.gitignore` is likely to exist.

I just converted my project to a package using `usethis::create_package()` — I noticed in my diffs that `.Rproj.user` was appended to my .gitignore file. Yet, my `.gitignore` already contained `.Rproj.user` (along with the usual suspects: https://github.com/toptal/gitignore/blob/master/templates/R.gitignore).

It would be awesome if the `create_package()` process would respect an existing .gitignores file, by avoiding creating duplicated entries.

**Comment by jennybc** [comment]
It looks like `use_rstudio()` isn't very consistent with other functions in usethis w.r.t. writing over an existing file / adding-content-only-if-not-already-there.

Probably tackle together with #1569.

**Comment by jabenninghoff** [comment]
> Note that this feature suggestion applies only to existing git-enabled projects, where a `.gitignore` is likely to exist.
> 
> I just converted my project to a package using `usethis::create_package()` — I noticed in my diffs that `.Rproj.user` was appended to my .gitignore file. Yet, my `.gitignore` already contained `.Rproj.user` (along with the usual suspects: https://github.com/toptal/gitignore/blob/master/templates/R.gitignore).
> 
> It would be awesome if the `create_package()` process would respect an existing .gitignores file, by avoiding creating duplicated entries.

I noticed this same issue as well. It may be because https://github.com/toptal/gitignore/blob/master/templates/R.gitignore contains:

```
# RStudio files
.Rproj.user/
```

While `create_package()` writes:

```
.Rproj.user
```

I too would like to see `create_package()` match https://github.com/toptal/gitignore/blob/master/templates/R.gitignore.

**Comment by hadley** [comment]
This is going to affect very few people, and I'd argue that usethis is the reference here; if any change is needed, toptal should be the one to change. (It's also harmless to have both).
