### ISSUE TITLE
`create_package()` should not alter `RestoreWorkspace` and `SaveWorkspace` in `Rproj`

### ISSUE THREAD

**Issue by kalaschnik** [r-lib/usethis#1569]
Similar to #1568, I observed that `create_package()` was changing my intentionally set
- `RestoreWorkspace: No`
- `SaveWorkspace: No`

to 

- `RestoreWorkspace: Default`
- `SaveWorkspace: Default`

It would be great if `create_package()` would respect an existing `Rproj` file, and not alter existing entries.

**Comment by jennybc** [comment]
It looks like use_rstudio() isn't very consistent with other functions in usethis w.r.t. writing over an existing file / adding-content-only-if-not-already-there.

Probably tackle together with #1568.

**Comment by jennybc** [comment]
I am not able to induce this problem. First of all, when I create new projects, `RestoreWorkspace` and `SaveWorkspace` are already set to `No`. In addition, if I run `create_package()` in a pre-existing project (and proceed past the "are you sure you want to create a project within a project?" challenge), I am asked if I want to overwrite the existing `.Rproj` file. So one can opt-out of that or opt-in and then tweak the result.

So I think this is either solved or comes up in some workflow that is not one we're really designing for.
