### ISSUE TITLE
use_description_field() isn't done yet

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#157]
https://github.com/r-lib/usethis/blob/9df50f5df5c731740f68c7358f4e693130c965d0/R/helpers.R#L75-L84

Currently the case of "new value for existing field" + `overwrite = FALSE` seems overlooked. It's a silent no op. Should it error? Or at least say something?

I admit this is a low priority because `use_description_field()` is unexported, but I noticed while writing tests.

**Comment by jennybc** [comment]
Also, is it intentional that the `desc` object falls out the bottom?

**Comment by jennybc** [comment]
@hadley

**Comment by jennybc** [comment]
This case would fit into some new tests right here:

https://github.com/r-lib/usethis/blob/7ef71d2fb1463fb0ccbca8a41f9b5aeeee2596c3/tests/testthat/test-helpers.R#L15-L16

**Comment by hadley** [comment]
Yup that’s a mistake
