### ISSUE TITLE
Create new use_git_ignore_template based on toptal.com (former gitignore.io)

### ISSUE THREAD

**Issue by kalaschnik** [r-lib/usethis#1571]
`usethis` may benefit a lot from the API provided by https://www.toptal.com/developers/gitignore

For example,
`use_git_ignore_template(c("linux", "macos", "windows", "r"))`, would translate to the API response of:
https://www.toptal.com/developers/gitignore/api/linux,macos,windows,r

As you see the response link, the entries of line 2 could be parsed and recycled if a users wants to modify this.

My usual .gitignore has the following pattern:
```
# my stuff
raw/
subjectdata/
token.R

# gitignore.io part (DO NOT MODIFY HERE USE use_git_ignore_template() to update the components below)
# Created by https://www.toptal.com/developers/gitignore/api/linux,macos,windows,r
# Edit at https://www.toptal.com/developers/gitignore?templates=linux,macos,windows,r

### Linux ###
*~

# temporary files which can be created if a process still has a handle open of a deleted file
.fuse_hidden*
# ...
```

**Comment by kalaschnik** [comment]
You could even provide some "completion" list, so the user does not need to enter the correct search keys:
![gitignore-demo](https://user-images.githubusercontent.com/9831678/150531358-4ce43d9a-f152-4eca-af6d-8f61e43e97bf.gif)

all possible keys and the ignore content is here: https://github.com/toptal/gitignore/tree/master/templates

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: it seems like quite a lot of work for relatively little pay off,  relying on external service adds a new point of failure, and usethis doesn't really want to be in the business of managing your `.gitignore`. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
