### ISSUE TITLE
release_bullets() found if usethis loaded via devtools but not via library

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#1579]
* I created a toy package.
* I added an R script in it with

```r
release_bullets <- function(){
  c(
  "bla",
  "blop"
)
}
```

## What works

If I `devtools::load_all("../usethis")` then `devtools::load_all()` then `use_release_issue()`, my bullets are used (`env_has(env, "release_bullets")` is TRUE).

## What does not work

If I `library("usethis")` (same version, from GitHub) then `devtools::load_all()` then `use_release_issue()`, my bullets are not used (`env_has(env, "release_bullets")` is FALSE).

## What I also did not expect

I did not know / remember one had to load the package before creating the release issue.

**Comment by jennybc** [comment]
Looks like this was part of the deal from the very start:

> `use_release_issue()` will include additional bullets if your package includes `release_bullets()` function which returns a character vector (and the package has been loaded with `load_all()`) (#941).

https://github.com/r-lib/usethis/blame/94619e37d4ab43f567c56432745e0d97e52ee7ff/NEWS.md#L145

https://github.com/r-lib/usethis/pull/1062

**Comment by jennybc** [comment]
Oh, for usethis itself? I'm not sure. There are special miseries around using usethis to work on usethis.

**Comment by maelle** [comment]
So to clarify, to be able to use the exta bullets on a package called lalala, I had to `load_all("../usethis")` as with `library("usethis")` things did not work. In my initial issue, everything until "What I also did not expect" describes the actual bug (after that, it's only a display of my ignorance) -- at least I think so. :grin:

**Comment by jennybc** [comment]
I just know that this feature recently worked for me on readr:

https://github.com/tidyverse/readr/issues/1362

The question about "Have checked with the IDE team?" is an extra for readr.

My personal experience of this is always through `devtools::release()` or `usethis::use_release_issue()`.

I've never looked into this bit of code myself, so I don't have a pre-existing sense of what the issues are.

**Comment by hadley** [comment]
This works for me too, so I think there must be something else going on for you @maelle.
