### ISSUE TITLE
Should use_data() check if project is a package?

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#158]
`use_data()` currently feels very package focused, but it **will** work on a non-package project.

``` r
devtools::load_all("~/rrr/usethis")
#> Loading usethis

pj <- scoped_temporary_project()
#> ● Switching to a temporary project! To restore current project:
#> proj_set("")
is_package(pj)
#> [1] FALSE
use_data(letters)
#> ✔ Creating 'data/'
#> ✔ Saving letters to data/letters.rda
```

Created on 2017-12-26 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

Should `use_data()` verify it's operating on a package before it does anything?

@hadley

**Comment by hadley** [comment]
Yeah I think so. I’m not sure what you should do with data in a more general project but it’s not this.
