### ISSUE TITLE
Add function to create a minimal `.lintr` config

### ISSUE THREAD

**Issue by AshesITR** [r-lib/usethis#1580]
[Related issue over at lintr](https://github.com/r-lib/lintr/issues/902)
#579 added a workflow template for `lintr`, but no `.lintr` config file (compare `use_pkgdown()`, which does create a minimal config IIRC).

It would be nice to support users by generating a small valid `.lintr` config file from where they can adjust to their liking.
Since `lintr` does not necessarily have to be used with a GHA workflow, maybe a new function would be nice.

We could also implement this directly in `lintr`, but I personally would look for such a function in `usethis`.

**Comment by jennybc** [comment]
Personally, although use lintr, I have never used a config file. So I associate a config file with more-than-entry-level use.

usethis doesn't currently have any lintr-specific functionality. But, yes, the existence of [`r-lib/actions/examples/lint.yaml`](https://github.com/r-lib/actions/blob/v2-branch/examples/lint.yaml) means that `usethis::use_github_action("lint")` can be used to set up a basic workflow. And likewise for [`r-lib/actions/examples/lint-project.yaml`](https://github.com/r-lib/actions/blob/v2-branch/examples/lint-project.yaml).

I think we've been over this ground in #579 and #580 and we've decided the current level of GHA workflow assistance is the way to go.
