### ISSUE TITLE
`usethis::use_tibble()` generated an R crash

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/usethis#1581]
My environment was a recently created R project/package, after the development of a few functions I decided to run `usethis::use_tibble()`, and I did not have package-level documentation, so to the question:

```
`use_import_from()` requires package-level documentation.
Would you like to add it now?
```
I answered yes, and then boom! :)

(I tried to replicate the problem but no avail)

![snap](https://user-images.githubusercontent.com/19862384/152663553-b43be15d-6ef5-4bed-ae78-08e312fecaf2.png)

My R version is 4.1.2. `{usethis}` version is 2.1.3. I am sorry I can't provide a more detailed bug report but I hope this might helpful, particularly those errors in the R console that can be seen from the screenshot.

**Comment by jennybc** [comment]
Thanks for the report. But until we can get something reproducible, we'll just have to let this one go.
