### ISSUE TITLE
use_gpl_license() gives a warning when devtools::check()

### ISSUE THREAD

**Issue by PursuitOfDataScience** [r-lib/usethis#1582]
Similar issue like [#683](https://github.com/r-lib/usethis/issues/683):

When I use `use_gpl_license()`, it automatically created `License: GPL (>= 3)` in the DESCRIPTION file, but when I carried out `devtools: check()`, it threw me the same warning as #683 had. When I add `+ file LICENSE`, the warning went away and everything looks fine. Is this a bug? Do I need to do anything extra like moving `LICENSE` to `.Rbuildignore`, or just keep everything as where it is ? It is rather confusing and hope someone can shed some light in this regard.

**Comment by hadley** [comment]
I just ran:

```R
create_package("~/desktop/test")
# in new session
use_gpl_license()
devtools::check()
```

And didn't see any problems (which is what I'd expect given my understanding of the `License` field). 

So you really need to provide a full reprex.

**Comment by PursuitOfDataScience** [comment]
Sorry, I made a mistake when working on that a while ago. I used a MIT license, which generated the LICENSE file, but then I switched to the GPL one, and the LICENSE file stayed, which I didn't notice and thought it was triggered by `use_gpl_license()`. Everything is fine and the package was published successfully.
