### ISSUE TITLE
`usethis:::is_rstudio_funded()` could returns NA which error in `upkeep_checklist()`

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#1600]
Discovered while trying to use ` usethis::use_tidy_upkeep_issue()`

````r
> usethis::use_tidy_upkeep_issue()
√ Setting active project to 'C:/Users/chris/Documents/DEV_R/rticles'
Which repo should we target? 

1: cderv/rticles = 'origin'
2: rstudio/rticles = 'upstream'

Sélection : 2
Error in if (cond) { : missing value where TRUE/FALSE needed
````

This is due to 
https://github.com/r-lib/usethis/blob/b8b0209425a26d8a439617e0dba5c54e31f40264/R/tidy-upkeep.R#L85

because 
``` r
usethis:::is_rstudio_funded()
#> [1] NA
```

I believe it should TRUE or FALSE only to be used in a `if()` condition

This is because in
https://github.com/r-lib/usethis/blob/a545714f8f94e916bbd52e007092b149dda1db79/R/release.R#L380-L381

`.x$given` is NULL. and can't be compared using `==`. Using `identical()` would be working

**Comment by cderv** [comment]
Also, some packages like rmarkdown or shiny sets RStudio in the `family` field. I know this function is not oriented toward those other RStudio packages, but I am thinking either it matters and it is a good idea to enforce using `given`, or it does not matter and `ìs_rstudio_funded()` could also check for `RStudio` in family. 

Anyway, in case the wrong field is set, the process will currently error.

**Comment by jennybc** [comment]
Summary of my analysis.

I looked at repos in these orgs:

``` r
orgs <- c("tidyverse", "r-lib", "tidymodels", "mlverse", "rstudio", "sol-eng")
```

and analyzed any package-y DESCRIPTION files I found at the top levels of said repos.

Here's the most relevant finding re: this issue:

``` r
rstudio_role_dat %>%
  count(given, family)
#> # A tibble: 9 × 3
#>   given         family            n
#>   <chr>         <chr>         <int>
#> 1 --            RStudio          68
#> 2 --            RStudio, Inc.     1
#> 3 --            RStudio, PBC     10
#> 4 --            RStudio, Pbc.     1
#> 5 RStudio       --              268
#> 6 RStudio Pbc   --                2
#> 7 RStudio PBC   --                2
#> 8 RStudio, Inc. --                2
#> 9 RStudio, PBC  --                4
```

**Comment by jennybc** [comment]
Of >200 repos that live in RStudio-associated GitHub orgs, there appear to be about 70 that have a DESCRIPTION file but RStudio is not listed in `Authors@R` at all. Some of these are probably not even real R packages, but some are. In addition to the variety shown above re: how RStudio is named and whether it's via `given` or `family`, there's also a lot of variety in terms of `role` (`fnd` only, `cph` only, `fnd` and `cph`). This is the context for the changes to `use_tidy_upkeep()` in the PR that closes this.
