### ISSUE TITLE
use_tidy_coc() should remove top-level file

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1602]
Since it creates a file in `.github`, and if you're not careful you'll end up with two.

It could also omit the advice to modify README, since both pkgdown and GitHub already prominently link to the CoC.

**Comment by tracykteal** [comment]
We updated the language to recommend "you may want to" more than require "don't forget to" add to the README, since this is for use beyond tidyverse and not all packages have pkgdown sites that would make it as visible.

**Comment by hadley** [comment]
Right, but for `use_tidy_coc()` in particular, we could omit the message.
