### ISSUE TITLE
`create_from_github()` errors when creating from GitHub Enterprise

### ISSUE THREAD

**Issue by jabenninghoff** [r-lib/usethis#1603]
`create_from_github()` throws an error when creating from a repository hosted on a GitHub Enterprise server.

Expected result: a new project is created from the specified repository
Actual result: 404 error (details below)

The reproducible example requires access to a GitHub Enterprise server, here listed as `github.example.com`:

```r
create_from_github("https://github.example.com/jbenninghoff/testrepo")

#> Error in gh_process_response(raw):
#> GitHub API error (404):
#> Message: Not Found
#> Read more at https://docs.github.com/rest/reference/repos#get-a-repository
#>
#> URL not found: https://api.github.com/repos/jbenninghoff/testrepo
```

The error is a result of a mismatch between `create_from_github()` and `gh_tr()`. `create_from_github()` includes the following code:

```r
  gh <- gh_tr(list(repo_owner = source_owner, repo_name = repo_name, .api_url = host))
```

However, `gh_tr()` specifies the parameter as `tr$api_url`. Changing this to `tr$.api_url` fixes the problem.

Doesn't work:

```r
gh_tr <- function(tr) {
  force(tr)
  function(endpoint, ...) {
    gh::gh(
      endpoint,
      ...,
      owner = tr$repo_owner, repo = tr$repo_name, .api_url = tr$api_url
    )
  }
}
```

Works!

```r
gh_tr <- function(tr) {
  force(tr)
  function(endpoint, ...) {
    gh::gh(
      endpoint,
      ...,
      owner = tr$repo_owner, repo = tr$repo_name, .api_url = tr$.api_url
    )
  }
}
```

**Comment by malcolmbarrett** [comment]
This works for me. Have you set up credentials with `usethis::gh_token_help("https://github.your_ghe_url.com")`? You might also want to try setting your host in your `.Renviron` with `GITHUB_API_URL="https://github.your_ghe_url.com"`

**Comment by jabenninghoff** [comment]
Your solution looks like it would work, but I'm pretty sure there's still a bug here. `tr$api_url` is not the same as `tr$.api_url`

**Comment by jennybc** [comment]
Yes, I can repro this and the fix is as you suggest.
