### ISSUE TITLE
`use_code_of_conduct()` unnecessarily creates a new copy of `CODE_OF_CONDUCT.md`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/usethis#1605]
Just like _[usethis](https://github.com/r-lib/usethis/blob/main/.github/CODE_OF_CONDUCT.md)_, I typically have my CoC document in the `.github` folder.

But, when I ran `use_code_of_conduct()` to update CoC to version 2.1, it created a new copy of `CODE_OF_CONDUCT.md` at the top level instead of overwriting the one already present in `.github` folder.

Is it possible for `use_code_of_conduct()` to anticipate this context and adjust accordingly? Thanks.

**Comment by batpigandme** [comment]
Thanks for pointing this out. @jennybc, I'm looking at my PR, which made the change of version (https://github.com/r-lib/usethis/pull/1591/), and cant see where I might have introduced it there.

Happy to dig into this more, though.

**Comment by jennybc** [comment]
[`use_code_of_conduct()`](https://usethis.r-lib.org/reference/use_code_of_conduct.html) is a pretty simple function and expects the `path` argument to be used as documented:

> `path`: Path of the directory to put CODE_OF_CONDUCT.md in, relative to the active project. Passed along to [use_directory()](https://usethis.r-lib.org/reference/use_directory.html). Default is to locate at top-level, but `.github/` is also common.
