### ISSUE TITLE
install non-CRAN package during pkgdown github action

### ISSUE THREAD

**Issue by josherrickson** [r-lib/usethis#1613]
I've got a package which includes as a dependency a non-CRAN (or any standard repository) package. The DESCRIPTION file points to a drat repo in `Additional_repositories` which is sufficient to pass CRAN checks.

However, when using the "pkgdown" Github Action, the installation of this dependency fails.

Is there some way to tell the pkgdown action to look at `Additional_repositories`, or failing that, some way to modify the yml to install the package manually?

**Comment by josherrickson** [comment]
I added a step prior to `setup-r-dependencies` to manually install it:

```
      - name: install rrelaxiv
        run: |
          install.packages("https://path/to/package/source.tar.gz", repos = NULL)
        shell: Rscript {0}
```

and while this worked, the following step still failed to re-install it.

**Comment by josherrickson** [comment]
Instead of installing in the previous step, I tried installing "drat" and using `drat::addRepo` to no success either. I could probably add `drat` to the `extra-packages` field but it's unclear to me where `drat::addRepo` would go.

**Comment by jennybc** [comment]
This question is about configuring GitHub Actions, so it's not really a usethis question. usethis just copies a YAML file from a specific remote location to a specific local location.

Here are good ways to get help:
https://github.com/r-lib/actions#where-to-find-help

I think you'll find the answer here:

https://r-pkgs.org/description.html#nonstandard-dependencies
