### ISSUE TITLE
FR: A method to delete a function

### ISSUE THREAD

**Issue by see24** [r-lib/usethis#1615]
Would it be possible to add functionality to remove a function? Currently if I delete a file containing a function I have to remember to remove it from the Description Collate field and if it was exported the Namespace. I know this is often not a good practice, but sometimes it would be helpful and there could be messages and require confirmation. 

It could be an option in `use_r` or a separate function.

**Comment by jennybc** [comment]
I'm not willing to add a function for this. I'm generally much more inclined to offer a helper if it's hard to *add* something correctly, whereas I think deleting stuff is usually much easier! Even if it takes 1 or 2 iterations.

I think it's clear you need to delete the function definition. Then, if you're using roxygen2, re-`document()`, and that should take care of NAMESPACE. I imagine if there's some debris left in `Collate`, one attempt to `R CMD check` the package will alert you to that.
