### ISSUE TITLE
feature: use_RdTemplate

### ISSUE THREAD

**Issue by mikeroswell** [r-lib/usethis#1617]
Starting a new package, I wanted to use templates for parameters used in multiple functions. I forgot how this was supposed to work with the `@template` syntax (what the directory needed to be, whether the templates were `.R` or `.Rd`, etc.) and was hoping **usethis** would do things for me. I wrote the below quickly to remind future me, but i think it would be a nice feature of **usethis**. I'll create a PR now as well, though I'm sure your team will write a better function if you add this functionality. 
```r
#' Create a template for package documentation
#'
#' @param templateName Character, name of template and file
#'
#' @return This function creates a `.R` file in the directory "man-roxygen". If
#' that directory does not already exist in your package, it will create it.
#' The function opens the new (blank) file in your editor.
#'
#' @seealso \code{\link{file.edit}}
#' @export
#'
#' @examples
use_RdTemplate <- function(templateName){
  if(!dir.exists("man-roxygen")){
    dir.create("man-roxygen")
  }
  pth <- paste0("man-roxygen/", templateName, ".R")
  file.create(pth)
  file.edit(pth)
}
```

**Comment by jennybc** [comment]
I just commented on the PR, but now I better see what you're getting at.

There is some ambivalence within our team about whether / how much to encourage the use of `@template` over other ways of reducing duplication in roxygen content. So that's relevant to the fate of this idea.

**Comment by mikeroswell** [comment]
Hi Jenny, glad the motivation/idea makes some sense now, sorry it wasn't clear before. Naturally, I'm eager to follow your lead on whether to use `@template`, curious what else your team advocates!

**Comment by jennybc** [comment]
In situations where I would have used `@template` in the past, in new code, we are more likely to use `@eval` these days:

https://roxygen2.r-lib.org/articles/rd.html#evaluating-arbitrary-code

and specifically:

> This makes it possible to eliminate duplication by writing functions. 

So I'm not sure that we want to introduce new usethis tooling around `@template`. It's certainly still supported (and I still have lots of usage in things I maintain), but I'm not using it in new code.

---

An example in usethis itself:

https://cs.github.com/r-lib/usethis/blob/3a7f697ff0e83b2b7b48c138806a174e19f3358f/R/coverage.R#L7

where the `param_repo_spec()` helper is defined here:

https://cs.github.com/r-lib/usethis/blob/3a7f697ff0e83b2b7b48c138806a174e19f3358f/R/utils-roxygen.R#L4

---

An example in googlesheets4, where the documentation-generating function `param_sheet()` takes an argument:

https://cs.github.com/tidyverse/googlesheets4/blob/4f719d198237079efe8aefe5b6caf8883c1a4c8f/R/sheet_write.R#L39

https://cs.github.com/tidyverse/googlesheets4/blob/4f719d198237079efe8aefe5b6caf8883c1a4c8f/R/sheet_write.R#L39

Actual helper definition:

https://cs.github.com/tidyverse/googlesheets4/blob/4f719d198237079efe8aefe5b6caf8883c1a4c8f/R/roxygen.R#L24

**Comment by hadley** [comment]
I don't think we want to really encourage the use of `@template` as IMO better approaches are now available.
