### ISSUE TITLE
Function for specifying minimum R version

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/usethis#1619]
I am presently writing a package utilizing the native pipe. As such, I would like to specify the minimum R version as 4.1. I was hoping to be able to do this via usethis as I do not know how to format this in a DESCRIPTION file. 

I see that there is a tangential closed issue at https://github.com/r-lib/usethis/issues/631. My suggestion, however, is not to infer it from `use_data()` but rather be something stated explicitly by the developer themselves. It could, however, be inferred that R v4.1+ is necessary when the native pipe is used.

**Comment by malcolmbarrett** [comment]
Sorry, I made it sound like a proposal rather than a solution. That code works out of box & is what I do, for better or worse

**Comment by jennybc** [comment]
Yeah the `use_package()` approach shown by @malcolmbarrett is the intended way, if you want to use usethis to do this. It's not something that comes up nearly as often as the main `use_package()` usage.

**Comment by JosiahParry** [comment]
Good to know! Thanks :)

**Comment by JosiahParry** [comment]
In light of the new check for R 4.1 incompatibilities in R-devel, it would be quite nice to have to a way to set the minimum version of R. I can never quite remember how to do it and come back to this issue every few months or so.

**Comment by malcolmbarrett** [comment]
Doesn't this solution still work?

**Comment by JosiahParry** [comment]
It definitely still works! Its just exceptionally difficult to remember how to do it and then quite tough to find this issue 

<details>
<summary> 
My search history trying to get here
</summary>

<img width="910" alt="Image" src="https://github.com/user-attachments/assets/1c8d05e7-de42-4284-8e29-1c3a5dded1e8" />

</details>
