### ISSUE TITLE
add comments to testthat.R

### ISSUE THREAD

**Issue by topepo** [r-lib/usethis#1631]
We recommend thins like "Do not edit tests/testthat.R". We should write out a note in comments to not do so. 

Are there other places for similar comments? Anything to put at the top of specific test files?

**Comment by jennybc** [comment]
This came from group discussion of revisions of the testing chapter of R Packages 2nd edition.

It will contain specific advice to discourage changes to the boilerplate `tests/testthat.R`.

We want to add a comment that's on the same wavelength as:

In NAMESPACE
```
# Generated by roxygen2: do not edit by hand
```

In a README.md that comes from README.Rmd
```
<!-- README.md is generated from README.Rmd. Please edit that file -->
```
