### ISSUE TITLE
use_github_links() aborts

### ISSUE THREAD

**Issue by juancasy** [r-lib/usethis#1632]
When I try to include Github links in DESCRIPTION file using 
use_github_links(), I get the message

Error in `abort()`:
! `message` must be a character vector, not a list.

Following system suggestion I took a look on the last error messages and I got:

rlang::last_error()
<error/rlang_error>
Error in `abort()`:
! `message` must be a character vector, not a list.
---
Backtrace:
 1. usethis::use_github_links()
 2. usethis:::target_repo(github_get = TRUE)
 3. usethis:::check_for_config(cfg)
 4. usethis:::check_for_maybe_config(cfg)
 5. usethis:::stop_maybe_github_remote_config(cfg)
 6. rlang::abort(...)

I get the same error with the same backtrace error messages when trying to use

usethis::use_pkgdown_github_pages()
Error in `abort()`:
! `message` must be a character vector, not a list.

I am currently using pkgdown for building a package web site; I am wondering if there might by some conflict between usethis and pkgdown.

**Comment by jennybc** [comment]
This has already been fixed in the dev version and I will do a usethis release soon.

f85e2dcf658da265a4e7475b92cc8262150183d1
#1608, #1531
