### ISSUE TITLE
snapshot files are removed when running devtools::test()

### ISSUE THREAD

**Issue by LDSamson** [r-lib/usethis#1633]
Within a package, when I run a test with snapshots (see below for an example), the snapshots are deleted when I run the command devtools::test(). The snapshots are not deleted when I run the command devtools::test_active_file(). Is this expected behavior?

Test in question:

```r
testthat::test_that("snapshot test", {
  testthat::expect_snapshot(mtcars)
})
```

when the tests are run:
```r
# this runs fine and creates a snapshot in the folder _snaps:
devtools::test_active_file()

# this runs the test, but deletes all the snapshots afterwards: 
devtools::test()
```

sessioninfo: 
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
testthat_3.1.4    psych_2.2.3       devtools_2.4.3   
 usethis_2.1.5

**Comment by jennybc** [comment]
I can't replicate this. (Also, this would appear to be a devtools or testthat issue, not usethis.)
