### ISSUE TITLE
Feature request: allow manual input in `use_version()`

### ISSUE THREAD

**Issue by rossellhayes** [r-lib/usethis#1637]
Currently, `use_version()` only allows the user to increment a component of the current version number by 1. This works well for most packages and helps developers to follow the conventions of semantic versioning. But it's less helpful for packages that want to use other versioning scheme, like [Calendar Versioning](https://calver.org/).

If `use_version()` supported manual version numbers, developers who use a different versioning scheme could still take advantage of `use_version()`'s other features, like automatically keeping the `DESCRIPTION` and `NEWS` files in sync.

If you're interested, I'd be happy to submit a PR.

**Comment by jennybc** [comment]
I'm comfortable with usethis being pretty opinionated in its support for semantic versioning. It's woven throughout many functions, not sure `use_version()`.
