### ISSUE TITLE
use_github(): behaviour if !uses_git() 

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#164]
I came across this while working on PR #125, and am happy to incorporate a solution into that PR.

The documentation for `use_github()` says that it calls `use_git()` if need be: https://github.com/r-lib/usethis/blob/80a2bbf062681965e7d6ce01fb46875b98756900/R/github.R#L3-L4

The code checks `uses_git()` and throws an error if not used: https://github.com/r-lib/usethis/blob/80a2bbf062681965e7d6ce01fb46875b98756900/R/github.R#L64-L66

Which is "correct"?

**Comment by jennybc** [comment]
If memory serves, in a previous devtools life, `use_github()` did call `use_git()`.

But I believe current behaviour is desired at the moment, so an update is needed on the docs, not the code.

**Comment by ijlyttle** [comment]
Will modify docs accordingly, thanks!

**Comment by jennybc** [comment]
Any chance you want to close this too while you're there? https://github.com/r-lib/usethis/issues/116 😁

**Comment by ijlyttle** [comment]
No problem!
