### ISSUE TITLE
`create_package()` checks the wrong name when using `fields` and "Package"

### ISSUE THREAD

**Issue by mmuurr** [r-lib/usethis#1651]
1. Create a directory that is not a valid package name, e.g. "my-test-directory".
2. Now from within that directory, try to initialize a package using {usethis}:
    ```R
    usethis::create_package(".", fields = list(Package = "valid.package.name"), check_name = TRUE)
    # Error: 'my-test-directory' is not a valid package name. To be allowed on CRAN, it should: ...
   ```

Setting `check_name = FALSE` allows the call to proceed correctly, and indeed the created DESCRIPTION file has the package name set correctly, too: `Package: valid.package.name`.

So, it appears `check_name = TRUE` ignores the case where the name is specified in the `fields` argument.

EDIT: behavior observed with {usethis} v2.1.6.

**Comment by jennybc** [comment]
usethis definitely assumes that the package lives in a directory by the same name, which is true most of the time. Also, it's definitely more common for usethis to create the target directory, i.e. `create_package(".", ...)` is not our most common workflow.

It sounds like you have a different workflow, which you can still make work with

``` r
usethis::create_package(".", fields = list(Package = "valid.package.name"), check_name = FALSE)
```

so I think that's what you should do.
