### ISSUE TITLE
gitignore from create_from_github

### ISSUE THREAD

**Issue by dbolta** [r-lib/usethis#1655]
Gitignore consistency between function and IDE wizard

```r
usethis::create_from_github(
  "https://github.com/user/shiny-rotary-phone.git"
)
```
 creates gitignore with 1 file extension:
 .Rproj.user
 
 File->New Project->Version Control->Git->Create Project
creates .gitignore with 4:
.Rproj.user
.Rhistory
.RData
.Ruserdata

**Comment by jennybc** [comment]
I'm not sure what to do about this. Or if we should do anything about this.

The "usethis way" of gitignoring most of these files is to encourage a user to have them in the user-level, global gitignore, perhaps by calling `git_vaccinate()`.

**Comment by hadley** [comment]
I don't think we need to do anything about this.
