### ISSUE TITLE
how do i specify the list of packages in the DESCRIPTION file for a project?

### ISSUE THREAD

**Issue by ChristelSwift** [r-lib/usethis#1657]
very basic question i'm afraid.. but i'm trying to create a DESCRIPTION file with `usethis::use_description` for a project (not a package) so that i can then use `renv::settings$snapshot.type("explicit")` and limit the list of packages that will end up in `renv.lock` to what i'm using in one of the files in my project.  

I've tried something like this:

```r
# create a DESCRIPTION FILE:
usethis::use_description(
  fields = list(
    Type = "project",
    Title = "my project",
    Depends = list("tidyverse", "duckdb", "RJDBC", "aws.s3", "aws.ec2metadata", "httr", "jsonlite", "stringr")
  )
)
```

 but the output doesn't look right as all the package names come out as one concatenated string:  

<img width="481" alt="image" src="https://user-images.githubusercontent.com/24437540/181289241-efa5602a-dfcd-453f-b067-276a52e73f0a.png">

What is the correct syntax to include a list of packages needed for a project?

**Comment by jennybc** [comment]
If you really want to use usethis for this task, I think you'd use `use_description()` with minimal input to initiate DESCRIPTION (maybe just specifying `Type` and `Title`, in your example). Then use `use_package()` to add packages (one at-a-time, I'm afraid) to the Imports, Depends, or Suggests fields.

But I'd say your use case isn't really what usethis's DESCRIPTION-modifying functions are really meant to do.

You might want to use the desc package directly, which is ultimately what usethis calls under the hood when working with DESCRIPTION programmatically.

https://r-lib.github.io/desc/
