### ISSUE TITLE
Should casing be ignored in the repo spec when finding parent remote?

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/usethis#1658]
Some GitHub users have mixed case usernames (hello @MilesMcBain), but this trips up `pr_init()`:

```r
pr_init("run_script")
#> Error in `stop_bad_github_remote_config()`:
#> ! Unsupported GitHub remote configuration: 'fork_upstream_is_not_origin_parent'
#> • Host = 'https://github.com'
#> • origin = 'gadenbuie/capsule' (can push) = fork of 'MilesMcBain/capsule'
#> • upstream = 'milesmcbain/capsule' (can not push)
#> • The 'origin' GitHub remote is a fork, but its parent is not configured as the 'upstream' remote.
```

To get into this situation I used the GitHub CLI to fork and clone Miles' repo

```
gh repo fork milesmcbain/capsule
```

and then I opened the project and ran the code above. Also I'm using SSH as my default protocol.

My `.git/config` in this repo is:

```
[remote "origin"]
        url = git@github.com:gadenbuie/capsule.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = upstream
        merge = refs/heads/master
[remote "upstream"]
        url = git@github.com:milesmcbain/capsule.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
```

<sup>sidenote: I edited the tracking remote for branch `master`, the `gh` CLI doesn't do that</sup>

and the mismatch appears to be happening when comparing the source remote reported by the REST API with the repo specs parsed from the remote URLs (I say this without actually inspecting any usethis code, so grain of 🧂 ).

```r
gh::gh("/repos/gadenbuie/capsule")$source$full_name
#> [1] "MilesMcBain/capsule"

gert::git_remote_list()
#> # A tibble: 2 × 2
#>   name     url                                   
#> * <chr>    <chr>                                 
#> 1 origin   git@github.com:gadenbuie/capsule.git  
#> 2 upstream git@github.com:milesmcbain/capsule.git
```

**Comment by gadenbuie** [comment]
A further data point: I realized I could simply change the upstream URL in the `.git/config` and then `pr_init()` worked as expected.

```
[remote "upstream"]
        url = git@github.com:MilesMcBain/capsule.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
```

**Comment by jennybc** [comment]
This sort of feels like a bug in the GitHub CLI.

If I do fork-and-clone with the usethis workflow, with an incorrectly-cased input:

```
> create_from_github("https://github.com/milesmcbain/capsule", destdir = "~/tmp")
✔ Setting `fork = TRUE`
✔ Creating '/Users/jenny/tmp/capsule/'
✔ Forking 'MilesMcBain/capsule'
✔ Cloning repo from 'https://github.com/jennybc/capsule.git' into '/Users/jenny/tmp/capsule'
✔ Setting active project to '/Users/jenny/tmp/capsule'
ℹ Default branch is 'master'
✔ Adding 'upstream' remote: 'https://github.com/MilesMcBain/capsule.git'
```

usethis targets the correct repo AND sets up the correctly-cased remote URL.

So I'm probably content that usethis is internally consistent / handles this at what I consider the right place (when setting up remotes).

But if you wanted to investigate what it would take to make usethis resilient to this sort of casing problem in Git URLs, I'd be happy to review a PR.

**Comment by gadenbuie** [comment]
I appreciate your gentle reminder that usethis has my back. Given that

```shell
gh repo clone milesmcbain/capsule
```

and

```r
usethis::create_from_github("milesmcbain/capsule", fork = TRUE)
```

are equivalent in every important way and that the usethis version works better with usethis functions... I think you're right to be content with usethis' approach. I also agree that the GitHub CLI should be the one to figure out the canonical remote URL. So I'm happy to close this issue 😃
