### ISSUE TITLE
Use SUPPORT

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#166]
Should we? For tidyverse packages, we have obvious places to link to, e.g. contributing guidelines, community.rstudio.com, [non-code contributions](https://www.tidyverse.org/contribute/).

https://help.github.com/articles/adding-support-resources-to-your-project/

**Comment by jennybc** [comment]
@batpigandme Do you want to make a PR for SUPPORT and `use_tidy_support()`?

A few examples in the first 3 pages of [search results](https://github.com/search?p=3&q=filename%3ASUPPORT.md&type=Code&utf8=✓) that seem vaguely like what we need:

https://github.com/hiqsol-attic/omnipay-webmoney/blob/6df54c2407a7bb76680ac60e8a70299202df36b8/docs/readme/Support.md

https://github.com/STEllAR-GROUP/hpx/blob/ef2912075630b221e763911b9382314908497e55/.github/SUPPORT.md

https://github.com/Edragon/Arduino/blob/a54ebb00b71ed649ff47a0f8e56a2ff28ee23341/libraries/ArduinoJson/SUPPORT.md

**Comment by batpigandme** [comment]
Yep. On it

**Comment by timtrice** [comment]
At line 23, the URL points to https://github.com/tidyverse/{{{package}}}/issues to search for issues. Shouldn't this actually point to the project repo?

I'd be happy to fix if need be.

**Comment by jennybc** [comment]
> Shouldn't this actually point to the project repo?

Are you pointing out the fact that this is hard-wired to the tidyverse org?

I believe this template is only used by `use_tidy_*()` functions (but I could be wrong), so the guarantee is only that they work for tidyverse packages.

**Comment by timtrice** [comment]
> Are you pointing out the fact that this is hard-wired to the tidyverse org?

Correct. I'm under the impression any of the `use_tidy_*()` functions can be used to create templates in our own packages or projects. In this instance, the SUPPORT template would be directing readers to search **tidyverse/my_project** for previously reported issues or PRs which, of course, would be the incorrect path.

**Comment by jennybc** [comment]
The `use_tidy_*()` functions were originally conceived for use in tidyverse packages. But I think it's true that the reality or perception has drifted more towards doing things in the style of a tidyverse package. We have so much infrastructure around tithe GitHub side of things now that it is probably fairly straightforward to generalize the template to use the correct `OWNER/REPO` here.
