### ISSUE TITLE
Could `pr_resume()` also work off PR numbers?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#1665]
`pr_resume()` currently works off a `branch` name, with the intention being that you might be coming back to a branch that you only have locally and don't have a PR for yet.

But when I have multiple PRs "in flight", I often find myself in this situation:

* `pr_push()` to open a PR
* `pr_pause()` and let Hadley review while i work on other pull requests
* Once he has reviewed, go back and read the review (i.e. I'm looking at the pr number on the screen at this point)
* `pr_resume(<branch-name>)` to incorporate changes
* Commit and push changes
* Merge on GitHub
* `pr_finish()` or `pr_finish(<pr-number>)` to finish up

GitHub doesn't make the branch name particularly easy to copy/paste, the PR number is often easier, so it might be nice if `pr_resume()` could use the number instead

(i.e. there is a button to copy the branch name when you are in the PR window on GitHub, but it is copied as `DavisVaughan:fix/cur-group-zero-row-gdf` with the user name prefixed on the branch name, and usethis doesn't know what to do with that)

**Comment by malcolmbarrett** [comment]
Have you tried the interactive workflow by using `pr_resume()` without any arguments?

**Comment by DavisVaughan** [comment]
I don't use that much. It seems like a reasonable option - except for the fact that it takes 15-20 seconds on a bit repo like dplyr where there have been a ton of issues/prs

**Comment by malcolmbarrett** [comment]
I use that workflow a lot, and it's great in most circumstances, but it does sound frustrating on a big repo. 

In similar functions for internal tooling, I've used the numbers approach, so I support that, too

**Comment by hadley** [comment]
FWIW you can just use `pr_fetch(123)` instead.

That said, I never use `pr_pause()`. I always use `pr_finish()` because then I don't have to remember if I need to delete the local branch, and functionally it seems no slower than `pr_pause()`/`pr_resume()`.

**Comment by hadley** [comment]
Maybe we should unify `pr_fetch()` and `pr_pause()` since they only really differ in whether you supply a numeric PR number or a string branch name.

**Comment by jennybc** [comment]
> I can see the need to keep both `pr_fetch()` and `pr_resume()`, because `pr_resume()` doesn't require you to actually open the PR on github, you just need to have a local branch.

Yeah I definitely use this fact (that there's no requirement there even be a PR (yet?)). Basically it gives you a branch chooser right in the R console.

**Comment by DavisVaughan** [comment]
I'm somewhat convinced this is just a (potential) documentation issue. Like, could the docs for `pr_fetch()` maybe mention something about what happens when you call it and you already have the branch checked out locally?
