### ISSUE TITLE
`use_pkgdown_url()` doesn't check if DESCRIPTION already has URL

### ISSUE THREAD

**Issue by dchiu911** [r-lib/usethis#1674]
This situation can occur when I am already using a pkgdown + github pages workflow but without CI. My DESCRIPTION URL field already has the github pages link, but after running `usethis::use_pkgdown_github_pages()` to migrate to github actions, I noticed that `use_pkgdown_url()` doesn't check for an existing URL before [adding](https://github.com/r-lib/usethis/blob/main/R/pkgdown.R#L108) to DESCRIPTION.

**Comment by hadley** [comment]
I think this is something you'll just need to resolve by hand.
