### ISSUE TITLE
Update TODO note in `usethis::use_github_release()`

### ISSUE THREAD

**Issue by dchiu911** [r-lib/usethis#1678]
The GitHub release process now uses a pencil icon with hover text "Edit release". `usethis::use_github_release()` mentions "Edit draft"
<img width="1229" alt="Screen Shot 2022-09-15 at 12 30 29 PM" src="https://user-images.githubusercontent.com/8665632/190493104-13f07678-84a8-4afe-a12d-f2243f67c52b.png">

**Comment by hadley** [comment]
We'll tackle this a different way.
