### ISSUE TITLE
Should `create_from_github()` support subdirs?

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1680]
e.g. `create_from_github("https://github.com/apache/arrow/tree/master/r")`

**Comment by jennybc** [comment]
How would that actually work?

**Comment by hadley** [comment]
I think _maybe_ it clones in the same way, you just `use_rstudio()` in a subdirectory?

**Comment by hadley** [comment]
Another approach would be to scan all subdirectories for an `.Rproj` file before creating a new one in the root.
