### ISSUE TITLE
For RStudio packages, add posit updates (if needed) to release checklist

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1683]
* update copyright holder in DESCRIPTION
* double check license file uses "{package} authors" not RStudio 
* update email addresses
* update logo (https://github.com/rstudio/hex-stickers)
* update cheatsheets (once they're updated)

**Comment by jennybc** [comment]
My understanding is that we should use Posit Software, PBC in `cph`.

**Comment by jennybc** [comment]
I think we're leaning more towards "Posit PBC" or maybe "Posit, PBC"

**Comment by tracykteal** [comment]
Final guidance is that we should be using

person("Posit Software, PBC", role = c("cph", "fnd"))

**Comment by jennybc** [comment]
That is already embodied in usethis. I think this issue should have been closed a while ago, actually.
