### ISSUE TITLE
`use_github_release()` requires a NEWS file - Release issue should reflect that correctly

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#1687]
Order of the release todo is the following for 

https://github.com/r-lib/usethis/blob/8ecb7ab8851faa7d8cc56bfb965e1895c326163e/R/release.R#L115-L117

In my first release package, I do not have a NEWS file yet - or at least I did not put one but checklist did not check for one.
https://github.com/r-lib/usethis/blob/8ecb7ab8851faa7d8cc56bfb965e1895c326163e/R/release.R#L69-L80

However, running `usethis::use_github_release()` throws an issue 
````
Error:
! No top-level headings found in 'NEWS.md'
````

I think `usethis::use_news_md()` needs to be run before creating the github release if there is no NEWS file, and even before submitting to CRAN as `use_github_release()` will use the SHA from `CRAN_SUBMISSION` so I would change the order in the checklist to reflect that

**Comment by malcolmbarrett** [comment]
If there's no `NEWS.md`, `use_github_release()` is supposed to say "Initial release"  in the body.

https://github.com/r-lib/usethis/blob/8f045dc0a88eac82a602df56e2dd62df90971a04/R/release.R#L325-L329

It doesn't look like that's changed recently

**Comment by cderv** [comment]
Ok I can't. let's forget about that. Must have been a specific weird situation. Sorry 😓
