### ISSUE TITLE
Fine-tune recommendation on editing testthat.R?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/usethis#1688]
Currently we are recommended not to edit testthat.R:

https://github.com/r-lib/usethis/blob/8ecb7ab8851faa7d8cc56bfb965e1895c326163e/inst/templates/testthat.R#L2

I think the point being conveyed is we shouldn't add all sorts of setup cruft in there.

But I think adding additional library() calls is perfectly fine. This is how I make crystal clear that a certain package (often, withr) is required for the test suite, even if it's just Suggested for the package overall. That way we can use it freely in the test suite without worrying about skip_if_not_installed().

Is that a reasonable interpretation? If so I can try to add a quick clarification to the docs here.

**Comment by jennybc** [comment]
I still don't like how this *attaches* withr, which presumably isn't true of how your package uses withr "in production", i.e. I assume withr is not in `Depends`.

**Comment by MichaelChirico** [comment]
I do still use it namespace-qualified... how about loadNamespace("withr") then :)

**Comment by jennybc** [comment]
Maybe you should just write a single test that tests for the availability of withr? I don't think we really have to agree on this, but I remain comfortable with the general advice to not modify this file.

**Comment by MichaelChirico** [comment]
that seems like a really puzzling/obscure/indirect way of declaring the package to be a requirement for testing.

Running loadNamespace (or library, for simplicity) in testthat.R, by contrast, is transparent, fails quickly, and is easy to find.

I am happy to disagree but it still seems overly restrictive to me.

**Comment by hadley** [comment]
Our general position is listing a package in suggests declares that it's required for testing.

**Comment by MichaelChirico** [comment]
> Our general position is listing a package in suggests declares that it's required for testing.

Having [`skip_if_not_installed()`](https://testthat.r-lib.org/reference/skip.html) is in conflict w/ that position, no? That function is all about ignoring tests when some suggested package is missing.

All of this makes sense on CRAN, where all the regularly-conducted tests are run with all Suggests available. But outside CRAN, it's dicier.

For example, we have a minimalist approach to package import. Only `Imports+Depends+LinkingTo` are included. Any other packages in Suggests that are not already imported must be specifically imported separately. That often means some tests/examples must be excluded and figuring out which can be a pretty manual process.

I imagine GitHub-only packages have a similar constraint (depending on if their GHA is configured to always import recursive depends of Suggests, and it's probably sensible to exclude some unstable GH-only Suggests packages from CI). And users working in air-gapped environments (so `install.packages()` handling recursive imports doesn't work) have a interest in a sharpened scope of packages on a test-by-test basis.

So I'm happy w/ our current approach in lintr, where there's two types of Suggests w.r.t. testing

 1. Helper packages for writing tests, of course `testthat`, but also a few others, in our case `withr`, `rex`, `patrick`. `rex` is in our Imports, but we avoid messing with the search path. They are required for running tests to make any sense. If the tests got their own `DESCRIPTION`, these packages would be Imports: https://github.com/r-lib/lintr/blob/a32f2d23d07d734358924e456b10f3d375fc70b3/tests/testthat.R#L1-L10
 2. Peripheral packages used for certain functionality in the package, they are a bonus for the package, and only users who actually need that functionality should care about the associated testing. Thus we skip the tests if the packages are unavailable on some installation (won't happen on CRAN): [whole test file](https://github.com/r-lib/lintr/blob/444a2fb1116cad796d326e3ba8fb5229ff8fa3f9/tests/testthat/test-sarif_output.R#L1) [individual units](https://github.com/r-lib/lintr/blob/8bec6df3109335c560147036e2d4422e64652039/tests/testthat/test-knitr_extended_formats.R#L2-L14)

**Comment by hadley** [comment]
Our dependency management has evolved over time. These days we tend to only use `skip_if_not_installed()` for suggested package where there's some reason to expect that they might not be available everywhere (e.g. we'll often use it for arrow, since it's compilation heavy and not always available on every platform).

Our system is not perfect, but it works for us (across GHA, CRAN, and our revdep checks) and the vast majority of other open source developers that we work with. You're certainly welcome to use your own system, but it'll be an uphill battle to get us to adjust our tooling because we prefer to stick with workflows that we use, as otherwise the chance of accidental breakage going unnoticed is too high.

All-in-all, I stand by the recommendation for folks to not modify `testthat.R`. The vast majority of modifications we see in the wild are ill-advised. Your use case seems fine to me, but you're also experienced enough to know when to ignore our advice 😄

**Comment by jennybc** [comment]
The tidyverse/devtools thinking on this is best recorded here:

https://r-pkgs.org/dependencies.html#sec-suggested-packages-and-tests

And it talks about `skip_if_not_installed()`.

Again, I don't think either of us has to convince the other to change our ways.

**Comment by MichaelChirico** [comment]
Thanks for the discussion! it is useful to have it written out as a reference.

**Comment by MichaelChirico** [comment]
> The tidyverse/devtools thinking on this is best recorded here:
> 
> https://r-pkgs.org/dependencies.html#sec-suggested-packages-and-tests
> 
> And it talks about `skip_if_not_installed()`.
> 
> Again, I don't think either of us has to convince the other to change our ways.

This link is dead, mind refreshing it? Thanks!

**Comment by jennybc** [comment]
https://r-pkgs.org/dependencies-in-practice.html#sec-dependencies-in-suggests-in-tests
