### ISSUE TITLE
use_news_md is out of order in use_release_issue()

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/usethis#1691]
I was working on my CRAN release of https://github.com/tidymodels/modelenv, and when I got to `use_github_release()` I got the following error because the release candidate didn't have a news file

![Screen Shot 2022-10-17 at 9 19 47 AM](https://user-images.githubusercontent.com/14034784/196230326-cfcffafe-1ee5-4a63-bf3d-dfaa2f96eaaf.png)

Maybe we can move `use_news_md()` up to `Prepare for release:` if a news file haven't been detected when calling `use_release_issue()`?

**Comment by jennybc** [comment]
Is this a duplicate of #1687?

**Comment by EmilHvitfeldt** [comment]
It appears to, sorry for the duplicate!

**Comment by jennybc** [comment]
Did you not have a NEWS file or did you have one with unusual / unexpected format? I'm just wondering why we're getting repeated reports of trouble with NEWS and `use_release_issue()`.

**Comment by EmilHvitfeldt** [comment]
I didn't have a news file, to begin with. Just started with `create_package()`

**Comment by jennybc** [comment]
I'm not able to replicate this. I can't explain why you and @cderv saw this.
