### ISSUE TITLE
Add 'RGL_USE_NULL: yes' in the yaml file for Github action

### ISSUE THREAD

**Issue by stla** [r-lib/usethis#1693]
Hello,

The CHECK from a Github action fails if an example in the package produces a 3D graphic with the **rgl** package. One has to add `RGL_USE_NULL: yes` in the **yaml** file.

**Comment by malcolmbarrett** [comment]
Two points: 1) this is actually related to https://github.com/r-lib/actions 2) either way, this is helpful for people doing what you say here but not something that should be in the YAML file by default. 

That said, having a place for tidbits like this would be nice. I wonder if a discussion or wiki section should be opened up on the actions repo?

**Comment by jennybc** [comment]
@malcolmbarrett did you mean to link to the rgl package? That's where it seems like this should be called out. We can't do this in the default actions placed by usethis, as it's completely unsustainable to add specific tweaks like this.

**Comment by malcolmbarrett** [comment]
No, I assumed this issue was implying we should add `RGL_USE_NULL: yes` to the actions generated by usethis, making it an issue for the actions repo. But obviously, you're right that we shouldn't add it anyways.

**Comment by jennybc** [comment]
@stla I suggest that you open an issue on rgl. Perhaps the developer would want to mention this somewhere in its docs, i.e. a special note about how to get rgl and GitHub Actions playing nicely.

https://dmurdoch.github.io/rgl/
