### ISSUE TITLE
Modernize `use_citation()`

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1695]
`use_citation()` uses a legacy approach in its `CITATION` skeleton.

Older approach seen in, for example, in lubridate. This is what `use_citation()` currently does.

``` r
citHeader("To cite lubridate in publications use:")

citEntry(entry = "Article",
  title        = "Dates and Times Made Easy with {lubridate}",
  author       = personList(as.person("Garrett Grolemund"),
                   as.person("Hadley Wickham")),
  journal      = "Journal of Statistical Software",
  year         = "2011",
  volume       = "40",
  number       = "3",
  pages        = "1--25",
  url          = "https://www.jstatsoft.org/v40/i03/",

  textVersion  =
  paste("Garrett Grolemund, Hadley Wickham (2011).",
        "Dates and Times Made Easy with lubridate.",
        "Journal of Statistical Software, 40(3), 1-25.",
        "URL https://www.jstatsoft.org/v40/i03/.")
)
```

Modern approach seen in, for example, in tidyverse. This is what we should be scaffolding for folks:

``` r
bibentry(
  "Article",
  title = "Welcome to the {tidyverse}",
  author = "Hadley Wickham, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D'Agostino McGowan, Romain François, Garrett Grolemund, Alex Hayes, Lionel Henry, Jim Hester, Max Kuhn, Thomas Lin Pedersen, Evan Miller, Stephan Milton Bache, Kirill Müller, Jeroen Ooms, David Robinson, Dana Paige Seidel, Vitalie Spinu, Kohske Takahashi, Davis Vaughan, Claus Wilke, Kara Woo, Hiroaki Yutani",
  year = 2019,
  journal = "Journal of Open Source Software",
  volume = 4,
  number = 43,
  pages = 1686,
  doi = "10.21105/joss.01686",
)
```

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#CITATION-files

**Comment by jennybc** [comment]
@Hadley Do I have this right, i.e. that the more economical approach in tidyverse is preferred?

**Comment by hadley** [comment]
I think that's correct.

**Comment by jennybc** [comment]
I'm just checking because this seems to still be dramatically less common (I haven't found another example, tho I haven't looked *that* hard). But I agree it seems cleaner than what we're currently doing.

**Comment by hadley** [comment]
Looking at `citation("tidyverse")`, it still automatically generates "To cite package ‘tidyverse’ in publications use:".

[R-exts](https://rstudio.github.io/r-manuals/r-exts/Creating-R-packages.html#citation-files) explicitly says:

> In case a bibentry contains LaTeX markup (e.g., for accented characters or mathematical symbols), it may be necessary to provide a text representation to be used for printing via the textVersion argument to bibentry

which I think implies that you don't usually need `textVersion`.

**Comment by DavZim** [comment]
FYI, I just got a CRAN Note that
```
Package CITATION file contains call(s) to citEntry(), citHeader() or
   citFooter().  Please use bibentry() instead.
```
but as you already discussed, usethis still uses the older (?) format.

**Comment by mpadge** [comment]
I got that note too, plus another because `personList` like in the above example is no longer accepted on CRAN, and has to be replaced with `c`.

**Comment by jennybc** [comment]
We will update this in the next release, which will be soon.
