### ISSUE TITLE
Support rmarkdown templates outside `usethis` in `use_vignette()`

### ISSUE THREAD

**Issue by pol-db4drd2** [r-lib/usethis#1696]
#### Idea

Redesign `use_vignette()` so users can specify (external) rmarkdown templates for desired vignette formats.

I can probably make a PR that would add this, if desired. I have not done this before.

#### Reason

- `use_vignette()` allows setting up only `rmarkdown::html_vignette` vignettes using `templates/vignette.Rmd`
- rmarkdown templates for other recommended uses of vignettes (e.g. [scientific publication](https://r-pkgs.org/vignettes.html#scientific-publication)) are in other packages (e.g. `rticles`)

#### Proposal

A new version of `use_vignette()` etc. looking something like

`use_vignette(name, title = name, format = "vignette", package = "usethis")`

that would read rmarkdown templates in any installed package, put `title` in the YAML front matter, and create new files.

#### Work expected

- parsing and editing YAML front matter in rmarkdown templates (as `render_template()` no longer helps) presumably with `ymlthis`
- function to find rmarkdown templates in installed packages, which are not where `find_template()` wants them
- move `article.Rmd` to `inst/rmarkdown/templates/article/skeleton/skeleton.Rmd` for finding via the above
- optionally do the analogous thing for `vignette.Rmd` if not relying on the template in `rmarkdown` instead
- change `use_vignette()` and `use_article()` and `use_vignette_template()` to use the above instead of `_template()` functions

#### Advantages

- directly enhances usefulness of `usethis` and other packages, especially `rticles`
- conforms this package to standard structure (per `use_rmarkdown_template()`) for installing rmarkdown templates within packages?
- optionally, no more supporting an `rmarkdown::html_vignette` template, as there is one in `rmarkdown`

#### Disadvantages

- doesn't eliminate `render_template()` or `find_template()` package-wide, adding complexity
- `article` vignette format not found elsewhere, so `usethis` will have to maintain it
- `usethis` may not use this? If this team never wants other kinds of vignettes, this feature may be only for others

#### Alternatives

What about just hand-editing YAML front matter in new file after creating with `use_vignette()`?

- state of my own current workflow
- hoping to get this automated for myself and anyone else building packages

What about an "internal usethis-like companion" as suggested in #1694?

- won't help any other users if it remains internal
- won't automatically keep up with changes to `usethis`
- `devtools::check()` will yell at me (best solution likely involves `usethis:::`)

What about just adding some templates for recommended use cases in `templates/`?

- requires work to curate and maintain new templates in `usethis`
- creates unlimited future FRs from users proposing support of particular formats

**Comment by hadley** [comment]
This seems like a reasonable feature, but our previous experience adding workflow features that we ourselves don't use has not been positive. It's typically hard to test this sort of feature so without sufficient users, it will tend to bitrot, leading to a negative experience for new users.
