### ISSUE TITLE
Allow `create_package()` to 'convert' an existing project

### ISSUE THREAD

**Issue by wurli** [r-lib/usethis#1697]
My usual workflow is usually this:

1. Create a new repo on GitHub/AZURE DevOps
2. Clone the repo using RStudio
3. Convert the project to a package using `use_namespace()` and `use_description()`

A rejigged `create_package()` would give a much nicer workflow here. Currently the behaviour is that it gives a warning, then tries to remake any pre-existing files, including the `.Rproj` file, which is unfortunately not that convenient if a project/repo has already been initialised.

Thanks!

**Comment by hadley** [comment]
This seems like a reasonable feature, but our previous experience adding workflow features that we ourselves don't use has not been positive. It's typically hard to test this sort of feature so without sufficient users, it will tend to bitrot, leading to a negative experience for new users.
