### ISSUE TITLE
Remind to add GitHub & pkgdown URLs for first release in `use_release_issue()`

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/usethis#1704]
It is getting more and more important to make sure you add your GitHub & pkgdown URLs when submitting your package to CRAN. Yet, if you omit them, all checks will still pass, making it easy to forget it when submitting to CRAN.

I see a large number of packages on CRAN that don't include these links even though they are on GitHub and have a pkgdown website.

For reference:

- Having GitHub & pkgdown URLs in DESCRIPTION is great for discoverability and easy navigation from CRAN

- pkgdown URL is **required** to enable cross-linking from other pkgdown websites

- GitHub URL is **required** by pkgdown to link to source
- GitHub URL is **required** by r-universe to match GitHub & CRAN packages

There could be a check to optionally include the pkgdown URL item if a `_pkgdown.yml` file is found.

**Comment by malcolmbarrett** [comment]
Hmm I agree these are valuable, but if you're using usethis to setup GitHub and pkgdown, it'll automatically add the related URLs to the `DESCRIPTION` file. My instinct is that adding to the checklist will just be clutter since we've really automated away that problem already

**Comment by jennybc** [comment]
Yeah, I'm not sure whether to do anything here. As @malcolmbarrett says, if you're on the Usethis Happy Path™️, these URLs will have been added long before someone gets to CRAN release. I think the folks using `use_release_issue()` are basically already usethis keeners. I don't think we're going to reach many of the people who are neglecting to advertise these URLs by adding a check in `use_release_issue()`. We basically have a policy of not trying to work with / fix every possible initial state, but rather to focus on the states that usethis actually creates.

That being said, I don't have a big objection. It's just a question of priorities.

**Comment by gadenbuie** [comment]
I'd like to add a vote in favor of including this item in the first release checklist. First, it's not likely to be annoying if they only appear in the one-off "first release" portion of the checklist. 

Second, some people may be used to non-usethis ways of setting up GitHub or their pkgdown site (e.g. copying and pasting pkgdown and workflow files from an existing project). It could be muscle memory or that some people join the usethis Happy Path after experiencing friction within an existing project. I'll echo the OP that anecdotally I've also noticed a large number of packages with missing links. To me, the value-add of discoverability outweighs the annoyance of two additional (one-time) task items.

**Comment by jennybc** [comment]
> anecdotally I've also noticed a large number of packages with missing links

I totally agree with this. I just question if `use_release_issue()` is going to have any noticeable effect.

**Comment by Bisaloo** [comment]
It would be super interesting if you have any data on this (but how?) but I'm not convinced that all usethis users are on the Usethis Happy Path.

This is anecdotal evidence again but as @gadenbuie decribes, I tend to use only a handful of usethis commands. I've learned how to develop packages before learning about usethis and while I have some functions that I love, such as `use_release_issue()`, I haven't gotten used to using all of them. I still do some tasks manually.

I don't think it's accurate to think of usethis as "all or nothing". I do think some users just start using a specific function because they heard about on twitter, in rOpenSci newsletter, etc. and thought "oh, that's a cool function, I'll integrate it in my workflow" but it doesn't mean they will learn about usethis as a whole.
