### ISSUE TITLE
Outdated link in package-README template

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r-lib/usethis#1707]
https://github.com/r-lib/usethis/blob/b9acf67511ffe165d9c42ef7ab9fab7ff5718eac/inst/templates/package-README#L63

is still working but points to an outdated version of r-lib/actions.
I am not sure if you could use {glue} and an R function that would get the latest release from the GitHub api to give a link that referenced the most recent release. But, at a minimum this link should probably be updated to v2 in the tree instead of v1. Thanks!

**Comment by jennybc** [comment]
I actually recently removed this entire sentence, for unrelated reasons (we don't actually use GHA to rebuild our READMEs). So that solves this one!
