### ISSUE TITLE
use_git() default branch

### ISSUE THREAD

**Issue by mdsumner** [r-lib/usethis#1711]
When initializing git with `use_git()` and accepting the prompt to commit changes, the branch created is called "master". 

I would like the default branch to be 'main'. 

In an unitialized project  (one with no '.git/' directory) : 

```r
usethis::use_git()  ## agree to commit files, agree to restart project
```

the default branch created is 'master'. 

The motivation for me is because I constantly create new package projects, and sometimes I forget to change the default branch.   Then I `use_github()` and by that point I need to shift branches, change the github branch, then delete the original default branch locally and on github.   I've been doing that a lot and it must happen for others. (I appreciate that I could simply learn to change the branch at the right moment!)

**Comment by malcolmbarrett** [comment]
It's neither usethis nor gert but git itself that manages the default branch name via `init.defaultBranch`. You can change the global default by running `git_default_branch_configure()`, then `use_git()` will create a default branch with your set name

**Comment by mdsumner** [comment]
thank you

**Comment by jennybc** [comment]
Just to complete this thread, this blog post from last year gives a decent overview of where usethis stands re: default branch, plus links to outside resources:

https://www.tidyverse.org/blog/2021/10/renaming-default-branch/

And as @malcolmbarrett says, the default name for the default branch is a matter of user-level configuration. usethis, gert, git, etc. just do what your config tells them to do.
