### ISSUE TITLE
use_package("tidyverse|devtools") should generate a warning

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#172]
And suggest using the individual core packages instead

**Comment by hadley** [comment]
Actually it should just do it for you

**Comment by jennybc** [comment]
Will it add all the individual core packages? Or just refuse to do anything and say what to do instead?

**Comment by hadley** [comment]
Should add all the individual core packages

**Comment by jennybc** [comment]
@hadley raised analogous point re: depending on devtools (once the lower-level packages are on CRAN) here: https://github.com/tidyverse/tidyverse.org/pull/115#discussion_r170421482
