### ISSUE TITLE
3rd option for `pr_merge_main()`: "i'm ready to merge, but don't open the files"

### ISSUE THREAD

**Issue by Aariq** [r-lib/usethis#1720]
`pr_merge_main()` is super convenient, but sometimes it ends up opening large files (e.g. the .html file generated by a self-contained R Markdown) that causes RStudio to hang.  Often it's not important that I actually resolve the conflicts in these files (e.g. in this example, I'd just re-knit the R Markdown and commit that version).  Maybe `pr_merge_main()` can have a third option besides opening the files or aborting the merge?

**Comment by olivroy** [comment]
To add to that, could you prevent the man pages from opening? any read-only files for that matter. It's already overwhelming when there are many conflicts.

Also, it would be great if the editor opened directly to the conflicts location. (1st conflict in each file) simple regex look for `====` `rstudioapi::documentOpen(line = )` allows to do that

Thanks for the great package. It is so useful and allows users to work with git more easily!

**Comment by jennybc** [comment]
I've merged the PR that adds the option to _not_ open the files.

And, yes, it is true that there are specific categories of file that don't make sense to edit with your bare hands, such as `man/*.Rd` files or test snapshots. Maybe we'll do something about that in a later pass.
