### ISSUE TITLE
Re-consider `install_*()` functions, in light of pak

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1723]
Should the README templates switch to using pak? Are there other places we recommend `devtools::install_github()` that should switch to pak?

**Comment by jennybc** [comment]
Just consulted @gaborcsardi. For now, let's keep `devtools::install_github()` in the template. In terms of orienting more towards pak, we lean towards having `install_github()` switch from remotes to pak in the not-too-distant future.

**Comment by jennybc** [comment]
Another idea from @gaborcsardi: perhaps devtools gains a more generic `install_remote()`-type function where the different sources are differentiated via pak's source DSL instead of via a bunch of different functions.

https://pak.r-lib.org/reference/pak_package_sources.html#shorthands

**Comment by hadley** [comment]
I still think we should consider at least switching to suggest pak for tidyverse packages, just as a way as exposing more people to it.

**Comment by jennybc** [comment]
@gaborcsardi Are you feeling more ready to put `pak::pak()` in usethis's README templates? I am.
