### ISSUE TITLE
use_latest_version

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#173]
Should automatically add package version to every dependency. 

@jimhester I think we discussed this previously. Do you see any issues with doing this more frequently? (In the long run we could add tests to find the minimum version needed but that seems like it will be a lot of work)

**Comment by jennybc** [comment]
`use_tidy_versions()` is awfully close to this already.

**Comment by jimhester** [comment]
Yeah I think we decided it was too restrictive in general, but we would have use_tidy_version to do it if needed

**Comment by hadley** [comment]
Doh, that's probably what I was thinking of :(

**Comment by jennybc** [comment]
Do you think `use_tidy_versions()` should be renamed?
