### ISSUE TITLE
`scope` argument for `pat_sitrep()`?

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#1732]
In `git_sitrep()`, `pat_sitrep()` is called for both `"user"` and `"project"` scopes. Regardless of scope, it consults the `"de_facto"` git email:

https://github.com/r-lib/usethis/blob/8104204fcd78eeb1d7588c1fd5882f707ff1e54a/R/github_token.R#L182

If reporting for the `"user"` scope, I think it should consult the `"global"` email address.

I think this could be addressed by adding a `scope` argument to `pat_sitrep()`; happy to offer a PR.

**Comment by jennybc** [comment]
Sure, sounds good.

**Comment by ijlyttle** [comment]
this is a duplicate of #1722
