### ISSUE TITLE
`use_quarto_ignore()`

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/usethis#1741]
As we add more support for quarto, we should consider supporting the [.quartoignore file](https://quarto.org/docs/extensions/starter-templates.html#creating-a-template) the same as we do for git and R pkgs.

**Comment by malcolmbarrett** [comment]
I don't know if it's needed at other times, but I discovered it will working on an extension theme for reveal.js. It ignores any other files in the extension directory that shouldn't be included when using the template.

Too specific? It also might be a better fit for the quarto package, but we already have the infrastructure to handle those types of files elegantly

**Comment by hadley** [comment]
Yeah, it feels a bit too specific to usethis to me.
