### ISSUE TITLE
Cleaner code for detecting default branch in `use_github()`

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1757]
Can now check `create$default_branch != default_branch`, thanks to improvements in the github API.

**Comment by jennybc** [comment]
I'm not 100% sure what this is about, but there is some evidence that some issues remain around not being able to trust the reported default branch in a freshly created GitHub repo:

https://github.com/r-lib/usethis/commit/c6757de6f8ebf75c0acd88b8ad6415d4e93d5522

That's about a fresh fork. So we'd have to do some manual testing to investigate the situation for a freshly created *de novo* repository. There is a definitely a history of bugs.

**Comment by jennybc** [comment]
I think I should have closed this when I closed the associated PR.
