### ISSUE TITLE
Help with removing quotes from DESCRIPTION

### ISSUE THREAD

**Issue by krlmlr** [r-lib/usethis#1760]
CRAN checks flag unknown words in the `Title` and `Description` fields of `DESCRIPTION` . There is a documented solution for that problem: https://ropensci.org/blog/2022/01/21/ropensci-news-digest-january-2022/#to-quote-or-not-to-quote-non-existing-words-in-description .

Should usethis help with that? Perhaps a function `usethis::dict_extract()` (to populate from `DESCRIPTION` and remove quotes) and `usethis::dict_add_words()` ?

Usage in the wild: https://github.com/search?q=org%3Acran%20aspell&type=code

CC @maelle.

**Comment by jennybc** [comment]
I think this is basically #1466.
