### ISSUE TITLE
Can `use_release_issue()` remind us if min R version needs a bump?

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1762]
(for packages that follow the tidyverse versioning policy)

**Comment by jennybc** [comment]
Some notes:

We've discussed how proactive we want to be about this in the past, in Slack I think, and it feels we're not necessarily resolved on what to do.

I tend to come down on the proactive side, while others prefer to let this slide until there's some reason to bump it.

Advantage of bumping:

- Eliminates users from discovering the actual minimum version the hard way, then reporting that: e.g., https://github.com/tidyverse/tibble/issues/1490
- Actually matches what we say we do

Disadvantage of bumping:

- Often a lower version of R is absolutely fine and lazy bumping gives folks using older versions some grace

I think the advantages outweigh the disadvantages.

---

How are we going to define "packages that follow the tidyverse versioning policy"?

Path of least resistance in terms of stuff we already do elsewhere: base this on the package's GitHub organization.

**Comment by hadley** [comment]
Based on recent issues across various repos, I'd agree that we need to be more proactive, and I think there's little downside.

**Comment by ateucher** [comment]
This was [in the 2021 Spring Cleaning tidy upkeep checklist](https://github.com/r-lib/usethis/blame/418bc89a5bc4e116315656d9a58b775d34e9cf81/R/upkeep.R#L172). Should it be in the release issue or perennially in the upkeep issue? Or both?

**Comment by jennybc** [comment]
I'd say let's get it into the release issue for now.
