### ISSUE TITLE
use_r() and use_test() do not allow periods in filename

### ISSUE THREAD

**Issue by mastoltejr** [r-lib/usethis#1763]
Brief description of the problem
I'd like to make a file called data.frame.R, however when I call use_r('data.frame') I get a file just called 'data.R'. 

```r
# insert reprex here
use_r('data.frame') # => data.R
use_test('data.frame') # => test-data.R
```

**Comment by malcolmbarrett** [comment]
Duplicate of #1690, which is addressed in the development version. Please install from GitHub and try again
