### ISSUE TITLE
[Feature Request] Badges for release document and dev document

### ISSUE THREAD

**Issue by eitsupi** [r-lib/usethis#1767]
While pkgdown can be configured to provide two versions of documentation, a release version and a development version, it would be great if badges to the link to these could be easily attached to the README.

**Comment by jennybc** [comment]
I'm not eager to package this as a function. I think it's the kind of thing that you should just implement in your own package if you want it (meaning: having such badges).

As it stands, usethis doesn't place any sort of badges related to pkgdown. In terms of someone discovering the pkgdown site from the GitHub repo, we use the repo URL for that.

<img width="691" alt="repo-url" src="https://user-images.githubusercontent.com/599454/219185890-2818e0dd-6571-4bd5-aa72-54c0fbdc690a.png">

That is one of many things that is automatically configured by `use_pkgdown_github_pages()`, which is generally how we setup our pkgdown sites.

(It would be nice if pkgdown itself somehow made it more obvious/easy to toggle between the released and dev sites, but so far that hasn't happened and I'm not sure it ever will.)
