### ISSUE TITLE
404 after `usethis::use_pkgdown_github_pages()`

### ISSUE THREAD

**Issue by asadow** [r-lib/usethis#1770]
`usethis::use_pkgdown_github_pages()` says my website should be available, but after visiting the site, I have a 404 error.

Output of function:

> ✔ Writing '_pkgdown.yml'
> • Modify '_pkgdown.yml'
> ✔ GitHub Pages is publishing from:
> • URL: 'https://asadow.github.io/pr/'
> • Branch: 'gh-pages'
> • Path: '/'
> ✔ Saving 'r-lib/actions/examples/pkgdown.yaml@v2' to '.github/workflows/pkgdown.yaml'
> • Learn more at <https://github.com/r-lib/actions/blob/v2/examples/README.md>.
> ✔ Recording 'https://asadow.github.io/pr/' as site's url in '_pkgdown.yml'
> ✔ Adding 'https://asadow.github.io/pr/' to URL field in DESCRIPTION
> • Run `devtools::document()` to update package-level documentation.

Site message:

> 404
> File not found
> 
> The site configured at this address does not contain the requested file.
> 
> If this is your site, make sure that the filename case matches the URL.
> For root URLs (like http://example.com/) you must provide an index.html file.
> 
> [Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.
> 
> [GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)

**Comment by malcolmbarrett** [comment]
The infrastructure was added but it looks like the pkgdown action failed: https://github.com/asadow/pr/actions/runs/4235129913/jobs/7358365647

**Comment by asadow** [comment]
Thanks Malcolm. Hmm I'm at a loss what to try next after searching for solutions to the action error. Do you have any ideas?

**Comment by jennybc** [comment]
If I google the key error I see in the logs ("Permission to denied to github-actions[bot]."), I get quite a few hits. Here's the first one:

https://github.com/ad-m/github-push-action/issues/96

I think something might be misconfigured at the user or repo level?

**Comment by jennybc** [comment]
I don't think usethis has anything to do with this.

**Comment by malcolmbarrett** [comment]
I haven't seen this error before, and I've used this function several times lately, so I don't think so, either

**Comment by asadow** [comment]
> If I google the key error I see in the logs ("Permission to denied to github-actions[bot]."), I get quite a few hits. Here's the first one:
> 
> [ad-m/github-push-action#96](https://github.com/ad-m/github-push-action/issues/96)
> 
> I think something might be misconfigured at the user or repo level?

Thanks Jenny! Followed the recommendation there of setting Settings - Actions - General - "Workflow permissions" to "Read and write permissions" and that solved it.
