### ISSUE TITLE
`usethis::rename_files()` does nothing for files between packages

### ISSUE THREAD

**Issue by asadow** [r-lib/usethis#1771]
I'd like to move a function from a package to different package and thought I'd try `usethis::rename_files()`. It does nothing and may be intended to only work within packages, which means the output and `?usethis::rename_files` could be more communicative.

**Comment by jennybc** [comment]
I think this is a clash between your specific hope and what `rename_files()` does. I think it's pretty clear what `rename_files()` is meant to do (and this is consistent with the overall design of usethis: operating on and within the active project). I don't see a change that would be an overall net gain for all users.
