### ISSUE TITLE
`use_github_release()` fails when CRAN submission didn't include `NEWS.md`

### ISSUE THREAD

**Issue by arcresu** [r-lib/usethis#1774]
Scenario: I released a package to CRAN without a `NEWS.md` and only committed the news file afterwards. I tried to use `use_github_release()` and got the same error from #1691:

```R
> use_github_release()
✔ 'CRAN-SUBMISSION' file found, from a submission on 2023-02-20
• Release name: 'ggmapinset 0.2.3'
• Tag name: 'v0.2.3'
• SHA: 'cb279aefe096c7195008830c1c79c0f6697bdfb6'
Error: No top-level headings found in 'NEWS.md'
```

I stepped through what `use_github_release()`  is doing internally, and traced the problem to this helper:

https://github.com/r-lib/usethis/blob/c9e8ecb873c36273394fe4bda80e524dd05460d2/R/release.R#L363-L387

Basically it tries to download the contents of `NEWS.md` to a temporary file from github as it was at the commit specified in the `CRAN-SUBMISSION` file, but if that commit doesn't have a `NEWS.md` like in my case, then the temp file looks like:

```
> usethis:::read_utf8(news_path)
[1] "{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/repos#get-repository-content\"}"
```

So the file was filled with an API error message from github when the code was expecting the contents of `NEWS.md` file. It tries to parse it as a news file and hence throws the original error about missing top-level headings.

The helper ought to check for errors from the github API (I imagine other types of errors are possible too) rather than writing them to the output file, and the code should cope with the fact that the released commit might not have included `NEWS.md`.

**Comment by arcresu** [comment]
I think `usethis` is making a wrong assumption about how `gh` behaves, which is a strange behaviour.

```R
gh <- usethis:::gh_tr(tr)
> gh( "/repos/{owner}/{repo}/contents/{path}", path = "NEWS.md", ref = sha)
Error in `gh_process_response()`:
! GitHub API error (404): Not Found
✖ URL not found:
  <https://api.github.com/repos/cidm-ph/ggmapinset/contents/NEWS.md?ref=cb279aefe096c7195008830c1c79c0f6697bdfb6>
ℹ Read more at <https://docs.github.com/rest/reference/repos#get-repository-content>
Run `rlang::last_error()` to see where the error occurred.
```

So gh is properly raising an error. The `purrr::possibly()` wrapper also behaves as expected:

```R
gh <- purrr::possibly(usethis:::gh_tr(tr), otherwise = NULL)

# should return NULL since NEWS.md doesn't exist in this commit
> gh( "/repos/{owner}/{repo}/contents/{path}", path = "NEWS.md", ref = sha, .accept = "application/vnd.github.v3.raw" )
NULL

# this should return bytes because README.md does exist:
> gh( "/repos/{owner}/{repo}/contents/{path}", path = "README.md", ref = sha, .accept = "application/vnd.github.v3.raw" )
   [1] 0a 3c 21 2d 2d 20 52 45 41 44 4d 45 2e 6d 64 20 69 73 20 67 65 6e 65 72 61 74 65 64 20 66 72 6f 6d 20 52 45 41
  [38] 44 4d 45 2e 52 6d 64 2e 20 50 6c 65 61 73 65 20 65 64 69 74 20 74 68 61 74 20 66 69 6c 65 20 2d 2d 3e 0a 0a 23
  # .. (snip) ..
```

But it breaks down when you use the `.destfile` option with `gh::gh()`:

```R
> gh( "/repos/{owner}/{repo}/contents/{path}", path = "NEWS.md", ref = sha, .accept = "application/vnd.github.v3.raw" , .destfile = news_path)
NULL
> usethis:::read_utf8(news_path)
[1] "{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/repos#get-repository-content\"}"

# trying with a file that does exist:
> gh( "/repos/{owner}/{repo}/contents/{path}", path = "README.md", ref = sha, .accept = "application/vnd.github.v3.raw" , .destfile = news_path, .overwrite=T)
[1] "/tmp/Rtmp7LCt65/ggmapinset-NEWS-cb279ae-272c87e801053"
attr(,"class")
[1] "gh_response" "path"  
> usethis:::read_utf8(news_path)
 [1] ""                                                                                         
 [2] "<!-- README.md is generated from README.Rmd. Please edit that file -->" 
 # .. (snip) ..
```

The bug in `usethis` is that it's using the existence of the tempfile as a proxy for success, when really it should be checking whether the return value of `gh()` is `NULL` or a path.

The fact that `gh::gh()` writes the API error message to `.destfile` is a strange behaviour and maybe a bug in `gh`.

**Comment by jennybc** [comment]
It's nice to have a better theory (maybe) for what was going on in #1691. In any case, yes, we should do better in `use_github_release()` and elsewhere when we fail to get the contents of a GitHub file.
