### ISSUE TITLE
Consider "skip" option when overwriting files

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#178]
i.e

```R
Overwrite 'blah.md'?
1. Yes
2. No, abort
3. No, continue
```

**Comment by jennybc** [comment]
I now see that this is essentially what PR #350 is becoming.

@hadley Do you care to offer any review of vague words on that, for me to follow up on?

**Comment by hadley** [comment]
I think the approach in #350 is probably better.

**Comment by jennybc** [comment]
Closed when merged #350 in 3046fde5536f0e6ac28432aadef82e7a291a94d8
