### ISSUE TITLE
Create a function to detect missing alt-text in images

### ISSUE THREAD

**Issue by ateucher** [r-lib/usethis#1783]
It would be great to have some code to help us detect images in READMEs, vignettes, etc. that do not have alt-text. This would include R code chunks in quarto/R Markdown documents that generate images (e.g., plots), as well as images included via `knitr::include_graphics)` in a code chunk and in markdown via `![Alt](/path/to/img.jpg “image title”)`

**Comment by jennybc** [comment]
Is usethis the obvious implementer of this? I'm wondering if something exists or should exist in, e.g., knitr / rmarkdown / quarto-r.

Then we would add a nudge to call this function, whoever owns it, in release and/or upkeep checklists.

**Comment by hadley** [comment]
Yeah, not clear that this code would naturally belong to usethis, but not clear where else it might belong.

**Comment by jennybc** [comment]
This would be worth some attention on tidyverse dev day, regardless of where the function would eventually live.

**Comment by hadley** [comment]
pkgdown now reports on missing alt-text, so I think we can close this issue?
