### ISSUE TITLE
`edit_r_profile(scope = c("user", "project"))` does not open project `.Rprofile`

### ISSUE THREAD

**Issue by asadow** [r-lib/usethis#1797]
It seems the function should open both or the documentation should reflect that only one is used with the default `scope = "user"`.

**Comment by jennybc** [comment]
Many R functions reveal the acceptable values for an argument in this way and then, internally, use `match.arg()` to effectively validate any user-provided input or, in the absence of that, set the value to the first element of the default value vector.

This is a *de facto* convention you will see in many places in base R and add-on packages.
