### ISSUE TITLE
`options(usethis.protocol = "https")` in .Rprofile does not change default for R sessions

### ISSUE THREAD

**Issue by asadow** [r-lib/usethis#1801]
`git_protocol()` is giving me ssh (I don't know why) and `options(usethis.protocol = "https")` in my .Rprofile after `edit_r_profile()`. is not setting the protocol to https. 

I have tried placing the options in Rprofile.site (where I also have `options(renv.config.user.profile = TRUE)`) but to no avail.

**Comment by jennybc** [comment]
Have you restarted R?

**Comment by asadow** [comment]
Yes.

D'oh! I had placed the example `options()` from the [usethis setup](https://usethis.r-lib.org/articles/usethis-setup.html) into my .Rprofile and not realized they invoked the ssh protocol. Apologies.

`[options](https://rdrr.io/r/base/options.html)(
  usethis.full_name = "Jane Doe",
  usethis.protocol  = "ssh",
  usethis.description = [list](https://rdrr.io/r/base/list.html)(
    "Authors@R" = utils::[person](https://rdrr.io/r/utils/person.html)(
        "Jane", "Doe",
        email = "jane@example.com",
        role = [c](https://rdrr.io/r/base/c.html)("aut", "cre"),
        comment = [c](https://rdrr.io/r/base/c.html)(ORCID = "JANE'S-ORCID-ID")
    ),
    Version = "0.0.0.9000"
  ),
  usethis.destdir = "~/the/place/where/I/keep/my/R/projects",
  usethis.overwrite = TRUE
)`

**Comment by jennybc** [comment]
The example shows setting the ssh protocol, because the default is https. I.e. if you want https, you should let the default behaviour happen.
