### ISSUE TITLE
Advice around github action pr-command to trigger

### ISSUE THREAD

**Issue by DyfanJones** [r-lib/usethis#1811]
Hi all,

I am having difficulty getting the github action pr-command to trigger correctly.  Here is the yaml file: 
https://github.com/paws-r/paws/blob/main/.github/workflows/pr-commands.yaml

From my knowledge a member of the team or the owner should be able to trigger the pr-command action. However I am unable to do so:
https://github.com/paws-r/paws/pull/601

From checking: https://github.com/paws-r/paws/actions/workflows/pr-commands.yaml it looks like the actions isn't getting triggered.

Any advice around this I would be very grateful.

**Comment by jennybc** [comment]
I'm going to point you to the general advice for troubleshooting the actions and examples house in r-lib/actions:

https://github.com/r-lib/actions#where-to-find-help

Once usethis has placed the workflow `.yaml` for you, that's all it does. So this isn't a place where we can help with workflow troubleshooting.

I'm totally speculating, but once you're absolutely convinced that your workflow file is up-to-date with the official example, I would consider if the hosting GitHub organization (paws) perhaps has some settings that are playing a role. Or, likewise, similar configuration questions at the repo level or re: your role and permissions.
