### ISSUE TITLE
Set write permission for action to deploy pkgdown site

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/usethis#1813]
I just moved an old project to Github, and `usethis` made the setup really easy.  Thanks!

One issue arose when I tried to add a `pkgdown` site:  by default Github actions don't have write permission that they need to deploy the site.

I don't know if `usethis` could make the setting change, but if not, it would be helpful to point users to instructions for doing it themselves.

I think this issue gives a reprex and the manual solution in the comments:  https://github.com/r-lib/pkgdown/issues/2279 .

**Comment by jennybc** [comment]
Which usethis function(s) did you use in the course of this?

This does not constitute a real answer, but I just know that, in a fresh repo, `use_pkgdown_github_pages()` appears to "just work" for lots of people, myself included.

So I suspect some part of this story is something about a weird or suboptimal starting state.

**Comment by dmurdoch** [comment]
I had the package source on my laptop to start.    Here are (all of) the commands I entered, according to the RStudio history:

```r
usethis::use_git()
usethis::use_github()
usethis::use_news_md()
usethis::use_readme_rmd()
example(plotcorr)
library(ellipse)
example(plotcorr)
?plotcorr
usethis::use_pkgdown()
pkgdown::build_site()
usethis::use_pkgdown_github_pages()
```

I can't show you the log that failed, because I fixed the permissions and told it to run again, but it looked a lot like the one in https://github.com/r-lib/pkgdown/issues/2279 .

It's quite possible that I have some settings on my Github account that are different than the defaults.  I'm not sure what to report to you.  I do have a PAT set up, and I have just set up 2FA, but this has happened before the 2FA request.

**Comment by dmurdoch** [comment]
This link:  https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/ probably explains it:

> [Repositories owned by personal account](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions): New repositories will have read-only token.

**Comment by jennybc** [comment]
Thanks -- yes, that seems to explain why new repos under personal accounts will behave differently from what we've experienced in the past. February is not that long ago.

**Comment by maelle** [comment]
I think closing this should close https://github.com/r-lib/pkgdown/issues/2280 since pkgdown points to usethis. :grin: (I hadn't realized it at the time of opening the issue :woman_facepalming:)
