### ISSUE TITLE
Expand use_release_issue() checklists with reminder about the CITATION file

### ISSUE THREAD

**Issue by stitam** [r-lib/usethis#1816]
Hi, Many thanks for developing this package. When I submit a new version of a package to CRAN I often forget to update the CITATION file. Since I always use `usethis::use_release_issue()` when preparing for a submission, I was wondering if the checklists could be expanded to include a reminder about the CITATIONS file?

**Comment by jennybc** [comment]
What sort of updates do you need to make in CITATION? I suppose I think of that as a something that's fairly static once it exists.

**Comment by stitam** [comment]
Thanks @jennybc. I am not 100% sure how `citation("<package>")` gets updated during a release but it seems if there is no CITATION file in `/inst` then the url will be a CRAN url and the authors will be selected automatically. Instead of this, I would prefer to use a permanent Zenodo DOI and check the list of authors manually. Because of this, for me it would be helpful to have a reminder to check the CITATION file. If you think this is very niche application, then it's fine for me to have a separate checklist which includes this.

**Comment by jennybc** [comment]
Reading between the lines a bit here, maybe I can guess going on.

CRAN has recently started to warn for old-fashioned CITATION files, preferring a newer format. And maybe you saw that and opened this issue?

This is still more of a one-time update than something that requires attention in every release. The development version of usethis now creates the more modern format.

If I'm right, you should call `use_citation()` to get a new-style CITATION file and then re-populate it with the correct information. This operation goes best, of course, if you're using version control. If not, make a safe copy of `CITATION` before you overwrite it with `use_citation()`.

More backstory:

#1695

https://github.com/r-lib/usethis/commit/394eb5c7f448318c865ca8e8fff58f2b0ea89e00

**Comment by stitam** [comment]
Thanks @jennybc, I think this is something else. To show you an example:

https://github.com/ropensci/taxizedb/pull/67/files

Here I am adding a CITATION file to include a permanent Zenodo DOI instead of the CRAN link. My understanding is that CITATION is a static file and it won't update automatically when there is a new release. Therefore, when preparing a new release, e.g. the version number in the `note` section will have to be increased manually. This is something I don't want to forget.

**Comment by jennybc** [comment]
I would experiment with **not** having a CITATION file! In its absence, there is a very good auto-citation generated from DESCRIPTION and it's possible that you can put your zenodo DOI somewhere in DESCRIPTION that makes it appear in a suitable way in the auto-citation.

If that doesn't check all your boxes, then you should add your own release bullet for this matter as described here:

https://usethis.r-lib.org/reference/use_release_issue.html

I don't think this is a general enough need to build something into `use_release_issue()`.
