### ISSUE TITLE
Be more flexible re: name of global gitignore file

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#182]
Mine is at `~/.gitignore_global`, not `~/.gitignore`.

I though I was typical, but [it looks like I am wrong](https://twitter.com/JennyBryan/status/947225672090468352). However, some people *do* use that filename and most tutorials / blog posts seem to favour it.

Right now, if you have `~/.gitignore_global`, `edit_git_ignore("user")` doesn't pick it up and instead creates and opens a new, empty file.

Handy way to check location of global gitignore, if you have access to command line git:

``` sh
jenny@2015-mbp usethis $ git config --get core.excludesfile
/Users/jenny/.gitignore_global
```

**Comment by jennybc** [comment]
It's not just the name, even the location can vary. But I think these other locations are pretty rare and are *quite* intentional: `$HOME/.config/git/ignore` and `$XDG_CONFIG_HOME/git/ignore` are also possibilities; see <https://git-scm.com/docs/gitignore>.

**Comment by batpigandme** [comment]
Possible you were right and people were just confused (I thought mine was `~/.gitignore` and lo: `core.excludesfile=/Users/maraaverick/.gitignore_global` ¯\(°_o)/¯

**Comment by jennybc** [comment]
@batpigandme Yeah I am skeptical of the poll because I'm surprised how few people (know they) have `.gitignore_global` 😏. I'm taking the data with a large grain of salt.

**Comment by jennybc** [comment]
Documenting where each form of global (i.e. user-level) gitignore appears, for posterity.

`.gitignore`

  * Dominates my [Twitter poll](https://twitter.com/JennyBryan/status/947225672090468352), at least, among people who know they have a global gitignore
  * The [official gitignore docs](https://git-scm.com/docs/gitignore)
  * What [Git in Practice](https://github.com/GitInPractice/GitInPractice/blob/master/07-PersonalizingGit.adoc#ignore-files-across-all-repositories-global-ignore-file) shows

`.gitignore_global`

  * [GitHub's resources](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore)
  * [Pro Git](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)
