### ISSUE TITLE
update links in inst/templates/testthat.R?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#1823]
links introduced by "Learn more about the roles of various files in" :slightly_smiling_face:

**Comment by jennybc** [comment]
For context, my head is somewhat elsewhere. But can you elaborate a bit on what specific update you're proposing?

**Comment by maelle** [comment]
Sorry, it wasn't clear at all. I was looking at a diff with that file and remembered about the newer book chapter + the new vignette (too new? there is dev in the link :sweat_smile: ). I made a PR.
