### ISSUE TITLE
`edit_*()` stalls RStudio when the file is already open and hidden in another source column 

### ISSUE THREAD

**Issue by olivroy** [r-lib/usethis#1838]
Steps to reproduce the problem

* Open RStudio
* Add source column Ctrl + F7
* Open Rprofile (with `edit_r_profile()`)
* Move `.Rprofile` to the other source column
* Hide `.Rprofile` / the new source pane (i.e. completely reduce it, see 2nd screenshot) (it works if the 2nd source pane is still visible)
* Rerun `edit_r_profile()`

The R session stalls.

![image](https://github.com/r-lib/usethis/assets/52606734/d9a8c0d0-a1d5-44af-aa61-545321ea25b5)

![image](https://github.com/r-lib/usethis/assets/52606734/d59ad2b9-4c28-4878-8fc6-ebc3a7552ff1)

I would expect that the focus would open and move to the secondary source pane.

It does the same thing with `edit_file()`.
I tried using the shortcut `Ctrl + .` to open it in RStudio, however, it doesn't work (no error or session stalling however), so it may be caused by the IDE, not by usethis itself.

Thanks.

Edit: I am on Windows, R 4.2.3 with RStudio 2023.03+386

**Comment by jennybc** [comment]
I think this is too unusual a maneuver for us to prioritize this, in the context of other issues that need attention here and elsewhere. And, yeah, the problem probably lies fully or partially in the IDE itself.

Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
