### ISSUE TITLE
Release usethis 2.2.0

### ISSUE THREAD

**Issue by ateucher** [r-lib/usethis#1849]
Prepare for release:

* [x] `git pull`
* [x] [Close v2.2.0 milestone](../milestone/10)
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_usethis.html)
* [x] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
* [x] Bump required R version in DESCRIPTION to 3.6
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `revdepcheck::cloud_check()`
* [x] Update `cran-comments.md`
* [x] `git push`
* [ ] ~Draft blog post~
* [ ] ~Slack link to draft blog in #open-source-comms~
* [x] Check that `use_code_of_conduct()` is shipping the latest version of the Contributor Covenant (<https://www.contributor-covenant.org>).

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [ ] ~Add preemptive link to blog post in pkgdown news menu~
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`
* [ ] ~Finish blog post~
* [x] Tweet

**Comment by ateucher** [comment]
revdepcheck failures (x5):

- [ ] **altdoc** failures
    ```
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
       2.   └─usethis:::cran_version()
       3.     └─utils::available.packages()
       4.       └─utils::contrib.url(repos, type)
      ── Error ('test-utils.R:48:3'): import_* functions work ────────────────────────
      Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
    ```
    I'm not sure if there is a way to set a CRAN mirror on the cloud revdepcheck service? I'm pretty sure this is a false positive - check runs cleanly locally.

- [ ] **cffr** test failures
     ```
      ── Failure ('test-cff_to_bibtex.R:416:3'): Errors ──────
      b <- cff_to_bibtex("testthat")` produced warnings.

     Warning message:
     In citation(n$package, auto = TRUE) :
         could not determine year for 'usethis' from package DESCRIPTION file
     ```
     calls `citation()` on all testthat dependencies (including usethis), and since the dev version of usethis is installed it does not have a year in the installed `DESCRIPTION` file. I believe this is a false positive.

- [ ] **exampletestr** failures
```
── Error ('test-files.R:22:3'): `make_tests_shells_file()` and `make_tests_shells_pkg()` work ──
<usethis_error/error/condition>
Error: Paths must be relative to the active project
Backtrace:
     ▆
  1. ├─base::replicate(...) at test-files.R:22:2
  2. │ └─base::sapply(...)
  3. │   └─base::lapply(X = X, FUN = FUN, ...)
  4. │     └─exampletestr (local) FUN(X[[i]], ...)
  5. │       └─exampletestr::make_tests_shells_file("R/detect.R", pkg_dir, open = FALSE)
  6. │         ├─withr::with_options(...)
  7. │         │ └─base::force(code)
  8. │         ├─usethis::ui_info("Wrote {usethis::ui_path(usethis::proj_path(test_file_name),\n                               usethis::proj_path())}.")
  9. │         │ └─glue::glue(x, .envir = .envir)
 10. │         │   └─glue::glue_data(...)
 11. │         ├─usethis::ui_path(usethis::proj_path(test_file_name), usethis::proj_path())
 12. │         │ └─fs::is_dir(x)
 13. │         │   └─fs::file_info(path, follow = follow)
 14. │         │     └─fs::path_expand(path)
 15. │         └─usethis::proj_path(test_file_name)
 16. │           └─usethis::ui_stop("Paths must be relative to the active project")
 17. └─glue (local) `<fn>`("usethis::ui_path(usethis::proj_path(test_file_name),\nusethis::proj_path())")
 18.   ├─.transformer(expr, env) %||% .null
 19.   └─glue (local) .transformer(expr, env)
 20.     └─base::eval(parse(text = text, keep.source = FALSE), envir)
 21.       └─base::eval(parse(text = text, keep.source = FALSE), envir)
── Error ('test-functions.R:43:3'): `make_tests_shell_fun()` works ─────────────
<usethis_error/error/condition>
Error: Paths must be relative to the active project
```
I believe this is related to https://github.com/r-lib/usethis/commit/f23c5a0ab51aabd71fbdd4891b5b9950dfbf9ac0. 

- [ ] **fledge** failures
```
── Error ('test-bump_version.R:5:3'): bump_version() works -- dev ──────────────
Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
Backtrace:
    ▆
 1. └─fledge::with_demo_project(...) at test-bump_version.R:5:2
 2.   └─fledge::create_demo_project(dir = dir, news = TRUE)
 3.     ├─usethis::with_project(...)
 4.     │ └─base::force(code)
 5.     ├─rlang::with_interactive(...)
 6.     └─usethis::use_news_md()
 7.       └─usethis:::cran_version()
 8.         └─utils::available.packages()
 9.           └─utils::contrib.url(repos, type)
```
Similar to **altdoc** I believe this is a false positive

- [ ] **fusen** failures
```
── Error ('test-inflate_utils.R:36:1'): (code run outside of `test_that()`) ────
Error in `get(x, envir = ns, inherits = FALSE)`: object 'use_description_field' not found
Backtrace:
    ▆
 1. ├─usethis::with_project(...) at test-inflate_utils.R:36:0
 2. │ └─base::force(code)
 3. ├─usethis::with_project(...) at test-inflate_utils.R:48:2
 4. │ └─base::force(code)
 5. └─fusen::inflate(...) at test-inflate_utils.R:49:4
 6.   └─fusen:::create_vignette(...)
 7.     └─utils::getFromNamespace("use_description_field", "usethis")
 8.       └─base::get(x, envir = ns, inherits = FALSE)
```
Using previously unexported, and now removed, `use_description_field()` via `getFromNamespace()`.

**Comment by ateucher** [comment]
For fusen, I can open an issue and suggest they use `desc::desc_set()` instead (or a PR?).

For exampletestr, I can open an issue or PR showing the new correct usage of `proj_path()`.

Thoughts @jennybc?

**Comment by jennybc** [comment]
I agree that altdoc, cffr, and fledge are false positives.

Sidebar: Maybe we should open an issue on the cloud check repo (the back end) to have them set a CRAN mirror?

And, yes, fusen using an unexported function ... that's a risk they take. It would be great if you opened an issue and/or PR for them to use desc instead.

I need to read the exampletestr bit more carefully. But yes, definitely, open an issue or PR. The question is whether we have to wait 2-3 weeks to give them time to update. That appears to be the only actual breakage.

**Comment by ateucher** [comment]
fusen: https://github.com/ThinkR-open/fusen/pull/205

**Comment by jennybc** [comment]
Summarizing some slack discussion: We've concluded that some of exampletestr's `ui_info()` calls have been creating nonexistent/nonsense paths, for use in messaging. The problem has gone undetected until now, because these paths are *only* used in messages. We have made a change in usethis such that these nonexistent/nonsense paths have become an error, thereby exposing the problem.

https://github.com/rorynolan/exampletestr/issues/11
https://github.com/rorynolan/exampletestr/pull/12

**Comment by jennybc** [comment]
It turns out that altdoc and fledge were not false positives, although the failures did not show up in CRAN's incoming revdep checks. But they have shown up after the fact. This is about `use_news_md()` leading to `Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror`.
