### ISSUE TITLE
namespace vs standalone

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/usethis#1853]
I'm not certain if this is a usethis issue, or an rlang issue, or neither and I'm just not understanding something.

I'm experimenting with the new `use_standalone()`, and I immediately ran into confusion. Here's a ~reprex (it's package-creation-level so not really a fully independent reprex) to see what I'm seeing:

```
# Create a mostly-empty package, then
use_standalone("r-lib/rlang", "types-check")
devtools::document(".")
devtools::load_all(".")

# Try to use anything that's in the standalone, such as
check_bool()
#> Error in env_get_list(nms = c("format_arg", "format_code"), last = topenv(),  : 
#>   could not find function "env_get_list"
```

Don't all the rlang functions in there either need to be namespaced or imported? I see that you're using that standalone in usethis, but I also see that you have `import(rlang)` in your NAMESPACE, so maybe that's masking this requirement? I also see that the namespacing was [removed in rlang](https://github.com/r-lib/rlang/blob/main/R/standalone-types-check.R#L49) to avoid issues, maybe that helped to mask this issue?

To avoid the [loop of errors](https://github.com/r-lib/rlang/issues/1482) that the namespacing caused in rlang, does the `# imports: rlang (>= 1.1.0)` directive need to be taken as "add `@import IMPORTPKGNAME` to PKGNAME-package.R"?

If there's a simpler solution that I'm not seeing, please let me know!

**Comment by jennybc** [comment]
@lionel- as the main designer/implementer of the standalone file system, do you care to weigh in? Happy to get suggestions for things we should refine in usethis code or docs.

**Comment by lionel-** [comment]
oh I thought it'd do that automatically in the usethis imports section.

**Comment by lionel-** [comment]
I'll take another look, thanks for the report

**Comment by lionel-** [comment]
I think ideally we'd solve this by leveraging roxygen2 and adding `#' @import rlang` in the standalone file. This way the file can precisely determine its imports.

Now I remember that I already tried this but ran into the issue that roxygen2 adds an `import(rlang)` entry in the NAMESPACE file of rlang itself, which causes loading issues.

@hadley Would it be reasonable to change roxygen2 so it ignores such self-import directives?

**Comment by hadley** [comment]
I think we should just document this. I don't think it's worth putting a bunch of effort into `use_standalone()` to make it 100% bullet proof.

**Comment by jonthegeek** [comment]
Documentation would have covered my original issue. I wasn't sure if I was misunderstanding something, so telling me I was right would have covered it.
