### ISSUE TITLE
Include all CC licenses

### ISSUE THREAD

**Issue by pachadotdev** [r-lib/usethis#1854]
Dear @jennybc 

Following https://github.com/r-lib/usethis/pull/870, I included CC licenses within `usethis`. This will be useful, for example, for R4DS translation projects (i.e., R4DS itself is under CC BY-SA 4.0) and other non-code projects and data packages.

I will send a PR linked to this feature request.

Best,
Pacha

**Comment by pachadotdev** [comment]
hi!
here's the PR https://github.com/r-lib/usethis/pull/1855
also, I think it would be valuable to reformat all the MD files with the licenses, to render those like this one: https://github.com/matthewmccullough/Creative-Commons-4.0-Markdown/blob/master/licenses/by-nc-sa.markdown
I can do that in a separate PR

**Comment by hadley** [comment]
We'd prefer to do this more tactically, adding CC licenses where there's a clear need. In general, we do want to steer our users towards specific licenses rather than offering a smorgasbord of every possible option.
