### ISSUE TITLE
biocthis v1.11.3 reflects internal changes in usethis + thoughts on how to best notice these changes

### ISSUE THREAD

**Issue by lcolladotor** [r-lib/usethis#1856]
Hi `usethis` dev team,

Thanks again for the great package. I just wanted to communicate to you that I've updated `biocthis` after internal changes in `usethis` https://github.com/lcolladotor/biocthis/commit/4488eca070339bb0b640364a6f374f4eb16b7f37. I know that I'm likely the only one using these un-exported `usethis` functions, and so like we have talked in the past, there's no need for you to export them as these internal functions are not designed for most users to rely on.

I noticed these changes while doing a live demo on `biocthis` today as the GHA workflow for it hadn't been run in about a month. I don't necessarily think there's anything to change as either through GHA or `biocthis` users, I should learn about braking changes like this fairly fast (same with the Bioconductor runs of `biocthis`). Though maybe you have suggestions on how to implement unit tests for these functions (the equivalent of your `use_news_md()`, `use_readme_rmd()` and `use_vignette()`). Maybe I just need to add unit tests like https://github.com/r-lib/usethis/blob/e02bc2f8745dd4ddd1d71c427b02030582fac56e/tests/testthat/test-vignette.R#L18-L22 but for `biocthis::use_bioc_vignette()` and similar functions, just to check that these files can be created.

If you have other suggestions, I'm all ears =)

Thanks,
Leo

**Comment by malcolmbarrett** [comment]
I wasn't involved in past conversations, but yeah, relying on internal functions from another package is just inherently high risk. There is no guarantee about them, and there shouldn't be. 

If you want to be even faster about these failure, you could 1) add a cron job to your GHA so it e.g. runs every day and/or 2) add an explicit set of tests around `getFromNamespace()` and/or 3) make sure your GHA testing is on the dev version of usethis to head off any issues

Alternatively, of course, you can hard code some of the functions into your package, but that comes with risks of its own, as bugs won't get fixed and other internals might change, breaking the hard-coded functions

**Comment by jennybc** [comment]
@malcolmbarrett has some good ideas.

Yeah, I think you should have your own tests that exercise your equivalents of `use_news_md()`, `use_readme_rmd()`, and `use_vignette()`, as you propose @lcolladotor.

As for checking against a dev version of another package, readr has a scheduled GHA workflow set up for this with vroom, given the very special relationship between those two packages.

https://github.com/tidyverse/readr/blob/main/.github/workflows/R-CMD-check-against-dev-vroom.yaml

**Comment by lcolladotor** [comment]
Awesome, thank you both for the feedback! I'll update `biocthis` shortly (in a few days) and implement unit tests + the chron GHA workflow with the devel version of `usethis`.

I'll close this issue (though I'll link to it on the related `biocthis` commits in case you are curious 👀).
