### ISSUE TITLE
use_github function uses global github credentials instead of local credentials specific to a project

### ISSUE THREAD

**Issue by evashah21** [r-lib/usethis#1860]
Brief description of the problem
I am using `use_github()` function in the usethis pack age inside a Quarto project, which I initiated using RStudio. My git credentials for this project are different from the global git credentials stored in git bash. So, the issue is that I want to create the github repo as per the local git credential, but when I use `use_github()` function, I end up creating a repo in the global account. Is it possible to change this? 

I would suggest you to give one more option in the function: if creds = "local", then it should create a git repo in the account stored in the local git config (specific to the project), but if creds = "global", then it should create a git repo in the account stored in the global git config.

# steps to reproduce this problem
1. Create a project in RStudio.
2. In the RStudio terminal, change the git credentials using `git config user.name` and `git config user.email` commands.
3. use the command `usethis::use_github()`
```

**Comment by jennybc** [comment]
`use_github()` determines the authenticated GitHub user from the current personal access token, not from the git config, which pertains to local Git operations. So you'll need to approach this problem through that lens:

https://github.com/r-lib/usethis/blob/97b2891a838fe0138543a9a93e8b2b7f5cf86677/R/github.R#L104

You'll have to do some analysis to see if what you want is achievable with local Git config that gets picked up by the gh and gitcreds package. The issue of which GitHub user to create the repo under is not within the scope of what usethis controls.

(This is a pretty niche use case, so it's unlikely usethis would implement something specific to this need.)

**Comment by evashah21** [comment]
Thank you Madam, for pointing me to right resources. I could really use my personal github token using gh and gitcreds packages.
