### ISSUE TITLE
`use_dev_package` tries to install from CRAN rather than the remote

### ISSUE THREAD

**Issue by Moohan** [r-lib/usethis#1870]
I created a package and initialised renv. I was using `use_dev_package("funspotr")` to add the [`{funspotr}`](https://github.com/brshallo/funspotr/) package to the `DESCRIPTION`. No matter how I specified it e.g. even as: `use_dev_package("funspotr", remote = "git::https://github.com/brshallo/funspotr.git")` `usethis` would say the package wasn't installed and if I chose to install the package it would go to CRAN, where it obviously wouldn't find it and then would fail.

I think if `use_dev_package` is trying to install a package it should try and install it from `remote`, if remote isn't specified the user should be prompted to enter one.

**Comment by jennybc** [comment]
It's pretty unusual to use renv while developing a package and, unless you have a specific reason to do so, I wouldn't recommend it. It's certainly not a use case that has been explored or designed around much in terms of devtools/usethis.

I'm guessing you have not installed funspotr into the project-specific library for this new project?

**Comment by Moohan** [comment]
Yep exactly, it hadn't been installed into the project specific library. 

Probably less likely but this issue could also occur outside of a renv context, if adding the package before installing it, which is surely the situation that the rlang::check_installed() is trying to catch... It just doesn't work when the package in question comes from a non-standard (CRAN) source.

**Comment by jennybc** [comment]
I feel like the message telling you that the package wasn't installed worked as intended here. devtools and usethis basically assume that when you are working on a package, you have all of its dependencies installed locally. I think it makes more sense for you to install `brshallo/funspotr` in the renv library specific to your package, then call `use_dev_package()` than for usethis to gain a lot of conditional code for this edge case.
