### ISSUE TITLE
`use_release_issue()`: should `devtools::release()` be preferred over `devtools::submit_cran()`?

### ISSUE THREAD

**Issue by florisvdh** [r-lib/usethis#1877]
The documentation of `devtools::submit_cran()` advises to use `devtools::release()` instead, since the latter provides extra checks.

> **Details**
>
> It's recommended that you use [release()]() rather than this function as it performs more checks prior to submission.

Would it be better to implement that advice in the task list of `use_release_issue()`?

**Comment by jennybc** [comment]
The current thinking is that the checklist in `use_release_issue()` replaces the checks done in `devtools::release()`. So we really do mean to have `devtools::submit_cran()` here.

(That being said, depending on context, I sometimes do `devtools::release()` anyway, just to be extra careful. It depends on how fraught this particular release or package is, how many releases I've done lately, i.e. whether I'm "in the zone" or not.)

The best resolution of this would be to change the `devtools::submit_cran()` advice to better reflect ☝️

**Comment by florisvdh** [comment]
That all makes much sense; thank you Jenny for the explanations – and your great work!

**Comment by jennybc** [comment]
So, you're welcome to make the corresponding PR to devtools (though you certainly don't have to!).

**Comment by ateucher** [comment]
FWIW I almost always use `devtools::release()` even with the release checklist. The extra few minutes is worth the peace of mind for me.
