### ISSUE TITLE
Idea: function to increment version number

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/usethis#188]
Would it be within the scope of this package to have a function similar to `usethis::use_dev_version()` but instead it could increment the ‘major’, ‘minor’ or ‘patch’ accordingly.

If it is of interest I would be happy to conjure something up.

**Comment by jennybc** [comment]
Interesting idea. Maybe `use_dev_version()` should be reconceived to be more general? I'm really pushing to get an update out soon and this is not going to make the current release, but could make the one after that.

Not sure what the name should be, but interactively, it could show current version and offer a menu of possible increments, with default behaviour for a non-interactive session (primarily for testing). At a high-level, it would do the same things that `use_dev_version()` does now, i.e. look after obvious git operations, populate/overwrite `Version` in DESCRIPTION, and add a heading to NEWS.
