### ISSUE TITLE
Circular reference in `use_description()` documentation

### ISSUE THREAD

**Issue by joeroe** [r-lib/usethis#1881]
`?use_description` contains the following text under the 'fields' argument:

> See [use_description()](#) for how you can set personalized defaults using package options.

With the link going to the same documentation page. Presumably it was mistakenly copied from `?create_package`, which has the same text.

I think it would be more useful to point the user to `use_description_defaults()` to discover the default value of this argument.

**Comment by jennybc** [comment]
@joeroe Did you intend to make a pull request?

**Comment by joeroe** [comment]
@jennybc Yes it's at #1882. I didn't link it to this issue properly, apologies.

**Comment by jennybc** [comment]
Oh sorry, I wasn't being pedantic, I really somehow overlooked that. But yes it's good to link them.

Thanks!
