### ISSUE TITLE
use_news_md doesn't work on (my) Windows

### ISSUE THREAD

**Issue by stla** [r-lib/usethis#1885]
Hello,

```r
> usethis::use_news_md()
✔ Setting active project to 'C:/SL/MyPackages/giacR'
Error in ie_get_proxy_for_url(test_url) : 
  ERROR_WINHTTP_UNABLE_TO_DOWNLOAD_SCRIPT
```
Well, not very important, I can do the NEWS.md manually.

**Comment by stla** [comment]
In fact, I get exactly the same error when I do `curl::has_internet()`. I'm using the laptop from my job, without admin rights. Would you know a workaround?

**Comment by ijlyttle** [comment]
If your organization is like mine, you may need to set environment variables: `https_proxy`, `http_proxy`, `no_proxy`, and perhaps some variables that specify a path to a certificate-file. 

Your org's IT dept should be able to tell you what those are.

**Comment by jennybc** [comment]
Thanks @ijlyttle for these pointers. Yes it sounds like a rather non-specific problem that will affect various internet-using actions.
