### ISSUE TITLE
Typing ?function in console goes to manpage for function-package not function after use_roxygen_md

### ISSUE THREAD

**Issue by SimonDedman** [r-lib/usethis#1886]
I installed `lifecycle` which asked me to first do `usethis::use_roxygen_md` and I *think* (not 100% sure) that this is the reason that when I now type
`?function`
For a function within my package, the help pane displays the manpage for the package, not for the function of the same name.

```
remotes::install_github("SimonDedman/gbm.auto")
library(gbm.auto)
?gbm.auto
```

Does it seem reasonably logical that installing `use_roxygen_md` and/or `lifecycle` would cause this? These (and possibly related required installs) led to all manpages being converted to `.Rd`, and `gbm.auto-package` being created.

Is there anything I can do about this? It's so nice to be able to jump straight to a function's manpage using `?function`, instead of clicking to the package, then the function within it. Thanks in advance!

**Comment by hadley** [comment]
I think `use_package_doc()` is more likely to be the culprit here. If you open `{yourpackage}-package.R` you should be able to fix the roxygen there.

**Comment by SimonDedman** [comment]
Thanks Hadley. Yep, I was able to solve this with Jenny's approach [here](https://github.com/r-lib/usethis/issues/1170). Cheers!
