### ISSUE TITLE
`use_release_issue()` should include `devtools::check_mac_release()`?

### ISSUE THREAD

**Issue by cpsievert** [r-lib/usethis#1887]
I've experienced, a couple time now, that CRAN doesn't run mac checks until after the package is accepted (which then results in a 2-week deadline request to fix the issue, after it's published). So it seems useful to include `devtools::check_mac_release()` in the pre-flight checklist.

**Comment by hadley** [comment]
Do you not use a mac? Or did something mac-CRAN specific fail?

**Comment by cpsievert** [comment]
I do use a mac, and yes, it was mac-CRAN specific

**Comment by jennybc** [comment]
Somewhat related to https://github.com/r-lib/devtools/issues/2507

**Comment by hadley** [comment]
@cpsievert can you be more explicit about what went wrong?

**Comment by hadley** [comment]
This hasn't affected us, and we don't have `check_mac_devel()` yet, so we're going to close. But we'll keep an eye on the situation and we can reconsider in the future.
