### ISSUE TITLE
[FR] Suggest to readRenviron() after edit_r_environ() instead of restarting R

### ISSUE THREAD

**Issue by ColinFay** [r-lib/usethis#1890]
Running `edit_r_environ()` returns the following message: 

```r
> usethis::edit_r_environ()
• Modify '/Users/colinfay/.Renviron'
• Restart R for changes to take effect
```

The message suggests that the user should restart R, but there is also the `readRenviron()` function, which is design to, well, read the .Renviron file. 

I wonder if the message of `edit_r_environ()` could be 

```r
> usethis::edit_r_environ()
• Modify '/Users/colinfay/.Renviron'
• Restart R for changes to take effect 
• You can also source the file with readRenviron('/Users/colinfay/.Renviron')
```

Happy to draft a PR 

Colin

**Comment by hadley** [comment]
If we could this we should also recommend `source()` after `edit_r_profile()`. And in both case, need to make sure that the code link is clickable.

**Comment by jennybc** [comment]
I think it's always a good idea to encourage people to restart R 😄

**Comment by jennybc** [comment]
I'm sticking by the advice that the best move after editing these startup files is to restart R.
