### ISSUE TITLE
Add `library()` call to `use_vignette`

### ISSUE THREAD

**Issue by colearendt** [r-lib/usethis#190]
Wasn't sure whether it would be worth adding a `library()` call to the setup block in `usethis::use_vignette` (if this information is available when the block is built).  

```r
library(<pkgname>)
```

I ask because this is one of those things that feels weird to add (if the package has not been built / installed, then it fails interactively (even after `devtools::load_all()`) but works with `devtools::build_vignettes` and `devtools::check`).  Adding it in `usethis::use_vignette` would establish it as a best practice (`devtools::check` seems to fail without it).  

We could always go extreme with something like:
```r
if (!require(testdevpkg)) {
  devtools::load_all(rprojroot::find_root(rprojroot::is_r_package))
}
```

Of course, that only works if `devtools` is installed.  It's very possible that documentation about best practices on vignette "self-dependence" would resolve the confusion that I have experienced.

**Comment by jennybc** [comment]
I think adding `library(<pkgname>)` to the newly created vignette sounds like a good idea.

The vignette is not currently templated, but rather calls `rmarkdown::draft()`. So that needs to be thought through.

**Comment by colearendt** [comment]
Ahh interesting!  Yes, and `rmarkdown::draft()` does not seem to support parameters or anything of the like.  Could obviously alter with a regex or propose adding `#library()` to the `html_vignette` template in rmarkdown (and then alter with a regex?).  I think it would be cool to have parameters for templates defined with the template (and default values).  Another upstream FR, though.  Curious for your thoughts!

**Comment by jennybc** [comment]
I think it would make more sense to argue for a `library(YOUR_PACKAGE_GOES_HERE)` reminder in the `html_vignette` template than to fully implement this here.

To do it here: I think that requires a custom Rmd template in usethis, which could then drift apart from the main one in rmarkdown. Plus, after drafting from this custom template, we'd still need to `whisker::whisker.render()` it to populate `library({{{package_name}}})`. It feels like a lot of moving parts.

**Comment by colearendt** [comment]
I second your sentiments; well said!  My only suggestion would be to add `library()` as a comment, so that it is still valid markdown.  

If you agree, I will close this and submit a issue/PR to `rmarkdown` accordingly!

**Comment by jennybc** [comment]
Sounds good.

**Comment by colearendt** [comment]
Just FYI, Yihui thought it best to leave `#library()` out of the vignette, lest it cause confusion that `library` is required.  Feel free to read discussion at https://github.com/rstudio/rmarkdown/pull/1233

I will continue to keep a look-out for ways to make this easier to explain (mostly for my own benefit at present, but hopefully for others down the road).
