### ISSUE TITLE
`create_from_github()` seems to be permanently changing the working directory

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#1900]
In R, but not in RStudio, run something like this (you will have to tweak it for your directory)

```r
usethis::create_from_github("r-lib/crayon", destdir = "~/files/r/packages/", fork = TRUE)
```

This should not launch a new RStudio session. It should keep you in the current R session.

However, if you then run `getwd()` it looks like it has left us permanently moved to the new crayon folder

```r
> getwd()
[1] "/Users/davis/files/r/packages/crayon"
```

which is not desirable

**Comment by jennybc** [comment]
I think you're describing the intended behaviour outside of RStudio. The assumption is that you are creating a new project from GitHub AND that you want to now work on / in it.

I think to get the result you seemed to want, you should also specify `open = FALSE`.

**Comment by DavisVaughan** [comment]
Yea `open = FALSE` indeed keeps me in the same working directory

**Comment by jennybc** [comment]
So I think `create_from_github()` is working as designed and you just got somewhat surprised by the difference in behaviour inside RStudio (presumably what you experience more often) vs outside.
