### ISSUE TITLE
Link to obvious places in R Packages and WRE from help files

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#191]

**Comment by batpigandme** [comment]
💯 this! I actually started a sort of help/basics dictionary mapping to R4DS many moons ago (I must've been distracted by a shiny object, and never finished/successfully started), but I think this is a _really_ good idea!

Is there a way to treat chapters like man pages from other packages?

**Comment by jennybc** [comment]
> Is there a way to treat chapters like man pages from other packages?

You mean with automatic linking behaviour or display within the help system? I think the answer is no on both fronts.

I've started to add with a `@seealso` tag if I'm there and it occurs to me. But that was very late in the game, in my recent pass through all the functions.

**Comment by jennybc** [comment]
I would welcome pull requests with very short `@seealso` entries adding links to [R packages](http://r-pkgs.had.co.nz) and [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) (WRE).

Example from the docs for `use_package_doc()`:

``` r
#' @seealso The [documentation chapter](http://r-pkgs.had.co.nz/man.html) of [R
#'   Packages](http://r-pkgs.had.co.nz)
```

**Comment by jennybc** [comment]
Yes @markdly I think having those links would be a clear improvement over not having them.

R Packages will go into revision for a 2nd edition at some point this year, which may have implications for links, but I still think it's good to establish these connections. A PR would be welcome.

**Comment by hadley** [comment]
Seems like we can close this issue now.
