### ISSUE TITLE
use_description() fails in temporary directory

### ISSUE THREAD

**Issue by kevinushey** [r-lib/usethis#1917]
```
> usethis::use_description(check_name = FALSE)
Warning in path_file(base_path) :
  restarting interrupted promise evaluation
Error: Path '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.eEeqQPBN/' does not appear to be inside a project or package.
Read more in the help for `proj_get()`.
```

I can work around this with `usethis::proj_set(force = TRUE)`, but it feels like this should "just work"?

**Comment by jennybc** [comment]
I think the `usethis::proj_set(force = TRUE)` solution is acceptable given how many years we've gone without anyone banging their shins on this. And in renv it didn't really come up organically, but rather in the name of creating a situation suitable for a reprex.
