### ISSUE TITLE
Add authors and/or contributors

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#192]
@hadley I'd like to add myself to DESCRIPTION. Several people seem to have made a non-negligible number of contributions: https://github.com/r-lib/usethis/graphs/contributors. A lot of that may date back to the devtools era and I don't understand the git surgery well enough to interpret re: the stuff that landed here.

Thoughts?

**Comment by hadley** [comment]
You should definitely add yourself.

I think most of the other significant contributors are from devtools era, so we don't need to worry about. But we should have a policy about when we add people to contributors that we can apply consistently (and ideally some way to apply retrospectively to packages like ggplot2)
