### ISSUE TITLE
Switch to `@exportS3Method()`

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1923]
If a package includes `register_s3()` and we can use R 3.6.

**Comment by jennybc** [comment]
``` r
usethis:::tidy_minimum_r_version()
#> [1] '3.6'
```

The case where we can't assume/require R >= 3.6 would be pretty exceptional at this point, yeah? I realize this might not just be about packages following the tidyverse policy, but I assume there aren't lots of packages that are intentionally trying to support R 3.5 or earlier.

**Comment by hadley** [comment]
Oh yeah, I just forgot we can rely on 3.6 now.

**Comment by hadley** [comment]
We don't really need to add this to upkeep since roxygen2 will warn about undocumented S3 methods.

**Comment by jennybc** [comment]
@hadley Do you care to revisit / restate the call to action here?

**Comment by hadley** [comment]
I think we can turn this into individual issues on specific repos. So the job for one of us is to:

* [Locate all packages that still use `s3_register()`](https://github.com/search?q=register_s3+%28org%3Atidyverse+OR+org%3Ar-lib%29&type=code)
* For each package, analyse why we're using it and suggest what actions someone needs to take

**Comment by hadley** [comment]
Maybe we should back off on this because of https://bugs.r-project.org/show_bug.cgi?id=18776?

**Comment by hadley** [comment]
And when `@exportS3method` fails it's really hard to realise/debug that the problem is an instance of this problem. And it doesn't really buy as anything so there's no reason to switch.
