### ISSUE TITLE
Any reason why `ui_*` functions are not in the package reference?

### ISSUE THREAD

**Issue by dshemetov** [r-lib/usethis#1924]
Looking at the package [reference page](https://usethis.r-lib.org/reference/index.html) I am unable to find any reference to the [ui page](https://usethis.r-lib.org/reference/ui.html) or its children. Is this due to an intentional deprecation or some other reason?

**Comment by jennybc** [comment]
Yeah the ideas behind the `ui_*` functions have been implemented more robustly, for use in other packages, in the cli package:

https://cli.r-lib.org/

In most cases, folks interested in the `ui_*` functions are better off using cli for their project.

**Comment by dshemetov** [comment]
Makes sense, thanks!
