### ISSUE TITLE
Why use the h1 heder for each version of the NEWS.md?

### ISSUE THREAD

**Issue by eitsupi** [r-lib/usethis#1930]
Currently when NEWS files are updated by usethis uses h1 `#` for the heading of each version.

https://github.com/r-lib/usethis/blob/709f82582eb3be6ed1cfea459e4e9de8d25ae553/R/news.R#L36-L59

But normally h1 is supposed to be used one for each page, wouldn't it be more natural to use h2?
Do you think it is worth having such an option to at least use h2 `##`?

**Comment by jennybc** [comment]
I don't really know why h1 was chosen here, but I think it would be pretty painful to do anything else at this point. There is code in usethis and pkgdown, just for starters, I imagine, that is built around this assumption.

@hadley do you have any observations?

**Comment by hadley** [comment]
Yeah h2 is arguably more correct, but it’s too late to change now.

**Comment by eitsupi** [comment]
Would you add an opt-in option to use h2 headers, as having multiple h1 headers may cause various tools to not work well.

**Comment by hadley** [comment]
This is going to be a bunch of work for us, so you'd need to provide compelling evidence that this is worth it.
