### ISSUE TITLE
When using use_data(), set LazyData: to TRUE by default?

### ISSUE THREAD

**Issue by jrosen48** [r-lib/usethis#194]
When using `use_this()`, I was a bit surprised to see that I could not load the `data.frame` / `tibble` by typing its name (asked a SO question which turned out to be a duplicate [here](https://stackoverflow.com/questions/48128751/using-built-in-data-in-an-r-package), and had to use `data()` instead. 

Given how common lazy loading of data is (i.e., in tidyverse packages such as `dplyr`), would it be a useful usethis default to change (and to tell the user of the change) the `LazyData` DESCRIPTION file field to `TRUE` by default?

**Comment by jennybc** [comment]
Which function(s) exactly did you use? If you create a package from scratch with `create_package()`, it does set `LazyData: true`.

**Comment by jrosen48** [comment]
My colleague set this up and it sounds like he used devtools / usethis to set up specific elements (like the vignette) but set up most of it package (including the NAMESPACE file) by hand. Given this situation, would it make a bit less sense to set `LazyData: true`, as ostensibly the user setting it up may have deliberately chosen not to load data in this way?

**Comment by jennybc** [comment]
I think we've got specific conventions for packages and usethis implements them. `LazyData: true` is one of them, hence it's the default. I'm content leaving it that way. If people like usethis for some things and not for others, they'll just need to tweak as they go.
