### ISSUE TITLE
use_github_release() could pull tags from github

### ISSUE THREAD

**Issue by hughjonesd** [r-lib/usethis#1947]
`use_github_release()` creates a tag on github but doesn't pull the tag to the local machine.

It might be nice to either pull the tag automatically, or add a bullet point to remind the user they can do that:

```r
ui_todo("Pull the new tag from github with `git pull --tags`")
```

**Comment by jennybc** [comment]
I seem to have release tags locally, for my packages in general, which leads me to believe that this self-resolves in a very short amount of time, for most folks. Meaning: something else we naturally in the normal course of package-development-using-GitHub causes the tag to make its way into the local repo. Therefore I don't think we need to do anything explicit here.

(Let me know if you think I've really missed something here.)
