### ISSUE TITLE
`use_dev_version()` and `use_version("dev')` don't behave the same when already in dev.

### ISSUE THREAD

**Issue by olivroy** [r-lib/usethis#1950]
If already in dev, i.e.

DESCRIPTION

```
Version: 1.0.0.9000
```

`use_version("dev")` increments to 1.0.0.9001 while `use_dev_version()` remains the same.

Would you be open to a PR to make the functions behave more the same, or is this by design? It seems to be by design. But could it add a (clickable) hint to use `use_version("dev")`, maybe?

Thanks

From docs:

```
use_dev_version() increments to a development version, e.g. from 1.0.0 to 1.0.0.9000. If the existing version is already a development version with four components, it does nothing. Thin wrapper around use_version().

```

**Comment by jennybc** [comment]
I agree the existing behaviour seems intentional and, in my current mindset, which is to move quickly towards a release, I'm going to stick with the _status quo_.
