### ISSUE TITLE
Function to document/set merge strategy 

### ISSUE THREAD

**Issue by Aariq** [r-lib/usethis#1955]
I think fairly recently git started requiring that you set one of three merge strategies before pulling when there are divergent branches:

```
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches
```

While these can be set with `use_git_config(pull.rebase = "false")`, for example, it might be nice to have a dedicated function for this.  It could serve as 1) a place to document pros and cons of these choices and maybe suggest a default (I had a lot of trouble deciding which one to choose when I first encountered this message) and 2) provide easier to remember options like `strategy = c("merge", "rebase", "fast-forward")`.  

Also `git_sitrep()` should check if one of these options is set, which I don't think it currently does.

**Comment by jennybc** [comment]
FWIW I'm a long-time happy user of:

```
[pull]
	rebase = true
```

I'm not really thinking about the git side of usethis right now, so it's hard to say if we'll wade this far into folks' git config. But I do think your Git life is happier if you make a conscious config choice here.

**Comment by jennybc** [comment]
Thought about this again and I just don't feel ready to cross this rubicon, i.e. get deeper into vetting the user or repo's Git config, in usethis itself.
