### ISSUE TITLE
use_package() `min_version` will not decrement

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/usethis#1957]
When `min_version` is provided and it is a smaller semver than the one currently in the DESCRIPTION file, it will not be decremented to the lower version. 

```r
usethis::use_package("dplyr", min_version = "1.0.0")
usethis::use_package("dplyr", min_version = "0.8.0")
```

**Comment by jennybc** [comment]
Tagging as "needs investigation" for tidyverse dev day.

Specifically: my hunch from skimming the code is that this behaviour is coming from the desc package and not something usethis has taken a stand on.

It would be great for someone to nail that down definitively.

**Comment by JosiahParry** [comment]
🎉 🚀
