### ISSUE TITLE
usethis theme `i` bullet

### ISSUE THREAD

**Issue by olivroy** [r-lib/usethis#1965]
Is it worth overriding usethis i bullet to make it yellow.

FWIW, in most devtools / tidyverse packages, the blue default is used.
![image](https://github.com/r-lib/usethis/assets/52606734/35fa81a8-ac9d-4ca6-8d49-decc47646f47)

And with latest dev usethis, with `pr_forget()`, I saw a blue i

![image](https://github.com/r-lib/usethis/assets/52606734/7d799ca8-b5bc-4a15-bcdf-a505b0677252)

Feel free to close with no further explanation, just my 2 cents. I see that you added a justification in https://github.com/r-lib/usethis/pull/1956#discussion_r1508343771

Edit: I am also biased for having used my cli branch #1928 for a couple months, so I got used to blue `i` in usethis there too.

`ui_abort()` doesn't seem to have it either?

`ui_abort()` is also contrary to the default of `cli_abort()` by putting a x as the first bullet..

**Comment by jennybc** [comment]
These moves are intentional. I don't feel strongly about the color of the "i". The `ui_abort()` behaviour is a more strongly held opinion. But I feel OK releasing as things are.
