### ISSUE TITLE
Please get rid of the different possible UI answers that mean yes or no but are worded differently

### ISSUE THREAD

**Issue by frederikziebell** [r-lib/usethis#1968]
After running `use_git()` in a new project, I'm asked if want to commit a number of files with the answers being, in my case

```
1: Negative
2: Absolutely not
3: I agree
```

This is confusing, as nobody is expecting other possibilities than 'yes' and 'no'. Moreover, it took me a while to understand that 'negative' and 'absolutely not' mean the same. I think a package that aims to implement and streamline best practices for package development should not contain confusing UI.

**Comment by ALanguillaume** [comment]
This three answers gimmick is implemented by {yesno}.

Its role is to act as a failsafe to make sure you are really aware of what you are about to do.

from the package documentation (`?yesno::yesno`):

> Asks a custom yes-no question with randomly varying responses. Returns a flag indicating whether
the user answered yes or no. It is designed to be used in situations where the users needs to confirm
an affirmative action.

The randomness is not an antipattern here, it is purposefully implemented as a puzzle to make you think twice about what you are doing.

**Comment by jennybc** [comment]
This is a discussion that's been had many times in many other issues and this is intentional friction that we think does more good than harm. I am well aware that not everyone agrees.
