### ISSUE TITLE
Use existing R versions for minimum required version

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/usethis#1972]
`usethis::use_data()` automatically adds a minimum required R version:

https://github.com/r-lib/usethis/blob/9e64daf13ac1636187d59e6446d9526a414d8ba6/R/data.R#L47-L51

But these version numbers do not correspond to any actual R version. In practice, this adds a dependency to `R (>= 2.10.0)` / `R (>= 3.5.0)`.

This can cause issues when programmatically passing this version number to downstream tools (e.g., to [`lintr::backport_linter()`](https://lintr.r-lib.org/reference/backport_linter.html), or to find the release date with the [rversions R package](https://r-hub.github.io/rversions/)). Instead of a single equality comparison, we now have to find the first version which matches an inequality comparison.

Is it possible to edit these lines to add the patch version number (`.0`)? As far as I can tell, it is a fully backwards-compatible change, since it only makes the de facto current behaviour explicit.

I'm happy to submit a PR for this if you agree with this minor change.

**Comment by jennybc** [comment]
Hmmm, usethis is just doing what is recommended in Writing R Extensions:

> The Depends field can also specify a dependence on a certain version of R — e.g., if the package works only with R version 4.0.0 or later, include R (>= 4.0) in the Depends field. (As here, trailing zeroes can be dropped and it is recommended that they are.) 

https://rstudio.github.io/r-manuals/r-exts/Creating-R-packages.html#package-dependencies
