### ISSUE TITLE
use_latest_dependencies() throws error for packages not on CRAN

### ISSUE THREAD

**Issue by bakaburg1** [r-lib/usethis#1979]
Hello!

Something is wrong with `use_latest_dependencies()` with a Description file:

```r
> usethis::use_latest_dependencies(overwrite = TRUE, source = "CRAN")
Error in utils::available.packages()[packages, "Version"] : 
  subscript out of bounds
```
 Oddily enough this works: 
 ```r
> utils::available.packages()["usethis","Version"]
[1] "2.2.3"
```

This are the packages in my package: 
```r
> usethis:::proj_desc()$get_deps()
      type   package   version
1  Imports      brms >= 2.20.4
2  Imports  cmdstanr  >= 0.7.1
3  Imports     dplyr  >= 1.1.4
4  Imports     furrr  >= 0.3.1
5  Imports    future >= 1.33.1
6  Imports   ggplot2  >= 3.4.1
7  Imports lubridate  >= 1.9.2
8  Imports     purrr  >= 1.0.2
9  Imports    scales  >= 1.2.1
10 Imports   stringr  >= 1.5.0
11 Imports     tidyr  >= 1.3.0
```

After some more investigation, I found that the problem is a specific package:
```r
> usethis:::proj_desc()$get_deps()$package |> purrr::walk( ~ {
     cat(.x, ": ", .x %in% utils::available.packages()[,"Package"], "\n", sep = "")
 })
brms: TRUE
!! cmdstanr: FALSE !!
dplyr: TRUE
furrr: TRUE
future: TRUE
ggplot2: TRUE
lubridate: TRUE
purrr: TRUE
scales: TRUE
stringr: TRUE
tidyr: TRUE
```

But I really can't understand why, since it's a package like many others.

UPDATE:
ok, cmdstanr is not on CRAN: https://mc-stan.org/cmdstanr/articles/cmdstanr.html

What about having the function throw an informative warning instead of that error?

**Comment by jennybc** [comment]
I think it's OK that `usethis::use_latest_dependencies(overwrite = TRUE, source = "CRAN")` errors for packages that are not on CRAN. This function (`use_latest_dependencies()`) should rarely be used by anyone, so, relative to other maintenance that usethis needs, I think it's acceptable that this error bubbles up.

**Comment by bakaburg1** [comment]
> This function (use_latest_dependencies()) should rarely be used by anyone

What's the proper alternative?

**Comment by jennybc** [comment]
> What's the proper alternative?

I'd say that it should be rare that to want to pin all dependencies at their latest version. The rationale for this attitude is here:

https://r-pkgs.org/description.html#sec-description-imports-suggests-minium-version

> Think carefully if you declare a minimum version for a dependency. In some sense, the safest thing to do is to require a version greater than or equal to the package’s current version. For public work, this is most naturally defined as the current CRAN version of a package; private or personal projects may adopt some other convention. But it’s important to appreciate the implications for people who try to install your package: if their local installation doesn’t fulfill all of your requirements around versions, installation will force upgrades of these dependencies. This is desirable if your minimum version requirements are genuine, i.e. your package would be broken otherwise. But if your stated requirements have a less solid rationale, this may be unnecessarily conservative and inconvenient.
>
> In the absence of clear, hard requirements, you should set minimum versions (or not) based on your expected user base, the package versions they are likely to have, and a cost-benefit analysis of being too lax versus too conservative. The de facto policy of the tidyverse team is to specify a minimum version when using a known new feature or when someone encounters a version problem in authentic use. This isn’t perfect, but we don’t currently have the tooling to do better, and it seems to work fairly well in practice.
