### ISSUE TITLE
Path reporting

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#198]
In the long-run, consider messaging about paths relative to a relevant path.

For functions that operate on current project,  that's `proj_get()`.
For functions that take a path, it's ... less clear and would ideally be specified by caller.

Motivation: I'm writing `use_course()`, which has no notion of project. And the user can specify a directory where the ZIP file should be written, then unpacked. It's awkward that `can_overwrite()` forcibly removes path in this message: `"Overwrite pre-existing file ", value(basename(path)), "?"`

**Comment by jennybc** [comment]
More ugliness, at least in `use_course()` and especially on Windows, comes from uneven treatment in different messages re: whether `~` has been expanded or not and replicated file path separators.

**Comment by hadley** [comment]
Maybe use `fs::path_rel(path, proj_get())` everywhere? The `basename()` stuff I did was a crude hack.

**Comment by hadley** [comment]
Probably not perfect, but I reviewed the `use_course()` code path and reduced some of the duplication (hopefully without losing anything important).
