### ISSUE TITLE
usethis commands in the command palette?

### ISSUE THREAD

**Issue by venpopov** [r-lib/usethis#1984]
[This](https://docs.posit.co/ide/user/ide/guide/pkg-devel/writing-packages.html) page claims that  "The [Command Palette](https://docs.posit.co/ide/user/ide/guide/ui/command-palette.html), accessed by Ctrl+Shift+P, can also execute devtools, usethis, or Package Development specific commands:"

However, in my palette I only see devtools commands, but not usethis commands. Is this a feature that has been removed, or is the link mistaken? And if it is not a feature, it would be great to have. For example, I often use `browse_github()` but I would love to set this is up with a keyboard shortcut, which would be possible if this was a command available in the palette.

**Comment by jennybc** [comment]
@jthomasmock Do you know if the command palette ever included usethis commands? Just in general, do you have any thoughts on this issue?

**Comment by jennybc** [comment]
FWIW I also use `browse_github()` so heavily that I do something in `.Rprofile` so that I can call it as `bg()`.

**Comment by jthomasmock** [comment]
I tested our 2024.07 daily and 2022.12, which was the release before we finished those documents.

I think the inclusion of `usethis` was a mistake, as I only see `devtools` commands in both.

**Comment by jennybc** [comment]
I think the easiest resolution is to correct that documentation, i.e. remove the usethis mention. @jthomasmock do you have the power to do that?

**Comment by jennybc** [comment]
Since there doesn't seem to be a call to action in usethis itself, I'm closing this.
