### ISSUE TITLE
Dot placeholder

### ISSUE THREAD

**Issue by dchiu911** [r-lib/usethis#199]
Is there value to add a `use_placeholder()` where it does [this](https://github.com/jennybc/googlesheets/blob/master/R/googlesheets.R#L16)? Currently I am manually adding
```r
globalVariables(".")
```
to most of my packages in a `R/utils.R` to suppress the R CMD Check notes.

**Comment by jennybc** [comment]
I feel like it's usually best to find other ways to address this problem. Where by "other" I sort of mean "more correct" coding practice that designs this need away. But of course you've found an example **me** doing it! 😂

It also may be unavoidable sometimes. If you're willing, will you give/link some concrete examples where a package author needs this? This will be useful for deciding how much usethis wants to facilitate this use of `.` inside packages. And if it does, these details will be useful for writing docs.

**Comment by dchiu911** [comment]
True, I've iterated away from the `. <- NULL` practice.

A gross search on GitHub showed [some](https://github.com/search?utf8=%E2%9C%93&q=globalVariables+language%3Ar&type=Code) use cases by other authors.

**Comment by jennybc** [comment]
@hadley Are we willing to facilitate this with an actual function?

**Comment by hadley** [comment]
This feels a bit too specific too me currently.

**Comment by jennybc** [comment]
OK thanks @dchiu911 for bringing this up. We're going to table it for now.
