### ISSUE TITLE
`use_codecov_badge()` URL seems incorrect now

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#1991]
i.e. here https://github.com/r-lib/usethis/blob/da18e11fa311ba7034ab58e86bb7b7e0977d1d26/R/coverage.R#L48

It generates a link like this:

```
https://app.codecov.io/gh/tidyverse/tidyr?branch=main
```

but if you go to that, it will still show `master`. It does not seem to know how to handle `?branch=main` and just ignores it, and then shows what it thinks is the default branch, which is `master` unless you've changed it in the codecov settings.

It seems like this might be a more correct link?

```
https://app.codecov.io/gh/tidyverse/tidyr/tree/main
```

That shows `main` for me

**Comment by DavisVaughan** [comment]
Ideally we'd just remove the branch piece entirely and show `https://app.codecov.io/gh/tidyverse/tidyr`, but since codecov doesn't automatically pick up git default branch changes, that is likely going to show `master` for all our repos until we go and change the setting on codecov.io too

**Comment by gaborcsardi** [comment]
Just changed the default branches to `main` in tidyverse. Hopefully new repos will default to `main` since that's the default branch on GH.

**Comment by jennybc** [comment]
This appears to be the documentation on the current structure of these URLs:

https://docs.codecov.com/docs/status-badges

```
You can modify the URL to show a specific branch by specifying the branch you'd like to see under below:

https://codecov.io/<codehost>/<orgname>/<reponame>/\branch/<branchname>/\graph/\badge.svg?token=XXXXXXXXXX
```

**Comment by jennybc** [comment]
However it's not terribly practical for us to adopt these. Here's an example of the [markdown provided for a tidyr badge](https://app.codecov.io/gh/tidyverse/tidyr/settings/badge):

```
[![codecov](https://codecov.io/gh/tidyverse/tidyr/graph/badge.svg?token=cJSNWFa5Hu)](https://codecov.io/gh/tidyverse/tidyr)
```

Note the `token`. Codecov's intended workflow seems to assume a human is clicking around their interface to get this URL. Or, alternatively, maybe that you're using their API? Which I'm not eager to do.

**Comment by jennybc** [comment]
Trying out some different URLs using tidyr as the example.

---

The official markdown badge (includes a token):

```
[![codecov](https://codecov.io/gh/tidyverse/tidyr/graph/badge.svg?token=cJSNWFa5Hu)](https://codecov.io/gh/tidyverse/tidyr)
```

[![codecov](https://codecov.io/gh/tidyverse/tidyr/graph/badge.svg?token=cJSNWFa5Hu)](https://codecov.io/gh/tidyverse/tidyr)

---

The official markdown badge WITHOUT the token (hey it works 🤔 and I suspect this is what I should do):

```
[![codecov](https://codecov.io/gh/tidyverse/tidyr/graph/badge.svg)](https://codecov.io/gh/tidyverse/tidyr)
```

[![codecov](https://codecov.io/gh/tidyverse/tidyr/graph/badge.svg)](https://codecov.io/gh/tidyverse/tidyr)

---

What usethis is currently producing (which looks like what the documentation says to do, if you want to specify a branch):

```
[![Codecov test coverage](https://codecov.io/gh/tidyverse/tidyr/branch/main/graph/badge.svg)](https://app.codecov.io/gh/tidyverse/tidyr?branch=main)
```

[![Codecov test coverage](https://codecov.io/gh/tidyverse/tidyr/branch/main/graph/badge.svg)](https://app.codecov.io/gh/tidyverse/tidyr?branch=main)
