### ISSUE TITLE
RStudio git pane can get out of sync when checking out branch with the `pr_*()` functions

### ISSUE THREAD

**Issue by olivroy** [r-lib/usethis#1992]
I'd suggest to add `rstudio_git_tickle()` in pr_resume()`

https://github.com/r-lib/usethis/blob/da18e11fa311ba7034ab58e86bb7b7e0977d1d26/R/pr.R#L265-L266

Also in `pr_finish()`, at the end of `pr_clean()`

I didn't follow the path of usage, but it feels harmless to add it in a couple places.

If you agree, I can open a PR.

**Comment by jennybc** [comment]
It seems like `rstudio_git_tickle()` should be safe to pepper in where needed (and, if it's not, that should be addressed). So yes a PR is welcome if you've found places where it should be added.
