### ISSUE TITLE
Should use_vignette support quarto?

### ISSUE THREAD

**Issue by jfunction** [r-lib/usethis#1997]
I'm not sure if this is a feature request, an opinion request or something else. 

I am building a package and want to include some vignettes. The community is, broadly speaking, moving from Rmd to qmd. The `use_vignette()` function assumes you want all your vignettes in Rmd format. 

I'm wondering if we are generally happy to use Rmd for vignettes still or if there is likely going to be a shift towards using quarto here also? Obviously in the latter case a change in `use_vignette` would be needed also.

**Comment by jfunction** [comment]
That said, I found this quote from Packages 2e:

> In vignettes, more than anywhere else, the answer to “But how do I do X?” is often “Don’t do X”.

**Comment by jennybc** [comment]
Yeah it's good to put this on the radar now. It's quite recent that quarto is a viable vignette engine, so it makes sense for usethis to become aware of this new reality.

**Comment by hadley** [comment]
pkgdown should support quarto vignettes soon (hopefully by the end of the week), so I think we should plan to make this an option, and then over the next few years transition to making it the default for new vignettes.

**Comment by olivroy** [comment]
Also `use_article()` should also be updated.
