### ISSUE TITLE
use_dev_package should always set package version

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#200]
To ensure that users get the latest version upon release.

**Comment by jennybc** [comment]
`use_dev_version()` bumps the version of the active project/package to a dev version. It is basically `use_version(which = "dev')`.

I'm having a hard time understanding this issue. Is it perhaps about setting the version of a dependency, e.g. something in Imports?

Regardless this brings up something I suffer from: confusion about functions that act on the version of the active project/package vs. setting minimum versions of *dependencies* of the active project.

Act on Version of the active project/package: `use_version()`, `use_dev_version()`

Set minimum version of a dependency of the active project/package: `use_dev_package()`, `use_tidy_versions()`

**Comment by hadley** [comment]
I do mean `use_dev_package()`, sorry.
