### ISSUE TITLE
Remove `revdepcheck::cloud_check()` from release issue checklist? 

### ISSUE THREAD

**Issue by t-kalinowski** [r-lib/usethis#2006]
https://revdepcheck.r-lib.org displays a prominent banner today: "This package is not actively maintained"
<img width="816" alt="image" src="https://github.com/r-lib/usethis/assets/8462255/86cb3a17-faf5-47dd-a51b-1bd8466e678c">

Should we remove `revdepcheck::cloud_check()` from the checklist created by `usethis::use_release_issue()`?

**Comment by jennybc** [comment]
@hadley @gaborcsardi Do you have thoughts on this?

**Comment by gaborcsardi** [comment]
It maintained for out internal use, so it is fine to keep it on the checklist.
