### ISSUE TITLE
`usethis::use_tibble()` does not add `@importFrom tibble tibble` to package-level doc

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/usethis#2007]
Contrarily to what the message says,  `@importFrom tibble tibble` is not added to package-level doc.

```
> usethis::use_tibble()
`use_import_from()` requires package-level documentation.
Would you like to add it now?

1: Negative
2: Nope
3: Absolutely

Selection: 3
✔ Writing 'R/mgi.report.reader-package.R'
• Modify 'R/mgi.report.reader-package.R'
✔ Adding 'tibble' to Imports field in DESCRIPTION
✔ Adding '@importFrom tibble tibble' to 'R/mgi.report.reader-package.R'
✔ Writing 'NAMESPACE'
✔ Loading mgi.report.reader
• Document a returned tibble like so:
  #' @return a [tibble][tibble::tibble-package]
```

This is how my package-level doc looks like after running `usethis::use_tibble()`:

```
#' @keywords internal
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL
```

So I always add it manually afterwards :)

**Comment by jennybc** [comment]
I can't reproduce this with dev usethis, so I guess it's been fixed 😅

**Comment by ramiromagno** [comment]
Hi Jenny,

Thanks for the quick reply. There might be something going on with my environment because using usethis version 2.2.3.9000 with a freshly created R package still shows the same problem:

```
> usethis::use_tibble()
! `use_import_from()` requires package-level documentation.
  Would you like to add it now?

1: Not now
2: No
3: Definitely

Selection: 3
✔ Writing R/random-package.R.
☐ Modify R/random-package.R.
☐ Run devtools::document() to update package-level documentation.
✔ Adding tibble to Imports field in DESCRIPTION.
✔ Adding "@importFrom tibble tibble" to R/random-package.R.
✔ Writing NAMESPACE.
✔ Loading random.
☐ Document a returned tibble like so:
  #' @return a [tibble][tibble::tibble-package]
```

Generated package-level doc:

```
#' @keywords internal
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL
```

As far as I can remember I've been always adding the `"@importFrom tibble tibble"` line manually. It's just I never bothered to file an issue before.

**Comment by jennybc** [comment]
With usethis installed from current `HEAD` I see:

```
> use_tibble()
✔ Setting active project to "/Users/jenny/tmp/random".
! `use_import_from()` requires package-level documentation.
  Would you like to add it now?

1: Absolutely not
2: Yeah
3: No

Selection: 
2
✔ Writing [R/random-package.R](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#).
☐ Modify [R/random-package.R](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#).
☐ Run [devtools::document()](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#) to update package-level documentation.
✔ Adding tibble to Imports field in DESCRIPTION.
✔ Adding "@importFrom tibble tibble" to [R/random-package.R](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#).
✔ Writing [NAMESPACE](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#).
✔ Loading random.
☐ Document a returned tibble like so:
  #' @return a [tibble][tibble::tibble-package]
```

And the contents of `R/random-package.R` are:

```
#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom tibble tibble
## usethis namespace: end
NULL
```

If you want to gain some insight into what's odd about your life, maybe step through it with `debug(use_tibble)` and see if you learn anything.

**Comment by jennybc** [comment]
I've added a test for this behaviour to prove that this is not "works on my machine". It does seem like something is special (in an unfavorable way) about your environment.

**Comment by ramiromagno** [comment]
Thanks, Jenny, for taking your time to help me out! I will take your advice to see what's going on. I will let you know.

**Comment by ramiromagno** [comment]
Hi Jenny,

There is nothing wrong with `usethis::use_tibble()` indeed. It is actually my desktop RStudio instance, that for some reason, does not immediately refresh the code of package-level doc. So if I have the file opened and I run `usethis::use_tibble()`, it actually changes the file, but I don't see it immediately... However, if I close it and open it again, it is there. 

Thanks again for helping me understand what is unfavorably special about my environment! :)
