### ISSUE TITLE
Straighten out default location for use_course() on Windows

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#201]
I've just realized that the Desktop lives in a different place relative to `HOME` on Mac and Windows. Thanks for the heads up @mdsumner.

**Comment by jennybc** [comment]
@mdsumer Will you install from the PR and confirm default location is now the Desktop for you?

``` r
devtools::install_github("r-lib/usethis#203")
```

**Comment by mdsumner** [comment]
@jennybc yep, all good works now - happy little vegemites all on the Desktop from friom bitly, dropbox and github
