### ISSUE TITLE
Transitioning from devtools to remotes

### ISSUE THREAD

**Issue by hhmacedo** [r-lib/usethis#2013]
Currently, it is recommended to use `remotes::install_github()`. Therefore, I kindly suggest considering the update in the README file created by `use_readme_rmd()`.

https://github.com/r-lib/usethis/blob/73b4e97b4f76d8c9b4b11761eb8e32a86bb2ceca/inst/templates/package-README#L31-L32

**Comment by olivroy** [comment]
I think the new standard is to use pak

**Comment by hhmacedo** [comment]
_pak_ is a new recommended function, but it's a different standard of installation, _remotes_ keeps the same standard and this is why I suggested _remotes_.

**Comment by jennybc** [comment]
We are definitely not putting remotes here. This section of R Packages explains more about why we prefer to feature devtools in this sort of user-facing, workflow-y situation:

https://r-pkgs.org/setup.html#sec-setup-usage

We are switching to pak in these places:

https://github.com/search?q=pak%20path:README.Rmd%20org:tidyverse&type=code

**Comment by hhmacedo** [comment]
Hi, @jennybc, firstly I want to apologize because I didn't see the #733 before.
Second, in my opinion, recommending devtools to install a package looks like recommending tidyverse to create a plot, and @eddelbuettel shared a similar opinion [here](https://stackoverflow.com/a/76923655). So I would be thankful if you could clarify why recommending devtools and not remotes just to install a package, I read the link but didn't get this answer.
