### ISSUE TITLE
browseURL() on RStudio Server

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#202]
The `browseURL()` usage in `use_course()` doesn't have the desired effect of opening the newly created directory on RStudio server. It attempts to open something like "8787/files/rematch2-master".

Reported by @mdsumner, who might care to elaborate here.

This is related to, but not the same as #129, in which `browseURL()` is being used to open an RStudio Project in, say, `create_package()`.

**Comment by jennybc** [comment]
cc @hadley

**Comment by hadley** [comment]
Maybe should just suppress on RStudio server?

**Comment by jennybc** [comment]
Do you happen to know the official way to test if running on RStudio server?

**Comment by hadley** [comment]
`rstudioapi::versionInfo()$mode`

**Comment by jennybc** [comment]
Consultation with hosted apps confirms that yes, I should just suppress this entirely on RStudio server.

**Comment by jennybc** [comment]
@mdsumner Are you willing to install usethis from GitHub and confirm that `use_course()` behaves well on RStudio server? Specifically, it should not attempt to browse the newly created folder. The path should be clear from messages and the user will have to figure out how they want to proceed.

**Comment by mdsumner** [comment]
LGTM  -use_course behaves well for me on RStudio Server ( also love how create_package now works to open the project :)

**Comment by jennybc** [comment]
Thanks!
