### ISSUE TITLE
`pr_` performance

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#2021]
In my heart of hearts I feel like the performance of the `pr_` functions is slower than it should be. I don't really have any evidence to base this feeling on, but now that [dev profvis](https://r-lib.github.io/profvis/dev/) defaults to elapsed timing, we now have a way to profile the code and see which API calls are taking up the time.

**Comment by jennybc** [comment]
My bet is that you are working in a repo that is somehow extreme. Like it has lots of PRs or something.

**Comment by hadley** [comment]
I think I now understand the basic problem. `pr_init()` calls `github_remotes()` twice: once in `github_remote_config()` and (often) again in `git_default_branch()`. Because `github_remotes()` has to hit the GitHub API, it takes around 300ms. The caching in dev gh speeds this up, but it would be nice to eliminate the double call, either by calling `github_remotes()` and then passing to both functions, or by capturing the default branch info in `github_remote_config()`.
