### ISSUE TITLE
Which repo to target is asked many times without more context (e.g in `use_release_issue()`)

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#2023]
Here is an example 
````r
> usethis::use_release_issue()
✔ Setting active project to "C:/Users/chris/Documents/DEV_R/quarto-r".
Which repo should we target? 

1: cderv/quarto-r = "origin"
2: quarto-dev/quarto-r = "upstream"

Sélection : 2
Current version is 1.4.3.9000.
What should the release version be? (0 to exit) 

1: major --> 2.0.0
2: minor --> 1.5.0
3: patch --> 1.4.4

Sélection : 3
Which repo should we target? 

1: cderv/quarto-r = "origin"
2: quarto-dev/quarto-r = "upstream"

Sélection : 2
Which repo should we target? 

1: cderv/quarto-r = "origin"
2: quarto-dev/quarto-r = "upstream"
````

First time ask to choose a repo, which makes sense for the action to where to open the issue. 

Though after it ask two more times, without context on the choice to make. Usually I select the same repo two times more. 

So either this is expected question, and maybe more context should be added, or the first choice could be cached and applied for next choices. 

I figured I would report as is - I did not look in code about what workflow is really happening in this case.

**Comment by hadley** [comment]
Is this now fixed?

**Comment by cderv** [comment]
Yes it is I believe - no more repetition of the question now. 👍 

````
> usethis::use_release_issue()
✔ Setting active project to "C:/Users/chris/Documents/DEV_R/rticles".
Which repo should we target? 

1: cderv/rticles = "origin"
2: rstudio/rticles = "upstream"

Sélection : 2
Current version is 0.27.3.
What should the release version be? (0 to exit) 

1: major --> 1.0.0
2: minor --> 0.28.0
3: patch --> 0.27.4

Sélection : 2
✔ Opening URL <https://github.com/rstudio/rticles/issues/575>.
````

**Comment by jennybc** [comment]
Ha! My Positron training to never close an issue with a PR made me uses "addresses" instead of "fixes" or "closes" 😬
