### ISSUE TITLE
Update http errors we're trying to catch for httr2

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#2025]
Fragment of a slack conversation with @hadley:

> ... since the code was written, gh has switched from httr to httr2 so there are a few `http_error_404` that should now be `httr2_http_404`

(I was reminded of this when looking at #1893 and #1894.)

**Comment by jennybc** [comment]
I just did a GET for a nonexistent repo and here are the classes of the error:

```
logi TRUE
 - attr(*, "class")= chr [1:5] "github_error" "http_error_404" "rlang_error" "error" ...
```

which suggests that perhaps gh is still emitting errors with the classes we are currently expecting.

My gh version is 1.4.1, which is _after_ the switch to httr2.

**Comment by hadley** [comment]
Ok we must've preserved the error classes in gh. I think we can close this then.
