### ISSUE TITLE
Can't turn on labels for tidyverse/tibble and r-lib/pillar

### ISSUE THREAD

**Issue by krlmlr** [r-lib/usethis#205]
Had to pass a manually created GitHub token with `"public_repo"` permission.

**Comment by jennybc** [comment]
I just used `use_github_labels()` on this package to add your "performance" label, with no trouble.

So I guess this is a scope problem? Or do you think usethis didn't pick up a token for you at all?

`gh:gh_whoami()` reports scopes for current token, so in theory we could check. But is maybe out of scope for usethis (no pun intended).

Here's what I get:

``` r
gh::gh_whoami()
#> {
#>   "name": "Jennifer (Jenny) Bryan",
#>   "login": "jennybc",
#>   "html_url": "https://github.com/jennybc",
#>   "scopes": "admin:org, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user",
#>   "token": "e5..."
#> }
```

What do you get?

**Comment by krlmlr** [comment]
Thanks. It's telling me that I need to obtain a PAT. So, I guess, it's working as intended.
