### ISSUE TITLE
'use_git()' stops partway through without error message

### ISSUE THREAD

**Issue by hrdawson** [r-lib/usethis#2050]
Steps to reproduce error:
1. Create new R project in an existing directory
2. Run `usethis::use_git()`
3. Answer yes to both questions about committing all files and restarting R. The error also happens if you say no to one question and yes to the other.
4. Wait for R to reboot
5. Discover that the R Studio Git tab has been added but the pull/push buttons are greyed out and the project does not appear in my repos on github.com, although a .git folder and .gitignore have been added to the directory

This happens on both a PC and a Mac running separate GitHub accounts. I (the Mac user) am running R v4.4.0 in R Studio 2024.04.2 Build 764 on Sonoma 14.5. I didn't get the system details for my student (the PC user). Outside of this issue, I regularly pull and push to and from GitHub on this computer using the R Studio Git tab.

(I'm sorry but I don't know how to build a reprex for this issue. If someone can link me to instructions, I'll be happy to do so.)

**Comment by jennybc** [comment]
`use_git()` does `git init`

It sounds like you actually want `use_github()`?

**Comment by hrdawson** [comment]
Wow, I feel quite foolish now. That is exactly what happened. Thank you for pointing it out!
