### ISSUE TITLE
use_description_defaults() contains invalid ORCID placeholder that throws error in R-devel

### ISSUE THREAD

**Issue by slager** [r-lib/usethis#2059]
`use_description_defaults()` contains an invalid ORCID placeholder here:

https://github.com/r-lib/usethis/blob/2cc9e5a4e5e3034399fafb65d871eec352d83a15/R/description.R#L127

When a package containing this default ORCID placeholder is built, a recent change to R-devel now catches the invalid ORCID. This is happening in the unit tests for my R package which is now failing CRAN checks on R-devel:

https://cran.r-project.org/web/checks/check_results_DataPackageR.html

**Comment by llrs** [comment]
It wouldn't be good to add a valid ORCID of someone that could end up with hundreds of packages on CRAN attributed... It works as a reminder for maintainers to add their own ORCID or delete it. 
I hope you can submit a new version with this and the other problems fixed. Good luck!

**Comment by slager** [comment]
I did not suggest hardcoding someone's real ORCID into usethis, and I agree that would be a bad idea!

ORCID is optional in a DESCRIPTION, so I would propose usethis just remove the invalid placeholder from the default.

**Comment by jennybc** [comment]
The general philosophy of many usethis functions is to help people get fiddly files or bits of files in the correct form. That is the spirit of the ORCID placeholder here. It is much easier for someone to delete the placeholder if they don't wish to populate than it is for everyone else to look up the syntax (or, more likely, not bother with placing an ORCID even though they have one). So it's a question of net benefit to package developers.

**Comment by slager** [comment]
Ok, sounds good.  I will work around this.

**Comment by slager** [comment]
Fixed by #2075.
