### ISSUE TITLE
create a `use_bsd3_license()` function

### ISSUE THREAD

**Issue by SaranjeetKaur** [r-lib/usethis#2064]
Are there any plans to include a `use_bsd3_license()` function [in this file](https://github.com/r-lib/usethis/blob/v3.0.0/R/license.R)? It would be nice to have it handy.

**Comment by hadley** [comment]
Not at this time.

**Comment by dalonsoa** [comment]
Would you accept contributions adding that license? Totally fine if you prefer to keep development in house, but just checking if would be open to others adding it.

**Comment by hadley** [comment]
It's just so close to MIT that I'm not sure it's worth supporting it.

**Comment by dalonsoa** [comment]
Well, it's close, but a distinct license legally speaking and many packages use it. It's not as if we were talking about a niche licence than no-one cares about.
