### ISSUE TITLE
superflous comma in `Authors` in DESCRIPTION file

### ISSUE THREAD

**Issue by luisDVA** [r-lib/usethis#2066]
Hi!
I just set up a new package with `create_tidy_package` and the DESCRIPTION file generated has a seemingly unnecessary comma between the author names and email.

Looks like this:
`
Authors@R: 
    person("First", "Last", , "first.last@example.c
` 

And this is also present in the current DESCRIPTION file for usethis:

`
Authors@R: c(
    person("Hadley", "Wickham", , "hadley@posit.co", role = "aut",
           comment = c(ORCID = "0000-0003-4757-117X")),
    person("Jennifer", "Bryan", , "jenny@posit.co", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0002-6983-2759")),
`

does not seem to be breaking anything but maybe worth fixing? I can volunteer to patch the culprit fn
thanks!

**Comment by jennybc** [comment]
```
person(given = NULL, family = NULL, middle = NULL,
       email = NULL, role = NULL, comment = NULL,
       first = NULL, last = NULL)
```

This is intentional, so that `"first.last@example.com"` matches `email` and not `middle`.

So we can't remove it. Or, rather, if we did, we'd have to explicitly name `email`. I feel like this has been discussed before and maybe we've even gone back and forth on it? I'm pretty sure there's some history here.

**Comment by luisDVA** [comment]
Thanks for the clarification Jenny!
I tried to find relevant issues but must have used the wrong search terms. Wasn't aware at all of the middle name in that position, seems to be fairly underused. Closing.
