### ISSUE TITLE
Create helper function combining tidy GitHub docs/templates

### ISSUE THREAD

**Issue by batpigandme** [r-lib/usethis#207]
Roll together`use_tidy_contributing()`, `use_tidy_issue_template()`, and `use_tidy_support()` into one function.
* Possible doesn't actually need to be in the package
* Good name suggestions?

**Comment by jennybc** [comment]
Related to #165 Put GitHub md files .github/

**Comment by jennybc** [comment]
Code of conduct is also involved here. It should have a `use_tidy_*()` function (even if just an alias), then get swept up in the above.

**Comment by batpigandme** [comment]
Ah thanks, Jenny! I knew that was somewhere.
