### ISSUE TITLE
use_lifecycle() raises an error, uses_roxygen_md() is confused by roclets

### ISSUE THREAD

**Issue by nkehrein** [r-lib/usethis#2073]
My package's `DESCRIPTION` file contains the following lines:
```
RoxygenNote: 7.3.2
Roxygen: list(markdown = TRUE, roclets = c("collate", "namespace", "rd",
    "roxyglobals::global_roclet"))
```

When I try to execute the following statement to add support for the *lifecycle* package:
`> usethis::use_lifecycle()`
Then the following error appears:
```
Error in if (!uses_roxygen_md()) { : 
  missing value where TRUE/FALSE needed
```
I have tested this with usethis version 3.0.0 and R 4.3.0.

As far as I can tell, the issue is because of [this check](https://github.com/r-lib/usethis/blob/a9afa2cb7578de6d6efaa5835cb83d570115de6f/R/roxygen.R#L69), which doesn't seem to account for the existence of roclets in the config object.

**Comment by maelle** [comment]
I came here to open the same issue. :smile_cat: 

Could the current condition be made more flexible, maybe only checking the string starts with `list(markdown = TRUE`? roxygen2 [evaluates the field](https://github.com/r-lib/roxygen2/blob/9652d15221109917d46768e836eaf55e33c21633/R/options.R#L86).

**Comment by maelle** [comment]
Thank you @jennybc :pray:

**Comment by nkehrein** [comment]
Thanks!
