### ISSUE TITLE
more convenient TDD support

### ISSUE THREAD

**Issue by katrinleinweber** [r-lib/usethis#208]
Hello and 1k thanks for working on simplifying R package development :-)

In the [test-driven development](https://en.wikipedia.org/wiki/Test_driven_development) model/philosophy, tests are written before the code, so that the latter fulfills what the former specify. Currently, [`usethis` supports this by calling `use_r()` without parameter](https://github.com/r-lib/usethis/commit/c5399df2788483c406561b9a3d4703ddb0ab9a03) to open the corresponding `.R` file from within an active `test-...R` file.

How about a parameter like `TDD = TRUE` in both or either [`use_r()`](https://github.com/r-lib/usethis/blob/master/R/r.R) and [`use_test()`](https://github.com/r-lib/usethis/blob/master/R/test.R#L24) (or a new function `use_TDD("function_name")`!) that:

a) creates both files, but
b) opens `test-function_name.R` last, so that the cursor focus is there first.

The user would need only one function call, then code the tests first and conveniently switch to the already prepared `function_name.R`.

Cheers :-)

**Comment by katrinleinweber** [comment]
> conveniently switch to the already prepared function_name.R

is [already achieved by `use_r`'s default behaviour](https://github.com/r-lib/usethis/blame/683df8cf850d2fb11415683eddf1f7024cde60f3/R/r.R#L3-L5), if one does `use_test("xyz")` 1st and `use_r()` 2nd.

**Comment by maelle** [comment]
@katrinleinweber I've recently discovered https://github.com/s-fleck/testthis, would this help?

**Comment by katrinleinweber** [comment]
Yeah, its `open_testfile()` seems to do that. Please feel free to downgrade this issue to low-prio.

**Comment by maelle** [comment]
@katrinleinweber I :eyes: that `devtools` itself now has similar functions cf https://www.tidyverse.org/articles/2018/10/devtools-2-0-0/#testing-single-files

**Comment by hadley** [comment]
This feels a bit too special-purpose to me. Especially since `TDD = TRUE` is more typing than `use_r()`
