### ISSUE TITLE
Figure captions in vignette work for one plot but not two (side-by-side) plots.

### ISSUE THREAD

**Issue by alexholcombe** [r-lib/usethis#209]
The CSS style for the vignette is nifty in that it allows figures side by side.
It also allows figure captions, but seemingly only if one figure is shown, see this example where the caption is seen for one figure but not for two: 
<img width="769" alt="nocaptionwork" src="https://user-images.githubusercontent.com/886094/34970886-2f974166-facb-11e7-9251-dfe36efc3c4a.png">

***
And below is the .Rmd code with YAML at the top turning on the figure caption.
***

`
---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
      fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Figures

```{r, fig.show='hold', fig.cap = "Your figure caption."}
plot(1:10)
#plot(10:1)
```

The figure sizes have been customised so that you can easily put two images side-by-side, but then the caption does not appear.

```{r, fig.show='hold', fig.cap = "Your figure caption."}
plot(1:10)
plot(10:1)
```
`

**Comment by jennybc** [comment]
usethis doesn't insert any of its own logic or styling for a vignette. It uses a template from the rmarkdown package. So this can only be addressed in the [rmarkdown repo](https://github.com/rstudio/rmarkdown/issues).

<http://rmarkdown.rstudio.com/package_vignette_format.html>

<https://github.com/rstudio/rmarkdown/tree/master/inst/rmarkdown/templates/html_vignette>
