### ISSUE TITLE
Consistent message style

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#211]
Consistently use the functions in [`style.R`](https://github.com/r-lib/usethis/blob/master/R/style.R).

Whenever I stumble across messages that need work, I'm going to dump here.

**Comment by jennybc** [comment]
https://github.com/r-lib/usethis/blob/53daf57ab0fab30b881287fb157847cec88ff1aa/R/rstudio.R#L46-L57

**Comment by hadley** [comment]
These have been revised already; I'll touch up others as I see them.
