### ISSUE TITLE
create_from_github() should share many arguments with use_github()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#215]
`create_from github()` is capable of creating a GitHub repository, so it should be possible to specify `private` and `host`. `create_from_github()` should also be setting one or more remotes, therefore it should have a `protocol` argument. Finally auth is definitely required, so `credentials` and `auth_token` are also necessary.

Re-framed version of #114. Should be solved in the context of #214 GitHub connectivity.

**Comment by cboettig** [comment]
Minor issue: in `create_from_github()`: if `path` doesn't exist, I get an error that it doesn't exist, while the docs imply the path will be created.  Also the behavior is a bit unexpected, in that:

```
git clone git@remote_address/repo_name path/to/local_name
```

Creates the new repo in the directory `to` with name `local_name`, while `create_from_github` does not allow the local directory to have a different name (this is related to a bigger conceptual issue I'll follow up in #214, essentially that I want to start by copying a repo called `my_template` from which I want to create repos called `project_1`, `project_2`, ..., which afik the current structure doesn't permit).

**Comment by jennybc** [comment]
> Minor issue: in `create_from_github()`: if `path` doesn't exist, I get an error that it doesn't exist, while the docs imply the path will be created. 

Current version (now merged btw) has no `path` argument, only `destdir`. But perhaps everything you say applies to that checking now. I just want to make sure you're using the most recent version because this feedback is super timely /time-senstive.

**Comment by jennybc** [comment]
@cboettig You're correct about the naming constraints. It is an intentional compromise/simplification for the time being. But if you feel really strongly, maybe we'll do something different before submission (imminent).

Basically, I want auto-naming to work well. I care more about that being able to override the name, because I perceive that it comes up more often. And with the current interface, you get to pick one. Long-term, I totally agree we should find a way to have both and a nice UI.

**Comment by cboettig** [comment]
@jennybc Thanks! sorry I was testing `master` prior to merge.  saw the merge, just re-installed `master` branch and testing that now.

**Comment by jennybc** [comment]
Address by this PR: #253 

@ijlyttle @cboettig I'd love it if you'd try this PR out.

@ijlyttle Does it work on GHE for you?

@cboettig I know this doesn't tick all your boxes -- it's aimed at typical single user use, not course workflow -- but hopefully still of interest.

**Comment by cboettig** [comment]
:+1:

**Comment by ijlyttle** [comment]
Hi just to add that I just got a chance to put this through its paces - it worked like a charm on both GH and GHE!

This will be very useful, thanks!
