### ISSUE TITLE
use_github(): be more resilient to partial setup

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#221]
Right now it is possible for `use_github()` to successfully create a GitHub repo and set a remote. But then fail to push, e.g. due to SSH key/passphrase problems.

Then, when you call it again, it exits early, because it thinks the repo already uses GitHub, because the remote is set. If you unset that, you get a new (cryptic) error because the remote repo already exists.

Could it handle "partial setup" better?

**Comment by ijlyttle** [comment]
Feeling shame because I should have thought to file this issue

**Comment by maelle** [comment]
Could one also set push to FALSE, exposing a `push` argument? E.g. this way any e.g. Windows user could setup everything, and just need to push "manually" afterwards.
