### ISSUE TITLE
Could use_github_pages() turn on GitHub Pages?

### ISSUE THREAD

**Issue by charliejhadley** [r-lib/usethis#224]
There is already support for `use_github_labels` in `usethis`, it would be great to programmatically turn on GitHub Pages for a repo without having to visit the settings page.

```r
use_github_pages(source.branch = "master")
# Your site is published at https://username.github.io/repo
```
If the provided `source.branch` cannot be found then return the following error (a la http://style.tidyverse.org/error-messages.html#hints):

```r
use_github_pages(source.branch = "not-a-real-branch")
#> Can't find branch 'not-a-real-branch' in the list of branches for GitHub repo 'my-repo'.
#> Refer to https://github.com/username/my-repo/settings for further settings.
```

**Comment by jennybc** [comment]
I see this:

https://developer.github.com/v3/repos/pages/#pages

It's not immediately clear to me if activation via API is possible.

More docs:

https://help.github.com/categories/github-pages-basics/

**Comment by hadley** [comment]
Given this only needs to happen once per repo, and there are options that might differ from package to package, I don't think it's a good fit for usethis.

**Comment by krlmlr** [comment]
Seems we can turn on via https://docs.github.com/en/rest/reference/repos#update-information-about-a-github-pages-site. `use_github_pages()` would:

- import the `pkgdown.yaml` GHA workflow
- turn on GitHub Pages
- replace the link on the GitHub home page, the `homepage` field in https://docs.github.com/en/rest/reference/repos#update-a-repository

Saves a lot of clicks, even if it's done only once. Could also help existing repositories.

**Comment by hadley** [comment]
Yeah, that seems reasonable, although I'd make `use_github_pages()` a simple function that just sets pages status, and then move the other logic in use `use_pkgdown()` (adding a `url` argument).

**Comment by hadley** [comment]
And should also add url to front of `Url` field in DESCRIPTION
