### ISSUE TITLE
support for GitLab?

### ISSUE THREAD

**Issue by vnijs** [r-lib/usethis#225]
I have been using GitLab with my students for a while. To make it easier for them to work with GitLab I created an Addin for Rstudio to create new repos on GitLab and fetch student assignments for local processing. We also use it to create forks from an assignment repo for all students or student teams using the API. Then when the due-date has passed, we create all the merge requests. 

It hope to add github API support to `gitgadget` at some point, but in the meantime, if you feel there might be something useful in the `gitgadget` code for `usethis` or `happygit`, please let me know. 

https://github.com/vnijs/gitgadget

**Comment by jennybc** [comment]
Thanks @vnijs!

I just (re-?)learned about https://github.com/rundel/ghclass, helmed by @rundel.

I think that might be a good place for all of us to concentrate these functions and, yes, for GitHub and GitLab. I also have a bunch of functions lying around in a sorry state, that support my STAT545 workflow. 

The classroom use feels like a big enough problem that it needs its own package, maybe with a dependency on usethis. I'd be happy to host utility functions that are useful in general (so, to typical end users) here and we can concentrate the classroom-specific workflows there.

What do you think @vnijs @rundel @cboettig @mine-cetinkaya-rundel?

Related #214 GitHub connectivity, esp. https://github.com/r-lib/usethis/issues/214#issuecomment-358388503

**Comment by mine-cetinkaya-rundel** [comment]
@jennybc Agreed that classroom usage is big enough to need/merit its own package so I'm on board with this idea.

**Comment by rundel** [comment]
I'd be more than happy to have ghclass be a central package for this kind of thing. It has gone through a fair bit of evolution and I'm happy with where it has gotten to but it very much reflects my current workflow. I would love to have contributions and feedback to support as wide a gamut as possible.

**Comment by jennybc** [comment]
@rundel Should we try to somehow collectively write requirements or design doc? Basically reverse engineering from what we've all seen fit to implement? For example, some high-level workflows all instructors need:

  * Create student repos
    - seed them with content?
  * Create teams (or organizations?)
  * Add people to teams (or organizations?)

etc etc
And that doesn't even get into possible student-facing functions.

**Comment by rundel** [comment]
@jennybc That sounds like a good idea to me, do you have a preference for working within a repo or wiki?

**Comment by jennybc** [comment]
I would either create an .Rbuildignored `.[R]?md` document inside ghclass, that we could all make PRs to or do it in a Google Doc that you invite us to edit or make suggestions on. The latter might be more practical? I sort of loathe GitHub wikis, perhaps unfairly.

**Comment by rundel** [comment]
Google doc for the initial sorting out of stuff makes sense to me then we can move it over to github once it has stabilized.

Created and invited @jennybc and @mine-cetinkaya-rundel, if anyone else wants access just let one of us know.

**Comment by cboettig** [comment]
Thanks for the link, looks `ghclass` looks excellent.  `mirror_repo` and the team management looks a lot like what I'm looking for.  Will give this a try soon.

**Comment by vnijs** [comment]
@rundel Time permitting (teaching 3 sections this quarter) I'd be happy to contribute or comment on the google doc

**Comment by rundel** [comment]
@vnijs invited you to the google doc

**Comment by jennybc** [comment]
I'm going to close this as it feels like we're agreed on developing classroom-specific, bulk-processing-oriented workflows in ghclass. I'd still love for generally reusable functions (i.e., for the typical useR) to live here and support higher-level wrappers in ghclass.
