### ISSUE TITLE
Option to do a system check via use_course()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#226]
Idea from @hadley:

> if `use_course()` could have knowledge of a special `needed.yaml` which would automatically check and report on R version, RStudio version, packages etc

**Comment by jennybc** [comment]
Let's just start collecting specifics. From current slack discussion with @jimhester:

check that `.Renviron` and `.Rprofile` have certain features, e.g. `.Renviron` ends with a newline

`pkgbuild::check_build_tools()`

**Comment by jennybc** [comment]
"X% of your Y installed packages are THIS far behind current CRAN version" (so many R installations I see in teaching settings are like a time capsule)

**Comment by jimhester** [comment]
We are planning to have some functions in pkgman to query / report on your installed libraries, so we should share code for this depending on where the work is done first.

I guess ideally it would be nice to see a histogram versions_behind x number_of_packages. The only slight difficulty would be I am not sure there is a way to figure out how many releases behind a given package is without scraping previous versions released on CRAN. Maybe a better solution would be to query prior releases on the GitHub CRAN mirror.

**Comment by hadley** [comment]
Also a lot of the oldness may be driven by the age of the installed R version, and if they have an old R version, it's not clear how they'll get newer versions.

**Comment by hadley** [comment]
A simpler place to start might be to look for a DESCRIPTION file in the root directory, and if that exists, verify that all packages are installed, and of stated version. For now, we can leave it up to the instructor to specify minimum versions (eventually providing better tooling for them to determine that)

**Comment by jennybc** [comment]
I think this is largely addressed by our growing family if sitrep functions.
