### ISSUE TITLE
use_cla()

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#23]
It would be nice to have a helper setup a Contributor License Agreement for a project. Using https://cla-assistant.io/ all you need is a GitHub gist with the CLA text, I just set one up for [covr](https://gist.github.com/jimhester/7e891e947f724339e0979a549de44ea6) derived from https://cla.github.com.

I like the GitHub CLA because it is short and pretty readable even for a layperson like myself.

**Comment by hadley** [comment]
@wch is working on a comparison of some options

**Comment by hadley** [comment]
Looks like there still isn't good tooling for this. We can reopen the issue if we ever figure it out.

**Comment by jimhester** [comment]
I have been using it in covr since I opened this issue. I think the main thing that still needs to be done would be to settle on a cla text to use as a template, then all usethis would have to do is create the gist based on the template and open the browser to https://cla-assistant.io

**Comment by hadley** [comment]
Would we want to share the gist across all tidyverse/r-lib repos so people only need to agree once?
