### ISSUE TITLE
Consider adding edit_r_buildignore()

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/usethis#231]
Similar to 
```r
usethis::edit_git_ignore()
```

**Comment by jennybc** [comment]
@lorenzwalthert Do you know about `use_build_ignore()`? If so, do you think this is necessary anyway?

**Comment by lorenzwalthert** [comment]
Thanks, I did not know about it. However, I wonder whether it would make sense to have both `use_rbuildignore()` and `edit_r_buildignore()` so the functionality for manipulating `.Rbuildignore` corresponds to the one the package offerers for `.gitignore`, just for consistency.

**Comment by jennybc** [comment]
Yeah, I think you are right @lorenzwalthert.
