### ISSUE TITLE
determine and enforce minimum version for backports and curl

### ISSUE THREAD

**Issue by rdrivers** [r-lib/usethis#232]
This is fixed by installing backports

> install.packages("usethis")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/usethis_1.2.0.tgz'
Content type 'application/x-gzip' length 173376 bytes (169 KB)
==================================================
downloaded 169 KB

The downloaded binary packages are in
	/var/folders/6k/ntwfppf522d359st5krfvl1r0000gn/T//Rtmp28Gkza/downloaded_packages
> library(usethis)
Error: package or namespace load failed for ‘usethis’:
 .onLoad failed in loadNamespace() for 'usethis', details:
  call: NULL
  error: 'import' is not an exported object from 'namespace:backports'**

**Comment by lionel-** [comment]
Same for `curl`, looks like the minimum versions required are not correctly specified in DESCRIPTION.

**Comment by krlmlr** [comment]
Thanks for raising this!
