### ISSUE TITLE
error when using usethis::use_lifeycle_badge()

### ISSUE THREAD

**Issue by jrosen48** [r-lib/usethis#234]
I used `usethis::use_lifeycle_badge("experimental")`. I then pasted the copied link for the badge (in markdown) to my `README.Rmd` file. When I knit that file, I saw this error:

```
pandoc: Could not fetch https://img.shields.io/badge/lifecycle-experimental-orange.svg
TlsExceptionHostPort (HandshakeFailed Error_EOF) "img.shields.io" 443
Error: pandoc document conversion failed with error 67
Execution halted
```

Am I using this incorrectly?

**Comment by jennybc** [comment]
This is a problem with specific badges, for specific versions on Pandoc. There's more detail in https://github.com/r-lib/usethis/issues/195#issuecomment-355867364 and https://github.com/rstudio/rstudio/issues/1922. The best solution for an individual is to upgrade Pandoc.
