### ISSUE TITLE
Cut down contributing template

### ISSUE THREAD

**Issue by batpigandme** [r-lib/usethis#236]
Per @krlmlr 's suggestion, the current "outline" for contributing guidelines is kind of a lot.
https://github.com/r-lib/usethis/blob/master/inst/templates/tidy_contributing.md

**Comment by batpigandme** [comment]
Discussed with @hadley, this one is meant as more of a "where to point people when they need pointing," as opposed to a template for contributing…

**Comment by jennybc** [comment]
So @batpigandme should I expect a PR from you for this?

**Comment by batpigandme** [comment]
Yes. I think I'll at least reference the option of just editing typos on GitHub- Rmd or R files, unless that seems woefully irresponsible to anyone.

**Comment by batpigandme** [comment]
Also of note, am now thinking about the pull request template option. Looking through more `contributing.md`s, they seem to be pretty sweeping documents. PR templates are more procedural…

https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by jennybc** [comment]
As I said in our workflow meeting, I think the vast majority of CONTRIBUTING.md should go into a development area of tidyverse.org and the CONTRIBUTING.md files in individual repos should be quite lean and timeless and link out to tidyverse.org for more details. I think this is a better model for anything that evolves over time.

**Comment by batpigandme** [comment]
@jennybc I'm totally in agreement (though we might have to rejig the naming, since contributing is already a section). 

As far as what to leave- if anything at all: just a bulleted list?

Should it become more of a pull request template?

My "inspiration"/models for this were basically [Jim's post](https://www.tidyverse.org/contribute/), and the [googledrive `CONTRIBUTING.md`](https://github.com/tidyverse/googledrive/blob/master/CONTRIBUTING.md), both of which are decidedly more substantial.

Is that something that each maintainer should add, or maybe that shouldn't be part of usethis?

**Comment by jennybc** [comment]
OK I'm reading: https://github.com/r-lib/usethis/blob/master/inst/templates/tidy_contributing.md

Here's stuff I would keep in a tidyverse contributing template here in usethis:

  * Prerequisites re: discuss in issue before substantive PR, issue with reprex to establish bug
  * Fixing typos
  * PR process in concise bullet list form:
    - look at Travis (and Appveyor) before vs. after
    - new code should follow our style but don't style code outside of your "work area"
    - roxygen2 w/ markdown syntax
    - testthat
    - NEWS bullet
  * Current mention of CoC
  * One or more unmissable links to greater detail on tidyverse.org. At the top and the bottom, at a minimum.

Here's stuff I would move to tidyverse.org:

  * PR process in current long-form state
  * Resources

> we might have to rejig the naming, since contributing is already a section

How about something like "development practices" or "development process"?

> My "inspiration"/models for this were basically Jim's post, and the googledrive CONTRIBUTING.md, both of which are decidedly more substantial.
>
> Is that something that each maintainer should add, or maybe that shouldn't be part of usethis?

I think those were/are great fodder for current instructions. I just think it should live in tidyverse.org. I will definitely pare down the CONTRIBUTING.md in googledrive once I can point to these instructions!

I would think of the usethis template as providing all of us something that is "better than nothing" and that links to a detailed guide that is actively maintained.

**Comment by batpigandme** [comment]
Awesome. Thanks, Jenny. I'll get on this tomorrow.
