### ISSUE TITLE
support for binder?

### ISSUE THREAD

**Issue by uribo** [r-lib/usethis#239]
[Binder](https://mybinder.org/) (beta) provides a reproducible execution environment based on the GitHub repository. Also, supports badges  and generates a link to launch the repository in the following format:

```
[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/<user>/<repository>/master)
```

[![Binder](http://mybinder.org/badge.svg)](http://mybinder.org/v2/gh/binder-examples/dockerfile-rstudio/master)

I think that badge display is useful for a everyone in a single report or article. 
So I would like to add a `use_binder_badge()` function like `usethis::use_lifecycle_badge()`.

If you are positive about this feature, can I submit a draft proposal as pull request? 
What I'm thinking is adding a *Dockerfile* that can launch an rstudio session (use the official [imagefile](https://github.com/binder-examples/dockerfile-rstudio/blob/master/Dockerfile)), if there is no *Dockerfile* or *runtime.txt*, along with the code output for the badge.

**Comment by batpigandme** [comment]
Point of clarification: are you proposing the integration of support for the binder _badge_ or binder on the whole? (No judgement either way, just trying to make sure I understand correctly 👍).

**Comment by uribo** [comment]
Thank you for your reply. I will prepare for the pull request soon.

**Comment by jennybc** [comment]
Thanks @uribo. Can you answer the question @batpigandme posed, before proceeding? Getting a PR for a badge is pretty different than for a Dockerfile. I'm not saying the latter is necessarily unwelcome, but it's a bigger responsibility re: maintenance.

**Comment by uribo** [comment]
Sorry @jennybc @batpigandme 

What I mentioned was a request for a function to display a binder badge.
The latter topic, I would like to discuss when usethis package will integrate with docker in the future.
