### ISSUE TITLE
Clarify where NEWS bullet should be added in tidy contributing template

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#244]
Make it clear that people should add bullets to the current dev version.

**Comment by batpigandme** [comment]
Good call — @krlmlr also suggested I pare it down a bit, so I'll be combing through it tomorrow.

**Comment by jennybc** [comment]
Context: some new contributors understandably wonder if they should increment the version, create a new section of NEWS, etc. So we should make it clear that there should always be a section at the top for current dev version and that's where their bullet belongs.
