### ISSUE TITLE
Tools facilitating reproducible analysis

### ISSUE THREAD

**Issue by jasonserviss** [r-lib/usethis#251]
This is not technically an issue but more a ping to see if there would be any interest in a feature(s)...

There is a lot of interest at the moment in the scientific community to facilitate reproducible analysis and it seems that using R packages are, in some ways, an optimal solution (see e.g. [template](https://github.com/Pakillo/template)). Despite this, there are some challenges when utilising R packages for this purpose, such as reproducing the environment in which the analysis was done (i.e. mostly package versions). Some tools like docker, [liftr](https://liftr.me), and others have provided a lot of help in accomplishing this but, in my opinion, the workflow could be more stream lined/automated to make the process easier. This is where I think usethis could be useful. 

Although I have not had the opportunity to extensively review different options (such as [checkpoint](https://cran.r-project.org/web/packages/checkpoint/index.html)), my current workflow uses liftr and docker to reproduce my analysis working environment. liftr uses a .yml file from which a docker file is produced. This is then used to recreate the working environment before rendering .Rmd files containing analyses. I have a quick and dirty example at: [reproducibleAnalysis](https://github.com/jasonserviss/reproducibleAnalysis) showing how I utilise these two tools. My thought was that usethis could have a "use_liftr" command that sets up the liftr .yml file dependant on what packages are currently loaded when the analysis takes place. Potentially there are other liftr/docker processes that could also be automated.

There may be better ways to reproduce a working environment and if there is any interest in facilitating reproducible analysis with usethis I could try to put some time into looking into this further although it is a bit unclear if this idea would fit into the primary goals for the usethis package.

**Comment by jennybc** [comment]
We have a medium term goal to articulate a framework for packaging data analysis and to create the necessary tooling. Where "we" = tidyverse/r-lib team, but mostly @hadley.

It's not clear what the relationship between that and usethis would be. It will likely be a big enough set of ideas to merit its own package.

I think usethis should remain fairly "dumb" and implement stuff that's quite standard in the community and/or helpers specific to tidyverse/r-lib development practices.

So, while I totally encourage what you're doing, I don't think we will bless any given approach to this problem in usethis in the near term. I'd say you should keep codifying your approach and watch development here to see when we get around to this problem space and are ready to re-examine what usethis will do.

I note that you could use the templating infrastructure in usethis as part of a package that implements your approach to reproducible data analysis.

**Comment by jasonserviss** [comment]
@jennybc Ok, good to know. Thanks for your input!
@hadley If you have any experimental code/package or ideas online for this purpose, i.e. "articulate(ing) a framework for packaging data analysis and to create the necessary tooling", I would be very interested to have a look!

**Comment by jennybc** [comment]
Here is a document but take it with a grain of salt (may be out of date in some respects): https://docs.google.com/document/d/1LzZKS44y4OEJa4Azg5reGToNAZL0e0HSUwxamNY7E-Y/edit#heading=h.blggi16hdosp
