### ISSUE TITLE
Document `tidy_labels()`

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#252]
Idea from [here](https://github.com/r-lib/usethis/pull/249#issuecomment-365610494):

> Would the docs for this function be a good place to park out descriptions of when to use the different labels?

Yes!

**Comment by jennybc** [comment]
@batpigandme Would you be willing to make a PR to document what our standard issue labels mean?

You could insert a section right here:

https://github.com/r-lib/usethis/blob/0d04d86096ab870fbc36c112089857e02b2b044d/R/github-labels.R#L12

Mechanics-wise, I'd follow the instructions that start with "You can add arbitrary sections to the documentation with the `@section` tag" from [here](http://r-pkgs.had.co.nz/man.html#roxygen-comments).

**Comment by batpigandme** [comment]
Yep.
