### ISSUE TITLE
use_tidy_github_saved_replies()

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#260]
To capture our and make consistent our saved replies

**Comment by jennybc** [comment]
https://help.github.com/articles/working-with-saved-replies/

Last I checked, saved replies belong to a user, not a repo or an Organization.

I also can't find any evidence they are exposed via the API.

That doesn't mean we can't do something to make this easier and more consistent, but it does put a bit of a damper on things.

**Comment by hadley** [comment]
No API is a major bummer 😢
