### ISSUE TITLE
Behaviour of proj_set() on a non-project folder

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#265]
Right now it is a silent no-op if `path` is not a project. This behaviour appears to be used internally in `proj_get()` but maybe this should be refactored. This seems weird to me:

``` r
> setwd("~")
> proj_get()
Error: Current working directory, '/Users/jenny',  does not appear to be inside a project or package.
> proj_set("~/tmp/aaa")
> proj_get()
Error: Current working directory, '/Users/jenny',  does not appear to be inside a project or package.
```

**Comment by jennybc** [comment]
The `force` argument of `proj_set()` is documented like so: "If `TRUE`, uses this path without checking if any parent directories are existing projects." I interpret that as avoiding *nested* projects. But I think what's actually meant is that the normal project criteria are not checked (`.here`, RStudio project, Git repo, etc.). I think we should reword this.

**Comment by hadley** [comment]
Even more damningly, this works:

```R
proj_set("asdfasdflkjasdflkjasdklfjadslk")
```
