### ISSUE TITLE
Remove travis check from use_tidy_contributing()

### ISSUE THREAD

**Issue by batpigandme** [r-lib/usethis#269]
The pared-down contributing template (#266) will no longer include a link to travis, so `use_tidy_contributing()` shouldn't need it either.
Currently:
```r
  if (!uses_travis()) {
    message(
      "Package ", value(project_name()), " doesn't have a Travis yaml file.\n",
      "Don't forget to run ", code("use_tidy_ci()"), " or ",
      code("use_travis()"), "."
    )
  }
```

**Comment by jennybc** [comment]
I think the tidy-contributing template could lose the explicit hyperlinks to both travis and GitHub, i.e. only pass package name through to the template.

While you're at it, can you make the name of the contributing template consistent with everything else? There is some underscore vs hypen funny business going on.

**Comment by batpigandme** [comment]
Got it. I actually did remove the GitHub link from the template in #266, so I'll cut that from the function as well. I don't want to rename the template until the changes are merged (or, I guess I could do that in 266).
