### ISSUE TITLE
use_gist

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#273]
This would download a gist and open the file(s) in RStudio, so they could be easily run.

Questions

1. What should this do if not run in RStudio? Maybe just download the gist and `edit.file()` / `browseURL()`?
2. Should it make a new folder?
3. Should it create a new RStudio project?

**Comment by hadley** [comment]
Are you still interested in this?

**Comment by jimhester** [comment]
I don't really remember why I wanted this, and now am not really sure that usethis is the best place for it...

We have [source_gist()](https://github.com/r-lib/devtools/blob/5ca45ef3d0272505ef153b9644a0ca24f4126323/R/run-source.R#L105) in devtools, maybe this should just be in devtools proper...

**Comment by jennybc** [comment]
In the usethis context, it feels more like an `edit_()` function, e.g., `edit_gist()`.

**Comment by hadley** [comment]
Let's close it, and we can reopen if we feel a pressing need.
