### ISSUE TITLE
use_article()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#281]
We need `use_article()` which is a minor variant on `use_vignette()`.

What's wrong with using `use_vignette()` to create an article?

  1. If you *only* have articles, you want to Rbuildignore the directory that contains them. So either `vignettes/` or `vignettes/articles/`.
  2. Creation of an article should never trigger an edit to DESCRIPTION. Specifically, do not add a `VignetteBuilder` field.
  3. The article itself should not have a `vignettes:` section in the yaml header.

To see me recovering from all of the above mistakes, look at these travis ci reports:

https://travis-ci.org/r-lib/usethis/builds/344519915

https://travis-ci.org/r-lib/usethis/builds/345021574

https://travis-ci.org/r-lib/usethis/builds/345023872

**Comment by hadley** [comment]
1. feels a bit tricky to me (what if you want a mix of articles and vignettes) so I'm just going to do 2 and 3.

**Comment by hadley** [comment]
I'm pretty sure we should still add rmarkdown to Suggests, just to ensure that it's always installed on travis (it probably is because pkgdown imports it, but better to be explicit here, I think)
