### ISSUE TITLE
Make use_description() more verbose (again)

### ISSUE THREAD

**Issue by jjchern** [r-lib/usethis#287]
The `create_description()` function from `devtools` prints out DESCRIPTION by default:

```R
devtools::create_description(quiet = FALSE)
#> No DESCRIPTION found. Creating with values:
#> Package: Rtmp5PZ0dI
#> Title: What the Package Does (one line, title case)
#> Version: 0.0.0.9000
#> Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
#> Description: What the package does (one paragraph).
#> Depends: R (>= 3.4.3)
#> License: What license is it under?
#> Encoding: UTF-8
#> LazyData: true
#> [1] TRUE
```

Right now `usethis::use_description()` only writes the DESCRIPTION file but doesn't print out information. I was wondering if it'd be useful to add a `quite = TRUE` argument in `usethis::use_description()`, so that users can have an option to see the output in the console.

**Comment by jennybc** [comment]
I think it probably just makes more sense to print this to screen again. I suspect the suppression of that was more a side effect of changing the internals than some explicit choice.

**Comment by hadley** [comment]
`use_description()` is only called from `create_package()` so this change seems benign.
