### ISSUE TITLE
use_usethis instructions

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#288]
Currently `usethis::use_usethis()` provides a list of 3 things to do, but the first and the last are the same which was a bit confusing for me. 🐨  I can see why it is so, because the function first calls `usethis::edit_r_profile()`. Maybe the first line of `usethis::edit_r_profile()`could be "Modify '.Rprofile' with the potential further explanations below" or something like that? Or the last point shouldn't be a `todo` but "More details:"?

**Comment by jennybc** [comment]
Can you discuss in terms of the exact output you see that's confusing? For reference, I see this:

``` r
> use_usethis()
● Modify '.Rprofile'
● Restart R for changes to take effect
● Include this code to make usethis available in all interactive sessions
Copying code to clipboard:
  if (interactive()) {
    suppressMessages(require(usethis))
  }
```

**Comment by maelle** [comment]
I'd expect

```r
> use_usethis()
● Modify '.Rprofile' which means including this code below to make usethis available in all interactive sessions
● Restart R for changes to take effect
Copying code to clipboard:
  if (interactive()) {
    suppressMessages(require(usethis))
  }
```

Because the current output makes it look as if there were 3 steps while there are only 2, the last to-do (include blabla) being an explanation for the first (what one needs to modify).

I agree that it's not _very_ confusing, one just needs to think maybe 10 seconds more. :-)

**Comment by jennybc** [comment]
I'll take a look, but this may be unavoidable. All these functions rely on internal helper functions, which puts some constraints on the message text and order.

**Comment by jennybc** [comment]
OK, I don't see a way to rework this where the effort justifies the payoff.

As you say, the first 2 messages come from the generic helper `usethis::edit_r_profile()`. So it's not easy to emit a custom message, such as "which means including this code below to make usethis available in all interactive sessions". We also communicate with the user via standard functions in [style.R](https://github.com/r-lib/usethis/blob/master/R/style.R), so removing the "todo" bullet is also not easy.
