### ISSUE TITLE
Give a hint on how to restart session?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#289]
(I hope it's ok for me to open so many issues with mere suggestions!)

`usethis` seems to encourage using the command line. When there's a todo "restart session", should the text suggest to do this by `rstudioapi::restartSession()`?

**Comment by jennybc** [comment]
I don't find mentioning `rstudioapi::restartSession()` very appealing. It's not entirely easy for me to say why. Basically I think people should do *Session > Restart R* if in RStudio (or keyboard shortcut equivalent). And other wise ... they have to figure out most efficient way to restart R.

The rstudioapi package is very much *not* user-facing, so it would be odd to feature like this. Also, I think it encourages the thinking that leads people to put `rm(list = ls())` at the top of the script.

I'll think about this some more.

**Comment by hadley** [comment]
I did a grep for "restart", and I'm happy with the current messaging.
