### ISSUE TITLE
GitHub API error (401): 401 Unauthorized

### ISSUE THREAD

**Issue by pat-s** [r-lib/usethis#291]
When using `usethis::use_github(auth_token = "GITHUB_PAT")` I face the following error:

```r
✔ Creating GitHub repository
Error in gh::gh("POST /user/repos", name = repo_name, description = repo_desc,  : 
  GitHub API error (401): 401 Unauthorized
  Bad credentials
```

SSH keys and GITHUB_PAT are stored properly (use them all the time for other projects). 

Any idea what might cause the problem here? `usethis` v1.3

**Comment by ijlyttle** [comment]
I would make sure that your GitHub PAT is stored in your `.Renviron` file as the environment variable `GITHUB_PAT`, and you have restarted your R session.

If you get a sensible result from this:

```R
Sys.getenv("GITHUB_PAT")
```

then this should "just work":

```R
usethis::use_github()
```

**Comment by batpigandme** [comment]
See the setup instructions in the usethis setup article here: http://usethis.r-lib.org/articles/articles/usethis-setup.html

**Comment by jennybc** [comment]
If you already have the PAT stored to env var `GITHUB_PAT`, you don't need to specify it, as that is the default place to look.

If I take you very literally about this: `usethis::use_github(auth_token = "GITHUB_PAT")`, you sent the actual string `GITHUB_PAT` as the PAT, so the error code would make sense.

**Comment by pat-s** [comment]
Thanks, I was indeed using `auth_token = "GITGUB_PATH"` - facepalm.

While the command now works, I get an error message during execution which does not seem to affect usage. The repo is successfully created and linked locally.

```r
Creating GitHub repository
✔ Adding GitHub remote
✔ Pushing to GitHub and setting remote tracking branch
Fehler in .local(object, ...) : 
  Error in 'git2r_push': unsupported URL protocol
```

**Comment by jennybc** [comment]
What is your version of git2r? It's in an above average state of flux right now. But if this is with a CRAN version, I'd like to know. And your OS.

**Comment by pat-s** [comment]
Debian 9, latest CRAN of `git2r`

```r
session_info("git2r")
Session info -----------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.2.353.3)         
 language (EN)                        
 collate  de_DE.UTF-8                 
 tz       Europe/Berlin               
 date     2018-02-27                  

Packages ---------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 git2r       0.21.0  2018-01-04 CRAN (R 3.4.3)
 graphics  * 3.4.3   2017-12-07 local         
 grDevices * 3.4.3   2017-12-07 local         
 methods   * 3.4.3   2017-12-07 local         
 stats     * 3.4.3   2017-12-07 local         
 utils     * 3.4.3   2017-12-07 local 
```

**Comment by jennybc** [comment]
I find this pretty peculiar. And the resulting repo is fully setup for pushing/pulling to GitHub? I don't know how to reconcile that with the error message.

**Comment by jennybc** [comment]
If there's something here, you should open a separate issue for it in any case.
