### ISSUE TITLE
Template for use_tidy_contributing() refers to covr::test_coverage()

### ISSUE THREAD

**Issue by maislind** [r-lib/usethis#292]
I believe there is an error or deprecated reference in the documentation for contributing, see "usethis/.github/CONTRIBUTING" on line 76. The text should direct to the "covr" package and prescribe running "covr::report()" @jimhester. I am happy to submit a pull request for this if this is the appropriate action.

**Comment by jimhester** [comment]
`devtools::test_coverage()` is a thin wrapper around `covr::report()`, however it is only available in the (as yet unreleased) devel version of devtools.

**Comment by maislind** [comment]
Ah, okay, that's where it is/will end up. I installed the currently released devel version and ran `sos::findFn('test_coverage')` and was still scratching my head.

**Comment by jennybc** [comment]
I'll probably let the passage of time fix this one.
