### ISSUE TITLE
use_bitbucket() (et al.)

### ISSUE THREAD

**Issue by chris-billingham** [r-lib/usethis#293]
Having the good fortune to use bitbucket here in the office it would be tremendous if there were analogue functions to connect to bitbucket rather than github.

Likewise: create_from_bitbucket(), use_tidy_bitbucket(), and so on through all the various github helper functions.

**Comment by jennybc** [comment]
FYI I'd be open to PRs here. Probably *not* a good first issue, though ... hence the label / lack of label.

It would definitely merit some advance discussion/planning. Might make sense to couple with a conversation about gitlab, because that's always the next question :)

**Comment by chris-billingham** [comment]
Whilst I'd love to step up and help here being the original requestor I probably don't have the programming chops to cover this, however happy to help anyway I can.

**Comment by LDalby** [comment]
use_gitlab() etc. would be super useful too.

**Comment by overmar** [comment]
I was actually thinking the addition of a gitlab-ci.yml template would be nice for those of us that use gitlab (ie the same process as use_travis()).

**Comment by jennybc** [comment]
@overmar I'm going to delete your comment re: gitlab ci (a la travis) because that should be opened as a separate issue. I am about to label this issue as fair fame for tidy verse developer day, hence my heightened concern re: scope.

**Comment by overmar** [comment]
Thanks @jennybc I created a new issue for the creation of only the ci file in gitlab. https://github.com/r-lib/usethis/issues/565

**Comment by jennybc** [comment]
A recent r-hub blog post [About URLs in DESCRIPTION](https://blog.r-hub.io/2019/12/10/urls/) contains a table that is relevant to this issue:

```
## # A tibble: 1,855 x 2
##    domain                    n
##    <chr>                 <int>
##  1 github.com             4660
##  2 www.r-project.org       164
##  3 cran.r-project.org      143
##  4 r-forge.r-project.org    82
##  5 bitbucket.org            67
##  6 sites.google.com         54
##  7 arxiv.org                52
##  8 gitlab.com               44
##  9 docs.ropensci.org        38
## 10 www.github.com           32
```

Taking a very naive summary of this suggests that ~98% of the URLs relating to remote hosts are GitHub vs 2% for bitbucket + gitlab.

So this is why we're pretty reluctant to take on (much) code relating to these other hosts, which also aren't used by the usethis maintainers.

**Comment by antoine-sachet** [comment]
There is no need for separate functions. `use_remote` should just pick up the right remote type. That's actually a straightforward change to a single function: `package_remote`. 

I would PR if I had time but not sure how to implement tests for the new remote types.

Current code (from `R/package.R`):

```R
## TO DO: make this less hard-wired to GitHub
package_remote <- function(package) {
  desc <- desc::desc(package = package)
  # @jimhester and @gaborscardi say that the Github* fields are basically
  # legacy, e.g., to support older tools like packrat
  # Remote* fields are the way to go now
  github_info <- desc$get(c("RemoteType", "RemoteUsername", "RemoteRepo"))

  if (!identical(github_info[["RemoteType"]], "github")) {
    ui_stop("{ui_value(package)} was not installed from GitHub.")
  }

  glue::glue_data(as.list(github_info), "{RemoteUsername}/{RemoteRepo}")
}
```

Suggested (untested) fix:

```R
package_remote <- function(package) {
  remote_info <- desc$get(c("RemoteType", "RemoteUsername", "RemoteRepo"))

  if (!any(c("github", "gitlab", "bitbucket") %in% remote_info[["RemoteType"]])) {
    ui_stop("{ui_value(package)} was not installed from GitHub, GitLab or Bitbucket.")
  }

  glue::glue_data(as.list(remote_info), "{RemoteType}::{RemoteUsername}/{RemoteRepo}")
}
```

The big visible change is that github remotes would now have an explicit `github::` prefix.

Thoughts?

**Comment by hadley** [comment]
I'm going to close this issue because unfortunately we just don't have the expertise to support significant bitbucket or gitlab functionality in this package. I think it would probably make the most sense for this code to live in separate packages that could be maintained by people particularly interested and invested in gitlab and bitbucket.
