### ISSUE TITLE
Change WIP or reprex label colour?

### ISSUE THREAD

**Issue by batpigandme** [r-lib/usethis#299]
Just realised that the WIP and reprex labels are the same colour. If this is intentional, 👍 . If not, I'm happy to PR a change.
https://github.com/r-lib/usethis/blob/952c023e676f5619b01f41501b0dc83f362d6507/R/github-labels.R#L125-L126
![image](https://user-images.githubusercontent.com/831732/36742029-a06572fa-1bb4-11e8-9969-342c06e93600.png)

**Comment by jennybc** [comment]
It is intentional. It is @hadley's way. It means "ball is in someone else's court".

I may have already tried to "fix" this once 😜

**Comment by batpigandme** [comment]
Ah…hence the 🏀 colour! Should've searched the issues… (>ლ)

**Comment by hadley** [comment]
You know how I love to use sports metaphors!

**Comment by batpigandme** [comment]
Soon your Bryan Adams - to - Steven Adams transformation will be complete…
