### ISSUE TITLE
use_url idea

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/usethis#303]
With the use of `use_github`, does `usethis` have enough information to populate the URL section in the description? 

If so, I think that would be a nice feature, especially for packages that end up on CRAN but have development on github.

**Comment by jennybc** [comment]
I think you are suggesting the functionality that is provided by `use_github_links()`:

http://usethis.r-lib.org/reference/use_github.html

I grant it's not very obvious from the current help, which is dominated by `use_github()`, so a PR would be most welcome.

What do you think?

**Comment by EmilHvitfeldt** [comment]
You are correct! That was what I wanted, must have missed it. Would It be too much to separate the help/documentation of `use_github()` and `use_github_links()`? 

Wether or not we separate, I would suggest that we have the word "url" somewhere on http://usethis.r-lib.org/reference/index.html and in the documentation in general since as of now a search of both comes back empty.

**Comment by jennybc** [comment]
I think you're right about documenting separately. `use_github_links()` appeared when all of this was in devtools and at the moment it made sense to document together. But yes it's awfully hard right now to discover `use_github_links()`. There are other things I need to do re: documenting a whole workflow, but your proposal is a step in the right direction.

**Comment by EmilHvitfeldt** [comment]
Okay, I'll work on a PR to get this sorted then.
