### ISSUE TITLE
use_course() does not accept a ZIP with mime type "application/octet-stream"

### ISSUE THREAD

**Issue by Chris-Engelhardt** [r-lib/usethis#304]
---
use_course() fails with zip files on the Open Science Framework, but works as expected with zip files on GitHub. The source of the failure appears to be the header passed to usethis:::check_is_zip(), where the headers on the Open Science Framework include "octet-stream", not "zip".  This problem might need to be resolved on the Open Science Framework side, but Jenny asked me to open an issue for further discussion. 

```r
#does not work
use_course("https://osf.io/b7sc5/download")

#works
use_course("https://github.com/Chris-Engelhardt/data_science_training/raw/master/vg_materials.zip")
```

**Comment by jennybc** [comment]
How sure are you @Chris-Engelhardt that the URL above is the most proper or only one for ZIP download from OSF? I know with DropBox there's a small trick needed to get the URL to download an entire folder as a ZIP archive.

It would be good to explore all avenues for getting an OSF download URL with the standard header for a ZIP archive, which is definitely `"application/zip"`. Up to and including them changing something on their end.

**Comment by Chris-Engelhardt** [comment]
@jennybc As far as I can tell, I'm using the preferred (and perhaps only) download method. My download link was obtained by right-clicking the "download" radio button and selecting copy link address. If I paste this link address in a browser, the zip download begins automatically. Of course, there could be some gotcha that I'm not aware of. 

I've reached out to OSF on Twitter. I'll be curious to hear what they say. Thanks for your help and time!

**Comment by jennybc** [comment]
Thanks. I'm not surprised that a browser will download it. And then your local OS might consult file extension and, if zip, proceed in an appropriate fashion.

`use_course()` is conceived as a pretty narrow function and is very conservative. At the moment, it expects the file to actually advertise itself as a ZIP file (vs. discovering that or assuming so and hoping for the best).

**Comment by jennybc** [comment]
From OSF:

https://twitter.com/OSFramework/status/970703774070312961

> Thanks for the heads up! Glad you were able to find a workaround. This might improve on our end when we finish migrating to a new cloud provider. If not, we might consider some work to improve content detection in the future - I'll file an issue in our tracker and keep you posted

**Comment by Chris-Engelhardt** [comment]
Wow. You're very attentive to your Twitter feed! Thanks for posting this update (was about to do the same).

What's somewhat odd is that OSF recognizes the zip file as a zip on the webpage itself but does not recognize the file as a zip in the headers. Bummer. 

Because I don't *need* to host the files on OSF, and because I have a workaround via GitHub, perhaps we can close this issue. What do you think?

**Comment by jennybc** [comment]
Sounds good. I think in the end ... I'm not willing to download and (attempt to) unzip just anything. And I'm not eager to add a content-type argument to `use_course()`. So let's close.

**Comment by Chris-Engelhardt** [comment]
I agree. Thanks for your attention.
