### ISSUE TITLE
use_cpp11, use_cpp14, use_cpp17

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/usethis#307]
I can't never remember what I have to do for variants of C++. 
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-C_002b_002b11-code
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-C_002b_002b14-code
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-C_002b_002b17-code

Should I make the relevant `use_cpp_` functions ?

**Comment by jennybc** [comment]
Sounds good to me! cc @hadley @jimhester

**Comment by romainfrancois** [comment]
This is somewhat orthogonal to Rcpp or not Rcpp, and more about when you want to use some C++ standard with or without Rcpp.

**Comment by coatless** [comment]
This would be an ideal extension candidate for the `use_makevars()` function sitting in #601. With this being said, the present implementation would require more versatility by parseing the file in a similar way to the `DESCRIPTION` parser used by `use_description()` to check for duplicates. One step at a time though...

**Comment by jennybc** [comment]
I'm putting this in the backlog w.r.t. preparing the release of v1.5.0. If anyone has immediate plans to move on this, let me know.

**Comment by coatless** [comment]
@jennybc no immediate plan to move on this. I'll likely have cycles in summer/fall to develop a `makevars` parser package similar to `desc`. 

Might also be worth noting @jeroen's [`makeconf`](https://github.com/jeroen/makeconf) package does wonders for understanding a user's compile options.

**Comment by jennybc** [comment]
Just added `use_cpp11()` in 194db5be028f45f59239b8cdbde2bb1866f4bf50. It doesn't feel like we have any highly specific, near terms plans to do more in this area.
