### ISSUE TITLE
include template for use_r()

### ISSUE THREAD

**Issue by HanjoStudy** [r-lib/usethis#311]
It might be useful to add a template option for `use_r()`  that generates a skeleton `R/function.r` file. Currently it only creates a file. I am imagining

```r
use_r(template = TRUE)
```
Should result in something like

```r
#' Title
#' @description 
#' @param param 
#'
#' @details
#' @importFrom 
#'
#' @examples
#' 
#' @seealso
#' 
#' @return
#' @export
#'
function_name <- function(param){
  
}
```

**Comment by hadley** [comment]
I think this is out of scope for usethis because there are other reasons to create an R file than to create a function, and it's already easy to generate the roxygen template in RStudio.

**Comment by florianm** [comment]
Respecting Hadley's OOS decision, I won't create a separate feature request for the following suggestion:

`use_r(..., template = TRUE, test = TRUE)` would save me the corresponding `usethis::use_test("")` if it generated a related test file. Bonus points if it added commented out cross-references at the bottom of each, i.e. `# usethis::use_r("...")` at the end of the test, and a `# usethis::use_test("...")` at the end of the R file.
