### ISSUE TITLE
On Windows, pasting the badge code into an Rmd causes a pandoc error

### ISSUE THREAD

**Issue by andrie** [r-lib/usethis#318]
I don't think the root cause of this bug is in `usethis`, but I'm documenting a workaround until somebody can trace the root cause.

The standard procedure of using a badge, e.g. `usethis::use_lifecycle_badge()` is to paste the resulting snippet into the `README.md` or `README.Rmd`.

However, on Windows, using the badge in an `.Rmd` file causes a pandoc error:

```
pandoc.exe: Could not fetch https://img.shields.io/badge/lifecycle-experimental-orange.svg
TlsExceptionHostPort (HandshakeFailed Error_EOF) "img.shields.io" 443
Error: pandoc document conversion failed with error 67
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS README.md --to html4 --from markdown_github-ascii_identifiers --output README.html --standalone --self-contained --highlight-style pygments --template "C:\Users\apdev\Documents\R\win-library\3.4\rmarkdown\rmarkdown\templates\github_document\resources\preview.html" --variable "github-markdown-css:C:\Users\apdev\Documents\R\win-library\3.4\rmarkdown\rmarkdown\templates\github_document\resources\github.css" --email-obfuscation none' had status 67 
Execution halted
```

The workaround is to not paste the badge snippet directly in the markdown, but to create a chunk with `results='asis'`, and the paste the badge snippet inside a `cat()` statement in the chunk.  For example:

```r

 ```{r echo=FALSE, prompt=FALSE, results='asis', comment=""}
cat('
[![lifecycle](https://img.shields.io/badge/lifecycle-experimental-orange.svg)](https://www.tidyverse.org/lifecycle/#experimental)
')
    ```

```

A similar issue was filed on the `badgecreatr` project at https://github.com/RMHogervorst/badgecreatr/issues/25, where the suggestion is to add `<!-- rmarkdown v1 -->` to the top of the `.Rmd`.  This doesn't work for me.

---

My session info:

```r
> sessioninfo::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               
 date     2018-03-31                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date       source        
 backports     1.1.2      2017-12-13 CRAN (R 3.4.3)
 clisymbols    1.2.0      2017-05-21 CRAN (R 3.4.2)
 devtools      1.13.5     2018-02-18 CRAN (R 3.4.3)
 digest        0.6.15     2018-01-28 CRAN (R 3.4.3)
 evaluate      0.10.1     2017-06-24 CRAN (R 3.4.1)
 htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)
 knitr         1.20       2018-02-20 CRAN (R 3.4.3)
 magrittr      1.5        2014-11-22 CRAN (R 3.4.0)
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)
 modelmanagr * 0.0.0.9000 2018-03-29 local         
 Rcpp          0.12.16    2018-03-13 CRAN (R 3.4.4)
 rmarkdown     1.9        2018-03-01 CRAN (R 3.4.4)
 rprojroot     1.3-2      2018-01-03 CRAN (R 3.4.3)
 rsconnect     0.8.8      2018-03-09 CRAN (R 3.4.3)
 sessioninfo   1.0.0      2017-06-21 CRAN (R 3.4.3)
 stringi       1.1.6      2017-11-17 CRAN (R 3.4.2)
 stringr       1.3.0      2018-02-19 CRAN (R 3.4.3)
 usethis       1.3.0      2018-02-24 CRAN (R 3.4.3)
 withr         2.1.2      2018-03-15 CRAN (R 3.4.4)
 yaml          2.1.18     2018-03-08 CRAN (R 3.4.3)
```

**Comment by jennybc** [comment]
What's your pandoc version?

``` r
rmarkdown::pandoc_version()
#> [1] '2.1.1'
```

There's an existing discussion/saga over on #195, i.e. how to put badges into the README in a way that is more resilient to handshake issues and badge non-existence. So I'll close this, but now they are linked.

Your chunk suggestion is a good addition to the workaround list. I must admit I don't immediately see why that helps, but I take your word for it.

**Comment by andrie** [comment]
```r
> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’
```
It's a good question why this works. 

I tried this because I noticed that it works when I copy the badge text into a `.md` file, but not the `.Rmd`, but I don't understand why this fails / works either.

**Comment by jennybc** [comment]
The alarming error generally comes from generating the html preview, not from Rmd --> md. It's possible that your experiments with `.md` vs `.Rmd` were also different wrt to preview generation?

Your individual woes might be solved if you upgrade Pandoc (although there's someone in #195 where that appears to be untrue). It did solve the problem for me.

But I would still like to find a more general solution, i.e. to be able to preview badge-containing READMEs without internet access.

**Comment by andrie** [comment]
I may have been working on the misapprehension that Pandoc was bundled my `rmarkdown`.  I'm going to upgrade Pandoc and will report on what happens.

**Comment by andrie** [comment]
It seems that Anaconda obscured my pandoc installation.

Once I upgrade to pandoc 2.1.3 and fixed the path, everything worked as I would expect.

Thanks for taking a look!
