### ISSUE TITLE
examples using create_package not functionnal

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#319]
In `use_github` example (and maybe other places), there is a call to `create_package("test-pkg")`. However, 
``` r
usethis::create_package("test-pkg")
#> Error: 'test-pkg' is not a valid package name. It should:
#> * Contain only ASCII letters, numbers, and '.'
#> * Have at least two characters
#> * Start with a letter
#> * Not end with '.'
```
I think the hyphen `-` does not follow the naming rule. It seems the example should be changed to a functional example. I can help with a PR if you want, trying to find all similar example. For `use_github`, the example is a _dont run_ one, it may be the reason this is still present.

**Comment by jennybc** [comment]
I'm about to merge #321 to fix this instance, which will close this. But @cderv I'm very interested in getting of any similar calls, so would be happy for other PRs.
