### ISSUE TITLE
`use_tidy_style` not working

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/usethis#326]
I am using the development version of `usethis`. But I am having troubles with the function ` usethis::use_tidy_style()`. 

This is the error I get-

```
> usethis::use_tidy_style()
Error in structure(.Call(git2r_status_list, lookup_repository(repo), staged,  : 
  Error in 'git2r_status_list': Invalid repository
```

**Comment by jennybc** [comment]
What is your git2r version?

`packageVersion("git2r")`

**Comment by IndrajeetPatil** [comment]
It's `0.21.0.9002`

**Comment by jennybc** [comment]
What happens if you call `git2r::status()` in this project?

**Comment by IndrajeetPatil** [comment]
I got the same error:
```
Error in structure(.Call(git2r_status_list, lookup_repository(repo), staged,  : 
  Error in 'git2r_status_list': Invalid repository
```

So I downloaded the stable version of `git2r` from CRAN and everything is working fine now!
Seems like there is something weird going on with how `usethis` is interacting with the development version of `git2r`.

**Comment by jennybc** [comment]
Can I see the actual output? Which call specifically triggers the error?

In any case, I don't see the interaction with usethis. It sounds like you get the same error with a direct call to git2r.

**Comment by IndrajeetPatil** [comment]
Sorry, I posted my reply even before you had edited your comment. Here is all the output:

```
> git2r::status()
Error in structure(.Call(git2r_status_list, lookup_repository(repo), staged,  : 
  Error in 'git2r_status_list': Invalid repository

Restarting R session...

> install.packages("git2r")
Installing package into ‘C:/Users/Indrajeet Patil/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/git2r_0.21.0.zip'
Content type 'application/zip' length 3028463 bytes (2.9 MB)
downloaded 2.9 MB

package ‘git2r’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Indrajeet Patil\AppData\Local\Temp\Rtmp0EIFkB\downloaded_packages
> git2r::status()
working directory clean
> usethis::use_tidy_style()
Styling  11  files:
```

So, yeah, I think this has something to do just with `git2r`, and not how it's interacting with `usethis`. I'll redownload the development version of `git2r` and if the same issue persists I will raise it on their GitHub page. 

You can close this thread. Thanks!

**Comment by jennybc** [comment]
> I'll redownload the development version of git2r and if the same issue persists I will raise it on their GitHub page.

Perfect! git2r is getting a big overhaul internally, so it's helpful to report the glitches right now.
