### ISSUE TITLE
use_revdep() using revdepcheck

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#33]
Need to update `use_revdep()` to use https://github.com/r-lib/revdepcheck

**Comment by hadley** [comment]
I think maybe we can eliminate it? The defaults in revdepcheck are good enough that I just run the function.

**Comment by jimhester** [comment]
But you still need to write the report files to `revdep/README.md`, `revdep/problems.md` right? Or did I miss a function which does this all for you?

**Comment by hadley** [comment]
Oh it could create the email template
