### ISSUE TITLE
use_course() with non-Latin system language

### ISSUE THREAD

**Issue by chris-prener** [r-lib/usethis#330]
Unfortunately I cannot provide a reprex, but I was teaching with `use_course()` yesterday and had an issue with a student whose computer was set to use Chinese characters. She was unable to use `use_course()` - kept getting regex errors. My assumption was that this had to do with her having a non-Latin script language? We helped her manually download and extract the course repo instead. Not sure if this is to be expected, a bug, or an area for further work on the function?

For every other student, however, it was the smoothest start to a seminar I've ever had, so **thanks so much** for such an awesome little function!

**Comment by jennybc** [comment]
This is not a great shock, as I know I didn't tackle encoding explicitly in `use_course()`. I would love to see more info, just to speed up the diagnosis and fix. Is this an ongoing course and you could give me a bit more?

**Comment by chris-prener** [comment]
It isn't an ongoing course but there is a change I can get you some output anyway. What additional info would be most helpful to you?

**Comment by chris-prener** [comment]
I got a response from one student - both the `.Rmd` and and `.nb.html` files are included so you can see the output etc. Hope this helps!

[Archive.zip](https://github.com/r-lib/usethis/files/1944540/Archive.zip)

**Comment by jennybc** [comment]
The error originates from usethis's homegrown filename sanitization. I'm about to switch over to a function in fs for this, so perhaps it is done more correctly there and this will be fixed. We'll see ...

Thanks very much for the info, definitely helpful.

**Comment by jennybc** [comment]
Here's the what I see in `usethis.nb-1.html` in the zip archive above:

---

usethis Info
(四月 24, 2018)

Ensure Packages Installed
Hide
install.packages("devtools")
Installing package into 愼㸱愼㹥C:/Users/Administrator/Documents/R/win-library/3.4愼㸱愼㹦
(as 愼㸱愼㹥lib愼㸱愼㹦 is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.5.zip'
Content type 'application/zip' length 443954 bytes (433 KB)
downloaded 433 KB
package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\Administrator\AppData\Local\Temp\Rtmp8mYhTV\downloaded_packages
Hide
install.packages("usethis")
Installing package into 愼㸱愼㹥C:/Users/Administrator/Documents/R/win-library/3.4愼㸱愼㹦
(as 愼㸱愼㹥lib愼㸱愼㹦 is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/usethis_1.3.0.zip'
Content type 'application/zip' length 198035 bytes (193 KB)
downloaded 193 KB
package ‘usethis’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\Administrator\AppData\Local\Temp\Rtmp8mYhTV\downloaded_packages
Get System Info
Hide
devtools::session_info()
Session info ------------------------------------------------------------------------------------------------
 setting  value                                              
 version  R version 3.4.1 (2017-06-30)                       
 system   x86_64, mingw32                                    
 ui       RStudio (1.1.423)                                  
 language en                                                 
 collate  Chinese (Simplified)_People's Republic of China.936
 tz       America/Chicago                                    
 date     2018-04-24                                         
Packages ----------------------------------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.1   2017-06-30 local         
 compiler    3.4.1   2017-06-30 local         
 datasets  * 3.4.1   2017-06-30 local         
 devtools    1.13.5  2018-02-18 CRAN (R 3.4.3)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.1)
 graphics  * 3.4.1   2017-06-30 local         
 grDevices * 3.4.1   2017-06-30 local         
 knitr       1.17    2017-08-10 CRAN (R 3.4.2)
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.2)
 methods   * 3.4.1   2017-06-30 local         
 stats     * 3.4.1   2017-06-30 local         
 tools       3.4.1   2017-06-30 local         
 utils     * 3.4.1   2017-06-30 local         
 withr       2.1.0   2017-11-01 CRAN (R 3.4.2)
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.1)
Download ATLAS Week Lesson
Hide
usethis::use_course("https://github.com/slu-dss/atlasWeek/archive/master.zip")
Error in gsub(control_regex, alt, x) : 
  invalid regular expression '[-€-焆', reason 'Missing ']''
If you get an error messages with use_course, can you please paste it below?

The error message: Error in gsub(control_regex, alt, x) : invalid regular expression ‘[-€-焆’, reason ’Missing ’]’’

---

Screenshot of the lower part

<img width="787" alt="screen shot 2018-05-31 at 5 42 27 pm" src="https://user-images.githubusercontent.com/599454/40815256-10d5487e-64fa-11e8-8035-bb97e7066dad.png">

**Comment by jennybc** [comment]
Here is the Rmd source for the above, `usethis-1.Rmd`:

---

```
---
title: "usethis Info"
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output: 
  github_document: default
  html_notebook: default 
---

## Ensure Packages Installed

```{r}
install.packages("devtools")
install.packages("usethis")
```

## Get System Info

```{r}
devtools::session_info()
```

## Download ATLAS Week Lesson

```{r}
usethis::use_course("https://github.com/slu-dss/atlasWeek/archive/master.zip")
```

**If you get an error messages with `use_course`, can you please paste it below?**

The error message: Error in gsub(control_regex, alt, x) : invalid regular expression '[-€-焆', reason 'Missing ']''
```

**Comment by jennybc** [comment]
The code that originally threw this error did filename sanitization, which now relies on a function in fs. I am hopeful that the fs approach is more robust to variability in the system language. I'm closing this for now. Please report back if you continue to see problems.

**Comment by chris-prener** [comment]
Thanks @jennybc - will have some opportunities during the fall semester to test it out!
