### ISSUE TITLE
usethis CRAN needs git2r dev version

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#334]
Working on #320, I encounter an issue with one `git2r` function.

https://github.com/r-lib/usethis/blob/9ab0e799e2c092913f74a4e3d55f893e266d99cc/R/github.R#L148-L150

This was a change to take into account new behavior in dev version of `git2r`. However, `utils::head` throws an error with CRAN version of `git2r`.
``` r
testdir <- tempfile("testdir")
dir.create(testdir)
dir_path <- file.path(testdir, "testpkg")
packageVersion("git2r")
#> [1] '0.21.0'
packageVersion("usethis")
#> [1] '1.3.0'
usethis::create_package(dir_path, open = FALSE)
#> Changing active project to testpkg
#> <U+2714> Creating 'R/'
#> <U+2714> Creating 'man/'
#> <U+2714> Writing 'DESCRIPTION'
#> <U+2714> Writing 'NAMESPACE'
withr::with_dir(dir_path, usethis::use_git())
#> <U+2714> Initialising Git repo
#> <U+2714> Adding '.Rhistory', '.RData', '.Rproj.user' to './.gitignore'
#> <U+2714> Adding files and committing
repo <- git2r::repository(dir_path)
git2r::head(repo)
#> [d499db] (Local) (HEAD) master
utils::head(repo)
#> Error in x[seq_len(n)]: objet de type 'S4' non indiçable
unlink(testdir, recursive = T)
```
Created on 2018-04-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Moreover, in new dev version of git2r, `head.git_repository` is [deprecated](https://github.com/ropensci/git2r/commit/4602da9c22b7afeed323f081bf7c53064bb6a09e). A [new ](https://github.com/ropensci/git2r/commit/24019226b771b10b5ccda48e1fece5880cc6ddbe) `repository_head` should be used now.

``` r
testdir <- tempfile("testdir")
dir.create(testdir)
dir_path <- file.path(testdir, "testpkg")
devtools::dev_mode(on = TRUE)
#> Dev mode: ON
packageVersion("git2r")
#> [1] '0.21.0.9002'
packageVersion("usethis")
#> [1] '1.3.0'
usethis::create_package(dir_path, open = FALSE)
#> Changing active project to testpkg
#> <U+2714> Creating 'R/'
#> <U+2714> Creating 'man/'
#> <U+2714> Writing 'DESCRIPTION'
#> <U+2714> Writing 'NAMESPACE'
withr::with_dir(dir_path, usethis::use_git())
#> <U+2714> Initialising Git repo
#> <U+2714> Adding '.Rhistory', '.RData', '.Rproj.user' to './.gitignore'
#> <U+2714> Adding files and committing
repo <- git2r::repository(dir_path)
git2r::head(repo)
#> Error: 'head' n'est pas un objet exporté depuis 'namespace:git2r'
utils::head(repo)
#> Warning: 'head.git_repository' est obsolète.
#> Utilisez plutôt 'repository_head'
#> Voir help("Deprecated")
#> [7472f5] (Local) (HEAD) master
git2r::repository_head(repo)
#> [7472f5] (Local) (HEAD) master
unlink(testdir, recursive = T)
```

Created on 2018-04-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

This line of code is currently inside the code I am modifying for the PR I am working on to fix #320. 
I am thinking of fixing also this. Would you prefer another PR instead ? 

Moreover, shouldn't CRAN usethis sticks with git2r CRAN version behaviour (0.21.0) until next git2r version arrives on CRAN ? concretely, should I use `git2r::head` or `git2r::repository_head` ? 
This fix is need in order for `use_github` to work properly and be correctly tested (part of #322 that I also will try to contribute to)

Thanks for your direction.

**Comment by cderv** [comment]
Currently, I am handling it like this:
```r
  repo_head <- if (packageVersion("git2r") > "0.21.0") {
    ## New function to get head of a repo
    git2r::repository_head(r)
  } else {
    ## Old behaviour from <= 0.21.0
    git2r::head(r)
  }
  git2r::branch_set_upstream(repo_head, "origin/master")
```
to be fully compatible. With this, I can continue on the PR for `use_github`

Otherwise, `usethis` will have to import `git2r (> 0.21.0)` when a new version will be on CRAN.

**Comment by jennybc** [comment]
Thanks for the issue (and other issues/PRs)! I'm starting to look into all this now, as we will make a modest usethis release soon to change a test, in anticipation of a backports release. I definitely want to put out any obvious usethis/git/github/git2r fires.

So to clarify this point:
I am going to bump the minimum version of git2r here to 0.21.0 and we will step boldly into the future with  `git2r::repository_head(r)`.

**Comment by cderv** [comment]
Perfect thanks! I will rebase my PR then to conform with this fix.

**Comment by cderv** [comment]
PR has been updated.
