### ISSUE TITLE
Add R 3.3 to use_tidy_ci()

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#336]
Now that it's out

**Comment by jennybc** [comment]
Given that "r: release" will become 3.5 and "r: older" will become 3.4 (or it will once @jimhester does something), is it more that we need to add 3.3?

**Comment by hadley** [comment]
Yes, sorry, we need to add 3.3

**Comment by jennybc** [comment]
@jimhester If you think of it, will you ping me when r-travis makes the switch, and I'll do this then?

**Comment by jimhester** [comment]
The PR has been merged now, but I don't know when it will be deployed https://github.com/travis-ci/travis-build/commit/2ac7fabb7f837971b05bca1422cfb6e6a71fce2d

**Comment by jennybc** [comment]
OK I will prepare things here then.
