### ISSUE TITLE
`use_tidy_eval()` creates broken link

### ISSUE THREAD

**Issue by echasnovski** [r-lib/usethis#343]
`use_tidy_eval()` creates help page with the following sentence: "To learn more about tidy eval and how to use these tools, read <http://rlang.tidyverse.org/articles/tidy-evaluation.html>". Mentioned link is broken.

Moreover, there is no articles in the current `rlang` site.

**Comment by jennybc** [comment]
@hadley Is it known at this time what this should link to 🤔?

**Comment by hadley** [comment]
No 😭
