### ISSUE TITLE
use_template doesn't work as intended when inside a package

### ISSUE THREAD

**Issue by lwjohnst86** [r-lib/usethis#347]
I've tried to use a reprex but the effects are as intended. But when the `use_template` is inside of a package, it can't find the template... debugging it seems to point to `system.file()` using the location that the developing package is... and not being smart enough to know that "templates" is found in the "inst" folder. 

While in debug mode inside `usethis:::find_template`, running `system.file("inst", "templates", ..., package = ...)` correctly points to the template... but without the "inst" (as it currently is) is returns a character vector of length 0.

I struggled to understand this issue for several hours, and I don't really know what the correct effect `use_template` should have here... Not sure if this is a bug, or if it is an intended effect. Either way, just wanted to report it, since I can't actually use `use_template` because of this ... bug? Even though `use_template` is exactly what I am looking for... Oh well.

**Comment by ijlyttle** [comment]
Please forgive me for what may be a silly question, but have you installed the package from which you want to `use_template()`, i.e. hit the "Build & Install" button on the RStudio IDE?

**Comment by lwjohnst86** [comment]
Haha, yes, a silly question, but analogous to the "did you restart the computer" for IT :P Yes, its a package I am developing, so I've done all the "load_all", "build and install" things I could and it doesn't do anything. Problem even occurs on travis.

**Comment by jennybc** [comment]
I believe @ijlyttle is already using `use_template()` in a package (yes?), so maybe he can point at his source to help figure out if there's a difference in usage.

**Comment by ijlyttle** [comment]
Thanks for your good humor on the question 😀

@jennybc responded as I was typing - I am using the CRAN version of `usethis` and it is working OK for me. The package for which I `use_template()` is ghentr, and you can see my templates folder here: https://github.com/ijlyttle/ghentr/tree/master/inst/templates

Having installed the package (using `install_github("ijlyttle/ghentr")`), these work for me:

```
system.file("templates", "install_ghe.R", package = "ghentr")
usethis:::find_template("install_ghe.R", package = "ghentr")
```

Does this shed any light?

**Comment by ijlyttle** [comment]
I think it is doing the same as for you: 

```R
> system.file("templates", "install_ghe.R", package = "ghentr")
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ghentr/templates/install_ghe.R"
> usethis:::find_template("install_ghe.R", package = "ghentr")
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ghentr/templates/install_ghe.R"
> devtools::load_all() # while in your package
Loading ghentr
> usethis:::find_template("install_ghe.R", package = "ghentr")
Error: Could not find template 'install_ghe.R' in package 'ghentr'
```

I think you have wrapped your arms around the issue; but, as you know, this leads to the question "what is the intended behavior of `devtools::load_all()`?"  I am not qualified to answer that (but am interested nonetheless).

**Comment by jennybc** [comment]
This sounds like a question for @jimhester!

But why is anyone calling `find_template()`, which is not exported from usethis? I mean, it's find to do so interactively, but that can't ever be used in a package anyway.

**Comment by jennybc** [comment]
I still don't grasp how the use of usethis functions, via it's exported API, is breaking. Is it?

**Comment by ateucher** [comment]
I swear I saw this discussion somewhere else recently but I can't find it... The crux is that `devtools::load_all()` masks `system.file()` with it's [own version](https://github.com/r-lib/pkgload/blob/master/R/shims.r#L48), so for testing the package you have do it without running `load_all()`.

**Comment by ateucher** [comment]
Related (maybe this was the discussion I saw): https://github.com/r-lib/devtools/issues/1404

**Comment by lwjohnst86** [comment]
@jennybc its not the `find_template` that is being used, but the `use_template`, which called the find under the hood... which then leads to it breaking when using `devtools::test` or `devtools::load_all`. But it seems that it works as intended *outside of* the devtools environment, i.e. when you actually use the package. 

@ateucher yes, I think that is true, devtools masks `system.file`. Do you know how to bypass devtools masking it or at least forcing it to use see inside "inst/"?

**Comment by lwjohnst86** [comment]
@ateucher took a look at your package. How do you bypass the error when running `devtools::test`? I don't quite understand how what you do is different from what I am doing... So what am I doing then...? I'll report back as I work through it.

**Comment by ateucher** [comment]
@lwjohnst86 I don't bypass the error unfortunately. I just use `devtools::check()` instead - which is definitely a bit of a pain but I don't know if there's a workaround

**Comment by jennybc** [comment]
So devtools's shim for `system.file()` should really only apply to calls emanating from the package that is the primary target for `load_all()` (these packages written by @lwjohnst86 @ijlyttle and @ateucher) and not for calls in imported packages (usethis, in this scenario). I don't know if this behaviour could be achieved or is worth it 🤔 Again, a better question for @jimhester.

**Comment by jennybc** [comment]
Presumably this conversation has its roots in some of these same issues:
https://twitter.com/joranelias/status/918499094603055104

**Comment by jimhester** [comment]
https://github.com/r-lib/pkgload/issues/69 is ultimately the same issue. I think the only way to make `system.file()` truly robust would be to modify the definition in the base namespace entirely. We have so far avoided doing this.

**Comment by jennybc** [comment]
I conclude this is a regrettable aspect of using `devtools::load_all()` when developing a 2nd package that uses `usethis::use_template()`. But it seems that `use_template()` works as advertised and any fix for the development friction would have to happen elsewhere, i.e. in pkgload.

I'd be happy to review a PR that adds a small note about this to the `use_template()` docs, to reduce future head-scratching.

**Comment by jennybc** [comment]
A nice solution to this is now available in the dev version of fs:

Use `fs::path_package()` instead of `base::system.file()`.

https://github.com/r-lib/fs/commit/de56a640e874b642d002108d4bb3f67f89bf7843

This should eliminate the gotcha from "secondhand" use of `system.file()`.
