### ISSUE TITLE
Clarify code of conduct

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#352]
Make it a bit more clear that code of conduct applies to contributors to the package, not users. Maybe

> By participating in this project you agree to abide by its terms.

->

> By contributing to this project you agree to abide by its terms.

**Comment by hadley** [comment]
Or maybe just remove that sentence and point directly to code of conduct for clarification?

**Comment by batpigandme** [comment]
Rumour has it (read: RLadies Slack) that there's a difference between Contributor Covenant [1.0](https://www.contributor-covenant.org/version/1/0/0/code-of-conduct) and [1.4](https://www.contributor-covenant.org/version/1/4/code-of-conduct) that makes the former somehow more palatable — presumably something having to do with scope of enforcement. So, "downgrading" to 1.0 is another option.

Under the theory that "the project" could somehow be misinterpreted to refer to the R project, we could also add disambiguating language (contributing to this package (herein referred to as "The Project").

**Comment by hadley** [comment]
Yeah we need to clarify that participating != using and project != R project. I suspect we only need to do that on the README.
