### ISSUE TITLE
use_addins()

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/usethis#353]
Function to help setup the necessary steps for addins in a package. 

Would 

- Create a file at inst/rstudio/addins.dcf (if not already present)
- Add the 4 lines to file and populates the binding.

## Example

```
use_addins("addin_function")
```
(following lines added in "inst/rstudio/addins.dcf")
Name: --- please supply name ---
Description: --- please supply description ---
Binding: addin_function
Interactive: false

**Comment by moodymudskipper** [comment]
I came to ask for almost exactly that, except that I'd suggest : 

```
use_addin <- function(binding, name = binding, description ="", interactive = FALSE)`
```

And overwrite an addin specification that would have the same name or the same binding function.

**Comment by hadley** [comment]
We'd love to see a PR for this. I think it should be fairly simple, following a template from an existing function.

**Comment by apreshill** [comment]
I'm at tidyverse dev day and looking at this, if anyone wants to join me 🌮
