### ISSUE TITLE
Update codecov badge

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#36]
To use official codecov url which doesn't cause problems with CRAN.

**Comment by jimhester** [comment]
I think CRAN has fixed the pandoc issue anyway, I used the shield.io one initially because it matches the travis badge, whereas the codecov one does not.

**Comment by hadley** [comment]
It's still causing problems for me locally though.

**Comment by hadley** [comment]
Template:

```
[![codecov](https://codecov.io/gh/r-lib/objectable/branch/master/graph/badge.svg)](https://codecov.io/gh/r-lib/objectable)
```
