### ISSUE TITLE
any chance you'd consider exporting write_union?

### ISSUE THREAD

**Issue by cboettig** [r-lib/usethis#366]
Was just writing something to do this when I realized `usethis` must already be using such a function to update `.Rbuildignore` and `.gitignore` lists; and of course it does and looking at the source of `write_union` I can easily see your version is better engineered than mine.  Of course I could adapt my code, but since it would then be a modification / derivation from `usethis` I should be crediting `usethis` directly and switching my license to GPL-3, and possibly listing `usethis` authors as `ctb` in the DESCRIPTION (though I sometimes worry that is misleading without proper context).  All of which is obviously more cumbersome than if I could just call it as an exported function.  Of course I realize my weird case is hardly a strong general case for exporting this.

**Comment by jennybc** [comment]
What do you think @hadley?

**Comment by hadley** [comment]
I think we could do it - we just need to think through the function name.
