### ISSUE TITLE
Allow multiple scripts to be applied for the same git hook

### ISSUE THREAD

**Issue by noamross** [r-lib/usethis#368]
When I apply `use_git_hook()` to apply multiple scripts to the same git hook, I get the following error:

```
usethis::use_git_hook("pre-commit", system.file("templates", "readme-rmd-pre-commit.sh", package = "usethis"))
  usethis::use_git_hook("pre-commit", system.file("templates", "description-codemetajson-pre-commit.sh", package = "codemetar"))
```
```
Writing '.git/hooks/pre-commit'
Error: '.git/hooks/pre-commit' already exists.
```
I believe this is because git only allows one script per hook type.  A possible solution is for usethis to have a _general_ hook script which calls any other script one applies via `use_git_hook()`, or perhaps append the script.  In this case [`description-codemetajson-pre-commit.sh`](https://github.com/ropensci/codemetar/blob/master/inst/templates/description-codemetajson-pre-commit.sh), is very similar to the usethis README hook - it checks that `codemeta.json` is updated after `DESCRIPTION.`

CC @maelle @cboettig

**Comment by hadley** [comment]
This is starting to feel out of scope for usethis — the goal is to make it easy to add a simple hook, not to provide a complete framework for managing git hooks.
