### ISSUE TITLE
Avoiding committing unwanted files with use_git()

### ISSUE THREAD

**Issue by karawoo** [r-lib/usethis#378]
I love that `use_git()` automatically puts .Rhistory, .RData, and .Rproj.user in .gitignore. Because it automatically commits everything else I often end up with other unwanted files in my git history, such as the ever-irritating .DS_Store. Would it be possible to gitignore this file by default as well (though that's potentially confusing for non-Mac users), or maybe for the user to have more control over what gets added to the initial commit?

**Comment by jennybc** [comment]
I think the traditional way for Mac users to prevent the `.DS_Store` problem is to list that in a user-level global gitignore file (I know I do).

But perhaps `use_git()` should be reigned in somehow, yes. I have also found it overzealous at times.

**Comment by jennybc** [comment]
Proposal:

  * If not interactive, continue to commit all files.
  * If interactive, ask user to choose:
    - Stage & commit all of \<THESE FILES\> with \<THIS MESSAGE\>?
    - Don't make an initial commit.

@hadley do you have an opinion?

**Comment by karawoo** [comment]
I like this. When I use `use_git()` I always expect it to do just the `git init` part and forget that it does the commit too, so it would be nice to have that as an option.

**Comment by hadley** [comment]
I like your proposed interactive option
