### ISSUE TITLE
Make use_pkgdown configurable?

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/usethis#392]
Would you take a PR that implements configurable arguments to `use_pkgdown()`? I'd like to use usethis in pkgdown but these values change across different pkgdown usage scenarios.

Something like this:

```r
#' Use pkgdown
#'
#' [pkgdown](https://github.com/hadley/pkgdown) makes it easy to turn your
#' package into a beautiful website. This helper creates `_pkgdown.yml`
#' and `docs/` for you, and adds to `.Rbuildignore`
#'
#' @export
use_pkgdown <- function(pkg_file = "_pkgdown.yml", pkg_dir = "docs") {
  check_is_package("use_pkgdown()")
  edit_file(proj_path(pkg_file))
  use_build_ignore(pkg_file)

  use_directory(pkg_dir, ignore = TRUE)
}
```

**Comment by jennybc** [comment]
Sure, sounds good. When the PR comes (or now), it's possible @hadley will have an opinion about the argument names.

**Comment by krlmlr** [comment]
In a package I'm using an `inst/_pkgdown.yml` file, and now an empty `_pkgdown.yml` file is created via `use_pkgdown()` whenever I run `pkgdown::build_site()` . This feature seems very relevant for my use case.

**Comment by maelle** [comment]
would it make sense to also add an argument for the `pkgdown` theme?

**Comment by jayhesselberth** [comment]
IMO theme is a site tweak, probably not the purview of usethis.

**Comment by maelle** [comment]
Ok. I guess I was thinking of this as a configuration like when a package gets created with the default/chosen licence/maintainer name, but I understand if it doesn't make sense.
