### ISSUE TITLE
Review directory creation

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#393]
Suspect the lower level helper should be more like `write_*()` family, with a `quiet` argument. Something's not quite right, since it is hard to comply with Hadley's suggestion to get more messaging when `edit_file()` causes directory creation: https://github.com/r-lib/usethis/pull/389#discussion_r196299938

**Comment by jennybc** [comment]
Reflect on and probably rationalize the directory creation stance of `edit_file()` and `write_*()`.

**Comment by hadley** [comment]
I wondered about renaming `create_directory()` to `write_directory()` but it seemed like a bit of a stretch. But it does really belong with the `write_` family.
