### ISSUE TITLE
Add Hugo/blackfriday-markdown-friendly `use_tidy_thanks()`

### ISSUE THREAD

**Issue by batpigandme** [r-lib/usethis#403]
With the `.Rmarkdown` -> Markdown workflow for blogdown, the leading slashes for `@` render in the final result (see https://github.com/tidyverse/tidyverse.org/pull/177). I'm happy to make the necessary mod, just not sure whether to change the existing `use_tidy_thanks()`, or if we should add as an option, or new function entirely.

**Comment by jennybc** [comment]
I think we should accomplish this in the existing function, for sure. Let's just make it do what's best for our workflow and, if more flexibility is needed, the universe will tell us.
