### ISSUE TITLE
Document how to use use_course() with a folder on Google Drive

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#404]
Example: the 2018 StackOverflow survey:

``` r
usethis::use_course("https://drive.google.com/uc?export=download&id=1_9On2-nsBQIw3JiY43sWbrF8EjrqrR4U")
```

Link captured from here: https://insights.stackoverflow.com/survey

**Comment by Naareman** [comment]
Working on it.

**Comment by jennybc** [comment]
Done in https://github.com/r-lib/usethis/commit/1f8b2693a043a461145d4ae57a898074a0edda1a and related commits.

**Comment by jennybc** [comment]
For posterity, it is not possible to do this with a folder, the same way we can with a folder on DropBox or a GitHub repo. We believe you can just do this with a ZIP file stored on Drive.
