### ISSUE TITLE
default to not running spell check tests on CRAN servers

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/usethis#408]
I have been using `usethis::use_spell_check()` to check spellings. But this creates a test that is good to run locally but not suitable for CRAN. My package has been rejected twice because of the spelling tests with the following comment-

> why do you run spell check in the tests?
> 
> Spelling won't change, hence no need to run that daily on several 
> machines on CRAN. Just do it once prior to submission.
> 
> In tests, the idea is to check whether your package is calculating 
> correctly which may change due to changes on the operating systems, in 
> R, or package dependencies.

What can I do to not run this test on CRAN servers? I tried adding `tests\^spelling` to `.Rbuildignore` file, but the test still runs on CRAN. It iwill be good to have defaults that avoid this issue altogether. Because, as pointed out by CRAN members, spellings are not changing on a daily basis and this is a waste computational resources.

**Comment by batpigandme** [comment]
Pilfering this from Karl Broman's [R package primer](http://kbroman.org/pkg_primer/pages/tests.html):

> Computationally intensive code could also be placed in `\dontrun{ }` or `\donttest{ }`. Code in `\dontrun{ }` will never be run automatically; code in` \donttest{ }` will be run when a user calls example( ) but won’t be run with R CMD.

Looking at the code inside usethis itself, here's the internal setup.
https://github.com/r-lib/usethis/blob/1a04c1487eb094ce82ee1b0cb741f311113257bb/tests/spelling.R

**Comment by IndrajeetPatil** [comment]
Thanks, Mara. But I am still not sure how to prevent R CMD CHECK from running spell check tests. Should I do the following?
```
\donttest{spelling::spell_check_test(vignettes = TRUE, error = FALSE)}
```

**Comment by batpigandme** [comment]
I believe that would keep R CMD Check from running it, but it would also not run automatically for you. 
Hopefully someone else with more experience with this (so, anyone, really) will weigh in. Just thought Karl's tips were nice options!

**Comment by gadenbuie** [comment]
Borrowing from [testthat::skip_on_cran()](https://github.com/r-lib/testthat/blob/e2703ca962af0419f122eb348b7a216e8861e887/R/skip.R#L115-L123), try:

```r
if (identical(Sys.getenv("NOT_CRAN"), "true")) {
  spelling::spell_check_test(vignettes = TRUE, error = FALSE)
}
```

**Comment by jennybc** [comment]
cc @jeroen

**Comment by jeroen** [comment]
Thanks. I'll update this in the template that `spelling` generates. For existing packages you should just modify this in the `tests/spelling.R` file in the package that you are spell checking, which is what gets run during CMD check.

**Comment by jeroen** [comment]
Oh sorry I didn't mean to close this, that happened by accident due to the commit message.

**Comment by jeroen** [comment]
Spelling 1.2 (released today) will by default skip all auto checking on CRAN.

**Comment by jennybc** [comment]
@jeroen When I install spelling from CRAN, the spelling set up file still doesn't seem to include the condition re: the `NOT_CRAN` env var 🤔

**Comment by jennybc** [comment]
Oh now I see you backed out of that and implemented 'skip on cran' differently.
