### ISSUE TITLE
Allow directory creation with use_course

### ISSUE THREAD

**Issue by vnijs** [r-lib/usethis#410]
If would be handy if `use_course` got an addition argument to create (recursively) the directory specified in `destdir` if it doesn't exist already. This would be especially useful when multiple faculty are using the same server and want to give students a little nudge to put the project folders in a relevant class directory. On Windows or Mac it is easy for students to drag a folder where they want it. However, on this is a bit more work for students new to Rstudio server for example

What I have in mind would be to share something like the commands below with students to ensure that the project folder goes into a class directory. The directory `class124/session` would be created on the fly as needed. Of course the student could always change the `dest` if they want.

`usethis::use_course("https://link.to.a.project.folder2", dest = "~/class124/session1", create = TRUE)`
`usethis::use_course("https://link.to.a.project.folder2", dest = "~/class124/session1", create = TRUE)`

I could also add something like the below to the code to share with students but the additional attribute for `use_course` seems nicer ... at least to me

`if (!dir.exists("~/class124/session1")) dir.create("~/class124/session1", recursive = TRUE)`

**Comment by jennybc** [comment]
Perhaps `destdir` should behave similarly to `path` in `create_package()` and `create_project()`.

**Comment by vnijs** [comment]
I haven't used those functions before but based on the help file it seems like that would work really well.

```r
#' @param path A path. If it exists, it is used. If it does not exist, it is
#'   created, provided that the parent path exists.
```

**Comment by vnijs** [comment]
I'm looking into this again. A function similar to the below could be useful in `use_course`, `create_project` and `create_package` as they would use (almost) the same code. The main issue is that `create_directory` in `usethis` does not allow recursive creation of directories, even though the call to `dir_create` in `create_directory` is `dir_create(target_path, recursive = TRUE)`. Is recursive creation of directories something you are open to?

```
check_path <- function(path) {
  path <- user_path_prep(path)
  name <- path_file(path)
  check_not_nested(path_dir(path), name)
  create_directory(path_dir(path), name)
}
```

**Comment by jennybc** [comment]
Just added this to milestone for next release. Should be easy enough to sort out.

**Comment by jennybc** [comment]
The more I think about this, the less sure I am that I want to implement it. `use_course()` is deliberately a very dumb function. It seems like a simple addition, but recursively creating directories introduces new considerations and ambiguity about how things will unpack. The connections to  (or deliberate lack thereof) `create_*()` functions are also another wrinkle.

Two things you might want to consider:

  * `fs::dir_create()` gives you a nicer option for creating the directory. If the directory already exists, it's a silent no-op. In general, fs is rapidly becoming my favorite way to do anything with the file system.
  * Would you ever consider writing a thin wrapper around usethis, customized for your course usage? Then you could make a `use_course()` function that meets your needs without the burden I have re: being very general. You could hardwire base url, etc. and other niceties.

**Comment by vnijs** [comment]
Thanks for looking into this @jennybc. I'll use `fs::dir_create`

**Comment by vnijs** [comment]
This does indeed work very nicely @jennybc. See example below in case anyone else is looking for a "solution". You don't even need a wrapper. Thanks for the suggestion and, of course, thanks to @jimhester for the excellent `fs`.

```
usethis::use_course(
    "https://www.dropbox.com/some-dropbox-folder?dl=1", 
    dest = fs::dir_create("~/class124/session2")
)
```
