### ISSUE TITLE
Option to automatically run `use_data()` code in `/data_raw/` during BUILD and CHECK?

### ISSUE THREAD

**Issue by bestdan** [r-lib/usethis#414]
This is as much a package workflow question as a code question, so please forgive if I'm thinking about this the wrong way. 

I really like the transparency of the package creation process where R scripts to generate `/data/foo.rda` files live in `/data_raw/generate_foo.R`. This means another user can see exactly how the `data(foo)` object was generated. 

But, there seems to be a weakness in the process: if you don't run the updated script, the `data(foo)` object will be out of sync with the `/data_raw/generate_foo.R` file. 

One option (mimic'ing `testthat`) is to have all `data_raw/generate-{x}.R` files run during BUILD or CHECK. Perhaps like roxygen there can be some intelligence about only running files with changes (I'm getting our of my depth here.) 

So, this would be more an option for BUILD or CHECK commands, but I wanted to see what others thought first. 🤓🙇

**Comment by jennybc** [comment]
Based on my own data packages (e.g. gapminder, repurrrsive) and use of data in other packages (e.g. googledrive, googlesheets4), I only rebuild these data objects at very specific points in development and it is a manually-initiated process. I would definitely *not* want the scripts run automatically at build or check time.

In my own usage, this is pretty different from examples or tests, which you do want to exercise frequently.  But I could imagine other people have different needs or workflow around package data.
