### ISSUE TITLE
export proj_path

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#415]
For devtools I often need to construct the full paths to files inside a package, so it would be useful to have `proj_path()` exported so I wouldn't have to use something like `file.path(usethis::proj_get() ...)`.

**Comment by jennybc** [comment]
The party line on that in usethis itself is that end users are supposed to use rprojroot (or here) to build paths within a project. Do you think that also applies to you (or, more generally, developers of packages that use usethis) or is the situation different? If I export `proj_path()`, we'd put the same caveats as with `proj_get()`/`proj_set()` about being for internal/package use, not end-user script use.

**Comment by jimhester** [comment]
I see, I guess this makes sense, you can close this if you don't think it is worthwhile.

**Comment by jennybc** [comment]
I think it probably does make sense to export it, for use in other packages. It just comes with same risk / downsides as exporting `proj_get()` and `proj_set()`.
