### ISSUE TITLE
Adding a package in the setup of travis

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#420]
When I `use_travis` a .travis.yml is generated. Later when I add a package with `use_package` the package is added in the DESCRIPTION file but not in the .travis.yml file which might lead to errors in Travis CI.

Could `use_package`, check if .travis.yml or (appveyor.yml) file exists and add the new packages to the configuration files? 

This will speed up the CI, but I'm not sure if this is a direction you want to take. It could mean adding a new dependency `yaml` to edit the files, but I'm not sure how it stands with the new tic package.

**Comment by jennybc** [comment]
In general, taking on a new dependency in, say, Imports, should not impact your CI yaml files. Can you be more specific about the scenario you have in mind?

**Comment by maelle** [comment]
@llrs do you mean you sometimes add a dependency on say a GitHub package? The function you want to use in that case is `usethis::use_dev_package`.

This function does not, however, modify the CI config files, which was maybe what @llrs would like to see? I've wondered about this too but I think @krlmlr told me that modifying YAML files could lead to losing comments in them?

**Comment by llrs** [comment]
@jennybc When I add some packages from Bioconductor I usually add them to the .travis.yml file so that I have them following:

```
cache: packages
r_packages:
  - devtools
  - covr
  - roxygen2
bioc_packages:
  - org.Hs.eg.db
  - reactome.db
  - BiocCheck
  - BiocStyle
before_install:
  Rscript -e 'update.packages(ask = FALSE)'
```
But maybe the problem is the before_install instruction, but I added that in reference to this issue in travis https://github.com/travis-ci/travis-ci/issues/6850. If this is the case, close the issue (and I will test it on my end if its needed).
Anyway, as @maelle says, I would like to add the package to the .travys.yml file when using use_package (I don't add dependencyes on a GitHub package usually, so I don't use `usethis::use_dev_package`). If modifying it would remove the comments, then this issue could be closed too.

Thanks for your time, and sorry for bothering you.

**Comment by jimhester** [comment]
I would not recommend using either `r_packages` or `bioc_packages` for package dependencies. If you can simply add them as normal dependencies in your `DESCRIPTION` and they will be installed appropriately by travis.

The one thing you will need to do is make sure your package has a `BiocViews:` field, this is required if you were planning to submit your package to Bioconductor, and it is also how devtools / remotes knows to look for the dependencies in the Bioconductor repositories. So your travis file should then need only

```yaml
language: r
cache: packages
```

**Comment by jimhester** [comment]
Also note using `r_packages:` or `bioc_packages:` will definitely _not_ speed up the CI, when these fields are used the packages are always installed on every build regardless if they already exist in the package cache.

**Comment by llrs** [comment]
Oh, thanks @jimhester for clarifying this issue. Indeed on the DESCRIPTION file of the package I am developing doesn't have a BiocViews field (yet).
