### ISSUE TITLE
Feature Request: use_readme_rmd specifies a different fig.path for R pacakges

### ISSUE THREAD

**Issue by njtierney** [r-lib/usethis#422]
Hello!

Thank you again for writing `usethis`! I use it almost every day.

Using `use_readme_rmd()` creates the following YAML and setup code chunk:

````
---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
````

However when using this in an R package, I I borrowed this trick from the [tidyverse packages](https://github.com/tidyverse/ggplot2/blob/master/README.Rmd) to change the `fig.path` to place the figures inside a `man/figures/` folder, like so: 

````
```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-"
)
```
````

I was wondering if it would be possible for this to be the default when using `use_readme_rmd()` - perhaps there could be a way for it to sense if it is inside an R package, and then change the `fig.path` accordingly?

Just an idea!

**Comment by gadenbuie** [comment]
Hi @njtierney -- I think this is how usethis is set up already. I remember noticing this as a one of the cool details of using `use_readme_rmd()`, which should [check if it was run inside a project](https://github.com/r-lib/usethis/blob/master/R/readme.R#L28) and if so use the the `package-README` template which has the [setup chunk you described](https://github.com/r-lib/usethis/blob/master/inst/templates/package-README#L8-L15).

````
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
````

I think package "status" is determined by presence of a DESCRIPTION file, so maybe you ran `use_readme_rmd()` before creating DESCRIPTION?

**Comment by njtierney** [comment]
Ah, indeed it does! I just checked now and that works great.

Thanks for pointing that out, @gadenbuie :)
