### ISSUE TITLE
Add setup code for CI with tic

### ISSUE THREAD

**Issue by krlmlr** [r-lib/usethis#430]
The [_travis_ package]() communicates with the Travis API v3 and supports, among others, enabling and disabling a repository, and adding public or private environment variables. The [_tic_ package](https://ropenscilabs.github.io/tic/) implements a CI-agnostic DSL for defining CI runs. Ultimately, most of the logic from Travis's [`r.rb`](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb) could be provided by _tic_.

Currently, the setup code for adding _tic_ support to a package lives in _travis_. It consists of:

- Code to enable the repo on Travis
- Code to add an SSH key as encrypted environment variable and add a deploy key to GitHub, to enable automatic deployment from Travis
- Template files for `tic.R` for various use cases (package checks, blogdown, bookdown, ...)
- Template files for _tic_-style `.travis.yml` and `appveyor.yml` (same for all project types)

I'd like to suggest to move this setup code to _usethis_, and provide an alternative to `use_travis()` and `use_appveyor()` that would set up this "new-style" CI. The old functions would remain until _tic_ becomes the recommended way for CI in R.

Even if we only wanted to use the "enable Travis" feature, work must be done because currently _travis_ imports _usethis_.

Existing PR: #411.

Reference: https://github.com/ropenscilabs/travis/issues/73

CC @hadley @karthik @pat-s.

**Comment by hadley** [comment]
Given that tic is not yet on CRAN, and we're generally happy with our travis workflow, I'm going to close this issue for now.
