### ISSUE TITLE
Review use_description()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#432]
At the time of writing, `use_description()` is the only function besides `use_git_hook()` that calls `write_over()` directly. Now that I know more about the desc package, I feel like I should review `use_description()` and helpers to see if we can delete code here and instead rely on desc more.

**Comment by hadley** [comment]
I read through the code, and I think it's fine — we're already using desc for most of the work, but because this is wholesale replacement of the file (rather than piecewise modification of a few fields), I think the use of `write_over()` is appropriate.
