### ISSUE TITLE
Submit v1.4.0 to CRAN

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#433]
* [x] Run manual tests and generally give git2r stuff a workout
* [x] `devtools::document()`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] Draft blog post, open PR, request review
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [x] Bump version (in DESCRIPTION and NEWS)
* [x] `devtools::check_win_devel()` (again!)
* [x] `devtools::submit_cran()`
* [ ] `pkgdown::build_site()` ⬅️ revise the index! #363 
* [x] Approve email
* [x] Tag release
* [x] Bump dev version
* [x] Check binaries available on CRAN
* [ ] Revise blog post and merge
* [ ] Tweet

Template (sort of) from <https://github.com/r-lib/usethis/issues/338>

**Comment by hadley** [comment]
Closing this since the release happened some time ago.
