### ISSUE TITLE
Error: [EXDEV] Failed to move '/tmp/RtmpnYxFHP/usethis-use-course-107f74b33e75'to '/home/rstudio/Desktop/usethis-example.zip': cross-device link not permitted

### ISSUE THREAD

**Issue by vnijs** [r-lib/usethis#438]
In `usethis` 1.3.0 the command below works fine. However, in `usethis 1.4.0` it throws an error. In my example, this happens, I believe, because /home/rstudio/Desktop is mounted on a different partition than /tmp. /tmp is "in" a Docker container but /home/rstudio is linked to the home directory on the users host system. As mentioned, this worked fine previously with version 1.3.0

This may be a bit tricky to reproduce of course unless you have, and can mount, different partitions. However, if you have docker installed, you will be able to reproduce by running the bash script linked below that will pull a docker image and start-up rstudio in your browser if you press 2 on the terminal menu.

Mac: `https://github.com/radiant-rstats/docker/blob/master/radiant/launch-mac.command`
Windows: `https://github.com/radiant-rstats/docker/blob/master/radiant/launch-windows.sh`
Linux: `https://github.com/radiant-rstats/docker/blob/master/radiant/launch-linux.sh`

Then run the `usethis::use_course` command to see the error ...

```
usethis::use_course("https://www.dropbox.com/sh/0dmcr2xsphtn1ha/AADsrYsi8KBkddWx_B-aQbi1a?dl=1")
```

**With usethis 1.4.0:**

```
> usethis::use_course("https://www.dropbox.com/sh/0dmcr2xsphtn1ha/AADsrYsi8KBkddWx_B-aQbi1a?dl=1")
 Downloaded: 0.09 MB  
A ZIP file named:
  'usethis-example.zip'
will be copied to this folder:
  '/home/rstudio/Desktop'
Prefer a different location? Cancel, try again, and specify `destdir`.

Is it OK to write this file here?
1: Definitely
2: Negative
3: Absolutely not

Selection: 1
✔ Downloaded ZIP file to '/home/rstudio/Desktop/usethis-example.zip'
Error: [EXDEV] Failed to move '/tmp/RtmpnYxFHP/usethis-use-course-107f74b33e75'to '/home/rstudio/Desktop/usethis-example.zip': cross-device link not permitted
```

**Comment by jennybc** [comment]
I suspect you can narrow this down to a minimal reprex involving `fs::file_move()`, as I think your observations re: works with v1.3 and does not work with v1.4 is likely to boil down to the switch to fs for all file system work.

Will you try?

**Comment by jennybc** [comment]
cc @jimhester

**Comment by vnijs** [comment]
Your insight seems correct @jennybc. See output below.

```
> fs::file_create("/tmp/test.txt")
> cat("example file", file = "/tmp/test.txt")
> fs::file_move("/tmp/test.txt", "/home/rstudio/test.txt")
Error: [EXDEV] Failed to move '/tmp/test.txt'to '/home/rstudio/test.txt': cross-device link not permitted
```

**Comment by jimhester** [comment]
https://stackoverflow.com/questions/43206198/what-does-the-exdev-cross-device-link-not-permitted-error-mean is the equivalent error for libuv, so essentially the rename system call does not support this.

We could probably provide a fallback to copy the file and then delete the old file in this case, as users would likely expect this to work with an error.

**Comment by jennybc** [comment]
@vnijs Is this setup something that would be common in educational settings? I'm trying to understand the urgency vis-a-vis the `use_course()` function and start of the academic term. I could do something in usethis and submit another version before the September 1 - 9 CRAN black out begins. But I should plan that soon.

**Comment by jimhester** [comment]
@jennybc for fs

**Comment by vnijs** [comment]
@jennybc This issue will likely apply to most linux based system as home directories are commonly on a different partition than /tmp. I tested with **Rstudio Server Pro** and **Rstudio Cloud** and the code example below produces the same error on both. Anything that uses Docker in the cloud or on self-managed hardware will likely also have the same issue.

My work-around is to load `usethis` 1.3.0 in the docker container but, like I said, this could impact a fair number of folks that want to use `usethis` with Rstudio Server based products for classes or workshops.

```
> install.packages("fs")
> fs::file_create("/tmp/test.txt")
> cat("example file", file = "/tmp/test.txt")
> fs::file_move("/tmp/test.txt", "~/test.txt")
Error: [EXDEV] Failed to move '/tmp/test.txt'to '/home/rstudio-user/test.txt': cross-device link not permitted
```

**Comment by vnijs** [comment]
Not sure if I understood this correctly @jimhester: "as users would likely expect this to work with an error". But I think users would prefer it to work **without** an error message :)

**Comment by jimhester** [comment]
Yes, it was a typo

**Comment by jimhester** [comment]
This should now be fixed in devel fs. I tested it on rstudio.cloud and your example now seems to work fine. Thanks for the simple reproducible example @vnijs!

**Comment by vnijs** [comment]
Nice! Works for my setup as well. Thanks @jimhester. FYI The example was @jennybc's idea.

Note: I was not able to install from github as a regular user. Had to use `sudo`. Not sure if this is an issue however. See messages below.

```
> devtools::install_github("r-lib/fs"

...

/bin/sh: line 3: ./configure: Permission denied
make: *** [libuv/Makefile] Error 126
ERROR: compilation failed for package ‘fs’
* removing ‘/home/rady/oce/01/vnijs/R/x86_64-redhat-linux-gnu-library/3.5/fs’
* restoring previous ‘/home/rady/oce/01/vnijs/R/x86_64-redhat-linux-gnu-library/3.5/fs’
Installation failed: Command failed (1)
```

**Comment by jennybc** [comment]
@jimhester What do you think re: submitting fs rather soon to include this? I'd like `use_course()` to work in the settings @vnijs describes, so I think either usethis or fs should go for a patch release. We could also put a workaround into usethis, if you don't want to update fs right now.

**Comment by jimhester** [comment]
I can do a fs release, would next week be fine?

**Comment by jennybc** [comment]
Sure! I will consider this successfully thrown over the wall to you then 😄

**Comment by jimhester** [comment]
Just an update, fs 1.2.6 which fixes this is now on CRAN.
