### ISSUE TITLE
VignetteBuilder DECSRIPTION field split over lines is not recognized

### ISSUE THREAD

**Issue by jackwasey** [r-lib/usethis#439]
I have a package DESCRIPTION which, after using `desc` package to reformat, contains:
```
VignetteBuilder:
    knitr
```
In this case, using
```
usethis:::use_description_field("VignetteBuilder", "knitr")
```
or, as I originally did:
```
use_vignette("Medical Twitter strategies used by other authors")
```
gives the error:

> Error: VignetteBuilder has a different value in DESCRIPTION. Use `overwrite = TRUE` to overwrite.

Furthermore, the error message refers to an argument to `usethis:::use_description_field` which is not passed through by `use_vignette` and thus it is not possible to act on this by doing `use_vignette("name", overwrite = TRUE)`

**Comment by gaborcsardi** [comment]
@hadley yeah, but this is relatively simple, and there are not too many comma separated fields. So maybe usethis could just handle this?
