### ISSUE TITLE
Make the "tidy DESCRIPTION" lifestyle the default or something one can opt in to

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#443]
I personally want this: (re-)tidy DESCRIPTION every time usethis touches it. Literally, call `use_tidy_description()`.

**Comment by jennybc** [comment]
@hadley Opinion?

**Comment by hadley** [comment]
Should be optional I think - it's a bit aggressive if you're used to other styles

**Comment by hadley** [comment]
It just remains to figure out how to activate this. Maybe just a global option?

**Comment by hadley** [comment]
To record this, I think we'll need to create a new file something. Maybe `_usethis.yml`?

**Comment by jennybc** [comment]
I don't care enough about this to implement it. I'll just call `use_tidy_description()`.
