### ISSUE TITLE
Code of conduct's clipboard contains unwanted symbols

### ISSUE THREAD

**Issue by jmgirard** [r-lib/usethis#447]
When calling `use_code_of_conduct()` or `use_tidy_github()`, the following text is output to the console: 

> Please note that the 'package-name' project is released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By contributing to this project, you agree to abide by its terms.

The package-name part is attractively styled in a blue color. However, the code that gets copied into the clipboard and to be pasted into the README includes some weird symbols that I assume come from the color command. 

> Please note that the [34m'package-name'[39m project is released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By contributing to this project, you agree to abide by its terms.

**Comment by jennybc** [comment]
Yeah this needs to strip ANSI escapes. I've seen this myself but forgot to open an issue. Thanks.

**Comment by hadley** [comment]
I think this should happen in `code_block()`
