### ISSUE TITLE
Some usethis messages unreadable with dark terminal theme

### ISSUE THREAD

**Issue by s-fleck** [r-lib/usethis#45]
I am using Rstudio nightly Version 1.1.305 on a recent Kubuntu version with a dark theme. Some of the message text of `use_data-raw()` and similar functions is completely unreadable on my machine.

![usethis_dark_theme](https://user-images.githubusercontent.com/9320338/29238448-1b89112e-7f36-11e7-97b6-cca113f4d12a.png)

**Comment by hadley** [comment]
@gaborcsardi do we have any way around this? I'm using `message()` and applying `crayon::black()` to get rid of the default red colouring in RStudio.

**Comment by s-fleck** [comment]
I thought about this some more, and maybe this should not be a bug for usethis but a feature request for crayon. I am not note sure if this is feasible / desired, but if crayon stored its color values in an option one could easily do something like `options(crayon.black = "#ffffff")`. This would make it trivial to create third party "theme" functions/packages for crayon.

**Comment by gaborcsardi** [comment]
@s-fleck `crayon` is just the basic machinery, so it will probably not do that.

We just need to have two themes, one for light background, one for dark. In RStudio we can use the API to auto-detect the better theme, otherwise the user can just select it manually. 

The other way would be to come up with colors that look good on both, but this seems pretty hard, maybe impossible.

**Comment by s-fleck** [comment]
If you go the way of package-specific theming, there should at least be a tidyverse-wide approach. E.g. the same issue comes with colformat and NA values, and likely other packages as well (haven't tested that many yet).

I understand that you don't want theming functionality im crayon, and it would be pretty awkward to redefine black as white like in my example. Maybe one could create a package that goes between crayon and tidyverse and provides something like coltheme::color1(), coltheme::color2(), etc... which can be redefined easily (think function-factory).

**Comment by gaborcsardi** [comment]
YEs, that's exactly what I meant. A `clithemes` package.

**Comment by s-fleck** [comment]
I have a long weekend coming up and could prototype something, should be pretty simple.

**Comment by hadley** [comment]
I think an easy work around would for me to just `cat()` rather than calling `message()`

**Comment by gaborcsardi** [comment]
Yeah, for this particular issue, maybe, but in general it would be nice to have theming with two default themes.

**Comment by hadley** [comment]
Yeah, agreed and we definitely need common conventions across r-lib/tidyverse.

**Comment by s-fleck** [comment]
I quickly hacked together a color theme wrapper around crayon (I wanted to create something similar for one of my packages anyways). I'd appreciate any nudges in the right direction; especially the ui-element naming scheme isn't very optimal yet.

https://github.com/s-fleck/colt

**Comment by ha0ye** [comment]
Any status updates? I'm encountering this issue in weecology/portalr#201, h/t @dill

Additional thoughts:
Would it also be reasonable to select some colors from the RStudio theme that would work well (in addition to or instead of detecting a light/dark theme?).

**Comment by jennybc** [comment]
We have reason to hope that something good will happen re: this on the RStudio front. We are working on some upgrades to our UI styling toolkit and will move it out of usethis and into a place (probably cli).
