### ISSUE TITLE
use_description to edit DESCRIPTION

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#450]
Not sure this is even worth an issue 😺 

I intuitively thought that using `use_description` would open DESCRIPTION (which I wanted to), but it seems that contrary to `use_r`, this function can only _create_ DESCRIPTION, not _open_ it. Any reason for this? Would it make sense to also be able to open DESCRIPTION with `use_description`?

**Comment by jennybc** [comment]
Hmn... it's more `use_r()` that violates the pattern here. In general, it's the `edit_*()` family that opens said file for editing.

**Comment by maelle** [comment]
Thanks!
