### ISSUE TITLE
Exporting styling functions from usethis?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/usethis#456]
I love the beautiful formatting of `usethis` messages 😻 and I would love to do the same for messages in my package.  I can use the internal functions shown in the image below, but the `R CMD CHECK` complains with the `:::` operator, so I was wondering if there was a possibility to export these functions. 

![image](https://user-images.githubusercontent.com/11330453/45131142-a1d38600-b159-11e8-89b0-be694c172a4a.png)

**Comment by hadley** [comment]
Duplicate of #308
