### ISSUE TITLE
use_appveyor could add appveyor.yml to git?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/usethis#458]
Maybe?

**Comment by hadley** [comment]
To git, or git ignore?

**Comment by gaborcsardi** [comment]
git

**Comment by hadley** [comment]
But `use_travis()` doesn't? 

In fact, I'd rather close this with the assumption that we'll be moving off appveyor (and onto travis for windows) in the near future.

**Comment by gaborcsardi** [comment]
Well, then `use_travis()` could do that as well? I guess all functions that add files that belong to the repo?

**Comment by hadley** [comment]
For some reason, that just feels risky to me. I'm going to close for now, but I'll keep contemplating it.

**Comment by gaborcsardi** [comment]
Well, if the project is a git repo, and we are creating files that belong there, I don't think there is much risk. Also, we would `git add`, but not `git commit`, and we would also print it that we added it to git. Think about it. :)

**Comment by jennybc** [comment]
I'm starting to think we should follow the approach in `use_git()` in more places:

https://github.com/r-lib/usethis/blob/8b2b4482a65e90ce7fc1929043d9274f80d576ee/R/git.R#L23-L33

**Comment by gaborcsardi** [comment]
IDK, personally, I would not commit, even if interactive(). I might want to
edit or group the changes, or a different branch.

But adding seems ok, because why would you add files to the project w/o
adding them to the repo?

**Comment by jennybc** [comment]
Yeah I'm with you @gaborcsardi. I generally _don't_ want usethis committing for me. But it's welcome to ask!

We're trying to balance what you and I want with people who appreciate more scaffolding, I think.

**Comment by hadley** [comment]
Oooh you just meant add to the index, and not commit.

**Comment by gaborcsardi** [comment]
@jennybc I guess this is highly subjective, but my problem with the linked code is that it is all or nothing. It either does nothing, or does both add & commit.

Well, I basically _always_ want to add, and _almost never_ want to commit (as is), so the cited code is not very useful for me.

But again, this is subjective, so feel free to choose a different default.

**Comment by hadley** [comment]
I'm going to close this and re-open a new issue without all the discussion
