### ISSUE TITLE
Don't mess with authors in use_tidy_description()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#460]
@hadley is not a fan of what this does to an existing authors field

https://github.com/r-lib/usethis/commit/bc82105b19c0a9d4affef5c462d04fc4bdfdf55e#diff-56a16d2c6c9bf71f93d113013ed8ceacR126

This is not desirable:

```
Authors@R: 
    c(person(given = "Hadley",
             family = "Wickham",
             role = c("aut", "cre"),
             email = "hadley@rstudio.com"),
      person(given = "Robby",
             family = "Shaver",
             role = "aut"),
      person(given = "RStudio",
             role = "cph"))
```

**Comment by jennybc** [comment]
This feels like a battle that is not worth fighting. Or fighting in a different way. I propose we impose the desired style for `Authors@R` on desc's notion of normalizing a DESCRIPTION file.

**Comment by hadley** [comment]
That style makes me sad though :(

**Comment by jennybc** [comment]
So that's a vote for changing what desc does right? 😁

It just feels fiddly to accept some of desc's normalization and reject other parts.

**Comment by hadley** [comment]
Oh I see what you mean; yes we should change this in desc, not here.

**Comment by jennybc** [comment]
Handling this now in https://github.com/r-lib/desc/issues/78
