### ISSUE TITLE
create_tidy_package() to create public package with tidyverse/r-lib convensions

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/usethis#461]
I am not sure if this is possible to do in one go, as the user might need to edit files, or maybe run git between the steps, we'll see. Order might change later.

1. `create_package()` 
1. `use_tidy_description()`
1. Add empty `R/package.R` file
1. `use_git()`
1. `use_github()`
1. `use_testthat()`
1. Add empty `tests/testthat/test.R` file.
1. `use_mit_license()`
1. `use_readme_rmd()`
1. `use_news_md()`
1. `use_tidy_ci()`
1. `use_appveyor()`
1. `use_tidy_contributing()`
1. `use_tidy_coc()`
1. `use_lifecycle_badge()`
1. `use_roxygen_md()`
1. `use_cran_badge()`
1. `use_coverage()`
1. Knit `README.md`
1. Add all newly created files to  git, commit, push.

The badges can be part of some `use_tidy_readme_rmd()`, because currently they need manual copy and paste.

**Comment by gaborcsardi** [comment]
Just tried it, mostly works. Some steps are manual, we can fix that with a tidy README.Rmd template.

**Comment by jennybc** [comment]
I think this might be best as a "doctor" or reporting function, i.e. it reports how much of this has been done and reminds of relevant functions for the un-done parts.

**Comment by gaborcsardi** [comment]
That would be great as well, but I would very much like a version that just did everything....

**Comment by hadley** [comment]
I guess I tend to run them more over time - i.e. I don't run `use_test()` until I write the first test, and I don't run `use_news_md()` until after the first release. But I don't have any objection to setting up from the very beginning.

**Comment by jennybc** [comment]
Perhaps the point is that is should be very resilient to re-application, i.e. it does something sensible *de novo* but can also cope when the work is partially done.

**Comment by hadley** [comment]
Yeah, and ideally you should be able to run it on a package that you created two years ago and bring it up to spec for today.

**Comment by gaborcsardi** [comment]
Yeah, some things you can do on demand, like tests. But others I just tend to forget sometimes...

**Comment by hadley** [comment]
See also the checklist: https://github.com/tidyverse/readxl/issues/241#issue-204430214

**Comment by hadley** [comment]
I think we need two pieces:

* `create_tidy_package()` which calls `create_package()` and then the functions listed above

* `use_tidy_standards(cur = "1.0.0")` which would create an issue checklist with the new functions you need to run.
