### ISSUE TITLE
conspicuous_place may get the "wrong" Desktop

### ISSUE THREAD

**Issue by vnijs** [r-lib/usethis#466]
FYI On newer Windows machines there may be multiple Desktop folders. One in `C:/Users/username/Desktop` and one in `C:/Users/username/OneDrive/Desktop`. It seems that `C:/Users/username/OneDrive/Desktop` is they one that is shown on screen. I have no idea if it is possible to determine programmatically which `Desktop` folder is actually being shown on screen.

I don't have a PC with this setup but a bunch of my new students do. `usethis::use_course` extracts to `C:/Users/username/Desktop` by default but it would be more "conspicuous" if it could exact to the Desktop shown

**Comment by jennybc** [comment]
🙄

(at this situation, not you)

**Comment by vnijs** [comment]
I completely agree 🙄That said, I expect the following would address this sufficiently. Can't test it myself unfortunately.

```
conspicuous_place <- function() {
  Filter(dir_exists, c(
    path_home("OneDrive/Desktop"),
    path_home("Desktop"),
    path_home(),
    path_home_r(),
    path_tidy(getwd())
  ))[[1]]
}
```

**Comment by vnijs** [comment]
@jennybc What do you think of the suggested "fix"?

**Comment by jennybc** [comment]
I think we need really good evidence that it works.

**Comment by hadley** [comment]
@vnijs one way to supply said evidence would be to do some googling to find the MS docs for this feature.

**Comment by vnijs** [comment]
@hadley I did do quite a bit of searching after posting this issue but didn't find much that I thought could lead to a clean solution. See e.g., link below:

https://stackoverflow.com/questions/634142/how-to-get-a-path-to-the-desktop-for-current-user-in-c

I work on macOS and I don't have a (recent) windows system so checked with our IT department as well in September. Part of the reply is shown below. Based on that response I'm not hopeful of a general solution at this point. Even if a OneDrive/Desktop folder exists I'm not sure how to determine if that folder is actually "shown" when the user views their Desktop.

I teach January - March and will use `usethis` so I expect to have some more direct experience with the issue in the near future. I will report back if I learn anything useful

**IT response:**

"The fact is the path to OneDrive is not constant and changes based on user preference and if they have both a personal and business one drive installed, so it will not be easy for your to figure out programmatically. If they turn it off it reverts to the standard local paths and when the turn it back on it changes back."

**Comment by hadley** [comment]
R code should look something like:

```R
utils::readRegistry(
  "Software/Microsoft/Windows/CurrentVersion/Explorer/User Shell Folders",
  hive = "HKCU"
)
```

**Comment by jennybc** [comment]
I'm going to close this as there is currently no solution that is clearly a net positive.

@vnijs Feel free to open a new issue if you get new and actionable info.
