### ISSUE TITLE
Do everything we can to help macOS users to NOT commit .DS_Store

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#469]

**Comment by ha0ye** [comment]
Make or append to a global .gitignore file, then do the appropriate Git config command? Happy to work on a PR if desired.

**Comment by batpigandme** [comment]
FWIW, this is how it's implemented in course.R
https://github.com/r-lib/usethis/blob/b58920ad6eb16fbf7d19b6f40f1e82c43d8dbc23/R/course.R#L271-L278

**Comment by jennybc** [comment]
The `course.R` code is about unpacking zip archives, not git stuff.

We do have existing facilities for editing / adding to gitignore files. This issue if mostly to remind me to figure out how best to offer macOS users some help on this. I'm just not sure where to stick it.

**Comment by batpigandme** [comment]
(>ლ) _whoops!_ Sorry.

**Comment by ha0ye** [comment]
I think it's probably safe to add .DS_Store into the `use_git` function. It's handy for non-Mac users, too, as I can imagine a scenario where someone creates a repo, and then a Mac user contributes to it, uses `git add .`, and inadvertently commits a bunch of `.DS_Store` files.

Modifying global .gitignore through `use_git_config` would also be a nice feature to have, but as that function currently doesn't touch those files, maybe that should be left alone.

**Comment by hadley** [comment]
I have it in my `~/.gitignore`. 

If we start touching that file, we should also add `.Rproj.user` to it.

**Comment by hadley** [comment]
And also `.Rhistory` (since that's an easy way to accidentally share credentials).

What we call such a function? It's a bit different because it acts globally, but I think it's a safe operation to perform.

**Comment by jennybc** [comment]
It feels like we’re developing a notion of a system “health check” and this is a check specific to git and macOS.

**Comment by hadley** [comment]
Maybe we could call it `vaccinate_git()` (we can't use `immunise()` for hopefully obvious reasons)
