### ISSUE TITLE
use_lintr_test()

### ISSUE THREAD

**Issue by hafen** [r-lib/usethis#470]
To help enforce code style in my organization, I like to add a unit test for code style in my packages and encourage others in my organization to do the same. Encouragement is best acted on when the task is made trivial, so it would be nice if usethis had a `use_lintr_test()` function which adds a file to the package `tests/testthat/test-lintr.R` with the following contents:

```r
if (requireNamespace("lintr", quietly = TRUE)) {
  context("lints")
  test_that("Package Style", {
    lintr::expect_lint_free()
  })
}
```

I'd be happy to issue a PR with this as I've already implemented it elsewhere.

I'm also happy to be shot down on this one if it's deemed not a broad enough use case or not an encouraged practice or if there's already something else out there to achieve this.

**Comment by hadley** [comment]
This seems a bit too specialised for me; it seems more appropriate for a company specific package.
