### ISSUE TITLE
use_this in the project .Rprofile

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#471]
I would expect that `use_usethis` or other functions that need action on the .Rprofile would open the local .Rprofile (`edit_r_profile("project")`) instead of the [`edit_r_profile("user")`](https://github.com/r-lib/usethis/blob/master/R/use_this.R#L7))

**Comment by jennybc** [comment]
I think user-level `.Rprofile` makes the most sense as a general default. Probably uniformly?

But, yes, it is conceivable that this should happen:

  * If an active project can be established and
  * it contains a project-level `.Rprofile`
  * default to that.

But I'm not sure I like having different default behaviour depending on the working directory.

Are you a heavy user of project-level `.Rprofiles`? I feel like that is fairly rare.

**Comment by llrs** [comment]
I only started when I started to use usethis. Before that I only used it for setting .liPaths, printing the session_info at the end of a script, and recently for setting options like Ncpus.

However, I have several projects, some of them are packages and some others are analysis.
I ran into some issues with an analysis pipeline after I added the conflicted package in my user folder. Probably the issues came from previous bad habits.

**Comment by jennybc** [comment]
If `.Rprofile` worked like git config, where local config selectively overrides elements that overlap with user-level and global config, project-level `.Rprofile`s would be much more useful. Unfortunately this is not how R startup works. If you've got a project-level `.Rprofile`, the user-level won't be consulted, which creates new awkwardness and workarounds (e.g. repeating code or sourcing user-level `.Rprofile` from within project-level `.Rprofile`).

Have we converged on the conclusion that usethis's current simplicity and preference for user-level `.Rprofile` is probably OK?

**Comment by jennybc** [comment]
I mean, it's still possible to edit project-level `.Rprofile` via `edit_r_profile("project")`.
