### ISSUE TITLE
Feature request: Helper for setting up default DESCRIPTION fields?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#474]
I'm thinking out loud about a helper for https://usethis.r-lib.org/articles/articles/usethis-setup.html#store-default-values-for-description-fields-in-all-new-packages

It'd create the template to copy-paste in .Rprofile, copy it to the clipboard and would say to use `edit_r_profile()`.

In the template, it could fill some fields (name and information of the first author in `Authors@R`) using `whoami`. It could look for the `ORCID_ID` environment variable if present like `desc` does, and add a `comment` field with it to the first author. cf #108

**Comment by ha0ye** [comment]
I was just thinking about this today... no surprise that @maelle got there first! :laughing:

**Comment by maelle** [comment]
related to #432 maybe

**Comment by hadley** [comment]
This doesn't seem that useful to me, as I think most of the information will need tweaking anyway. I'd review a PR to implement it, but given how many open issues there are right now, it's unlikely to be something we tackle ourselves.
