### ISSUE TITLE
Check that documentation is up to date

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#481]
I relay more and more on usethis! Thanks for maintain it. 

I keep forgetting to update documentation when I modify R files. Usually I find this after upgrading a package and installing it to use in other projects. I expect that a function I created to be exported, but as I forgot to document the package it is not yet on the NAMESPACE. 

When I try to `use_version`,  it only prevents to upgrade the version if I haven't committed changes, but not if I forgot to document the package.

Perhaps a internal `check_undocumented_changes` that printed something like 
`
TODO: You modified the package source code, update the documentation.
`

I am don't know if not updating the documentation should prevent upgrading the version number or not. What are your thoughts on this?

**Comment by jennybc** [comment]
Reflecting on my workflow ... I think I explicitly `document()` a lot, yes. I also run `check()` frequently, which runs `document()`. And I would always run `check()` before installing the package. I'm not convinced another function would help here, as you would also have to remember to run that!

I'll have to think about whether it's appropriate to put something about this in `use_version()` 🤔

**Comment by llrs** [comment]
I develop an analysis project. When I find that I repeat the code I move code from that project to a package. I then install the repository to continue with the analysis. From time to time I restart the R session to use the additions to the helper package, then I remember to update the version number of the package to see which updates are available to that session. That's why I usually forget to check the package, because "I know" it works, and I keep using `use_version`.

Perhaps my workflow should be improved (suggestions are welcome :), but I think  people with similar approaches might find this useful.

**Comment by hadley** [comment]
There's no terribly easy way to tell if the documentation is out of date except to actually run it. Unfortunately at this point, you just need to train yourself to document or check more frequently.
