### ISSUE TITLE
Feature request: create the license file if it is present in defaults

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#482]
One can store the default license in default description fields. https://usethis.r-lib.org/articles/articles/usethis-setup.html#store-default-values-for-description-fields-in-all-new-packages

When calling `create_package()`, the default fields will be used in DESCRIPTION, but no license file will be created. Would it make sense to create the license file if the default license is one of the licenses that the `use_blabla_license()` functions would have created?

**Comment by hadley** [comment]
I think we want to keep these functions separate. If you want to have a heavily customised default, I think you should create a function that calls multiple usethis functions.
