### ISSUE TITLE
use_readme_rmd: resurrect the install_github() part of the template

### ISSUE THREAD

**Issue by GregorDeCillia** [r-lib/usethis#483]
Most R packages that are not available on CRAN suggest something like

```r
# install.packages("devtools")
devtools::install_github("my_organization/my_package")
```

in the installation instructions of their `README.md`.  This is to  to help users who are only familiar with `utils::install.packages` to install their package directly from github. Even some packages that are released on CRAN suggest to use `install_github` for the "development version". An example would be this repository (`r-lib/usethis`).

_____________

It would be handy if `usethis::use_readme_rmd` could automatically add something similar to the created file based on the `URL:` field in `DESCRIPTION`.

**Comment by jennybc** [comment]
If you have a GitHub URL in DESCRIPTION, `use_readme_rmd()` is designed to do this already:

https://github.com/r-lib/usethis/blob/master/inst/templates/package-README

if it's not happening, then that has somehow gotten broken.

**Comment by GregorDeCillia** [comment]
Oh, I see. It seems `github` does not end up in the `data` object that is passed down to `whisker::whisker.render`. I think this could be fixed either in `project_data` or in `use_readme_rmd`, where the `Rmd` flag is set also.

**Comment by jennybc** [comment]
This used to work, so I will need to look into where along the way this got broken and add a test so it does not break again.

**Comment by GregorDeCillia** [comment]
I would like to help, but unfortunately I am not familiar with the bisection methods that are usually used for this kind of task.

One thing I can say is that the flag used to be defined in `use_readme_rmd`. See [here](https://github.com/r-lib/usethis/blob/708248bc01019f4159270fbca7ed6b3940058abe/R/infrastructure.R#L493).

**Comment by jennybc** [comment]
Thanks! Yeah the functions that marshal package or project data have evolved a lot and somehow this field was lost.

**Comment by hadley** [comment]
@batpigandme what was the results of our discussion about this for tidyverse packages? Did we decide it was potentially confusing to include up front and center on the homepage?

**Comment by batpigandme** [comment]
For tidyverse packages we wanted to move it down, but that was because most users should be working with CRAN.

**Comment by hadley** [comment]
@batpigandme do you have an example of a package where we've done that?

**Comment by batpigandme** [comment]
We did it for dplyr (https://github.com/tidyverse/dplyr/commit/692aed61e5bf18e91c00e2f35114aab03bff082b), and then you told me to hold off on doing the others

**Comment by hadley** [comment]
I didn't see any easy way to test this because `uses_github()` looks at `gh_tree_remote()` and simulating a remote is a moderate amount of work.

@batpigandme looks like the usethis template already breaks it up in a way that's fine for most sites.

**Comment by batpigandme** [comment]
Agreed.
