### ISSUE TITLE
Helper for bioconductor dependencies

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/usethis#488]
Would be nice if this updated DESCRIPTION with the appropriate entry:

```r
usethis::use_package("SingleCellExperiment", type = "biocViews")
```

**Comment by hadley** [comment]
And what is that appropriate entry?

**Comment by jayhesselberth** [comment]
In this case the `DESCRIPTION` entry would be:

```
biocViews: SingleCellExperiment
```

https://bioconductor.org/developers/how-to/biocViews/

**Comment by hadley** [comment]
Isn't this for when you're developing a package, not when you're depending on it?

**Comment by jayhesselberth** [comment]
I think I would use it for both cases? The difference seems semantic to me.

https://github.com/r-lib/devtools/issues/700#issuecomment-235127291

**Comment by jimhester** [comment]
BiocViews is for packages currently in or planning to be included in Bioconductor, and the value should be the categories (views) the package should be included under. You can see the available views in the dropdown on the left side of https://bioconductor.org/packages/release/BiocViews.html#___Software.

So I do not think it is appropriate to be added to `use_package()` and this example also doesn't really make sense, SingleCellExperiment is a Bioconductor software package, but it is _not_ a valid entry for BiocViews. ([Single Cell](https://bioconductor.org/packages/release/BiocViews.html#___SingleCell) on the other hand is a valid category)

All packages which depend on Bioconductor packages should (IMHO) really be in Bioconductor and therefore have BiocViews. But even if they are not in Bioconductor for whatever reason they should still categorize themselves appropriately with an appropriate BiocViews category, for no other reason than the remotes / devtools install functions will look in the Bioconductor repositories for dependencies then.  `biocViews::recommendBiocViews()` uses some rough heuristics to recommend BiocViews categories based on the package title and description in the DESCRIPTION file.
