### ISSUE TITLE
use_git_ignore does not write a trailing newline

### ISSUE THREAD

**Issue by colearendt** [r-lib/usethis#514]
https://github.com/r-lib/usethis/blob/3abf7fb7c48c93d35a76dd51c2482d22c36bfa58/R/git.R#L71-L73

Not sure how problematic this is, but I know conventions suggest including a trailing newline at the end of a file. Is that the case for `.gitignore` as well? In any case, `usethis::create_project` and `usethis::create_package` both do not take care of newlines at the end of the file when calling `use_git_ignore`:
![image](https://user-images.githubusercontent.com/23075542/49130626-d3fd0b80-f2a2-11e8-9af1-08b1b41814a8.png)

**Comment by hadley** [comment]
Would you be interested in doing a PR? I think the best place to tackle this would be in `write_union()` (or maybe even in `write_utf8()`)

**Comment by hadley** [comment]
I suspect this was needed for some reason, but removing the if statement didn't lead to any failing tests. I've added a unit test that references this issue so if the opposite problem crops up, we'll know why.
