### ISSUE TITLE
Standard way for usethis to manage part of a file

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#517]
By surrounding lines of code with comments

Use in:

*  [x] `use_badge()`, replacing home grown solution
*  [x] `use_rcpp()`, `use_tibble()` for NAMESPACE management (roxygen2 or otherwise)
*  [ ] `use_conflicted()`, `use_reprex()` etc for `.Rprofile` insertion

**Comment by jennybc** [comment]
If you customize your Emacs preferences via the built-in "Easy Customization" tool (hahaha), you get entries prefaced like this at the end of `~/.emacs`:

```
;; custom-set-variables was added by Custom.
;; If you edit it by hand, you could mess it up, so be careful.
;; Your init file should contain only one such instance.
;; If there is more than one, they won't work right.
 ```

**Comment by hadley** [comment]
I'm not going to include the `.Rprofile` stuff right now because it doesn't seem as important, and needs more infrastructure in `block_insert()` so we can have extra explanatory text around it.
