### ISSUE TITLE
Use base parameter when looking for PRs

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#520]
https://developer.github.com/v3/pulls/#list-pull-requests

**Comment by jennybc** [comment]
When developing this:

http://happygitwithr.com/pr-extend.html

I learned that this parameter does not mean what you think it means.

**Comment by hadley** [comment]
It sounds exactly what I need a I have the name of a local branch and want to find the corresponding PR. But you're right; it doesn't work.

**Comment by jennybc** [comment]
Jinx. Yeah see my addition above.

**Comment by hadley** [comment]
The `head` parameter doesn't seem to work either 😬

**Comment by jimhester** [comment]
the base is not the local branch name, it is the base of the PR, e.g. where the PR branched from (normally master). I think what you are looking for is the `head` parameter. e.g. if I want to retrieve https://github.com/r-lib/usethis/pull/518 from the `gh-labels` branch then you can do the following

``` r
res <- gh::gh("/repos/:owner/:repo/pulls", owner = "r-lib", repo = "usethis", head = "r-lib:gh-labels")
length(res)
#> [1] 1
res[[1]]$number
#> [1] 518
res[[1]]$head$ref
#> [1] "gh-labels"
```

<sup>Created on 2018-11-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Aha, I was using the wrong username for head.

**Comment by jennybc** [comment]
I may have misunderstood what this was about. Luckily, my observation that `base` never means what you want it to mean still holds 😁
