### ISSUE TITLE
Optionally allow non-CRAN names in create_package and use_description

### ISSUE THREAD

**Issue by noamross** [r-lib/usethis#528]
It's often useful to have package structures or even just DESCRIPTION files in projects that aren't fully packages or will never go to a repository, but the namespace is only so big and underscores/dashes are useful in project names.  I would like a `check_name=TRUE` argument for `use_description()` and `create_package()` so I can skip the name-checking error and use these functions for more projects.  It could also default to `getOptions(usethis.checkname)`

Happy to write the PR for this if you think the feature should exist.

**Comment by hadley** [comment]
I think that's ok for projects, but not for packages (since I believe that invalid names won't allow you to build the package etc — do you have evidence to suggest otherwise?)

**Comment by hadley** [comment]
Yeah, that's reasonable. See also #169 — your thoughts would be greatly appreciated there.

**Comment by jennybc** [comment]
@noamross I'm amenable to this change but won't be able to get to it personally for this coming release. If you make a PR quite soon, we can try to get it in.

I'm not so keen on the option. The `use_description()` + `create_project()` plan seems the most promising.

**Comment by noamross** [comment]
Can you clarify what the favored plan is? I think it is:

-  `use_description()` does not check for a valid name
-  `create_package()` checks for a valid name and  calls `use_description()`
-  `create_project()` does not check for a valid name and calls `use_description()` (Per #169)

**Comment by jennybc** [comment]
I think step 0 is to confirm the impact of having a package with an illegal name and record that here. Then, yeah, what you say.

**Comment by sctyner** [comment]
`create_package("my_package")` with an illegal package name doesn't give any warning message by default as far as I can, and new package developers (at Uncoast Unconf) are getting lost. It looks like it works (i.e. like the package has been created), but then none of the usual things (e.g. install) work obviously because a package wasn't really created. 

I'm fairly new to `usethis` but it seems like if the package name is illegal it should warn you and make you say "yes I'm sure I want to do this" before creating any files.

**Comment by jennybc** [comment]
Here's what I see:

``` r
usethis::create_package("~/tmp/illegal_name")
#> Error: 'illegal_name' is not a valid package name. It should:
#> * Contain only ASCII letters, numbers, and '.'
#> * Have at least two characters
#> * Start with a letter
#> * Not end with '.'
```

<sup>Created on 2019-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Can someone show me an example of this? With code I can run?

>` create_package("my_package")` with an illegal package name doesn't give any warning message by default as far as I can tell, and new package developers (at Uncoast Unconf) are getting lost. It looks like it has "worked" (i.e. like the package has been created), but then none of the usual things (e.g. install) work obviously because a package wasn't really created.
