### ISSUE TITLE
Build protocol flexibility into pr_*() functions

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#533]
`pr_fetch()` is currently hard-wired for ssh

https://github.com/r-lib/usethis/commit/9bc4f6d5359cf457bab7dd9489d8b194c774b29c#r31557485

**Comment by hadley** [comment]
Seems like we don't need an argument for `pr_fetch()` since we already have a repo — we just need a `git_protocol()` that tells protocol of current repo. Something like this?

```R
git_protocol <- function() {
  r <- git_repo()
  if (!"origin" %in% git2r::remotes(r)) {
    ui_stop("origin remote not configured")
  }
  
  url <- git2r::remote_url(r, "origin")
  if (substr(url, 1, 4) == "git@") {
    "git"
  } else if (substr(url, 1, 8) == "https://") {
    "https"
  } else {
    ui_stop("Unknown git protocol")
  }
}
```
