### ISSUE TITLE
use_pkgdown_travis() lacks some detail

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#535]
~I have not yet succeeded~ but want to record some notes as I go.

`ui_todo("Create gh-pages branch")` is a bit of an understatement. In greater detail:

1. Quit any RStudio instance in the target project. You don't want a lock on any hidden files used by RStudio that will diminish the effect of the recursive file removal we're about to do.
2. In the shell, in the target repo (in fact, I suspect this should be `rm -rf .` 😬) ... *Update: I now see that these git instructions are given in `pkgdown::deploy_site_github()`. It would be a great idea to link to that!* It's really important that this branch be completely empty. I learned this the hard way.

You need to make sure the repo's settings re: GitHub Pages are correct, i.e. set to `gh-pages branch`.

The `before_deploy` and `deploy` blocks for insertion into `.travis.yml` need to be inserted into the build matrix, presumably for `r: release`.

For tidyverse packages only, tidytemplate needs to be installed from GitHub.

**Comment by jennybc** [comment]
In https://github.com/r-lib/usethis/commit/7d5f93e269c23b509c414ca0ced1ac7343e2e995, I added the suggestion to read `?pkgdown::deploy_site_github`, triggered by the creation of `gh-pages` branch.

Is there anything else here in my tale of woe that is general enough to do something about? Here's what remains:

  * The `.travis.yml` fodder should not just be plopped in anywhere. It needs to be integrated into your build matrix, if you have one.
  * Going to repo Settings and making sure Github Pages source is set correctly.

The tidytemplate thing is clearly specific to us.

**Comment by hadley** [comment]
We might be able to automate the gh-pages branch creation process — but git does not make this easier (and obviously we'd want to do it without touching the local directory)

We might also be able to use the API to either automatically switch the docs branch, or at least tell you if it's necessary.

**Comment by jennybc** [comment]
> We might be able to automate the gh-pages branch creation process

That sounds frightening, due to the `rm -rf` aspect 😱

**Comment by jennybc** [comment]
```
git checkout --orphan gh-pages
git rm -rf .
git commit --allow-empty -m 'Initial gh-pages commit'
git push origin gh-pages
git checkout master
```

I also think that `git rm -rf .` arguably should be `rm -rf .`. Otherwise you don't delete `.Rhistory` and `.Rproj.user. All it takes is someone adding `-a` to the `git commit` and now you've committed and pushed them.

**Comment by hadley** [comment]
We should avoid `rm -rf .` because it's so dangerous. But accidentally adding files was the reason I exposed my github/aws credentials. Maybe @jimhester can suggest another way of creating this branch that doesn't have those problems.

**Comment by hadley** [comment]
Or maybe we could somehow create the branch only on github using the API?

**Comment by jennybc** [comment]
Unless things have changed, I don't think we can use the API for this:

  * creating an empty, orphan gh-pages branch

https://stackoverflow.com/questions/18565425/how-do-i-create-an-orphan-branch-from-the-github-api

I'm pretty sure that used to be true re: setting source for Github Pages. But this is now in preview 🎉:

https://developer.github.com/v3/repos/pages/#update-information-about-a-pages-site

**Comment by hadley** [comment]
From my reading, that SO thread isn't a definitive no; it just needs a bit more spelunking (by someone who has more understand of the underlying git datastore than me)

**Comment by jimhester** [comment]
What is wrong with

```shell
git checkout --orphan gh-pages
git reset
git commit --allow-empty -m 'Initial gh-pages commit'
git push origin gh-pages
git checkout --force master
```

You have to use `--force` when switching back to master because there will be some files that 'could be overwritten', but in actuality they are the same files so there should be no concern.

**Comment by hadley** [comment]
There's still the concern of accidentally checking in files that you shouldn't? (i.e. if someone doesn't follow the instructions to the letter)

**Comment by jimhester** [comment]
You can create an empty branch with two GH API commands, first create a new commit with an empty tree, then assign a ref to that commit. e.g. to create a `gh-pages2` branch on my personal readr remote. Note `4b825dc642cb6eb9a060e54bf8d69288fbee4904` is the SHA constant for an empty tree, which you can derive by running `git hash-object -t tree /dev/null`.

```r
res <- gh::gh("POST /repos/:owner/:repo/git/commits", owner = "jimhester", repo = "readr", message = "first commit", tree = "4b825dc642cb6eb9a060e54bf8d69288fbee4904")
gh::gh("POST /repos/:owner/:repo/git/refs", owner = "jimhester", repo = "readr", ref = "refs/heads/gh-pages2", sha = res$sha)
```

**Comment by jimhester** [comment]
And if you wanted to do the equivalent with command line git

```shell
sha=$(echo 'first commit' | git commit-tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904)
git push remote_name $(sha):refs/heads/gh-pages-123
```

**Comment by jimhester** [comment]
yes you are right sorry, I fixed it.

**Comment by hadley** [comment]
I think we should probably use the github api to detect if there's a remote `gh-page` branch and to create it if not. We should also error if `url` is not set; I think it's useful to have even if you're not using a subdomain.
