### ISSUE TITLE
consider putting `install_cran("pkgdown)` in `before_cache` rather than `before_deploy` 

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#541]
`use_pkgdown()` recommends you put `remotes::install_cran("pkgdown")` in `before_deploy`. This works well, the only issue is because the package cache is uploaded _before_ the before_deploy stage happens pkgdown and its dependencies will not be in the cache. If `pkgdown` is a normal dependency of the package (such as in the usethis pkg itself) this isn't a problem, but if your package would not normally depend on pkgdown it will be.

Putting the install command instead in `before_cache` would cause it to run right before the cache is uploaded, which would cause the packages to be included in the cache. The cache is only updated on successful builds, so I think this will do what we want.

The main downside to this approach is it is more confusing, but I think likely it is worthwhile...

**Comment by hadley** [comment]
Maybe `after_success` would be more clear?

**Comment by jimhester** [comment]
`after_success` is too late, it happens after the cache is uploaded.

**Comment by hadley** [comment]
Bummer. I really wish https://docs.travis-ci.com/user/job-lifecycle/ was clearer.

**Comment by hadley** [comment]
Now in #535
