### ISSUE TITLE
Adjust ui_*() colors based on RStudio theme

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#546]
The `darkgrey` used by `ui_code()` is hard to see in some RStudio contexts. Examples where RStudio is offering debugging facilities:

<img width="868" alt="screen shot 2018-12-11 at 1 02 53 pm" src="https://user-images.githubusercontent.com/599454/49833080-567ad600-fd4d-11e8-8840-ca679c60f0c6.png">
<img width="866" alt="screen shot 2018-12-11 at 12 44 43 pm" src="https://user-images.githubusercontent.com/599454/49833090-5b3f8a00-fd4d-11e8-86ec-38e5857ac391.png">

When [cliapp](https://github.com/r-lib/cliapp) matures or another option presents itself, take advantage to make styling adapt to a dark vs. light theme, e.g. consult `rstudioapi::getThemeInfo()$dark`.

https://github.com/r-lib/cliapp/blob/cbf8f1a692a44b12db508a2050c9133487ae07bc/R/simple-theme.R#L71

**Comment by hadley** [comment]
@jimhester do you think this should be resolved in RStudio so that the "darkgrey" colour is still readable with a dark theme?

**Comment by hadley** [comment]
I think this is related to https://github.com/rstudio/rstudio/pull/4076

**Comment by hadley** [comment]
I'm now convinced that this is really an RStudio issue, so closing in favour of https://github.com/rstudio/rstudio/issues/1959
