### ISSUE TITLE
use_article() should put the new thing below vignettes/article/

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#548]
`use_article(`) should put the new thing below `vignettes/article/` not just `vignettes/`.

**Comment by hadley** [comment]
Why? It's added to `.Rbuildignore`

**Comment by hadley** [comment]
I'd rather close for now, while leaving still leaving discussion about the correct behaviour for articles open (i.e. we also need to think about how we might auto link to them from pkgdown).

**Comment by jennybc** [comment]
@Hadley It feels like perhaps we have decided to put non-vignette articles in `vignettes/articles/`, yeah? If so, then `use_article()` should be adjusted.

**Comment by hadley** [comment]
I'm still conflicted about non-vignette articles because we don't have any way to generate links to them in pkgdown.

**Comment by jennybc** [comment]
I see.

`use_article()` is a bit confused / confusing right now because it Rbuildignores `vignettes/articles`, as opposed to `vignettes/ARTICLE_NAME`.

**Comment by jennybc** [comment]
I guess this is something I recently fiddled with:

https://github.com/r-lib/usethis/commit/b2414200c2c941b5a5d168a48cc4ca44d397e809

**Comment by hadley** [comment]
Re-closing because I don't think we have enough of a structure around articles to turn it into code yet. I've open https://github.com/r-lib/pkgdown/issues/1247 to track the problem more broadly.

**Comment by hadley** [comment]
The current behaviour of `use_article()` is provably incorrect and I think the simplest fix would be to put articles into `vignettes/article`. I think I previously misunderstood exactly what was going in the .Rbuildignore.
