### ISSUE TITLE
add use_gitattributes() or other function to set GitHub linguistics for .Rmd files

### ISSUE THREAD

**Issue by Aariq** [r-lib/usethis#552]
Apologies if this isn't an appropriate function for this package, but I just found out that GitHub doesn't count .Rmd files as R for it's language tags (https://github.com/github/linguist/issues/2756). I'm going through all my projects adding a .gitattributes file to set R as the language (`*.* linguist-language=R`) where it makes sense, but perhaps there could be a function that pulls this information from the code chunks in .Rmd files and adds a .gitattributes file?

**Comment by hadley** [comment]
I think this should either be done at the linguist level, or not at all. But it's not clear to me that .Rmd should count as R and not markdown.

**Comment by BojanMakivic** [comment]
> 
> 
> Apologies if this isn't an appropriate function for this package, but I just found out that GitHub doesn't count .Rmd files as R for it's language tags ([github/linguist#2756](https://github.com/github/linguist/issues/2756)). I'm going through all my projects adding a .gitattributes file to set R as the language (`*.* linguist-language=R`) where it makes sense, but perhaps there could be a function that pulls this information from the code chunks in .Rmd files and adds a .gitattributes file?

Thanks for your input here. It solved me a lot of trouble. :)

**Comment by khurchla** [comment]
@BojanMakivic thanks so much for '*.* linguist-language=R)' I was having trouble getting my .gitattributes to still recognize R before this. Cheers,

**Comment by remlapmot** [comment]
I wondered about this too. 

In case helpful to others, I found the solution to this in the `.gitattributes` file of the rmarkdown-book repository [here](https://github.com/rstudio/rmarkdown-book/blob/ed81b894d5d2665d6ef4657c5840634512b97ff5/.gitattributes), i.e. add the following line to your `.gitattributes` file.
```
*.Rmd  linguist-detectable
```
It's probably safer to make the fully lower case `.rmd` detectable as well, so add
```
*.rmd  linguist-detectable
*.Rmd  linguist-detectable
```
or I think one line with a simple regexp will work too
```
*.[Rr]md  linguist-detectable
```

You can see that Linguist now recognises R Markdown as a language as it's included as `RMarkdown` [here](https://github.com/github/linguist/blob/0fca6f46491731d9adedc678d8663aa74d40a5a6/lib/linguist/languages.yml#L4868).

**Comment by namhaivu173** [comment]
> I wondered about this too.
> 
> In case helpful to others, I found the solution to this in the `.gitattributes` file of the rmarkdown-book repository [here](https://github.com/rstudio/rmarkdown-book/blob/ed81b894d5d2665d6ef4657c5840634512b97ff5/.gitattributes), i.e. add the following line to your `.gitattributes` file.
> 
> ```
> *.Rmd  linguist-detectable
> ```
> 
> It's probably safer to make the fully lower case `.rmd` detectable as well, so add
> 
> ```
> *.rmd  linguist-detectable
> *.Rmd  linguist-detectable
> ```
> 
> or I think one line with a simple regexp will work too
> 
> ```
> *.[Rr]md  linguist-detectable
> ```
> 
> You can see that Linguist now recognises R Markdown as a language as it's included as `RMarkdown` [here](https://github.com/github/linguist/blob/0fca6f46491731d9adedc678d8663aa74d40a5a6/lib/linguist/languages.yml#L4868).

@remlapmot Thanks a lot for this. Is there a similar solution for GitHub to recognize .r or .R script files as well?

**Comment by remlapmot** [comment]
It already does, because R is included in Linguist. The subtlety with RMarkdown and Quarto files is that because in Linguist they are type `prose` you need to make them detectable for them to show on the front page stats of a repo. Whereas R is type `programming` so you don't need to add/change anything in your `.gitattributes` file.

**Comment by namhaivu173** [comment]
@remlapmot Thanks for clarifying. The reason I'm asking is I have a repo (https://github.com/namhaivu173/Uber_Lyft_project) containing both .ipynb and .R files, but somehow GitHub only shows 100% Jupyter Notebook in the language bar. I don't know if this is because my .ipynb file is much larger than my .R script or is it something else. I have tried to add "*.[Rr] linguist-language=R" to my .gitattributes file but still no change. Can you help with this?
