### ISSUE TITLE
use_readme_rmd ingests git hook

### ISSUE THREAD

**Issue by petermeissner** [r-lib/usethis#556]
Currently `use_readme_rmd()` does ingest a pre commit Git hook into the package's local git repository. There are two problems resulting from this: (1) This hook also prevents updates of the repo when the Rmd-file is simply re-rendered (e.g. automatically obtained information is updated). (2) User are neither informed about the ingestion happening and have no possibility to prevent it. 

This is related to the discussion found here https://github.com/r-lib/usethis/issues/312 and to that found here https://twitter.com/jeroenhjanssens/status/1075010648587886592.

I have forked this repo and will file a pull request with a possible solution that will ...

1. allow users to opt in or opt out per function argument, 
2. will default to opt out in non-interactive environments, 
3. will ask user what to do in case of an interactive session, 
4. and will have tests covering the new adopted behaviour.

**Comment by hadley** [comment]
Given that no one else has reported any problems with it, and the complexity of your proposed solution, I would rather simply encouraging people to delete the hook if they find it annoying.

**Comment by jennybc** [comment]
We could consider

  * Messaging when the hook is created, to build awareness.
  * Asking whether to create the hook.
