### ISSUE TITLE
use_gitlab_ci

### ISSUE THREAD

**Issue by overmar** [r-lib/usethis#565]
For those of us who use gitlab can we add a function to create the gitlab-ci.yml file, in a similar manner as the package currently creates a .travis.yml? Currently gitlab doesn't have an R specific .gitlab-ci.yml R template, so it would be useful to be able to do this through usethis.

**Comment by overmar** [comment]
I originally referenced this in https://github.com/r-lib/usethis/issues/293#issuecomment-453369309 but was asked to make a new issue. Also I submitted a pull request which creates this the .gitlab-ci.yml file https://github.com/r-lib/usethis/pull/562

**Comment by jennybc** [comment]
Closed by 8a76a85de1df2164435da511e1eb1075e341d50d
