### ISSUE TITLE
use_template and devtools::load_all() docs?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#572]
Reg https://github.com/r-lib/usethis/issues/347 are you still interested in "a PR that adds a small note about this to the use_template() docs, to reduce future head-scratching."?

At least since reading that thread I know I'm not crazy. :grin:

**Comment by jennybc** [comment]
@maelle Now would be a really good time for this ⏰ we're pushing towards a release.

**Comment by maelle** [comment]
Oops I had missed your answer in January, on it now!
