### ISSUE TITLE
`usethis::use_test()` does not remain true to original *.R open source file name

### ISSUE THREAD

**Issue by stufield** [r-lib/usethis#581]
With `use_test()`, if the current source editor file name is, e.g. camel case, the `test-*.R` file that is created is converted to all lower case with a call to `tolower()`. I think this is making an unnecessary decision for the user. Additionally, if the user tries to force the file name by passing a `name =` argument, this is also converted to lower case.

Example of the problem with default:
```r
source editor filename: "my_coolFunctionPrint.R"
use_test()
resulting test: "test-my_coolfunctionprint.R"
```
Example of the problem with `name = ***` passed:
```r
source editor filename: "my_coolFunctionPrint.R"
use_test("theBestFunctionEver")
resulting test: "test-thebestfunctionever.R"
```

This is likely unnoticed if strict adherence to the Tidyverse style guide, but other style guides will break the filename.R -> test-filename.R pattern. There appears to be a `tolower()` call somewhere converting the case that needs some conditional logic to it. I'd be happy to submit a PR if necessary.

**Comment by hadley** [comment]
@stufield do you still want to tackle it? I'm also happy to do it if you don't have time.

**Comment by hadley** [comment]
Hmmmm, why are we calling `asciify()` at all? Maybe the problem is that we actually need a completely different branch if the path comes from an existing file?

**Comment by stufield** [comment]
I am not 100% sure I follow. Do you mean coming from an existing (open) R script, or from an existing `test-*.R` file? I *think* this branch is created on Line 34 where if `name` is `NULL` we create a name from the existing file with `get_active_r_file()`. Then below, if that file already exists, we simply open it. Otherwise we create it with `use_template()`. However, I have a feeling I've misunderstood what you mean.

My understanding of `asciify()` is to stop users from introducing any non-ascii characters that may not be cross-platform friendly. Wouldn't this be the case no matter what? Or, are you saying that IF the user has some non-ascii file name (either the `test-*.R` file or the open RStudio file), we shouldn't be making this decision for them?

**Comment by hadley** [comment]
There are two ways to get a name for the test file:

1. User supplied - the user could type anything, so we need to make sure it's a valid file name. (Although maybe rather than trying to fix up a bad name we should just throw an error)

2. From an existing open file, which implies there's already a valid file name and we don't need to check.

i.e. maybe `use_test()` should just do:

```R
if (is.null(name)) {
  name <- get_active_r_file(path = "R")
} else {
  check_file_name(name)
}
```

**Comment by stufield** [comment]
Do you think it's safe to assume that if the file already exists it is valid? It might be safer not to assume anything and check in either case. Perhaps softening things with a warning if the existing file is invalid.

Maybe we could just do something like:

1. If user supplied, check with `check_file_name()` and throw error ... bad `name =` argument passed.

1. If existing file, check with `valid_path_name()`, and trip a warning suggesting to change the file to something safer.

This satisfies your original intuition, we don't need to be calling `asciify()` at all.

**Comment by hadley** [comment]
Yeah, I think it's fine to skip the check if the file already exists.

**Comment by stufield** [comment]
Ha ha! I actually came around to your original instinct once I got into writing it. Does it really make sense to be creating a file called `test-$ome#fun+I_like.R`? So I went with with checking both cases. Perhaps as this point I should submit a PR and give you an opportunity to actually look at the code? Would you prefer that?

**Comment by hadley** [comment]
Yeah, that'd be great.
