### ISSUE TITLE
pr_* does not work with non ssh credentials

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#585]
Macro issue is #534 

While testing those new functions, I have seen that `pr_push` does not work when your are not using ssh credential. 

```r
> usethis::pr_push()
✔ Checking that 'fix/155-paste-oracle' branch is up to date
✔ Pushing changes to GitHub PR
Error in git2r::push(git_repo(), name = name, refspec = paste0("refs/heads/",  : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
```

By default git2r uses ssh, and for other auth mechanisms, a credential object should be pass in each function. It is not possible to setup globally at the moment (see ropensci/git2r#337)

While this is not supported in git2r, usethis could create the `git2r::cred_token` if a GITHUB_PAT exists and use it each time it is needed when remote is https.

**Comment by cderv** [comment]
Additionnally, `pr_fetch` will add remotes only with ssh url.
https://github.com/r-lib/usethis/blob/e9ae00335efdbb3c49493f53eb11e6d74b634bc6/R/pr.R#L76-L79

So even if we supplied other credentials, it won't work with unless ssh. 

This is to adapt too.

**Comment by jennybc** [comment]
I'll do this once #602 plays out.

**Comment by jennybc** [comment]
Actually this is a duplicate with pre-existing #533.

**Comment by cderv** [comment]
😮 I missed this one! oups... ! sorry 🙃 

However, #533 is about `pr_fetch` and this one at first about `pr_push` that requires some credentials other than ssh on https remote. I think this should also be dealt with to make https support. The issue title may have been too evasive... 🤔 

I would make a proposition to help if required but it seems you're deep into this full time currently (more than me for sure) and do no want to interfere. I uses this config (windows + git https) so I can easily test. please do not hesitate to ask.

**Comment by jennybc** [comment]
Yes, I understand -- we will try to fix the https vs ssh issue for the whole `pr_*()` family of functions. And, yes, your feedback will be very useful!
