### ISSUE TITLE
Write vignette of how to use `use_this`, particularly in a package dev context

### ISSUE THREAD

**Issue by angela-li** [r-lib/usethis#589]
I started to use `use_this` while writing a new function for it (#584), and wanted to learn more about the functions in it specifically designed for package development. There's a lot of stuff in the package, so I wanted to know:

- What functions are especially useful in package dev vs. which ones are nice to have? 
- What order should I use them in? 
- Which ones save you a lot of time?
- Which ones are the ones I should be using regularly when developing packages? Which ones are more for special use?

I thought a vignette called "Package Development with usethis" might be a good way to put some of this info in, but maybe a blog post or a book chapter would be more appropriate? 

I talked to @jennybc and she mentioned [Stat 545 materials](http://stat545.com/packages06_foofactors-package.html#use_mit_license()) as a possible starting point for a vignette. I can try to put something together from that, perhaps? Let me know what you think!

**Comment by jennybc** [comment]
Yeah, that is the STAT 545 content I was referring to and here is another version of same, as a proposed devtools vignette:

http://rpubs.com/jennybc/build-a-basic-package

I think it holds up fairly well as a concise "whole game" view of getting a package set up. It needs updating / checking against the current versions of devtools and related packages.

**Comment by hadley** [comment]
I'm going to suggest that we instead move this to r-packages. @jennybc and I have already discussed the chapter, so I don't think we need to formally move the issue; we'll remember it.
