### ISSUE TITLE
Relax check for uncommitted changes?

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#592]
Would it be possible to relax the check for uncommitted changes, e.g. for `pr_fetch()` and others?

I pretty regularly have purposefully untracked files that I have no plan to commit. It is a bit of a pain to `git stash --include-untracked` them every time I have to use a `pr_*()` function, or I guess I could add them to `.gitignore`.

For me at least I would prefer if this only checked if you had changes in tracked files, and did not consider untracked files.

**Comment by hadley** [comment]
Yeah, I think that would be fine, if you wanted to write the code.

**Comment by jennybc** [comment]
Strong AGREE here. I've even been forced to stash because of this 😱

**Comment by hadley** [comment]
This is just a matter of excluding the `untracked` component returned from `git2r::status()`

`check_uncommitted_changes()` is currently used in the following functions:

* `use_version()`
* `pr_fetch()`, `pr_push()`, `pr_pull()`
* `use_github()`
* `use_news_md()`
* `use_tidy_style()

It seems to me that changing the behaviour within all these functions will be ok.

**Comment by hadley** [comment]
Despite my passive aggressive earlier comment I will write the code 😄

**Comment by jimhester** [comment]
lol
