### ISSUE TITLE
Re-export := with use_tidy_eval

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/usethis#595]
:= (the tidyeval assignment operator, which I pronounce "digested is") is often as useful for tidyeval as the functions exported by the file generated via usethis::use_tidyeval(). It would be helpful if it were also re-exported.

**Comment by hadley** [comment]
But it doesn't actually do anything?

**Comment by jonthegeek** [comment]
Don't you need it when there's tidyeval on the LHS of a parameter assignment? When I do that, cran checks complain about := until/unless I at least import.

**Comment by batpigandme** [comment]
This is still the method we have in the tidyeval cookbook, and programming with dplyr:

``` r
library(rlang)
name <- "the real name"
c(name = NA)

rlang::qq_show(c(!!name := NA))
rlang::qq_show(c(!!name = NA))
#> Error: <text>:6:25: unexpected '='
#> 5: rlang::qq_show(c(!!name := NA))
#> 6: rlang::qq_show(c(!!name =
#>                            ^
```
<sup>Created on 2019-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by jonthegeek** [comment]
Sure, I can probably knock this out tonight.

**Comment by jennybc** [comment]
Ironically I am getting this exact NOTE in a usethis branch, due to my use of `:=`.

**Comment by lionel-** [comment]
Reexporting it in our packages will give a useful error message when `:=` is used in a wrong context, so that seems helpful.
