### ISSUE TITLE
Option for create_project to create common additional sub-folders

### ISSUE THREAD

**Issue by khailper** [r-lib/usethis#597]
Would it be useful to submit a PR to add a parameter to `create_project` to add folders like /data and something for .Rmd outputs (I believe /docs in the convention) instead of manually running `use_directory()`?

**Comment by khailper** [comment]
An alternative approach occurred to me: a parameter that takes a character vector of directories to create, with a default of c("R"). Documentation might include common additional directories.

**Comment by stephlocke** [comment]
< shameless self promotion>
I've got a package for that! Check out [starters](//github.com/lockedata/starters)
< / shameless self promotion>

**Comment by hadley** [comment]
The usethis philosophy is to create folders as needed; if you want more of a templated approach, I'd go with @stephlocke's suggestion.
