### ISSUE TITLE
rstart_rstudio needs to restart the whole rstudio session, not just the R session

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#60]
`rstudioapi::restartSession()` Restarts the R process, but in order to enable the git integration in RStudio you need to restart the whole RStudio session, not just the R process. It doesn't look like there is a hook in rstudioapi for this currently.

**Comment by hadley** [comment]
Part of #57. 

Looks like we can use `openProject()` for this: https://github.com/rstudio/rstudioapi/commit/018de2858f111b4e64ecf11c1e52402046789b52#diff-75f50f18dc53dad83b1afb99e9d230dcR189
