### ISSUE TITLE
style the output of use_spell_check()

### ISSUE THREAD

**Issue by maurolepore** [r-lib/usethis#603]
The output of `usethis::use_spell_check()` looks like this:

(tests/spelling.R)
```R
if(requireNamespace('spelling', quietly = TRUE))
  spelling::spell_check_test(vignettes = TRUE, error = FALSE,
                             skip_on_cran = TRUE)
```

Wouldn't it be nice if instead it looked like this?:

(after `styler::style_file("tests/spelling.R")`)
```R
if (requireNamespace("spelling", quietly = TRUE)) {
  spelling::spell_check_test(
    vignettes = TRUE, error = FALSE,
    skip_on_cran = TRUE
  )
}
```

It would be nice if the code was styled by the spelling package but spelling does not import nor suggest styler. usethis suggests syler so I guess it'd be more feasable to style the code here?

**Comment by hadley** [comment]
Fixing this small problem will require quite a lot of new complexity, so at this time I don't think it's worth it, unfortunately.
