### ISSUE TITLE
Helpers to edit important config files

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#61]
* `edit_profile()`: `~/.Rprofile`
* `edit_environ()`: `~/.Renviron`
* `edit_makevars()`: `~/.R/Makevars`

**Comment by hadley** [comment]
Also think about git config and ignore files.

Should also consider project vs. global settings - use different prefix/suffix, or an argument?

**Comment by jennybc** [comment]
I have pretty thorough coverage of git config setting and querying here (private repo but you @hadley should be able to see it):

https://github.com/jennybc/githug0/blob/master/R/git_config.R

**Comment by hadley** [comment]
@jennybc this is much smaller in scope (just opening the file in RStudio) but that gives a good list of files to consider

**Comment by hadley** [comment]
Done in ec3914bc164be08d207a307a8300f9dfb4b6805f
