### ISSUE TITLE
Remarks/questions about use_pkgdown_travis()

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#614]
:wave: here! I've used `use_pkgdown_travis()` and was wondering about these two things:

- Why does the function gitignore and Rbuildignore "docs"? With this setup no docs/ folder should be created anyway?

~- Should the deploy script also mention that the deploy should happen from master only i.e.~ No it's the default "branch: name of the branch. If omitted, this defaults to the app-specific branch, or master." sorry!

**Comment by hadley** [comment]
Because you'll still generate that folder when previewing/debugging/experimenting locally.
