### ISSUE TITLE
function to add `PULL_REQUEST_TEMPLATE.md`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/usethis#621]
Like the `ISSUE_TEMPLATE.md` and `CONTRIBUTING.md` templates, will it be worth having a tidyverse template for how to create PR for any given repo? And maybe this can be generated using a new `usethis::use_pr_template()` function?

I found this to be a good example of such a template-
https://github.com/apexcharts/apexcharts.js/blob/master/PULL_REQUEST_TEMPLATE.md

A similar issue was raised in #13 but I can't find any commit that addressed it.

**Comment by hadley** [comment]
I don't think we can consider this without a specific list of ideas for what to include. In our experience issue templates have been of relatively little use, so I don't have strong hopes that PR templates will be either.
