### ISSUE TITLE
Why do we create the `man/` directory in create_package()?

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#622]
Why do we create the `man/` directory in create_package()?

Is there a specific reason we do this vs. waiting until it gets created organically?

https://github.com/r-lib/usethis/blob/2e5f213fce79d1991d6e743ce7c764f687fc310b/R/create.R#L46

cc @hadley

**Comment by hadley** [comment]
I don't know. I think we can probably remove it.
