### ISSUE TITLE
Change default ext for `use_travis()` to "com"?

### ISSUE THREAD

**Issue by apreshill** [r-lib/usethis#623]
The current default value for the `ext` argument (affects both `browse_travis()` and `use_travis()`) is `"org"`. Should it be changed to `"com"`?

Based on:
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

**Comment by cderv** [comment]
For reference this relates to discussion in #349

**Comment by hadley** [comment]
Given the uncertainty around travis, I don't think we should change anything unless forced to.
