### ISSUE TITLE
use_devtools()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#624]
In light of https://github.com/r-lib/devtools/issues/1985, where I learned that devtools already attaches usethis and will probably Depend on it one day, I think we should have `use_devtools()`. It will do this:

```
> use_devtools()
● Restart R for changes to take effect
● Modify '/Users/jenny/.Rprofile'
● Include this code in '.Rprofile' to make devtools available in all interactive sessions
  if (interactive()) {
    suppressMessages(require(devtools))
  }
  [Copied to clipboard]
```

and we should only (or mostly) publicize `use_devtools()`, as opposed to `use_usethis()`.

Agree @jimhester @Hadley?

**Comment by jimhester** [comment]
Sounds good to me!
