### ISSUE TITLE
Helpers for GitHub Actions

### ISSUE THREAD

**Issue by maxheld83** [r-lib/usethis#625]
[GitHub actions](http://github.com/features/actions) is a new workflow automation (~ CI/CD) service from GitHub, still in limited beta as of now.
I think it has some potential for R.

I've written a package for quickly getting started with GitHub actions: [ghactions](http://www.maxheld.de/ghactions/).

It's very closely modelled on usethis, and also includes a front line `ghactions::use_ghactions()` function that writes out sensible defaults for many projects.

It's still very early days for GitHub actions, and ghactions (the pkg) is still maturing.

But *if* things work out and the R community finds GitHub actions helpful, I'd love to write up a short PR wrapping `ghactions::use_ghactions()` in / exporting to `usethis::use_ghactions()` for easier access.

So this will be some time, just wanted to raise this here lest someone else do the same work again.

And also, of course, to gather feedback on [ghactions](http://www.maxheld.de/ghactions/).

**Comment by hadley** [comment]
Fixed by #929, now that github actions have completed changed their UI since you started working on this 😬
