### ISSUE TITLE
README should use `remotes::` not `devtools::`

### ISSUE THREAD

**Issue by friendly** [r-lib/usethis#627]
The README file says `devtools::install_github("r-lib/usethis")` but that generates an error on my R version 3.5.2 system.  `remotes::install_github works`

    > devtools::install_github("r-lib/usethis")
    Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
      there is no package called ‘usethis’
    > remotes::install_github("r-lib/usethis")
    Downloading GitHub repo r-lib/usethis@master
    Installing 1 packages: clipr
    trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.5/clipr_0.5.0.zip'
    Content type 'application/zip' length 40751 bytes (39 KB)
    downloaded 39 KB

**Comment by hadley** [comment]
I think we will re-consider this at some point in the future, but not right now. Remotes is a low-level package that will work better in some situations, but will fail in others. In the long-term, we will probably recommend [pak](https://github.com/r-lib/pak)
