### ISSUE TITLE
Delete CRAN-RELEASE

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#630]
The checklist created by `use_release_issue()` prompts you to use `devtools::submit_cran()`, which creates a file named CRAN-RELEASE with contents like this:

```
This package was submitted to CRAN on 2019-02-14.
Once it is accepted, delete this file and tag the release (commit f3bdd61d8e).
```

We should delete it or ask if it should be deleted in subsequent functions in the checklist: `use_github_release()` and/or `use_dev_version()`, especially since otherwise it will show up in the set of files that `use_dev_version()` offers to commit for you.

**Comment by hadley** [comment]
It's deleted by `use_github_release()`
