### ISSUE TITLE
Predictable Answers to use_course() Prompts

### ISSUE THREAD

**Issue by chris-prener** [r-lib/usethis#636]
I had a [quick exchange](https://twitter.com/JennyBryan/status/1098391788694323200) with @jennybc on Twitter today about the way that `use_course()` answers appear in "random" fashion:

```
> usethis::use_course("https://github.com/slu-dss/wrangling-01/archive/master.zip")
 Downloaded: 2.06 MB  
A ZIP file named:
  'wrangling-01-master.zip'
will be copied to this folder:
  '/Users/chris/Desktop'
Prefer a different location? Cancel, try again, and specify `destdir`.

Is it OK to write this file here?
1: No way
2: No
3: I agree
```

I have been using `use_course()` for teaching the last few semesters and it solves a lot of issues we've dealt with in the past. The unpredictable way that answers to "Is it OK to write this file here?" are presented seems to throw folks off - it's harder for us to provide guidance beyond "answer in the affirmative" to each question. 

I'm happy to put together a PR that adds a `ui_yeah_simple()` function to `ui.R` that presents only "Yes" and "No" as options in the same order each time. I'd then update `use_course()` to use the simplified version rather than `ui_yeah()`. Wanted to open up an issue for discussion before I dug into this, though!

**Comment by hadley** [comment]
Unfortunately I don't think this is a good idea — we are doing something dangerous here, and we want to be sure that the user has carefully consider it. This is our best attempt to do so, and while it's not perfect, I think it's better than making it too easy.

**Comment by chris-prener** [comment]
Thanks for considering this @hadley - I appreciate your response.
