### ISSUE TITLE
Should use_version also add tag in git?

### ISSUE THREAD

**Issue by MishaCivey** [r-lib/usethis#637]
It might be a good idea to also add tag to git branch whenever you increment a version using `use_version` to make sure that there is no possibility to be out of sync between tags/releases and actual version in DESCRIPTION. 

Adding it won't be that difficult, I think, and I'll be happy to take a stab at it, but it's a design decision, so don't want to do it before there is some consensus on details of implementation.

**Comment by hadley** [comment]
I don't think it makes sense because you want to tag the version _after_ it has been accepted to CRAN. See `use_release_issue()` for our process.
