### ISSUE TITLE
Feature requests: use_r generate test file

### ISSUE THREAD

**Issue by GShotwell** [r-lib/usethis#638]
I often create R files and associated test files with a similar name. I was wondering if it would be a worth adding an argument to `use_r()` which would also create a properly named test file. In other words: 

```
use_r("my_script", create_test = TRUE)
```
Would create both `my_script.R` and `test-my_script.R`

**Comment by hadley** [comment]
That feels a bit too specialised to me. You can always call `use_test()` immediately after `use_r()`, and it's less typing.
