### ISSUE TITLE
Set R_REMOTES_STANDALONE in appveyor.yml template

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#640]
Add this to the appveyor template used by `use_appveyor()`:

https://github.com/tidyverse/googlesheets4/blob/1976bb9ecf9a32bf11b04c12935f447f1ff0cc5a/appveyor.yml#L19

e.g.

```
environment:
  USE_RTOOLS: true
  R_REMOTES_STANDALONE: true
```

to prevent this (upon implicit upgrade of curl to a new CRAN version):
```
package 'curl' successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package 'curl'
Execution halted
Command exited with code 1
```

More details here:
https://github.com/r-lib/remotes#standalone-mode

**Comment by jimhester** [comment]
This is a pretty heavy hammer though, I am not sure you would want to enable it by default.

**Comment by jennybc** [comment]
Perhaps we could have it there but commented out, with a comment explaining when you might want to toggle that state?

**Comment by ldecicco-USGS** [comment]
One thing to keep in mind is the people who are really depending on appveyor are not Windows users by default...and may be un-aware of the necessity of Rtools. So, here's one outside perspective vote for *at least* having it in there commented out.

**Comment by jennybc** [comment]
Just to provide more background on the Rtools front ...

Rtools will be automatically installed on AppVeyor for packages with a `src/` directory.

It becomes intermittently necessary for packages that lack compiled code when one of their dependencies requires compilation. Either because of depending on a dev version (ie listing in `Remotes`) or because of the normal gap between something being on CRAN and Windows binaries being available. And that's where people are often caught off-guard.

So, morally, there is a shared quality between the `R_REMOTES_STANDALONE` and Rtools situation -- it's something most people do not need, most of the time. But most people will also need it, now and then, as the surrounding ecosystem evolves.

**Comment by jimhester** [comment]
Maybe having it there commented out would be a good idea, but I do not think we should have either of these on by default.

**Comment by hadley** [comment]
I think this is mostly a documentation issue, and it's not clear usethis is the right place for it.

**Comment by jennybc** [comment]
Document it where, though? Maybe in the [travis section](https://r-pkgs.org/check.html#travis) of R Packages. We could list the most common reasons for failure that basically don't have anything to do with your package, but come from natural blips in the ecosystem.

Every time I catch myself copying snippets from one package's config to another, I think "this should just be in usethis".

**Comment by jennybc** [comment]
I made a PR to beef up the docs in the README of r-appveyor:

https://github.com/krlmlr/r-appveyor/pull/147
