### ISSUE TITLE
Consider setting NOT_CRAN: true in Appveyor?

### ISSUE THREAD

**Issue by cboettig** [r-lib/usethis#641]
Would you consider a pull request to the Appveyor template that sets 

```
environment:
  global:
    NOT_CRAN: true
```

I believe this will fix the behavior of Appveyor such that it does not automatically skip tests that are marked `skip_on_cran()`.  Thanks to @ldecicco-USGS who pointed this out to me.

**Comment by jennybc** [comment]
@jimhester Thoughts?

I'm particularly trying to fit this into things I know, mostly experientially, about appveyor vs travis.

@cboettig If this gets the green light, your PR could also fix #640 Set R_REMOTES_STANDALONE in appveyor.yml template, while you are in the neighborhood.

**Comment by jimhester** [comment]
Sure I suppose so, I don't think there is any particular reason it is not set in the default template and a cursory issue search in https://github.com/krlmlr/r-appveyor seems to indicate the same.

**Comment by cboettig** [comment]
maybe I should open a second ticket, but the other env var I often need to add to my appveyor is: ` USE_RTOOLS: true`

**Comment by jennybc** [comment]
I think `USE_RTOOLS` will open the same conversation we are having in https://github.com/r-lib/usethis/issues/640#issuecomment-467200136, which is that you don't want this on all the time, with no reason.

I think it comes down to whether we think of these templates as minimal or something more general, possibly with a few common additions commented out. That's ugly, but might be useful enough in practice to justify.

**Comment by cboettig** [comment]
Right, that makes sense to me.  I think `NOT_CRAN` should always be set, (unless I'm miss-understanding something fundamental about how `skip_on_cran()` is intended to work -- I'm just now getting tripped up by tests I thought were running on Appveyor but were being skipped because of this).  

`USE_RTOOLS` is more of a judgement call and best left to a separate ticket, my apologies sounds like this is already being discussed in #640.  

I don't know if the `global` part is actually necessary in my example above, you folks probably know better.  For a PR, do you have a preference where said `environment` block would appear in the template?

**Comment by jennybc** [comment]
This search shows you the diversity of approaches in current packages below r-lib:

https://github.com/search?q=NOT_CRAN+filename%3Aappveyor.yml+user%3Ar-lib&type=Code

@jimhester will you recommend the form that is most worthy of putting in our template?

**Comment by jimhester** [comment]
`NOT_CRAN=true` is the only thing that would actually do what we want, as testthat has `identical(Sys.getenv("NOT_CRAN"), "true")` in `skip_on_cran()`.

**Comment by jennybc** [comment]
Oh sorry, I wasn't clear. I meant: is it important to specify that this is a `global` variable, i.e.

```
environment:
  NOT_CRAN: true
```

versus

```
environment:
  global:
    NOT_CRAN: yes
```
