### ISSUE TITLE
use_build_ignore(): Handle directories specially

### ISSUE THREAD

**Issue by alandipert** [r-lib/usethis#643]
Not a bug, but an idea for possible enhancement to `use_build_ignore()`.

Currently, all arguments to `use_build_ignore` are terminated with a `$` before being written to `.Rbuildignore`. This is helpful for individual files. However, If any argument is a directory, the result is not what I expected: none of the contents of the directory are ignored.

One mitigation that comes to mind is to test each `file` and determine if it's a directory. If it is, don't terminate its `.Rbuildignore` line with `$`. I'm happy to contribute a PR to do this if one is desired.

```r
# create a directory
dir.create("foob")
# ignore it
usethis::use_build_ignore("foob")
# observe that ^foob$ has been added (which will not match the contents of foob/)
file.show(".Rbuildignore")
```

**Comment by jennybc** [comment]
I see different behaviour. For example, our standard location for GitHub community files is `.github/` and the standard entry in `.Rbuildignore` is `^\.github$` and it appears to be working as advertised.

**Comment by jennybc** [comment]
Here's the relevant bit of WRE

>  To exclude files from being put into the package, one can specify a list of exclude patterns in file .Rbuildignore in the top-level source directory. These patterns should be Perl-like regular expressions (see the help for regexp in R for the precise details), one per line, to be matched case-insensitively against the file and directory names relative to the top-level package source directory.

Could your specific example be special in some way?

**Comment by alandipert** [comment]
Thanks for looking into it. I tried with vanilla `create_package`/`R CMD build` and also can't reproduce. So, something else must be going on. If I can track it down I'll be back. Until then, sorry for the noise 😄
