### ISSUE TITLE
Function to do the remote rename dance

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#649]
When people first start contributing to a package one of the first major roadblocks is they likely have cloned the repo from the initial repo rather than from a fork. So they have to 

1) rename the origin remote to upstream then add the new remote as origin
2) or burn it all down and re-clone from their fork, then add the origin as upstream later.

As far as I know there is no real way to do either step without needing command line git or something like Sourcetree, so it ends up being a pretty big hurdle for new contributors.

**Comment by hadley** [comment]
I think we should probably test for this situation in `pr_init()`, and if in an interactive environment, offer to resolve it automatically.

**Comment by jennybc** [comment]
`use_git_remote()` makes this possible and the "remote rename dance" is one of the examples. It's possible we'll even provide more support in a hypothetical "unbork my fork" function (#618 Undo commits to a fork's master branch).
