### ISSUE TITLE
Publicise git_sitrep() and git_vacciniate()?

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#650]
These are not yet on the pkgdown function-references page, I think it could be useful that they be there.

Assuming that this is OK, and that **Git and GitHub** is the right place to put these in function-references.

Thanks!

**Comment by jennybc** [comment]
Sounds good, yes!

**Comment by ijlyttle** [comment]
This was fixed in #652, but one of my superpowers seems to be finding ways of avoiding GitHub's automatic issue-closing mechanism, even after the occasion of @hadley taking the time to explain it to me (to little effect, apparently 🙃).

**Comment by hadley** [comment]
To Lyttle effect 😛
