### ISSUE TITLE
use_github requires UK spelling of "organisation"

### ISSUE THREAD

**Issue by webbedfeet** [r-lib/usethis#655]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by webbedfeet** [comment]
This got saved before I finished. 

The US spelling is "organization", and it gives an error:

```
> use_github(organization="araastat")
Error in use_github(organization = "araastat") : 
  unused argument (organization = "araastat")
```

**Comment by batpigandme** [comment]
Possibly useful info for a PR:

In ggplot2 `color` works as an alias for `colour`, but was recently given a more robust implementation (discussion here)
https://github.com/tidyverse/ggplot2/issues/2649
```r
#' Standardise aesthetic names
#'
#' This function standardises aesthetic names by converting `color` to `colour`
#' (also in substrings, e.g. `point_color` to `point_colour`) and translating old style
#' R names to ggplot names (eg. `pch` to `shape`, `cex` to `size`).
#' @param x Character vector of aesthetics names, such as `c("colour", "size", "shape")`.
#' @return Character vector of standardised names.
#' @keywords internal
#' @export
standardise_aes_names <- function(x) {
  # convert US to UK spelling of colour
  x <- sub("color", "colour", x, fixed = TRUE)


  # convert old-style aesthetics names to ggplot version
  revalue(x, ggplot_global$base_to_ggplot)
}
```
https://github.com/tidyverse/ggplot2/blob/7f13dfafccea19304ae140eb14a6cdfd5b5275ec/R/aes.r#L144-L159

**Comment by jennybc** [comment]
It's conceivable we should just use "organization" here because it's really a parameter of the GitHub API. And they use the American spelling.

**Comment by jennybc** [comment]
Or use `owner` and default to the user associated with the `auth_token`. A complete end run around the problem.

**Comment by hadley** [comment]
Or since it's the first argument, we don't worry about it at all? I think it's going to be unusual to name it.
