### ISSUE TITLE
Add parameters to use_pkgdown()?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#660]
At the moment `use_pkgdown()` allows to choose the destination of the website in the config file, but nothing else. Would it be possible to have a `template` argument that'd create these lines

```yaml
template:
  package: <template-name>
```

Or even have a `config_template` argument so one could have a boilerplate config (with template, TOC depth, authors field etc.)?

I'd understand if this were not in scope :-)

**Comment by maelle** [comment]
I think I used the wrong word, rather than boilerplate config I mean e.g. an organization would have an internal package with a pkgdown config file, and one would use that in `use_pkgdown()`, to make sure all packages of the organization start out with the organization template etc.

**Comment by jennybc** [comment]
Will you sketch out the interface you have in mind here? I'm assuming you'll propose something that makes it possible to fetch a `_pkgdown.yml` template file from another package and, probably via `...`, to pass data to it (?).

Literally, how would the signature of `use_pkgdown(config_file = "_pkgdown.yml", destdir = "docs")` change under this proposal?

**Comment by hadley** [comment]
If you’re wrapping for an organsition usethis, wouldn’t it be simpler to wrap `use_template() directly?

**Comment by maelle** [comment]
Indeed! Might be easier for everyone. It means I'd probably need one package with the template (easy to install, for Travis&co) and one with the wrapper, depending on  usethis. Probably fine since there are other functions that package dependent on usethis could have.  https://github.com/ropenscilabs/rodev#functions

Summary: good idea, thanks, I understand if you close this 🙂

**Comment by jennybc** [comment]
OK yeah I will close. If you go on to implement this for ropensci, feel free to comment / link here so others can see an example of extending to usethis to facilitate this sort of custom workflow
