### ISSUE TITLE
use_package_doc: prefill from DESCRIPTION

### ISSUE THREAD

**Issue by GregorDeCillia** [r-lib/usethis#662]
This feature request suggests adapting the template for package-level documentation. The DESCRIPTION file already provides a title and description for a package. It should be relatively straightforward to utilize these entries in the `use_package_docs()` templates as `@title` and `@description`. For example.

```r
#' @importFrom desc desc_get_field
use_package_doc <- function() {
  check_is_package("use_package_doc()")
  use_template(
    "packagename-package.R", 
    package_doc_path(), 
    data = list(
      title = desc_get_field("Title"),
      description = desc_get_field("description")
    )
  )
}
```

First lines of the template:

```
#' @title {{{ title }}}
#' @description {{{ description }}}
"_Package"
```

The current template provides no hints how the final roxygen block should look like. Also, it seems most r-lib and tidyverse packages are consistent between the DESCRIPTION file and the package-level documentation in that regard. This feature would encourage other package authors to adapt this consistency.

If this feature is considered worthwhile, I can submit a PR with a new implementation of `inst/templates/packagename-package.R` and `use_package_doc()`.

**Comment by jennybc** [comment]
`use_package_doc()` already does what you are suggesting. 

>  Once you call `devtools::document()`, roxygen will flesh out the `.Rd` file using data from the `DESCRIPTION`.

So you won't see an explicit roxygen header appear. But rather the special sentinel will cause package-level documentation to be generated from DESCRIPTION.
