### ISSUE TITLE
Could create_from_github() use rstudioapi::selectDirectory()?

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#664]
I am finding it to be a friction point to find, then type, the `destdir` argument to `create_from_github()`.

If `destdir` is `NULL` and `create_from_github()` is called interactively (and if using RStudio), could the behavior be changed to invoke `rstudioapi::selectDirectory()`?

Happy to make a PR, if you like.

PS - could this idea be extended to `create_project()`, `create_package()`, `use_course()`, or others?

**Comment by jennybc** [comment]
In discussion in #665, we decided to not pursue this at this time.

**Comment by ijlyttle** [comment]
I appreciate you all considering this, thanks!
