### ISSUE TITLE
create_package creating a directory

### ISSUE THREAD

**Issue by topepo** [r-lib/usethis#67]
For `usethis`, isn't setting the path once the package is created a little awkward (as done in the README file)? Almost everything from `devtools` is done inside the package directory. `create_package` could create the package files and subdirectories in the current path instead.

**Comment by hadley** [comment]
It is, and that's how you'd usually use it. Let me tweak the readme to better reflect that

**Comment by hadley** [comment]
Hopefully that's a bit better - it's hard to simulate realistic interactive usage with Rmarkdown because knitr resets the working directory between chunks
