### ISSUE TITLE
Rationalize styling

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#673]
Various styling issues have accumulated:

Are we consistent in our use of `ui_THIS()` vs `ui_THAT()`? For example, I think URLs should probably be treated with `ui_field()` not `ui_value()`. Maybe we should create `ui_url()` (even if it's aliased to `ui_field()`.

The way we handle multi-line messages is all over the place. Mostly, I think, because it's not clear what you're actually supposed to do. Write that down in principles.md then fix obvious violations.

**Comment by krlmlr** [comment]
I agree each kind of output should have its own `ui_...()` function, even if it's only a redirect. Specialized `ui_...()` functions could check the input format and warn (once) if there's a mismatch.

**Comment by jennybc** [comment]
Roll this into #956. Converting to cli would be an obvious time to rationalize usage and styling of `ui_*()` functions.
