### ISSUE TITLE
git2r_credentials() isn't exported

### ISSUE THREAD

**Issue by nbrgraphs** [r-lib/usethis#677]
```
> usethis::git2r_credentials()
Error: 'git2r_credentials' is not an exported object from 'namespace:usethis'
```

Version 1.4.0.9000, installed from GitHub today

**Comment by jennybc** [comment]
It's in the NAMESPACE

https://github.com/r-lib/usethis/blob/c5f9b3e8d05bdec0695e0871c9430ff3cdad33ac/NAMESPACE#L23

and I can call it

``` r
usethis::git2r_credentials()
#> NULL
```

<sup>Created on 2019-03-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I think something else must be going on with your session or installation.

Can you do `reprex::reprex(devtools::package_info("usethis"))`?

**Comment by nbrgraphs** [comment]
Tested again and now it's working... sorry!
