### ISSUE TITLE
pr_finish() could offer to remove the remote

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#679]
As @jtr13 points out, `pr_fetch()` etc. leave a remote behind, even when you use `pr_finish()`. Perhaps it should offer to remove the remote. I just need to determine if other branches are currently tracking a branch associated with that remote.

**Comment by jtr13** [comment]
Or you if you want to go really low key, `pr_finish()` could simply provide a message that says that remote <name> still exists and you can do X to remove it if no longer needed.

**Comment by jtr13** [comment]
Also, `pr_finish()` could be more informative if there's a problem switching back to master.
Example:
```
> pr_finish()
✔ Switching back to 'master' branch
Error in checkout_branch(lb[[1]], force) : 
  Error in 'git2r_checkout_tree': 1 conflict prevents checkout
```
`git` provides more detail:

```
$ git checkout master
error: The following untracked working tree files would be overwritten by checkout:
        fix_pr.Rmd
Please move or remove them before you switch branches.
Aborting
```
