### ISSUE TITLE
On RStudio Cloud, git_sitrep() and pr_push() contradict each other

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#685]
Hi,

I am mindful that you are pushing towards a release (for which I am very grateful). I am also mindful that this may be an RStudio Cloud issue, so I am prepared to be re-directed.

My motivation for using RStudio Cloud is to have an emergency-backup available at a workshop, in case we can't get anyone's laptop up-to-speed in time. I have set up a project, and created my `.Rprofile`, `.Renviron`, and `.gitconfig` files; `edit_r_profile()`, `edit_r_environ()`, `browse_github_pat()`, and `use_git_config()` all work perfectly.

For what it's worth, the config files are created in a directory called `/home/rstudio-user`.

Once I have everything set-up:

```r
usethis::git_sitrep()
```

```
User
* Name: 'Ian Lyttle'
* Email: 'ian.lyttle@schneider-electric.com'
* Protocol: 'HTTPS'
* Has SSH keys: FALSE
* Vaccinated: TRUE
git2r
* Supports SSH: TRUE
GitHub
* User: 'ijlyttle'
* Name: 'Ian Lyttle'
```

So far, so good. I used `create_from_github("r-lib/usethis")`, made a change, then called `pr_init("cloud-test")` - still good.

I run into a problem with `pr_push()`

```r
usethis::pr_push()
``` 

```
✔ Setting active project to '/home/rstudio-user/usethis'
✔ Checking that 'local/cloud-test' has changes in 'origin/cloud-test'
✔ Pushing local 'cloud-test' branch to 'origin/cloud-test'
 Error in git2r::push(git_repo(), name = remote_name, refspec = glue("refs/heads/{branch}:refs/heads/{remote_branch}"),  : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials 
```

I am using usethis 1.4.0.9000, installed from GitHub:

```
Built: R 3.5.2; ; 2019-03-31 23:09:42 UTC; unix
```

Any guidance gratefully appreciated, thanks!

**Comment by jennybc** [comment]
Can you try this again and show me the output of `create_from_github()`? I'm interested to see if a fork has been created, whether the main repo has been added as upstream, and what the URLs are.

Can you also confirm that `github_token()` shows your token?
Does `git_credentials()` reveal a `"cred_user_pass"` credential object, with that token?
Can I see `git2r::libgit2_features()`?

**Comment by ijlyttle** [comment]
Having followed your advice, and recreated my work, I suspect this was me doing Something Wrong™️. In the spirit of the "blameless post-mortem" (but I accept blame, nonetheless):

I think this was (perhaps still is) my unfamiliarity with RStudio Cloud - I was unaware that I had *two* copies of usethis: one in `/cloud/project` and another in `/home/rstudio-user`.

I think the default "conspicuous place" for RStudio Cloud is `/home/rstudio-user`, so I have no recollection of how I got a copy in `/cloud/project`. I suspect I was experimenting with `create_from_github()` without my PAT installed (just to see what would happen) - as a result the `/cloud/project` copy did **not** have the remotes set up "correctly".

Once I installed my PAT, I must have run `create_from_github()` again, creating my "secret" copy, then I tried to `pr_push()` from my "original" copy, hence the failure.

When I recreated the entire process with open eyes:

- PAT installed
- knowing where *the* copy is

everything worked well. In this most-recent instance, all of the calls you suggested - looking at remotes, `github_token()`, etc, did what I would expect.

My apologies for creating confusion, and my continued thanks for pointing me in the right direction. 

I have a couple of followup ideas that I'll post in the next note; I'd be happy to turn them in to issues if you will like.

**Comment by ijlyttle** [comment]
Followup notes:

- This is adjacent to #466, but I wonder what should be the default "conspicuous place" on RStudio Cloud. Currently, it seems to be `home/rstudio-user`, which I think is meant for dotfiles and the like. I wonder if the default conspicuous-place for RStudio Cloud should be `/cloud/project`.

- If I `create_from_github()` on someone else's repository for which I already have a GitHub fork (e.g. `r-lib/usethis`), the copy that gets cloned to my computer is *my* master branch, not the upstream master branch. I will want to start my work from the upstream master, rather than my likely-stale master. I know that this is easily fixed with `pr_pull_upstream()`, but I wonder if this might be a useful default behavior for `create_from_github()`.

Happy to file issues or take further action as you see fit.

Thanks!

**Comment by jennybc** [comment]
Thanks for the detective work! Yes please do open one issue each for the two bullet points in last comment.
