### ISSUE TITLE
pr_push() should report on its success (or lack thereof)

### ISSUE THREAD

**Issue by jtr13** [r-lib/usethis#686]
I tested the `pr_fetch()`, `pr_push()`, `pr_finish()` sequence with a PR in which the contributor did not allow edits from maintainers. There was no indication that something was awry, though the changes were not pushed. (Further testing advised... just flagging this issue in case it's useful.)

**Comment by jennybc** [comment]
Were they not pushed? Or were they pushed into a branch in the main repo vs in the fork? I feel like I've seen the latter in some related, weird situations. If they are not pushed anywhere, I think you'll see some sort of message about that.

**Comment by jennybc** [comment]
I have thought about this and I think my initial investigation suggested that there's no practical way to know if you're allowed to push into the PR other than "just try it". And it is the default, so it's rare that it does not work.
