### ISSUE TITLE
Is the use of cat_line for questions possibly too quiet?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#689]
I've just set `options(usethis.quiet = TRUE)` and after that when using `use_git()`, there's no question asked, just the possible answers, i.e. I get

```r
1: For sure
2: Absolutely not
3: Not now
```

not

```r
There are 12 uncommitted files:
* '.gitignore'
* '.Rbuildignore'
* 'CODE_OF_CONDUCT.md'
* 'cooooool.cats.Rproj'
* 'DESCRIPTION'
* 'LICENSE'
* 'LICENSE.md'
* 'NAMESPACE'
* 'R/'
* 'README.Rmd'
* 'tests/'
* 'vignettes/'
Is it ok to commit them?

1: No way
2: For sure
3: Absolutely not
```

as I'd expect.

**Comment by maelle** [comment]
What I mean is I wonder whether the call to `cat_line()` inside e.g. `ui_yeah()` should have `quiet=FALSE`.

**Comment by jennybc** [comment]
If you have set the option to achieve one thing (silence) but then you want another (verbosity), you'll have to toggle it yourself. We need to be consistent within usethis.

`withr::with_options()` or `withr::local_options()` might provide a nice solution for you.
