### ISSUE TITLE
Custom completers for a few functions

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#69]
`use_dev_package()` like https://github.com/hadley/devtools/pull/1595
`use_package()` maybe just use packages from `library()`?
`use_data()` names from `ls()`?

**Comment by hadley** [comment]
I like it!

**Comment by hadley** [comment]
Is completeme on CRAN yet/

**Comment by jimhester** [comment]
No, not yet, but I could probably submit it tomorrow if needed

**Comment by hadley** [comment]
Don't worry about it - we'll save this for the next release of usethis.

**Comment by hadley** [comment]
@jimhester any interest in finishing this off, or should we just close?

**Comment by jimhester** [comment]
I guess we should just close, it would need completeme to be more fleshed out which doesn't seem a high priority.
