### ISSUE TITLE
feature request: use_openmp()

### ISSUE THREAD

**Issue by jackwasey** [r-lib/usethis#690]
OpenMP can be a major performance factor in some applications, and also a frequent cause of misery in setting up Makevars, as evidenced by various stackoverflow questions.

https://github.com/r-lib/usethis/issues/688 about RcppEigen and openmp is somewhat related. Having `use_openmp()` would transfer responsibility for OpenMP activation to the user, rather than `use_rcpp_eigen()` potentially doing it for them.

I've personally had a bad interaction between CRAN's solaris testing and OpenMP in a C++11 enabled package a couple of years ago. I don't know where this stands now, but `usethis` could check for this kind of thing, and warn or stop on such interactions, again helping the end user avoid hours of trial-and-error with CRAN or searching the web.

This could also make a skeleton C or C++ file (or Fortran!) with OpenMP pragmas defined for a simple loop.

**Comment by coatless** [comment]
Standard Disclaimer: Here be dragons. 

The push for OpenMP is good and bad. Many of the StackOverflow posts and high traffic personal site posts I've written deal with OpenMP. In short, the summary here is:

- Multithreading in _R_ has to be done carefully. From the [Writing R Extensions manual](http://cran.r-project.org/doc/manuals/r-patched/R-exts.html#OpenMP-support):

> Calling any of the R API from threaded code is ‘for experts only’: they will need to read the source code to determine if it is thread-safe.

- Until R 3.4.* there wasn't a guarantee of OpenMP on all supported _R_ platforms.
    - This requires using a special compiler outside of the Xcode CLI 
- State of link flags right now when a package has Fortran/C/C++ code.
    - c.f. [SO: CRAN-acceptable way of linking to OpenMP some C code called from Rcpp](https://stackoverflow.com/questions/54056594/cran-acceptable-way-of-linking-to-openmp-some-c-code-called-from-rcpp), [WRE Section: 1.2.1.1](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#OpenMP-support)
- Lastly, `usethis` doesn't have a good way of parsing the `Makevars` file similar to `desc`, c.f. #307. Once that's done... I think this would be a bit more approachable.

**Comment by jennybc** [comment]
I am reluctant to wade into this, especially right now, before release. usethis's current target audience leans more towards people who are still unclear on the requirements of an R package vs. those writing compiled code.

I'd be happy for us to take this up again at a later date, when it's more clear what one should do around OpenMP and when usethis has better tooling for modifying package parts related to compiled code.

**Comment by jackwasey** [comment]
These are all excellent points. Thanks for considering.
