### ISSUE TITLE
Let git_vaccinate() fetch from gitignore.io

### ISSUE THREAD

**Issue by katrinleinweber** [r-lib/usethis#709]
Thanks for the timely 1.5.0 update :-)

Since:

- [`git_vaccinate()`](https://github.com/r-lib/usethis/blob/2a862fa9c3420ff9282896331053c9fbaf12a54a/R/git.R#L593-L622) currently has a list of only 4 ignore rules hardcoded, but 
- R-related "credentials" can be at least in [one other place](https://github.com/github/gitignore/pull/1530),

I was wondering whether the function should mabye pull [`R.gitignore` from gitignore.io plus the OS-specific `.gitignore`](https://github.com/github/gitignore/blob/master/R.gitignore). The latter could be detected with some [code like `switch(Sys.info()[['sysname']], ...`](https://stackoverflow.com/a/4463105).

Or might it be too drastic to push 2 community-developed `.gitignore` templates onto a user's machine?

**Comment by jennybc** [comment]
I see that gitignore is [on CRAN now](https://cran.r-project.org/package=gitignore). Congrats! I think that means this immediate issue can be closed, but does not preclude some future conversation about possible connections.
