### ISSUE TITLE
Creating `use_reexport()` in the spirit of `use_pipe()`

### ISSUE THREAD

**Issue by kvasilopoulos** [r-lib/usethis#710]
Have you consider creating  a function `use_reexport()`?

Usage:
```r
use_reexport("tibble", "data_frame")
```

That will generate the following code, probably in the reexports.R or reexports-tibble.R
```r
#' @importFrom tibble data_frame
#' @export
tibble::data_frame
```

**Comment by jennybc** [comment]
At this point, I think our targeted functions for this are getting the job done, such as `use_pipe()`, `use_tibble()`, or `use_tidy_eval()`.
