### ISSUE TITLE
Search is partially broken

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#712]
The usethis site has search now 🎉 but some searches lead to bad URLs that 404.

https://usethis.r-lib.org

Successful search terms: "create", "credentials".
Unsuccessful search terms: "https", "ssh", "git2r", "continuous".

The unsuccessful terms produce a promising dropdown menu, but all of the associated links are broken in this sort of way:

```
https://usethis.r-lib.org/reference/undefined?q=continuous#section-continuous-integration
https://usethis.r-lib.org/reference/undefined?q=ssh#value
https://usethis.r-lib.org/reference/undefined?q=git2r#arguments
```

I cannot break the dplyr search in the same way. I note that dplyr's site uses tidytemplate. Is that somehow the favourable difference?

**Comment by jennybc** [comment]
Probably related to 

https://github.com/tidyverse/dplyr/issues/4151

https://github.com/algolia/docsearch-configs/commit/cc56f8b7885ca46a37a719419d964c7d92a3ba26

**Comment by jayhesselberth** [comment]
Your [config](https://github.com/algolia/docsearch-configs/blob/6cfffb135b98532c9e22b43543f148106866aede/configs/usethis.json) needs to match the [tidyverse config](https://github.com/algolia/docsearch-configs/blob/e3e6a22562773f6e95ee6d3312c93e71bcb69685/configs/tidyverse.json). In particular, you are missing this section:

```json
  "custom_settings": {
    "separatorsToIndex": "_",
    "attributesToRetrieve": [
      "hierarchy",
      "content",
      "anchor",
      "url",
      "url_without_anchor"
    ]
  },
```
Where did you get your config? Was it auto-generated?

**Comment by jennybc** [comment]
Yeah that just "happened".

**Comment by jayhesselberth** [comment]
You mean pkgdown generated the docsearch config? If so, we should update the default.

**Comment by jennybc** [comment]
We got algolia turned on in August 2018 (as their config suggests), but then I didn't do anything about it until just now. So perhaps the config they would generate now would be correct? But in any case, I think I need to ask them to update it to match what you've got above.

**Comment by jennybc** [comment]
> You mean pkgdown generated the docsearch config? If so, we should update the default.

I have no idea who made it.

**Comment by jayhesselberth** [comment]
Ah, yes @s-pace can help you out.

**Comment by jennybc** [comment]
Algolia config for usethis:

https://github.com/algolia/docsearch-configs/blob/master/configs/usethis.json

**Comment by jayhesselberth** [comment]
pkgdown auto-gernerates one for you. Yours is here:

https://usethis.r-lib.org/docsearch.json

**Comment by jennybc** [comment]
So I want algolia to update their config to match the auto-generated one within usethis's site?

Or I can take matters into my own hands and fix this myself?

**Comment by jayhesselberth** [comment]
Yes Algolia needs to update their config to the auto-generated one.

You could also submit a PR to the dosearch-config repo but usually @s-pace just makes this happen.

**Comment by jennybc** [comment]
I made a PR with the auto-generated config, in case it saves @s-pace some work.

**Comment by s-pace** [comment]
👋 

@jennybc Thank you for the PR 🙏 

It should solves this issue. I let you integrate the suggestions an I will merge it ASAP.

**Comment by jennybc** [comment]
Fixed via https://github.com/algolia/docsearch-configs/pull/818
