### ISSUE TITLE
New use_tidy_style()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/usethis#72]
should run `styler::style_pkg()`, perhaps exposing the `strict` argument.

@lorenzwalthert: Would you like to take a stab? It's not urgent, but eventually we'd like to point contributors to this function.

**Comment by lorenzwalthert** [comment]
Sure. Should we wait with this until styler is released on CRAN?

**Comment by hadley** [comment]
Yeah, this will need styler on CRAN.
