### ISSUE TITLE
Could use_roxygen_md() give more info on roxygen2md package?

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#723]
This is one of the feedbacks from a successful workshop where we used **usethis 1.5.0**.

If you create a package from nothing, using `create_package()`, then `document()` it before calling `use_roxygen_md()`, you get in a situation where you get the **roxygen2md** message:

https://github.com/r-lib/usethis/blob/a7d6eb42d457e893f384bc9788a0b931bfef4479/R/roxygen.R#L19

Because the roxygen2md package is not (yet ?) on CRAN, it might be useful to provide explicit feedback that you will have to use something like `devtools::install_github("r-lib/roxygen2md")`. 

I see that this is implied in the function documentation for `use_roxygen_md()`.

Also, if roxygen2md will be on CRAN in the near future, perhaps this issue takes care of itself.

---

One possible solution may be to add an optional `msg` argument to the internal function `check_package()`.

Happy to make a PR following any approach you may suggest.

**Comment by hadley** [comment]
I'd rather solve this by getting roxygen2md on CRAN.

**Comment by krlmlr** [comment]
On its way, along with 26 other newbies:

``` r
foghorn::cran_incoming("roxygen2md")
#> # A tibble: 1 x 4
#>   package    version cran_folder time               
#>   <chr>      <chr>   <fct>       <dttm>             
#> 1 roxygen2md 1.0.0   newbies     2019-05-29 23:05:00
dplyr::count(foghorn::cran_incoming(), cran_folder)
#> # A tibble: 4 x 2
#>   cran_folder     n
#>   <fct>       <int>
#> 1 newbies        26
#> 2 inspect         2
#> 3 pretest         3
#> 4 archive        84
```

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
On CRAN now. Had to add examples surrounded by `if (interactive()) {}` for acceptance.

**Comment by ijlyttle** [comment]
Thanks! I trust it's OK for me to close the issue.
