### ISSUE TITLE
remotes instead of devtools in package-README

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/usethis#733]
As a package developer, I'd like use_readme_* to give github install instructions using remotes instead of devtools, so that I don't have to help people debug why certain packages can't install.

I've been seeing the "install using remotes instead of devtools" confusion in a lot of repos. Should the Readme template suggest remotes directly instead of devtools?

**Comment by jennybc** [comment]
We actually prefer that the default README instructions use devtools and not remotes.

devtools is thought of as the main, user-oriented package for this toolkit and remotes is more computer-facing and developer-oriented. For example, I would do `devtools::install_github()` in a README but `remotes::install_github()` in file like `.travis.yml`.

That being said, you can of course recommend either, but that is why the template inside of usethis is the way that it is.

>  give github install instructions using remotes instead of devtools, so that I don't have to help people debug why certain packages can't install

I'm not entirely sure what this refers to, but if you can make it concrete, it sounds like a valid issue to open on devtools.

**Comment by jonthegeek** [comment]
@jennybc it was inspired by this (plus a few related things that came through on repos I'm watching... Although it may have actually been entirely on rlang and thus maybe not a big deal): https://github.com/r-lib/rlang/issues/769

**Comment by jennybc** [comment]
I think the general advice we want in the template remains `devtools::install_github()`.

Let's see if @jimhester has anything to say about this: are there specific packages for which we would want to recommend `remotes::install_github()`, even in a README?

**Comment by jonthegeek** [comment]
If it's only packages that devtools depends on (directly or indirectly) that have the problem, it's probably ignorable. I didn't know devtools was still the general recommendation. So... Nevermind, unless Jim says otherwise!

**Comment by jimhester** [comment]
If we were going to change the template in usethis I would be more in favor of changing it to pak than I would to change it to use remotes. And in general devtools is fine, the only time you run into problems is if the package is a devtools dependency _and_ you are on windows _and_ the package uses compiled code.
