### ISSUE TITLE
Code for Appveyor badge should be updated

### ISSUE THREAD

**Issue by GegznaV** [r-lib/usethis#735]
The current version of Appveyor badge generated by `usethis` in the **pkgdown** website of my package led to this image:
![image](https://user-images.githubusercontent.com/12725868/56851214-10499c00-6915-11e9-8de3-93e8b1a27f88.png)
On GitHub, the badge was displayed but the link did not work (it seemed that the badge had no link).

I expect either a correct code for badge that works as expected or a note / warning on how to fix the issue manually.

---

**Details**

My package is called **RcmdrPlugin.biostat**. In Appveyor website I found out two things:

1) To make hyperlink working as expected, dot (`.`) in the link should be converted into a hyphen (`-`), e.g.:

- https://ci.appveyor.com/project/GegznaV/RcmdrPlugin.biostat
- https://ci.appveyor.com/project/GegznaV/rcmdrplugin-biostat/branch/master

Capital / non-capital letters are not so important.

2) Appveyor suggested using the code
 ` [![AppVeyor build status](https://ci.appveyor.com/api/projects/status/hm4h2rjb8ayr2df1/branch/master?svg=true)](https://ci.appveyor.com/project/GegznaV/rcmdrplugin-biostat/branch/master)` for the badge [![AppVeyor build status](https://ci.appveyor.com/api/projects/status/hm4h2rjb8ayr2df1/branch/master?svg=true)](https://ci.appveyor.com/project/GegznaV/rcmdrplugin-biostat/branch/master)
It works not only on GitHub but also on **pkgdown** website. The code includes security token so I'm not sure if it could be reproduced by **usethis**. But **usethis** could give instructions, how to fix the issue if one wants to use the badge in **pkgdown** website. E.g., a message like this could be generated:
"The code of badge that is displayed correctly not only on GitHub could be found at:
https://ci.appveyor.com/project/GegznaV/rcmdrplugin-biostat/settings/badges"

**Comment by hadley** [comment]
We're moving away from appyveyor in favour of GitHub actions, so we'd probably accept a PR that fixed this, but we're unlikely to do ourselves.
