### ISSUE TITLE
use_data_raw() creates template usethis::use_data("{name}")

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/usethis#736]
`use_data_raw()` creates template `usethis::use_data("{name}")` but `use_data()` expects unquoted names.

**Comment by hadley** [comment]
And it probably should set `overwrite = TRUE`

**Comment by cderv** [comment]
I also encountered this error. Good to know it is already reported
@batpigandme I think this could be fixed during [tidydevday](https://github.com/tidyverse/dev-day-2019) next monday
