### ISSUE TITLE
use_rmd_setup_chunk()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#74]
I frequently dig around in existing `README.Rmd` files for the standard tidyverse setup chunk.

<pre><code>
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE
)
```
</pre></code>

Could usethis offer some support for inserting this or getting it on the clipboard? Or can we campaign for this to replace that first chunk in RStudio's `.Rmd` default new file?

**Comment by hadley** [comment]
It would be easy enough to just print, but then it doesn't really feel like a `use_` function. We also need to expose it as a regular text string so that the `readme.Rmd` generator can use it.

**Comment by hadley** [comment]
I think we should review all vignette/readme templates and make sure they include:

````

```{r, include = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE
)
```

```{r setup}
library({package}
```
````
