### ISSUE TITLE
use_release_issue workflow

### ISSUE THREAD

**Issue by dchiu911** [r-lib/usethis#740]
In the `use_release_issue()` checklist, should there be an extra step to update the pkgdown site after the package has been accepted on CRAN so that on the NEWS page the newest version shows the release date, instead of "Unreleased"? Something like this:
* [ ] `usethis::use_github_release()` 
* [ ] `pkgdown::build_site()` 
* [ ] `usethis::use_dev_version()`

**Comment by jennybc** [comment]
Yes.

**Comment by lorenzwalthert** [comment]
In addition, maybe a release is also a good moment to polish the source code and run styler so we could add such a bullet as well?

**Comment by hadley** [comment]
I would rather tackle this automatically in pkgdown or in the deployment system.
