### ISSUE TITLE
create_from_github() on Windows 

### ISSUE THREAD

**Issue by Chris-Engelhardt** [r-lib/usethis#746]
As @jennybc has mentioned elsewhere, getting R to work programmatically with GitHub on Windows can be a pain. Part of that pain stems from setting up ssh keys and making sure that git2r knows where to find them. I wrote the following gist, which is a aggregation of resources found in various usethis docs and #711. 

In light of @jennybc's message on Twitter (https://twitter.com/JennyBryan/status/1124346858841595905), my initial sense is to add more description to the docs on `create_from_github()` rather than create a separate function. Perhaps a Windows-specific note on how users might need to make explicit use of `use_git_credentials()`. What are your thoughts? I'd be happy to submit a PR. 

```r
prep_for_pr <- function(username, repo_spec){

use_git_protocol("ssh")
  
creds <- cred_ssh_key(publickey = glue("C:/Users/{username}/.ssh/id_rsa.pub"),
                      privatekey = glue("C:/Users/{username}/.ssh/id_rsa"), 
                      passphrase = character(0))    

use_git_credentials(credentials = creds)

create_from_github(glue("{repo_spec}", 
                   destdir = "C:/Users/{username}/Desktop"))
} 

prep_for_pr("chrisengelhardt", "r-lib/usethis")
```

**Comment by jennybc** [comment]
Yes a PR would be welcome!

I suggest you add a `@section` to the `create_from_github()` docs with verbatim code (not an `@example`!) with this snippet. You can just call `cred_ssh_key()` as `git2r::cred_ssh_key()` because anyone running usethis has git2r. Remove any use of glue and use `USERNAME` or some such to show people where their name goes. We've already got a `OWNER/REPO` convention running through other docs.

I think you also need to make it very clear that this is for an **SSH person**. Whereas I recommend HTTPS as the default on Windows. Precisely because of this sort of friction.

**Comment by Chris-Engelhardt** [comment]
Hi, @jennybc. This is my first contribution to the tidyverse, so I'm pretty excited about it! Thank you for welcoming a PR. 

As you will see below, I added to the `create_from_github()` docs, in line with your suggestions above. Do you have any additional comments/suggestions before I submit a PR? Happy to amend.  

```r
#' @seealso [use_github()] for GitHub setup advice. [git_protocol()] and
#'   [git_credentials()] for background on `protocol` and `credentials`.
#'   [use_course()] for one-time download of all files in a Git repo, without
#'   any local or remote Git operations.
#'  #### ------------ NEW DOCS ----------------- ####
#' @section Using SSH Keys on Windows:
#' If you are a Windows user and want to use SSH keys to authenticate to Github,
#' we advise that you explicitly specify the paths to your keys and register them
#' in the current R session.
#'
#' Note: *This is for SSH authentication only.*
#'
#' In the snippet below, replace <USERNAME> with your Windows username. Replace
#' <OWNER/REPO> with the appropriate GitHub specificaction.
#'
#' \preformatted{use_git_protocol("ssh")
#'
#' creds <- git2r::cred_ssh_key(publickey = "C:/Users/<USERNAME>/.ssh/id_rsa.pub",
#'                              privatekey = "C:/Users/<USERNAME>/.ssh/id_rsa",
#'                              passphrase = character(0))
#'
#' use_git_credentials(credentials = creds)
#'
#' create_from_github(repo_spec = "<OWNER/REPO>",
#'                    destdir = "C:/Users/<USERNAME>/Desktop")
#' }
#' #### ------------ END NEW DOCS ----------------- ####
#' @inheritParams create_package
```

**Comment by jennybc** [comment]
Looks good! I might tweak, in your PR or after merge, but this is great.

We generally use markdown syntax in our roxygen comments, so I think your use of `\preformatted{}` can be replaced with regular "three backtick fencing".

**Comment by Chris-Engelhardt** [comment]
Cool! I'll fix the fencing and submit a PR. Thanks, Jenny!
