### ISSUE TITLE
improve documentation about use_pkgdown_travis()

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#748]
When I used `use_pkgdown_travis()`, I was suprised to discover that is was settings things up for travis **for a gh_page github deployment**. It has created th gh-page branch and pushed to github. 

I was expecting that the `.travis.yml` would be filled with some template stuff and that some manual step would be required based on where I would deploy (netlify vs github for example) but not that it would do things on my git repo for me regarding github. 

I did not realize that because it is not detailed in the documentation
https://github.com/r-lib/usethis/blob/815debaca2b80036d3eea1366195087da1cab0f6/R/pkgdown.R#L7-L8

How about some improvement in the documentation about this deployment process working only with github ?

**Comment by jennybc** [comment]
Sure, better docs would be great.

**Comment by alexpghayes** [comment]
Second this request. Just ran into 

```r

> travis::use_travis_deploy()
Authenticating with GitHub
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in get_repo_data(repo, gh_token = gh_token) : 
  Not Found (HTTP 404). Failed to retrieve repo information for: alexpghayes/distributions.
```

and pretty stuck debugging.

**Comment by jennybc** [comment]
@alexpghayes Your issue sounds like it belong on the [travis](https://github.com/ropenscilabs/travis) repo.

**Comment by cderv** [comment]
It seems things will change about pkgdown deployment (https://github.com/r-lib/pkgdown/issues/994#issuecomment-493474345)

💭 This may not be the time to improve current doc ? 🤔
