### ISSUE TITLE
Nicer error when trying to use_pkgdown_travis on an already setup repo

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#749]
When you try to use `use_pkgdown_travis` on an already setup repo (by error or to see back the advices for .travis.yml), you got an error
```r
> usethis::use_pkgdown_travis()
✔ Setting active project to 'C:/Users/chris/Documents/DEV_R/#project/crrri'
● Set up deploy keys by running `travis::use_travis_deploy()`
● Insert the following code in '.travis.yml'
  before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
  deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
  [Copied to clipboard]
Error in gh::gh("POST /repos/:owner/:repo/git/refs", owner = github_owner(),  : 
  GitHub API error (422): 422 Unprocessable Entity
  Reference already exists
````

I think the error message could be nicer on what is going on (I guess gh-page branch already exists here). ☺️ 

I can try a PR on this if you want, or this is something for tidydevday I guess

**Comment by jennybc** [comment]
While, in theory, I'm in favour of a better message, I'm skeptical if the added complexity/fragility is justified by the volume of usage. This is a pretty niche function, I think. But I'm willing to be pleasantly surprised 😁

**Comment by alexpghayes** [comment]
I just ran into this.

**Comment by cderv** [comment]
It seems things will change regarding pkgdown deployment (https://github.com/r-lib/pkgdown/issues/994#issuecomment-493474345)
It is one more point for team skeptical about this issue 😄  

This could be close or just put on hold maybe.
