### ISSUE TITLE
Should use_pipe() use a different template if the docs are markdown?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#754]
I.e. if there's a 

```
Roxygen: list(markdown = TRUE)
```

line in DESCRIPTION, should 

https://github.com/r-lib/usethis/blob/815debaca2b80036d3eea1366195087da1cab0f6/inst/templates/pipe.R#L3

use Markdown syntax?

**Comment by jennybc** [comment]
I'd say that we're comfortable with this syntax. Having a single template keeps things simpler and it's possible there's even a reason to prefer it here, i.e. maybe there's something special about link-y documentation for an operator.
