### ISSUE TITLE
support multiple issue issue templates

### ISSUE THREAD

**Issue by maxheld83** [r-lib/usethis#755]
It might be nice to add *several* issue templates, from which people can than choose the type of issue (say, bug report or feature request). 

Like so:

![new-issue-page-with-multiple-templates](https://user-images.githubusercontent.com/5372770/57464040-48899c80-727c-11e9-95c3-d9aa2d6bed66.png)

This could help people to self-filter their issues a bit, maybe even reducing the issue load.

FYI, current issue template is also now superseded by a new format, says github when inspecting the source for `usethis::use_tidy_issue_template()`:

<img width="1237" alt="old-template" src="https://user-images.githubusercontent.com/5372770/57464188-956d7300-727c-11e9-8ce1-89f5dc5f1b64.png">

cc @batpigandme 

Also, maybe this would be a nice tdd-issue? (can't tag it).

**Comment by jennybc** [comment]
I think updating the current, sole issue template should be in a separate issue from the possibility of having multiple templates.

**Comment by hadley** [comment]
Yeah, and the multiple template issue isn't a great fit for TDD since we need to decide on which templates first.

**Comment by hadley** [comment]
I don't find these templates terribly useful, and we don't have a concrete proposal here, so I think it's time to close this issue.
