### ISSUE TITLE
Tone down refusal of using tidyverse as a dependency

### ISSUE THREAD

**Issue by krlmlr** [r-lib/usethis#760]
I have put together a minimal set of "best practices" that help when you start using functions in data analysis projects: https://krlmlr.github.io/tidyprog/best-practices.html. This includes declaring the packages your analysis uses: https://github.com/krlmlr/tidyprog/blob/master/08-Best-practices.Rmd#L37.

`use_package("tidyverse")` is "verboten". This is for a good reason, but I think that a data analysis project that uses parts of R's packaging infrastructure should be allowed to at least depend on the tidyverse. Would you support an amendment of this check?

**Comment by jennybc** [comment]
Sure would you like to outline your proposal, for discussion? If we can agree on what to do about this, then this could become an issue for tidyverse dev day. I'm going to apply that label a bit prematurely now, because it helps us with planning.

**Comment by krlmlr** [comment]
Perhaps:

"{ui_value(package)} is a meta-package and it is rarely a good idea to import it.  Please determine the specific underlying package(s) that offer the function(s) you need and depend on that instead. (For data analysis projects that use a package structure but do not implement a formal R package, adding {{ui_value(package)}} to `Depends` is a reasonable compromise. Use {ui_code(...)} to achieve this.)"
