### ISSUE TITLE
`use_version()` should detect a (development version) NEWS header

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#762]
When updating from a `dev` version to a non-`dev` version, it would be great if `use_version()` could detect that the first line of the NEWS was `# pkgname (development version)` and automatically overwrite that with `# pkgname <new_ver>`.

The current behavior just adds a new header, so you are stuck with:

```
# strapgod 0.0.2

# strapgod (development version)

* In dplyr 0.8.1, the behavior of `group_map()` was moved to `group_modify()`,
and `group_map()` was repurposed to always return a list. strapgod has been
updated to reflect these changes.

# strapgod 0.0.1

* Added a `NEWS.md` file to track changes to the package.

```

The suggestion from Jim is:

"I think just removing `# .* (development version)` if it is the first line would be sufficient to fix the common case at least..."

**Comment by hadley** [comment]
Want to take a stab at this?

**Comment by DavisVaughan** [comment]
Sure
