### ISSUE TITLE
Peculiar message from pr_fetch()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#764]
I made a PR from Windows then fetched it on macOS. This message is funky.

``` r
> pr_fetch(261)
✔ Setting active project to '/Users/jenny/rrr/reprex'
✔ Checking out PR 'tidyverse/reprex/#261' (@jennybc): 'Specify UTF-8 encoding to rmarkdown::render()'
ℹ Note that user does NOT allow maintainer to modify this PR at this time,
  although this can be changed.
✔ Creating local branch 'utf8-render'
✔ Setting upstream tracking branch for 'utf8-render' to 'origin/utf8-render'
✔ Switching to branch 'utf8-render'
```

And, yes, to be clear, I can (obviously) push into this PR.

**Comment by hadley** [comment]
Came here to mention this too:

```
✔ Checking out PR 'r-lib/pkgdown/#1028' (@jeroen): 'Add \'devel\' parameter'
ℹ Note that user does NOT allow maintainer to modify this PR at this time,
  although this can be changed.
✔ Creating local branch 'develparam'
✔ Setting upstream tracking branch for 'develparam' to 'origin/develparam'
✔ Switching to branch 'develparam'
```

**Comment by jennybc** [comment]
<img width="601" alt="Screen Shot 2019-07-02 at 3 35 08 PM" src="https://user-images.githubusercontent.com/599454/60551097-06f6fa00-9cdf-11e9-8c96-1ab14ea78b3e.png">

So I made another PR from my Windows VM and fetched on macOS.

And it's true that in this situation `pr$maintainer_can_modify` is `FALSE`, which makes no sense. But I note that `pr[["author-association"]]` is `'MEMBER'`. I don't recall ever seeing that field before, but this observation related to the fix I'm about to apply.

**Comment by jennybc** [comment]
My current hypothesis is that we're seeing this with (some subset) of internal PRs.
