### ISSUE TITLE
FR: write_over() improvements

### ISSUE THREAD

**Issue by krlmlr** [r-lib/usethis#767]
1. Preserve line ending. Otherwise we are too much dependent on the "eol" Git config settings. I have an implementation for transforming a file preserving line endings in {enc}, but I'm retiring it: https://github.com/krlmlr/enc/blob/master/R/io.R#L110.

1. Consider adding an `ask` argument that defaults to `interactive()`, so that other tools can call this function to unconditionally overwrite.

**Comment by hadley** [comment]
We also need to handle the case where the file doesn't yet exist; possible by reading the line endings from the `DESCRIPTION` (not sure where to look if the project isn't a package).
