### ISSUE TITLE
export github_x helpers

### ISSUE THREAD

**Issue by maxheld83** [r-lib/usethis#769]
I'd love to be able to use a bunch of the GitHub helpers in my own packages for building more usethis-style templates, including especially:

- `github_home()`
-  `check_uses_github()`

If you deem this useful, I'd be happy to write up a PR for this.
(perhaps during tdd?)

**Comment by jennybc** [comment]
We'll need to discuss -- if these functions god exported -- where they should live. I'm not sure I'd want usethis to acquire revdeps for this functionality. Possibilities other than usethis include gh and gert.

**Comment by hadley** [comment]
Yeah, we definitely don't want to expose these from usethis at this point in the game; they'll need considerable maturation before we'd want to share with the world. For now, I'd just recommend accepting code duplication as the best solution.
