### ISSUE TITLE
Rename use_tidy_versions()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#771]
`use_tidy_versions()` is *not* parallel to `use_tidy_ci()` or `use_tidy_github()`, i.e. it's not enforcing a policy we embrace unconditionally. Aggressive minimum versions are another feature that can make a package feel like a heavy dependency (in addition to having lots of dependencies).

**Comment by jennybc** [comment]
This should possibly get split into 2 functions, instead of 1 function with `source "local"` vs `source = "CRAN"`.

Brainstorming names:

  * `use_installed_versions()`
  * `use_local_versions()`
  * `use_cran_versions()`
  * `use_released_versions()`

**Comment by hadley** [comment]
I gave relatively little thought to the name because I don't think it's something anyone should be doing routinely. I added `@keyword internal` to hopefully reduce the number of people who stumble across it accidentally.
