### ISSUE TITLE
Code of Conduct link in README needs to be full URL

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#772]
There's a new CRAN check that gets triggered by README links to files below `.github/`, such as the code of conduct.

Make sure usethis's tools replace this internal link with a full URL. Probably to the file on GitHub? The one I just did "by hand" links to the file in the pkgdown site, which is probably a nice solution, but that can't really be the default strategy.

**Comment by hadley** [comment]
Note that problem still applies even if the file is in the root directory because we `.Rbuildignore` them to solve a different R CMD check problem.

**Comment by jennybc** [comment]
I'm tagging this for Tidyverse-dev-day. Even if someone opts NOT to fix the logic / template in usethis, making PRs to fix READMEs in existing repos would still be great. Here's the sort of commit that's needed to fix this *post hoc* in the case of a package that has a pkgdown site:

https://github.com/r-lib/usethis/commit/77d49e48b7582fe4f8b47e8ebe3b351dcf17e809

**Comment by krlmlr** [comment]
If pkgdown exposed its configuration settings, usethis could query and adapt.
