### ISSUE TITLE
no overwrite argument in use_vignette function, conflicts with error message

### ISSUE THREAD

**Issue by ras44** [r-lib/usethis#773]
Reprex: 

Ensure a package DESCRIPTION file already contains a value for VignetteBuilder, eg:
```
VignetteBuilder: utils
```

Then run 
```
usethis::use_vignette("my_vignette")
```
Response:
```
Error: VignetteBuilder has a different value in DESCRIPTION.Use `overwrite = TRUE` to overwrite.
```
But there is no overwrite argument in the `use_vignette` function.

**Comment by jennybc** [comment]
Is it this simple? Is it possible we need to append? Or fail early with a good message if it's hard to tell what to do?

Feels like a bit of research needs to be done here. From WRE:

> The ‘VignetteBuilder’ field names (in a comma-separated list) packages that provide an engine for building vignettes. These may include the current package, or ones listed in ‘Depends’, ‘Suggests’ or ‘Imports’. The utils package is always implicitly appended. See Non-Sweave vignettes for details. Note that if, for example, the vignette ‘engine’ is ‘knitr::rmarkdown’ this field needs to declare both knitr and rmarkdown.

[Non-Sweave vignettes](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Non_002dSweave-vignettes)
