### ISSUE TITLE
feature request: `use_tidy_api()` function to make API files

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/usethis#779]
Recently I have started to notice `API` files in `tidyverse` packages (e.g., [dplyr](https://github.com/rstudio/gt/blob/master/API), [gt](https://github.com/tidyverse/dplyr/blob/master/API), etc.) and was wondering if you would consider adding support for making such files in a function like `use_tidy_api()`? 

Currently, there doesn't seem to be a unified way to do it. Some people seem to use `pkgapi::extract_api()`, while others use `pkgattrs::write_pkg_api()`. 

The problem with the former is that it doesn't generate a file, but rather outputs the `API` as text which needs to be copied to `API` file. This means the API file needs to be manually generated after every single change to the package API.

The latter _does_ generate a file but doesn't seem to be working and the repo has been inactive for a while (https://github.com/rich-iannone/pkgattrs/issues/1).

**Comment by jennybc** [comment]
This practice isn't something we've reached consensus on for the tidyverse packages as a group. It's more of an individual maintainer thing. So that means I don't have a clear mandate or "spec"  to work against at this time.
