### ISSUE TITLE
Can't post release issue

### ISSUE THREAD

**Issue by lionel-** [r-lib/usethis#781]
My first problem is that usethis tries to post on origin rather than upstream. Since posting issues in forks is unlikely, would the following patch make sense?

```diff
--- a/R/release.R
+++ b/R/release.R
@@ -25,7 +25,7 @@ use_release_issue <- function(version = NULL) {
   checklist <- release_checklist(version)
 
   issue <- gh::gh("POST /repos/:owner/:repo/issues",
-    owner = github_owner(),
+    owner = github_owner_upstream() %||% github_owner(),
     repo = github_repo(),
     title = glue("Release {project_name()} {version}"),
     body = paste(checklist, "\n", collapse = "")
```

Then when I try with this patch, I get:

```
Error in gh_process_response(raw) : 
GitHub API error (404): 404 Not Found
Message: Not Found
Read more at https://developer.github.com/v3/issues/#create-an-issue

URL not found: https://api.github.com/repos/r-lib/vctrs/issues
```

Not sure what to do from here.

**Comment by jennybc** [comment]
OK I'll have a look at what's wrong.

But, as you have discovered, this function clearly currently expects that you are working on a repo that you "own", i.e. that `origin` is the repo where the issue should be opened. It's pretty rare for someone to be in a fork **and** have the authority to release a package. I think we (members of tidyverse & r-lib) should usually be working in the main repo and not have personal forks.

**Comment by lionel-** [comment]
I prefer working from personal forks, this keeps the main repo tidy (we often end up with dangling branches otherwise because the author forgot to remove it, and the other members don't know what it's about). Also when I own the repo (i.e. personal repos in `github.com/lionel-`), I still call it `upstream`. IIRC this strategy simplified github management in my Emacs config (mainly for interacting with the main github repo). Maybe I could find a way to change it.

**Comment by jennybc** [comment]
No, I think you're right that it should prefer `upstream` over `origin`, if both exist. It just doesn't come up in my personal workflow, which is why I've never noticed.

**Comment by lionel-** [comment]
I see the same issue with:

```r
usethis::use_tidy_thanks(from = "v0.3.1", to = "v0.4.0")
#> Resolving timestamp for ref 
#> Error in parse_github_remotes(url)[[1]] : subscript out of bounds
```

The error goes away when I temporarily rename `upstream` to `origin`.

**Comment by jennybc** [comment]
Yeah it makes sense that your workflow continues to expose cases where we've over-customized to the remote set up Hadley and I seem to share.

**Comment by jennybc** [comment]
Another case where we mis-handle the situation where user (e.g. me) has a personal fork of an r-lib or tidyverse package. Imagine my fork is `origin` and the main repo is `upstream`. When I `pr_fetch()`, I get a "false alarm" message:

```
i Note that user does NOT allow maintainer to modify this PR at this time,
  although this can be changed.
```

This is technically true, i.e. the `maintainer_can_modify` field truly is `FALSE` and I'm not sure that makes sense. But it's out of our control. The fact remains is that I can still push into the PR.

**Comment by lionel-** [comment]
I have started using `origin` instead of `upstream` to try and fix my issues with usethis. I think what I find confusing is that this only works as a default when you clone the upstream repo on your computer rather than your fork, and I tend to do the latter. Anyway, I don't want to cause trouble for usethis if I'm the only one to use the origin vs upstream non-convention.

**Comment by jennybc** [comment]
I think it's reasonable for us to behave well when someone has a personal fork (`origin`) AND has write permission on the main repo (`upstream`). When I swap out gert for git2r, I have to refactor all the git stuff and I hope to rationalize this at the same time.
