### ISSUE TITLE
use_tutorial() creates file in wrong location and ignores html built files, but run_tutorial() requires it

### ISSUE THREAD

**Issue by lwjohnst86** [r-lib/usethis#782]
`use_tutorial()` creates R Markdown files in `inst/tutorials/` as single files. But learnr requires them in individual folders:

> Create a tutorials directory within the inst sub-directory of your package and then create a directory for your tutorial there (e.g. inst/tutorials/hello, inst/tutorials/slidy, etc.). https://rstudio.github.io/learnr/publishing.html

Likewise, `use_tutorial()` adds git ignore to the generated html tutorials, but learnr requires the html files to be present: 

> Render your tutorial .Rmd to .html and include the rendered HTML in your R package (this will happen automatically during development & preview of the tutorial, you just need to be sure to include the .html file within the R package when you build it). https://rstudio.github.io/learnr/publishing.html

So when you run `run_tutorials()` for the tutorial, you get:

``` r
> learnr::run_tutorial("chapter1", package = "acdcourse")
Error in shiny_prerendered_html(input_rmd, encoding, render_args) : 
  Prerendered HTML file not found at ./chapter1.html
```

Not sure if there is a disconnect between usethis and learnr or if learnr intends to go the route as indicated by `use_tutorial()`.

**Comment by jennybc** [comment]
Hello folks with the `use_tutorial()` PR (#645) from tidyverse dev day!

@angela-li @xvrdm @jules32 @jessesadler

I'd appreciate your thoughts on this problem.

**Comment by jennybc** [comment]
Maybe people at the second tidyverse dev day can pick up this baton and push things forward.

**Comment by angela-li** [comment]
Yes, I believe the original team on this project (@jules32 @xvrdm and me) will all be at Tidyverse Dev Day #2, so we can plan to tackle this then!

**Comment by jules32** [comment]
Yes -- I haven't had a chance to think about it ahead of time but I'd love
to continue together on Monday!

**Comment by xvrdm** [comment]
Hi all!
Unfortunately I did not register in time for the conf (we realized too late that my “ticket” was only a prebooking) so I had to cancel the entire trip, including tidyverse dev day. 
😭😭 

Gutted I won’t be here, but I am sure you will teach this issue a lesson 🕵️‍♀️!

**Comment by jules32** [comment]
We are at tidyverse developer day and tackling this issue! With @angela-li @isteves!

**Comment by angela-li** [comment]
Hi @lwjohnst86! Thanks so much for reporting this. The development version of `learnr` no longer requires html files to be in the tutorial folder (this is a better practice, generally), so we will not implement the following in this bugfix:

> Render your tutorial .Rmd to .html and include the rendered HTML in your R package (this will happen automatically during development & preview of the tutorial, you just need to be sure to include the .html file within the R package when you build it). https://rstudio.github.io/learnr/publishing.html

You can install the dev version with `remotes::install_github("rstudio/learnr")` - make sure to install updated versions of dependencies too, especially rmarkdown. You can also see rstudio/learnr#169 for more info.
