### ISSUE TITLE
Improve error : "Error: `use_pipe()` requires that you use roxygen."

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/usethis#785]
Context : 

I run a batch of `usethis::use_package("foo")` commands and they run fine, then `usethis::use_pipe()` triggers the error :

> Error: `use_pipe()` requires that you use roxygen.

I make sure that *roxygen2* is installed and problem remains, I dig into the code and see that it's related to the description file not having the field "RoxygenNote".

This is solved simply by running `document()` beforehand. 

Maybe the error could contain something like "You might want to run devtools::document() before usethis::use_pipe()" ?

**Comment by jennybc** [comment]
Ha! I was working on `use_pipe()` on the plane yesterday and hit this frustration myself and have fixed in a branch. So when I bring that into master, this will get fixed.
