### ISSUE TITLE
Error when _R_CHECK_LENGTH_1_LOGIC2_=true

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/usethis#786]
This generates an error, looks like the same bug as r-lib/pkgdown#1064 and tidyverse/reprex#267

``` r
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_" = "true")

usethis::use_vignette("test")
```

You'll have to collapse templates before calling `whisker.render()`.

**Comment by jennybc** [comment]
I've made a PR to fix this in whisker itself, which will fix several packages, in a better way, than all of us working around it. Let's see if that gets any traction.

**Comment by jayhesselberth** [comment]
Perhaps you should also e-mail the whisker maintainer directly—it's been a few years since there was activity on the whisker Github repo.

**Comment by jennybc** [comment]
I have pinged him via another channel and note he'll be at useR! next week, which is plan C.

**Comment by jennybc** [comment]
✅ I've had successful communication with whisker maintainer and he'll look at the PR.

**Comment by hadley** [comment]
Fixed in https://github.com/edwindj/whisker/commit/9144a35466ef3716437e050356d90cb0108d07da, which I believe is now on CRAN thanks to @jennybc's help.
