### ISSUE TITLE
use_roxygen_md() provides wrong message for using roxygen2md()

### ISSUE THREAD

**Issue by lwjohnst86** [r-lib/usethis#790]
`use_roxygen_md()` gives the output:

```
● Run the following code, then rerun `devtools::document()`
  roxygen2md::roxygen2md("/home/luke/Desktop/zipffreq")
  [Copied to clipboard]
```

But `roxygen2md::roxygen2md()` docs say it only takes the `scope` argument:

> roxygen2md(scope = c("full", "simple", "none"))
> 
> `scope`: The scope of transformations: "simple" runs only transformations that shouldn't substantially change the resulting .Rd files, "full" runs all transformations. In larger packages, run "none", double-check and track the changes, and then run "simple" and then "full".

I assume `use_roxygen_md()` should give:

```
● Run the following code, then rerun `devtools::document()`
  roxygen2md::roxygen2md("full")
  [Copied to clipboard]
```

Or maybe `"simple"` instead of `"full"`.

Versions:

```
> packageVersion("roxygen2md")
[1] ‘1.0.0’
> packageVersion("usethis")
[1] ‘1.5.0’
```

**Comment by cderv** [comment]
This follows #723 where `roxygen2md` has been pushed to CRAN but no update made in usethis whereas changes have been made in `roxygen2md` in r-lib/roxygen2md@76b53f1486750826a9e7d0c76ced2985580df990 and r-lib/roxygen2md@634cd22c34886c21123224a333d79eb85ea72deb

Doc should obviously be updated 👍

**Comment by jennybc** [comment]
A PR would be very welcome. I suggest wording that is less specific, so we don't have this problem again, and that refers the user to the relevant function in roxygen2md.
