### ISSUE TITLE
`ui_yeah` and `ui_nope` option choices and ordering

### ISSUE THREAD

**Issue by rundel** [r-lib/usethis#796]
I like both of these functions and would like to use them in `ghclass` when users request potentially destructive actions. However, I'd like the option to control what choices are presented to the user and whether or not they are randomized.

Both of these behaviors were also unclear to me from the docs. 

Happy to propose a modified version of both if that would be helpful.

**Comment by jennybc** [comment]
It sounds like you might have some good suggestions for the docs here and also that you might ultimately want to inline versions of these functions in ghclass. A PR to drive discussion would be great.
