### ISSUE TITLE
Proposal : function use_todolist

### ISSUE THREAD

**Issue by CorentinLemaitre** [r-lib/usethis#800]
Hello,

First I am quite new to the building of package, i have start after a meetup that show how easy it is to do it with `usethis`. I did start to use it and it really great !  :clap: :clap: :clap: :clap:

When i start a project with R i try to keep my todolist nearby what i develop, it can be in one specific file or even in each function. what could be perfect is that when you build you package it search all todos and show it if you want to tick it.

**Comment by BastiHz** [comment]
@CorentinLemaitre Just in case you didn't know: There is an [RStudio addin ](https://github.com/dokato/todor)which can list all your projects TODO, FIXME, etc. It does not let you "tick" the items like you want to but it's useful nonetheless.

**Comment by CorentinLemaitre** [comment]
Sorry I did not answer... I tested it and it perfectly do the job and adapt even to non package project.
