### ISSUE TITLE
`use_data()` should prompt you to document your data set

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#801]
Currently `usethis::use_data(internal = FALSE)` just creates a `data/` folder and places the data in an rda file there. Since a `check()` warns that you should document your data files, it might be nice for usethis to prompt the user to do so as well. 

It might also go ahead and generate a data file in `R/data.R`.

Could it even go so far as to look at the columns in your dataset and generate a `@format` roxygen block that `\describe`s all the columns? That is done in the Documenting Data section in the link below.

See this section for exporting data, which mentions `usethis::use_data()`:
https://r-pkgs.org/data.html#data-data

And this section for documenting data sets, which could be updated if this feature is added:
https://r-pkgs.org/data.html#documenting-data

**Comment by jennybc** [comment]
This has been discussed before:

https://github.com/r-lib/usethis/issues/274

and it looks like any actual "doing" re: creating the docs should happen in roxygen2.

So usethis could:

  * TODAY: have better messaging about the need to document exported datasets
  * FUTURE: call this hypothetical function on roxygen2 to actually do it

**Comment by ijlyttle** [comment]
FWIW, we worked on something related at Uncoast Unconf: https://uncoast-unconf.github.io/steward/articles/steward.html#create

Admittedly, this approach may be a lot heavier than what you are proposing here, but if there is something in "steward" that can help the effort, you are welcome to it.
