### ISSUE TITLE
provide possibility to reorder package names in use_package

### ISSUE THREAD

**Issue by espinielli** [r-lib/usethis#803]
As @hadley writes in [Section 5.1 of R Packages](https://r-pkgs.org/description.html#dependencies)

> Both Imports and Suggests take a comma separated list of package names.
> I recommend putting one package on each line, and keeping them in alphabetical order.
> That makes it easy to skim.
> 

while developing a package it makes life easier to have the packages in Imports/Suggests/...
sorted alphabetically 

I would suggest to extend `use_package` with an extra argument in order to also make it
possible sort the packages.
The default value `sort = FALSE` would reproduce current behavior
```
use_package <- function(package, type = "Imports", min_version = NULL, sort = FALSE)
```
while `sort = TRUE` would also sort the packages within the relevant `type`, i.e. something
like the following inside `use_dependency` could do the trick:

```
rest_deps <-  deps %>% filter(type != type)
type_deps <- deps %>% filter(type == type) %>% arrange(package)
# put them together
deps <- type_deps %>% bind_rows(rest_deps)
```

**Comment by hadley** [comment]
I think it would be slightly easier to just detect if they're already sorted, and if so, preserve the sorting.

**Comment by espinielli** [comment]
Ah, so `use_package` if used consistently since the beginning of the package development (when the deps are empty) would keep things sorted...

I was viewing it from the messy situation I am in whereby I have a longish list of unsorted dependencies
and would like to reorder.

**Comment by jennybc** [comment]
I routinely use `use_tidy_description()` for this, which generally normalizes your DESCRIPTION file. 

I have generally thought that usethis should possibly do this whenever it touches DESCRIPTION.

https://github.com/r-lib/usethis/issues/443

But at the time @Hadley didn't really agree.

**Comment by espinielli** [comment]
Fantastic! I missed to find/read about `use_tidy_description()` and it looks perfect for my use case.
(Maybe worth to mention int the book ;-)

If you want issue can be closed from my point of view...

**Comment by jennybc** [comment]
Yeah, the name suggests its part of the tidyverse package workflow, but it really means "tidy" as in "tidy up" in this case 😬
