### ISSUE TITLE
use available::available() when creating / submitting a package

### ISSUE THREAD

**Issue by njtierney** [r-lib/usethis#808]
When a package is created or submitted, it would be neat to cross-reference the name against other packages on CRAN/GitHub/Bioconductor etc using https://github.com/ropenscilabs/available

**Comment by jennybc** [comment]
I'm unsure what to do with this. But I have spontaneously demo'd `available()` in 2 of the last 3 workshops I've taught, so you're right we need to publicize it.

I agree it's a good idea for *some* packages, i.e. packages eventually destined for CRAN. But I wouldn't really want to add this chatter to every invocation of `create_package()`.

In short, I don't *think* it belongs in usethis, but I think these make sense:

  * Open an issue to propose adding to `devtools::release()`. Here the user has already explicitly asked for tons of checks and questions. Now, that is also a bit late in the development process to think about your name, but what can you do.
  * Open an issue and/or PR to add to the R Packages book: https://github.com/hadley/r-pkgs, which should definitely mention available.

**Comment by njtierney** [comment]
Hi @jennybc,

Thanks for looking at this - I had originally placed this as an issue for `create_package()` after discussing it with @jimhester, who suggested I open it here.

I agree with you that it is hard to know where to put this - at the start might be rather interrupting, and at the end might be a bit late. But I think that `devtools::release()` makes sense, and putting it in the rpkgs book make a lot of sense as well, I'll submit an issue and look into adding a PR.

Thanks! :)

**Comment by jennybc** [comment]
Sorry that @jimhester and I are playing ping pong with you 😬

**Comment by njtierney** [comment]
All good! :)

**Comment by jimhester** [comment]
Gabor and I talked about this at the dev day and decided `release()` was too late I think it really should be in `create_package()`, but maybe not on by default? Could we have it as an option?

**Comment by jennybc** [comment]
I just don't think anyone would ever use such an argument in `create_package()`. If you're thinking that much about these matters, you'll do the check yourself. Documenting this well in the R Packages book might very well be the best lever we have, i.e. the best chance of hitting the right eyeballs at the right time, without aggravating other people who just want to do their thing.

When I tackle RStudio project templates, I could make one that's fitted out with extra goodies like this (#770).

**Comment by jimhester** [comment]
You are right

**Comment by hadley** [comment]
If anywhere, I think this should go in `use_release_issue()`, but it's likely to be too late by that case. But I think generally if you're planning on submitting a package to CRAN, you know that you have to give it a unique name, and you're probably already doing some investigation.

**Comment by njtierney** [comment]
I think that while that might be true, FWIW, I have experience to the contrary where a package name was taken and submitted to CRAN.
