### ISSUE TITLE
Be explicit about when just cloning (as vs. forking + cloning) with create_from_github()

### ISSUE THREAD

**Issue by angela-li** [r-lib/usethis#816]
It's frustrating when you think you've forked and cloned a repo, but you've only just cloned the repo, because you don't have a Github PAT set up (or you normally use SSH, so `create_from_github()` doesn't quite work for you from the outset...). 

Could there be a check/warning added in the `create_from_github()` function to see if you have a Github PAT in your .Renviron, and some message in red saying "NOTE: you don't have a Github PAT, so you will just clone this package, rather than forking + cloning it"? It could also be an numbered/"select this" option, but that would probably be annoying for most users who've already set up the PAT.

**Comment by jennybc** [comment]
If you know you want to fork, then you should probably put `fork = TRUE` in the call. If `fork = TRUE` and we don't have a PAT, that should fail, very informatively. I just chatted with @ijlyttle about this and he's going to see if that is in fact true.

The docs for `create_from_github()` do already stress the importance of a PAT for forking. To a certain extent, I think it's possible that people need to fail with `create_from_github()` once 😬, to learn that their setup isn't complete. But from that point on, the regular day-to-day experience becomes pretty smooth. At least, it is for me.

**Comment by ijlyttle** [comment]
Here's my reprex - I think this does what @jennybc claims.

``` r
withr::with_envvar(
  list(GITHUB_PAT = ""), 
  usethis::create_from_github("tidyverse/ggplot2", destdir = "..", fork = TRUE)
)
#> ✔ Creating '../ggplot2/'
#> Error: No GitHub `auth_token` is available.
#> See `browse_github_token()` for help storing a token as an environment variable.
```

<sup>Created on 2019-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
