### ISSUE TITLE
let user decide whether to open R file created with use_r

### ISSUE THREAD

**Issue by friep** [r-lib/usethis#817]
In `use_test` the user can specify the `open` argument to avoid opening the R files in the editor. 
In `use_r`, this is not possible right now. I think for automation this would be a nice to have feature. Plus, it would increase consistency of the two functions that are quite similar. 

``` r
    lapply(c("foo", "bar", "zett"), usethis::use_r) # opens windows in Rstudio
    lapply(c("foo", "bar", "zett"), usethis::use_test) # opens windows in Rstudio (because interactive()  is default)
    
    # don't open windows
    lapply(c("foo", "bar", "zett"), usethis::use_test, open = FALSE) # does not open windows
    lapply(c("foo", "bar", "zett"), usethis::use_r, open = FALSE) # <- open argument not availale -> error
```

**Comment by jennybc** [comment]
I agree `use_r()` and `use_test()` should be consistent in this way. You are welcome to make a PR that adds the `open` argument to `use_r()` that works as it does for `use_test()`.
