### ISSUE TITLE
`use_tutorial()` - add option to import learnr

### ISSUE THREAD

**Issue by isteves** [r-lib/usethis#822]
Currently, `use_tutorial()` places `learnr` in "Suggests", which is ideal for package developers who want to include `learnr` tutorials as documentation. 

In a teaching context, it is often more important to reduce user friction than to reduce dependencies. Thus, we'd like to create a "heavyweight"/learner-friendly option for `use_tutorial()` that would do the following:

1. place `learnr` in "Imports" instead
2. re-export `learnr::run_tutorial()`

@jules32 @angela-li

**Comment by hadley** [comment]
This just feels a bit too specific for usethis — we'd need to distinguish between the package-developer and teacher uses cases either with different function names or arguments, and I just doubt that it would be discoverable enough to actually help people. I think it's a good idea, it just doesn't feel like usethis is the right home for it to me.
