### ISSUE TITLE
When pr_push() fails, error message is too specific (wrong, sometimes)

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#823]
`pr_push()` can fail for someone trying to make a PR because of general git2r failure, i.e. they simply can't push using git2r, due to all the usual problems.

But the error message is too specific to the maintainer scenario, where the problem is usually that the PRer doesn't allow maintainer to modify.

That's confusing.

**Comment by hadley** [comment]
Just tweaked the messaging here to distinguish the two failure modes described in #700, and to make it more clear that there are other failure modes.
