### ISSUE TITLE
use_vignette("<package.name>") fails if the package name contains dots "."

### ISSUE THREAD

**Issue by maurolepore** [r-lib/usethis#830]
`use_vignette("<package.name>")` fails if the package name contains dots `"."`.
I expected this to work as dots "." are valid in package names (although I know they are discouraged).

Somewhat related to #793 

---

### Example

```R
use_vignette("r2dii.data")
#> ✔ Setting active project to 'C:/Users/Mauro/git/r2dii.data'
#> Error: 'r2dii.data' is not a valid filename for a vignette. It must:
#>   * Start with a letter.
#> * Contain only letters, numbers, '_', and '-'.
#> Error in x[[n]] : 
#>   attempt to select less than one element in integerOneIndex
```

#### GOOD: Has Get Started section

![image](https://user-images.githubusercontent.com/5856545/60970764-f1a74e80-a322-11e9-9bf4-1a74dde45cc4.png)

.

####  BAD: No Get Started section

![image](https://user-images.githubusercontent.com/5856545/60970646-b1e06700-a322-11e9-8c91-6eb058804ea8.png)

**Comment by jennybc** [comment]
Here's what WRE has to say about vignette filenames:

[1.4 Writing package vignettes](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-package-vignettes)

> To ensure that they can be accessed from a browser (as an HTML index is provided), the file names should start with an ASCII letter and be comprised entirely of ASCII letters or digits or hyphen or underscore.

I believe that aligns with our current regex in `valid_vignette_name()`

``` r
valid_vignette_name <- function(x) {
  grepl("^[[:alpha:]][[:alnum:]_-]+$", x)
}
```

So I think you just can't name your vignette after your package, if your package name violates these rules.
