### ISSUE TITLE
Should pr functions tweak the prompt?

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#831]
So that you don’t forget you’re in a branch?

**Comment by jennybc** [comment]
Interesting idea.

Just for `pr_fetch()`, i.e. "maintainer-view"? Or also for `pr_init()`, i.e. "contributor-view"?

Would it make more sense just to provide some tooling to help more people use the [prompt package](https://github.com/gaborcsardi/prompt) and then they get this for free?

**Comment by hadley** [comment]
I was imagining the casual contributor who probably doesn’t need a persistent setup, but would be helpfully reminded of where they were in the process.

**Comment by hadley** [comment]
Now think this is a bit too fragile to be worth doing
