### ISSUE TITLE
Add a widget for selecting multiple files to be sent to use_buildignore

### ISSUE THREAD

**Issue by ColinFay** [r-lib/usethis#841]
Hey, 

How would you feel about an RStudio addin with a shiny Widget for selecting files and sending them to some `{usethis}` functions? 

My use case is that I received a project which is supposed to be a package but that has a lot of file at the root of the project that I want to send to buildignore. 

Right now I have to manually select them all and pass them to usethis::use_build_ignore. 

It would be nice if I could interactively select them like this : 

```r
library(shiny)
library(miniUI)
library(shinyFiles)
ui <- function(request){
  miniPage(
    gadgetTitleBar("Add to buildignore"),
    miniTabstripPanel(
      shinyFilesButton(
        'files', 
        'File select', 
        'Please select a file', 
        TRUE
      )
      , 
      fillRow(
        verbatimTextOutput("out")
      )
      
    )
  )
}

server <- function(input, output, session){
  roots <-  c(wd='.')
  
  output$out <-renderPrint({
    cli::cat_rule("Selected files")
    parseFilePaths(roots, input$files)[, c(1,4)]
  })
  
  shinyFileChoose(input, 
                  'files', 
                  roots=roots, 
                  defaultPath='', 
                  defaultRoot='wd')
  
  observeEvent( input$done , {
    lapply(input$files$files, function(x){
      p <- fs::fs_path(purrr::flatten_chr(x))
      usethis::use_build_ignore(
        fs::fs_path(
          purrr::flatten_chr(x)
        )
      )
    })
    stopApp(returnValue = invisible(input$files))
  })
  
}

runGadget(shinyApp(ui, server), viewer = paneViewer())

```

It could also go into a standalone package so that `{usethis}` stays lighter and don't depend on `{shiny}`

**Comment by jennybc** [comment]
Cool idea! But, yeah, it feels a bit niche and, historically, I seem to let shiny gadgets languish in my packages, since I don't use shiny very often. So I think it would be better off elsewhere.
