### ISSUE TITLE
usethis::use_vignette() argument overwrite does not seem to exist

### ISSUE THREAD

**Issue by jrosen48** [r-lib/usethis#843]
I am trying to use `usethis::use_vignette()` to create a new vignette. Per #473, it appears that because my `DESCRIPTION` file is as follows, it created an error:

```r
VignetteBuilder:
    knitr
```

The error told me to use `overwrite = TRUE`, but, this argument does not appear to exist:

``` r
usethis::use_vignette("Benchmarking mclust and MPlus", overwrite = TRUE)
#> Error in usethis::use_vignette("Benchmarking mclust and MPlus", overwrite = TRUE): unused argument (overwrite = TRUE)
```

<sup>Created on 2019-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jennybc** [comment]
I can't reproduce this problem now, even in a package that has a `VignetteBuilder` field like yours in DESCRIPTION.

Can you show me the initial call `usethis::use_vignette()` and the exact error message you saw?

I'd also like to see your session info: `devtools::session_info("usethis")`.

**Comment by jrosen48** [comment]
Hi, I'm sorry, I've updated `usethis` and this no longer seems to be an issue. My apologies!
