### ISSUE TITLE
`pr_fetch()` fails if the associated fork has been deleted.

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#845]
Trying to use `pr_fetch()` with https://github.com/r-lib/xml2/pull/183 fails, because the forked repository has been deleted since the PR was initiated.
```r
usethis::pr_fetch(183)
#> ✔ Setting active project to '/Users/jhester/Dropbox/projects/xml2'
#> ✔ Checking out PR 'r-lib/xml2/#183' (@hrbrmstr): 'Added a "user agent" section to `read_html`/`read_xml` documentation.'
#> ✔
#> Error in git2r::remote_add(git_repo(), remote, url) :
#>   Error in 'git2r_remote_add': 'url' must be a character vector of length one with non NA value
```

**Comment by hadley** [comment]
@jimhester what can we do here? Just a better message? Or is there some other way to retrieve the data?

**Comment by jimhester** [comment]
Just throwing a better error message is fine, it is not common enough to try to support more fully I think.

**Comment by hadley** [comment]
I can no longer reproduce this — `pr_fetch(917)` succeeds even though #917 was merged in October and the branch deleted.

**Comment by hadley** [comment]
OTOH it still fails for that xml2 PR. Maybe github only lazily deletes the branches under some circumstances?

**Comment by hadley** [comment]
Oooh it's the repository being deleted; not the branch.
