### ISSUE TITLE
Make use_readme_rmd() work outside of a package

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#85]
We'd need another README template to use for a project that is not a package.

**Comment by hadley** [comment]
If you supply the template, I can now make this work

**Comment by jennybc** [comment]
Something like this:

````
---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# {{{ Project }}}

The goal of {{{ Project }}} is to ...

What is special about using `README.Rmd` instead of just `README.md`? You can include R chunks like so:

```{r cars}
summary(cars)
```

You can also embed plots, for example:

```{r pressure, echo = FALSE}
plot(pressure)
```

In that case, don't forget to commit and push the resulting figure files, so they display on GitHub!
````

Sidebar: OMG 😵🎉 have you tried 4 backticks yet? Thx @romainfrancois for telling me about that.

**Comment by hadley** [comment]
You can can always use one more backtick: ````` ```` ````` 😉 which I wrote with ``````` ````` ```` ````` ```````

**Comment by hadley** [comment]
Should we set a figures directory? Or is the default ok?

**Comment by jennybc** [comment]
Sidebar: I thought this "one more backtick" things was new-ish, i.e. came when GFM became based on CommonMark (granted was several months ago). Sadly can't be used in, say, local Rmd.

I have no special opinion about figures directory, so I guess I'd accept the default. I specifically didn't mention the path, to minimize chance of contradicting what someone sees locally.
