### ISSUE TITLE
Show off usethis using asciicast

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#850]
Replacing the current chunk on the readme: https://github.com/gaborcsardi/asciicast

**Comment by jennybc** [comment]
I also have several mp4's now, thanks to the useR! talk (a catenated version is here [on YouTube](https://youtu.be/3vsPMyTfT8I)). It sort of matters, because organic usage of some of the most exciting functions will do things to/in RStudio and the browser, i.e. is beyond the reach of asciicast.

**Comment by hadley** [comment]
Ok, then lets shelf this for now — we're probably better off saving such material for the book, anyway.
