### ISSUE TITLE
Feature Request: use_vdiffr

### ISSUE THREAD

**Issue by njtierney** [r-lib/usethis#851]
My thought is that `use_vdiffr()` could add `vdiffr()` to Suggests and also set up a template visualisation test in `tests/`

**Comment by jennybc** [comment]
I've never used vdiffr myself, so I don't have a sense of what the setup looks like. Can you point me to a good example of what adopting vdiffr in one's tests entails?

**Comment by njtierney** [comment]
Sure, `vdfiffr` adds the `expect_doppelganger` to `testthat`, the format looks something like this (although @lionel- (author of vdiffr) correct me if I am wrong)

```r
context("plot-test")

library(ggplot2)
gg_example <- ggplot(midwest,
                     aes(x = area,
                         y = poptotal)) +
                geom_point()

test_that("geom_point() works with midwest",{
  skip_on_cran()
  skip_on_appveyor()
  vdiffr::expect_doppelganger("midwest-geom-point", gg_example)
})
# run vdiffr::manage_cases() to test and validate your new plots
```

Maybe one of the messages usethis could display could be 

`* run vdiffr::manage_cases() to test and validate your new plots`

I'd be happy to give a PR of this a go, but I'm not really sure where to start, if you have some pointers I'd be happy to try, but it might take me a few weeks to find the time.

I also have an example here: https://github.com/njtierney/brolgar/blob/master/tests/testthat/test-facet-strata.R

**Comment by hadley** [comment]
This feels a bit too specialised to me.

**Comment by njtierney** [comment]
Perhaps it belongs in vdiffr then?

**Comment by lionel-** [comment]
yup I think that makes sense.
