### ISSUE TITLE
Refactor Rbuildignores for vignettes

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#853]
We've started to see this in local checks:

```
 WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'tidyr/vignettes/rectangle_cache/html/unnamed-chunk-18_9373ed2d8b44950836502f9a9b4037ca.RData' 
```

so the standard Rbuildignore strategy for `use_vignette()` needs a once over. Probably should include `*_cache`.

**Comment by hadley** [comment]
Do you have a reprex for this? I added the following chunk to `usethis-setup.Rmd`:

````

```{r, cache = TRUE}
x <- 1
```
````

Then knitted, and ran R CMD check. I didn't see any warnings.

**Comment by hadley** [comment]
Seems like this was maybe fixed upstream
