### ISSUE TITLE
Ensure alphabetical order when adding a dependency with usethis

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/usethis#857]
Problem: New dependency added with `use_package()` and `use_dev_package()` is added as last item in the respecive Field in DESCRIPTION. 

Easy fix:  should run `use_tidy_description()` on exit to make sure the added entry in DESCRIPTION is put in the right place. This will in general have unintended side effects with the formatting of DESCRIPTION.

Clean fix: Make sure you instert in the right place in the first place. 

What do you think?

**Comment by jennybc** [comment]
Kind of a duplicate of #443

**Comment by jennybc** [comment]
To be clear, my personal taste is also to alphabetize them and rigorously maintain that style.

**Comment by hadley** [comment]
It's easiest to do this in desc, I think: https://github.com/r-lib/desc/pull/85
