### ISSUE TITLE
Helper to rename a package

### ISSUE THREAD

**Issue by llrs** [r-lib/usethis#858]
As explained in this [post](https://www.njtierney.com/post/2017/10/27/change-pkg-name/) renaming a package (on the experimental phase) can be tedious. I think it would be possible to automate this in a single function using the existing functionality and without more dependencies. 

The function could go along this lines:

```r
rename_package <- function(package_name) {
    # Published on CRAN? https://stackoverflow.com/q/22654421/2886003
    warning("Are you sure?") 
    # Find old name on the active project
    # replace with the new name
    # Move up and rename the directory
    # Change github repo name
    # change remote repositories of the computer
    # Change other services linked to that remote repository
    #    (travis, appveyor, covr, pkgdown?)
}
```

Admittedly this will be of interest to few users and used fairly rare (but perhaps it avoids package2 in the future :)

**Comment by hadley** [comment]
My sense is that this would be useful, but it's going to be really hard to do, so I don't think benefit currently outweighs the cost.

**Comment by IndrajeetPatil** [comment]
Of interest here (cc @moodymudskipper):
https://cran.r-project.org/web/packages/changer/index.html
