### ISSUE TITLE
Feature Request: new use_news_rmd()

### ISSUE THREAD

**Issue by phargarten2** [r-lib/usethis#859]
I think that having RMD template for the NEWS template will be helpful for users to follow Rmarkdown syntax as suggested by the [tidyverse style guide](https://style.tidyverse.org/). Being able to knit an Rmd file resembles the final result of the NEWS file when the package is posted on CRAN. Thus, I would be able to catch any Rmarkdown syntax errors. 

If you like the idea, the new `use_news_rmd()` function would be adjusted from `use_news_md()`.  Then, you can create a `NEWS.Rmd` template from the `NEWS.Rd` template and add
```
---
output: github_document
---
```
at the top of the document.  Thank you.

**Comment by hadley** [comment]
Having let this issue set for a while, I unfortunately don't find it that compelling. It's very unusual for me to feel the lack of full `.Rmd` processing in NEWS — mostly it's just snippets of code that don't need to be executed.
