### ISSUE TITLE
Pass argument `open = ` to `use_template()` from wrappers

### ISSUE THREAD

**Issue by mixtrak** [r-lib/usethis#86]
Some functions to add useful infrastructure to a package also then open the files created. For example, use_news_md() will create and then open the news.md file, and similar behaviour is found in use_readme_rmd(), use_package_docs(), use_vignette() and possibly others.
I have written a wrapper function which initialises a new package with infrastructure and then switches to the new RStudio project in a new RStudio session. However, as a side-effect, all the files mentioned above get opened in my old RStudio session.
It would be nice to be able to pass an `open = FALSE` argument to the underlying code. For example, here is the code for use_package_doc:

```R
function (pkg = ".") 
{
    pkg <- as.package(pkg)
    use_template("packagename-package.r", file.path("R", paste(pkg$package, 
        "-package.r", sep = "")), data = list(name = pkg$package), 
        open = TRUE, pkg = pkg)
}
<environment: namespace:devtools>
```

Note the `open = TRUE` on the fourth line of function body code, which seems to be an argument of the internal {devtools} function devtools:::use_template. Perhaps this argument could be exposed to users of the higher-level functions.

**Comment by hadley** [comment]
Would you be interested in a writing a pull request to this effect? You'd just need to make sure that every function that calls `use_template()` with `open = TRUE` gains an `open` argument so that you can control this behaviour.

**Comment by mixtrak** [comment]
Would I! (yes)

**Comment by mixtrak** [comment]
Pull request submitted. Only potential issue is some weird tests I made - I can revert that commit if you like, or you can do it on merge.
