### ISSUE TITLE
PR vignette use case fails behind authenticated PROXY

### ISSUE THREAD

**Issue by espinielli** [r-lib/usethis#863]
I am very happy with the PR facilities offered by `usethis`: the vignette "[Pull request helpers](https://usethis.r-lib.org/articles/articles/pr-functions.html)" in particular is a use case that fits very well the workflow we are establishing at work.

BUT I found it failing due to `git2r` lack of support for authenticating PROXY, see ropensci/git2r#395 .

Maybe it is worth mentioning that limitation in the vignette to warn the `usethis` users.

(or try to find some bold and knowledgeable person who can fix the issue :innocent: [I just reported it and would love to contribute to a solution but it is really outside my possibilities :disappointed: ])

**Comment by ijlyttle** [comment]
Hi @espinielli,

I will need to check on my end, but I am able to use all the `pr_*()` functions despite working behind a proxy.

Normally, I use ssh for git, but I seem to remember being able to use https, too. 

I can make some experiments on my side for https. For now, could ssh be a workaround for you?

**Comment by espinielli** [comment]
IT security dept used to limit the use of `ssh` (but if you give me some hints I could give it a try again).

So at work I have `http_proxy` and `https_proxy` configured at system level with something like

```
http_proxy='http://user:password@prox-server:3128'
https_proxy='http://user:password@prox-server:3128'
```

I have also set things up globally in git config such as

```
[http]
	proxy = http://user:password@prox-server:3128
[https]
	proxy = http://user:password@prox-server:3128
[url "https://"]
	insteadOf = git://
[url "https://github.com"]
	insteadOf = git://github.com
```

this works for command line `git` and other apps that make use of the above settings (`curl`, `R`/`RStudio` et al.) but not for `git2r`.

**Comment by ijlyttle** [comment]
The difference between our proxies is that yours requires authentication in the the address, and mine does not - I suspect this is what lets me use https from behind my proxy. 

In the future, I hear that usethis may be switching to using the [gert](https://github.com/r-lib/gert)
package to interface with git, so it may be interesting to see if gert handles this case.

As for ssh hints, I would recommend [Happy Git with R](https://happygitwithr.com/ssh-keys.html) and [GitHub](https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).

**Comment by espinielli** [comment]
A search for `proxy` in the whole [`gert` repo](https://github.com/r-lib/gert) did not bring back a single entry 😢: I am not holding my breath then 😉

**Comment by espinielli** [comment]
@ijlyttle  I checked and ssh is very strictly configured for us at work, so not an option 😭

**Comment by hadley** [comment]
Yeah, we're going to use gert in future, so I'd recommend following up there.
