### ISSUE TITLE
usethis::use_testthat() fail

### ISSUE THREAD

**Issue by MagdyLaban** [r-lib/usethis#864]
when setting up my package , writing usethis::use_testthat() gives me this error 
✔ Setting active project to 'the path'
Error in if (any(mismatch <- res != res2)) { : 
  missing value where TRUE/FALSE needed
what should I do ?
```

**Comment by jennybc** [comment]
It would be interesting to see the result of `usethis::proj_sitrep()`.

I assume you edited this line by hand?

```
✔ Setting active project to 'the path'
```

**Comment by MagdyLaban** [comment]
No , I didn't modify anything and all use_* commands give me this error

**Comment by jennybc** [comment]
I have no theories about how you are getting `'the path'` for what should be an actual filpath. So my hypothesis must be ... that you have something peculiar in your overall setup. Have you done anything interesting recently with overall configuration or R setup? What do you see with `getwd()`? I suppose you could reinstall fs, which is what usethis uses for all path handling, but this seems like a more profound glitch.

**Comment by jennybc** [comment]
Are you using an IDE, like RStudio? What version?

**Comment by MagdyLaban** [comment]
I have reinstalled R and it works well thank your for your great efforts
