### ISSUE TITLE
Colors provided `use_github_labels()` result in random colors on the finalized GitHub labels

### ISSUE THREAD

**Issue by rich-iannone** [r-lib/usethis#865]
When using `use_github_labels()`, the colors provided don't result in the final labels (on GitHub) receiving those colors. Here is the code used:

```r
library(usethis)

labels <-
  c(
    "Blocked (╥﹏╥)",
    "Difficulty: ③ Advanced",
    "Difficulty: ② Intermediate",
    "Difficulty: ① Novice",
    "Effort: ③ High",
    "Effort: ② Medium",
    "Effort: ① Low",
    "Help Wanted ㋡",
    "Priority: ♨︎ Critical",
    "Priority: ③ High",
    "Priority: ② Medium",
    "Priority: ① Low",
    "Type: ☹︎ Bug",
    "Type: ✎ Docs",
    "Type: ★ Enhancement",
    "Type: ⁇ Question",
    "Type: ٩(͡๏̯͡๏)۶ Refactor",
    "Type: ❏ Visualization"
  )

colours <-
  c(
    "#96fff1",
    "#d93f0b",
    "#fbca04",
    "#0e8a16",
    "#d93f0b",
    "#fbca04",
    "#0e8a16",
    "#4add30",
    "#c12e49",
    "#d93f0b",
    "#fbca04",
    "#0e8a16",
    "#bfe85a",
    "#fcf82a",
    "#84b6eb",
    "#d4c5f9",
    "#fce5c2",
    "#fef2c0"
  )

usethis::use_github_labels(
  repo_spec = "rich-iannone/SplitR",
  labels = labels,
  colours = colours,
  delete_default = TRUE
)
#> ℹ No labels need renaming
#> ℹ No new labels needed
#> ✔ 
#> ✔ 
#> ✔ Removing default labels: 'bug'
```

<sup>Created on 2019-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Here is how the labels are supposed to appear (from a repo's labels that I want to duplicate):

<img width="1022" alt="old_labels" src="https://user-images.githubusercontent.com/5612024/62636762-2b5e7b80-b908-11e9-8c5d-458cb47769df.png">

Here is what `use_github_labels()` creates, based on the colors obtained from the above repo:

<img width="1012" alt="new_labels" src="https://user-images.githubusercontent.com/5612024/62636830-47621d00-b908-11e9-94e3-2872044db0b6.png">

So, for the `blocked` label we get the color `#382637` from the supplied color of `#96fff1`. The colors seem randomized because even identical colors supplied result in different colors.

**Comment by hadley** [comment]
This isn't an amazing ui, but it is documented: `colours` needs to be a named character vector. The code is complicated enough that I'd prefer not to implement a new ui at this time.
