### ISSUE TITLE
use_rstudio: use different templates for packages and projects

### ISSUE THREAD

**Issue by cstepper** [r-lib/usethis#867]
Hi,

not sure if necessary, but I modified `use_rstudio()` for creating different _RStudio_ Proj files, depending if the user calls `create_package()` or `create_project`. 
I added a second _Rproj_-template for the _project_-case (using the Rproj file generated in Rstudio when creating a new project using the IDE) and renamed the original one to _package.Rproj_.

Additionally, I moved the `use_git_ignore()` to an if-statement, thus adding the _.gitignore_ file only, if the project uses git (not sure, if this is necessary here at all, or if this should only be called later if the user calls `use_git()`)

 ```r
 if (uses_git()) {
    use_git_ignore(".Rproj.user")
  }
```
 Check my modifcations here: https://github.com/cstepper/usethis/tree/use_rstudio_proj
and tell me, if I should create a PR.

Best, Christoph

**Comment by hadley** [comment]
Not sure what you're asking here?

**Comment by cstepper** [comment]
Hi, 
I apologize if my comment was not clear.

When using the current version of `create_project()`, the subfunction `use_rstudio()` creates the *RStudio Proj* file based on the *inst/templates/template.Rproj*.  
Thus, in the *RStudio Proj* file of the created project, there is something like:
 
```
BuildType: Package
PackageUseDevtools: Yes
PackageInstallArgs: --no-multiarch --with-keep.source
PackageRoxygenize: rd,collate,namespace
```
As not all projects are packages, I created a second template (*project.Rproj*, using the Rproj file generated in Rstudio when creating a new project using the IDE) and renamed the current template from *template.Rproj* to *package.Rproj*.

I modified the function `use_rstudio()`:
If called for creating a package, it uses the template *package.Rproj*; if called for creating a project, it uses the template *project.Rproj*.

WRT to my second change (moved the `use_git_ignore()` to an if-statement):
I was just wondering, why I should create a `.gitignore` file (for ignoring the .Rroj.user) for every project, even if I don't use git for it. Therefore I moved this to an extra if statement: 

```
if (uses_git()) {
   use_git_ignore(".Rproj.user")
 }
```
HTH, Christoph

**Comment by hadley** [comment]
I don't think there's any downside to including a few extra package lines in the `.Rproj` file, and it makes the usethis code much simpler.

Similarly, we have to run `use_git_ignore()` early so that it protects you if you later decide to make an RStudio project.

In the future, if you have already written the code, it is easier for me to see if it you do a pull request.

**Comment by cstepper** [comment]
Thanks for your comments.
Just thought opening an issue before creating a pull request is more in line with your *Contributing Guide*. I'll do a pull request in future, if I have some code to show.
