### ISSUE TITLE
Feature) use_tidy_select()

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#868]
(Maybe `use_tidyselect()` but that doesn't fit the naming scheme)

This would import and reexport the tidyselect helpers shown here:
https://github.com/tidyverse/tidyr/blob/00a66b44d2f304a73e953dd73139db61ed9cc289/R/tidyr.R#L29-L53

The implementation code would likely look similar to `use_tidy_eval()`, and the template would be similar to `tidy-eval.R`, with a nice help doc landing page for any `?mypkg::tidyselect_fn` calls:
https://github.com/r-lib/usethis/blob/master/inst/templates/tidy-eval.R

**Comment by jennybc** [comment]
Motivated by tidyr revdep drill and the under-development vignette on how to use tidyr in a package. It's the first time we've done a deep dive on using tidyselect stuff in a 3rd party package.

**Comment by hadley** [comment]
This will no longer be needed in the next version of tidyselect.
