### ISSUE TITLE
Limit covr to r-release in tidy travis template

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#87]
If we use the large build matrix (3.1 thru r-devel), it might be worth it to limit covr run to r-release.

As seen in devtools, among other places:

``` yaml
# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
```

**Comment by hadley** [comment]
@jimhester can you please confirm this is the most concise syntax?

**Comment by jennybc** [comment]
Who do you think gave me the above syntax? 😉

**Comment by jennybc** [comment]
The above snippet from devtools consults `TRAVIS_R_VERSION_STRING`.

The [docs say to consult `TRAVIS_R_VERSION`](https://docs.travis-ci.com/user/languages/r#Environment-Variables).

While we're here, maybe we can get to the bottom of that?

**Comment by hadley** [comment]
It's just so long and ugly 😞

**Comment by jimhester** [comment]
The problem is `TRAVIS_R_VERSION` changes if the R-release version changes, so you have to keep updating it. `TRAVIS_R_VERSION_STRING` will always be release.

I agree it is ugly, an alternative which is maybe not as ugly (but no shorter) would be

```yaml
matrix:
  include:
  - r: release
    after_success: Rscript -e 'covr::codecov()'
```

**Comment by jimhester** [comment]
Also generally I think it is probably fine to omit this and just run covr on all builds. Cases where you would not want to are when you are running into API rate limits, which was the case in devtools and googlesheets / googledrive.
