### ISSUE TITLE
`usethis::use_spell_check()` doesn't follow tidyverse style guide and contains lints

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/usethis#871]
Currently, using `usethis::use_spell_check()` creates a new file `spelling.R` with the following code-

```r
if(requireNamespace('spelling', quietly = TRUE))
  spelling::spell_check_test(vignettes = TRUE, error = FALSE,
                             skip_on_cran = TRUE)
```

But, according to the `tidyverse` style guide, the code should instead be-

```r
if (requireNamespace("spelling", quietly = TRUE)) {
  spelling::spell_check_test(
    vignettes = TRUE, error = FALSE,
    skip_on_cran = TRUE
  )
}
```

Additionally, this code also contains the following two lints-

![image](https://user-images.githubusercontent.com/11330453/62816401-bf8d3600-baf4-11e9-9732-0300e1b5a5ed.png)

It will be neat if `usethis::use_spell_check()` can create the `spelling.R` that avoids both of these issues which will make it easier to not worry about running `styler` after every spellcheck.

**Comment by hadley** [comment]
This code comes from `spelling::spell_check_setup()`, so it's outside the scope of usethis. You can just restyle after you run `usethis::use_spell_check()`
