### ISSUE TITLE
use_pkgdown_travis() should let you know it creates a gh-pages branch

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#872]
Twice now I have used `use_pkgdown_travis()`, and then tried to create a gh-pages branch directly afterwards because it doesn't print out any information about its creation. Would you accept a PR adding a `ui_done()` along the lines of `"Initializing an empty gh-pages branch"` into `create_gh_pages_branch()`?

**Comment by jennybc** [comment]
Sure.
