### ISSUE TITLE
Feature Request: use_operator() for general operator importing.

### ISSUE THREAD

**Issue by MilesMcBain** [r-lib/usethis#876]
Note: I've suggested this once before in [`devtools`](https://github.com/r-lib/devtools/issues/1593) but didn't get any interest.

The idea is for a more generic version of `use_pipe` that takes any operator and package as arguments. 

For example:

```r
use_operator(operator = `%<-%`, package = "zeallot", dependency = "Imports", export = TRUE)
```

Would have the following effects:

* `zeallot` is added to DESCRIPTION under "Imports" (if not already in DESCRIPTION)
* an R is created file that makes `%<-%` available, e.g.:

```
#'  operator '%<-%'
#'
#' See \code{zeallot::\link[zeallot]{\%<-\%}} for details.
#'
#' @name %<-%
#' @rdname operator '%<-%'
#' @keywords internal
#' @export
#' @importFrom zeallot %<-%
#' @usage lhs %<-% rhs
NULL
```

* Informs the user via console of the need to run `devtools::document()` next.

**Comment by hadley** [comment]
This doesn't feel quite right to me — I don't think you should be routinely re-exporting operators, so I don't think it's a good idea to make it really easy.
