### ISSUE TITLE
Creating a standard convention for dev scripts in packages

### ISSUE THREAD

**Issue by ColinFay** [r-lib/usethis#879]
Following [a Twitter conversation with Hadley](https://twitter.com/hadleywickham/status/1166028404786946049), I'm opening this issue to discuss the standardisation of the `dev/` scripts from `{golem}`: 

https://github.com/ThinkR-open/golem/tree/master/inst/shinyexample/dev

The idea behind these scripts is that anyone starting a new Shiny App with `{golem}` can follow a series of common steps. Newcomers are then guided, and seasoned developers are sure they don't forget anything. 

To some extent, I think this can be applied to a lot of cases, and in particular to package development, which (almost always) contains the same steps, more or less the one from https://github.com/ThinkR-open/golem/blob/master/inst/shinyexample/dev/01_start.R: 

- filling DESCRIPTION 
- creating README
- use licence
- use news
etc. 

Same goes before building: one will test locally, check for CRAN with r-hub, etc.

Maybe a `usethis::use_dev_script()` would be nice, with a series of steps to follow when creating a package?

**Comment by jennybc** [comment]
I don't think @Hadley or I have any near term plans to work on this. That doesn't mean it can't happen, so this can come back on the radar. But closing for now.
