### ISSUE TITLE
Adding a commit feature 

### ISSUE THREAD

**Issue by chsafouane** [r-lib/usethis#881]
One can use usethis to create a project (using create_project) and to make an initial commit during setup phase. 
I wonder if it makes sense to add a feature so as to make commits and pushes (within the project scope) instead of having to use git2r or gert?

Thanks

**Comment by jennybc** [comment]
No, I think usethis should stay out of the general git business. I think that's too much "mission creep".

**Comment by chsafouane** [comment]
Thanks Jenny gor the feedback ^_^
