### ISSUE TITLE
edit_rstudio_snippets() deletes the default snippets

### ISSUE THREAD

**Issue by GegznaV** [r-lib/usethis#884]
By default, RStudio does not contain any files in `~/.R/snippets` (#84). If the snippets of some kind (e.g., SQL) were not changed in RStudio through the default snippets editor window accessible through "Top menu in RStudio → Tools → Global Options → Code → Edit Snippets" the files with snippets are not created. And if one tries to edit snippets for the first time by using `usethis::edit_rstudio_snippets(???)` creates an empty `???.snippets` (??? - the kind of snippets) file and, in this way, it deletes the default RStudio snippets. E.g., `usethis::edit_rstudio_snippets("sql")` deleted the default snippets for SQL on my PC (there were several default snippets before):
![snippets](https://user-images.githubusercontent.com/12725868/64559513-264d7b80-d34f-11e9-96a7-fc677fdbbdde.png)

The behavior of `edit_rstudio_snippets()` should be safer: 

1) it either should open a file and create the default snippet if they are not present;
2) or open the default snippets editor window in which the default snippets are already present (I'm not sure if **rstudioapi** allows programmatically accessing this functionality at the present moment);
3) or at least warn the user that the default snippets will be lost and allow to cancel the operation.

**Comment by jennybc** [comment]
OK I just did an experiment.

If I use `edit_rstudio_snippets("SQL")` to create `~/.R/snippets/sql.snippets`, those user-contributed snippets appear to **mask** the previous default SQL snippets. So, if you want the defaults AND your own, you should use the RStudio UI to view them first and copy them.

But simply deleting my user-contributed snippets -- so deleting the file `~/.R/snippets/sql.snippets` -- and restarting RStudio made the default SQL snippets reappear.

usethis isn't deleting anything. I think RStudio just consults user snippets first and, if they don't exist, falls back to built-in defaults. Which are clearly housed elsewhere.

**Comment by GegznaV** [comment]
> user-contributed snippets appear to **mask** the previous default SQL snippets.
Could `edit_rstudio_snippets()` warn in case of masking the default snippets?

> But simply deleting my user-contributed snippets -- so deleting the file ~/.R/snippets/sql.snippets -- and restarting RStudio made the default SQL snippets reappear.

Yes, it happened. Could this information how to reset to default snippets be included in the documentation of `edit_rstudio_snippets()`?

Still, for end-user, it does not matter if the snippets are deleted or get masked. The result is the same: the snippets are deactivated. So it would be nice if **usethis** could create a file with the default snippets so that they were not masked or at least warn about the consequences.

**Comment by jennybc** [comment]
The files for RStudio's default snippets are not lying around in some accessible place, for usethis to consult. So I've just added a bit more documentation.
