### ISSUE TITLE
[Feature request] Limit the values of `type` in  edit_rstudio_snippets() to reasonable options only

### ISSUE THREAD

**Issue by GegznaV** [r-lib/usethis#885]
As I understand, RStudio has a limited number of different types of snippets:
![snippet](https://user-images.githubusercontent.com/12725868/64560891-1daa7480-d352-11e9-8e72-c3a2fb27c33f.png)

But `edit_rstudio_snippets()` argument `type` can have any value. For example, once I forgot that I have to use "markdown" and not "rmarkdown" and created a wrong type of document. Snippets in it did not have an effect. 
I expect that only reasonable values of `type` should be accepted. In other cases, either a warning or an error message should be issued.

**Comment by jennybc** [comment]
Sure, referring to some list of valid snippet types sounds like a reasonable idea.
