### ISSUE TITLE
use_pkgdown_travis() should check that we have a GitHub PAT

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#886]
If we don't and attempt to do the `gh-pages` branch setup, we get a (very confusing) 404:

```
:heavy_check_mark: Initializing empty gh-pages branch
Error in gh::gh("POST /repos/:owner/:repo/git/commits", owner = github_owner(),  :
 GitHub API error (404): 404 Not Found
 Not Found
```

cc @andrie @jmcphers

**Comment by hadley** [comment]
Similarly here; I think this workflow is likely to change dramatically soon.

**Comment by hadley** [comment]
Closing since we're moving to actions and since pkgdown now resolves this problem itself.
