### ISSUE TITLE
Inconsistent output from tidy_description

### ISSUE THREAD

**Issue by csgillespie** [r-lib/usethis#887]
I have the following package DESCRIPTION
```
Package: jrIdentity
Title: Style Jumping Rivers Branded Content
Version: 0.0.1
Authors@R:
    person(given = "Jumping",
           family = "Rivers",
           role = c("aut", "cre"),
           email = "info@jumpingrivers.com")
Description: Package to provide RMarkdown templates to create
    Jumping Rivers branded content.
License: file LICENSE
Imports:
    rmarkdown,
    rmdformats
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1
Suggest: knitr
```
Running `usethis::use_tidy_description()` doesn't change the file. However, when I run `use_tidy_description()` on our GitLab runner it changes the description line to:
```
Description: Package to provide RMarkdown templates to create Jumping 
     Rivers branded content.
```
What I don't understand is why.

 * Both systems are ubuntu 18.04
 * Both running R 3.6
 * Both access the file via a GitLab repo
 * Both use the same versions of `usethis` (1.5.1) and `desc` (1.20.

I've searched usethis and desc for a width option, but it appears the width of the file is [hard-coded](https://github.com/r-lib/desc/blob/7c12d369c202018dfc3dfa3f975f03c8b6c18437/R/str.R#L55)

__reprex__

The DESCRIPTION file above. Not sure what the correct output should be.

**Comment by jennybc** [comment]
Do you have an easy way to figure out if usethis has anything to do with this? I sort of suspect it should repro with desc alone (?), although I obviously have something to gain from that 😬
