### ISSUE TITLE
use_dev_package() should respect the branch

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/usethis#888]
With the CRAN version of usethis, when I do

```r
remotes::install_github("lorenzwalthert/R.cache@shallow")
usethis::use_dev_package("R.cache")
```

I get the following added to my DESCRIPTION under `Remotes`:

```
Remotes:  
    lorenzwalthert/R.cache
```

But I believe it should be

```
Remotes:  
    lorenzwalthert/R.cache@shallow
```

**Comment by jennybc** [comment]
Contemplating this lead to a little internal discussion and the consensus is that we won't pursue this. 

We think it makes `use_dev_package()` more complicated for little gain. Depending on a dev version and esp. a branch should be a relatively rare and short-lived state. So I'm going to say you should just add that extra `@ref` to `DESCRIPTION` with your bare hands.

**Comment by lorenzwalthert** [comment]
Ok, thanks for the quick answer.
