### ISSUE TITLE
Unicode symbols printed raw in external R session

### ISSUE THREAD

**Issue by matthijsvanderloos** [r-lib/usethis#889]
When using any of the `ui_*` functions that include unicode symbols in an external R session, the unicode symbols are printed raw:

``` r
library(usethis)
# This prints OK:
ui_done('test')
#> ✔ test

bin <- if(.Platform$OS.type == "windows") {
  file.path(R.home("bin"), "Rscript.exe")
} else {
  file.path(R.home("bin"), "Rscript")
}

# This prints raw unicode:
system2(bin, args = "--slave -e library(usethis);ui_done('test')")
#> <U+2714> test
```
<sup>Created on 2019-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This should be resolved by the switch to cli. If it's not, it's possible that it's a problem with `system2()` and you might consider using `callr::r()` (or similar) instead.
