### ISSUE TITLE
Documentation says "activate a package"

### ISSUE THREAD

**Issue by barryrowlingson** [r-lib/usethis#891]
The documentation for `create_tidy_package` says it "activates" the package:

https://github.com/r-lib/usethis/blob/master/R/tidyverse.R#L11

Packages cannot be activated. Projects can. I know its probably pedantry but I can't help myself...

Suggest either rename the function to `create_tidy_project` or change the documentation to indicate this also makes an RStudio *project* skeleton and activates that.

(Its a shame that lots of the useful functionality of `devtools` and `usethis` are becoming project-oriented and less useful to anyone trying to do less opinionated package development)

**Comment by hadley** [comment]
The `_tidy` functions are primarily used internally.
