### ISSUE TITLE
README dev installation defaults to devtools and not remotes

### ISSUE THREAD

**Issue by edgararuiz** [r-lib/usethis#892]
Now that we're asked to start using `remotes` for dev installs, I wonder if it makes sense to change it here as well. 

https://github.com/r-lib/usethis/blob/a2342b8a937e32d17de01b29b42154e92ccb5e6b/inst/templates/package-README#L37-L38

**Comment by jennybc** [comment]
Well, I wouldn’t really characterize that as the advice. I’m on a phone, but my take on this is here:

https://r-pkgs.org/setup.html#setup-usage

**Comment by edgararuiz** [comment]
Ok cool, just checking

**Comment by jennybc** [comment]
I do see lots of people switching to remotes in a README. It's not my top pick, because I think of devtools as the interactive toolkit, but this is also not a hill I plan to die on.
