### ISSUE TITLE
Consider adding a create_learnr_package function

### ISSUE THREAD

**Issue by angela-li** [r-lib/usethis#895]
I'm looking into creating package with just interactive learnr tutorials (for a class), and I'm wondering if there could be a function that automates the set up of this type of package. If this is too specific a scope for a usethis function, I understand. In conjunction with `use_course`, it could possibly speed up the rate at which educators could create and deploy educational modules for students?

**Comment by jennybc** [comment]
Maybe it should be the other way around where learnr owns this function?

**Comment by angela-li** [comment]
That might be a good idea! Will propose in learnr repo.
