### ISSUE TITLE
usethis::use_ccby_license() creates a "non-standard license specification" that is not "standardizable" by devtools::check()

### ISSUE THREAD

**Issue by kiernann** [r-lib/usethis#898]
To create a reproducible example, I used `usethis::create_package()` to create a blank template package.

```r
usethis::create_package(path = "issue")
```

Then, in the new package project, I used `usethis::use_ccby_license()` to use the CC BY-SA 4.0 license. I need to use this license, as my package relies on some data under this same license.

``` r
packageVersion("devtools")
#> [1] '2.2.0'
packageVersion("usethis")
#> [1] '1.5.1'
usethis::use_ccby_license(name = "Kiernan Nicholls")
devtools::check()
```

This `devtools::check()` returns a warning, as the license is apparently non-standard.

```
── R CMD check results ── issue 0.0.0.9000 ──
Duration: 3.1s

❯ checking DESCRIPTION meta-information ... WARNING
  Non-standard license specification:
    CCBY-4.0
  Standardizable: FALSE

0 errors ✔ | 1 warning ✖ | 0 notes ✔
```

I'm following along in the [R Packages book](https://r-pkgs.org/), which says this warning would prevent my package from being released to CRAN.

> If you want to release your package to CRAN, you must pick a standard license. Otherwise it’s difficult for CRAN to determine whether or not it’s legal to distribute your package! You can find a complete list of licenses that CRAN considers valid at https://svn.r-project.org/R/trunk/share/licenses/license.db.

Going to that link, CC BY-SA 4.0 is listed as a valid license (and all other CC BY-SA versions recommend CC BY-SA 4.0)

> Name: Creative Commons Attribution-ShareAlike 4.0 International License
> Abbrev: CC BY-SA 4.0
> FSF: free_and_GPLv3_incompatible
> URL: https://creativecommons.org/licenses/by-sa/4.0
> FOSS: yes
> Extensible: yes

**Comment by batpigandme** [comment]
It might be that there is a difference between valid and standardizeable, given no CC licenses are listed in the internal R check (n.b. just linking to the line, since it's quite long)
https://github.com/wch/r-source/blob/780021752eb83a71e2198019acf069ba8741103b/src/library/tools/R/license.R#L205

**Comment by kiernann** [comment]
So would a package with this warning be accepted by CRAN? I haven't actually run `R CMD check`, just `devtools::check()`. That is, can you use accepted licenses in a non-standard format? The package I'm writing uses data originally found in the [`zipcode`](https://cran.r-project.org/web/packages/zipcode/index.html) CRAN package, which was accepted with a CC BY-SA 2.0 license.

**Comment by jennybc** [comment]
Here are the packages currently on CRAN with a CC BY-SA 4.0 license. So, yes, it must be possible. I suggest you poke around their source to see if there is something suboptimal about what `usethis::use_ccby_license()` does. If you grab source for one of these and run `check()` or `R CMD check`, do you see the same messaging as you're getting?

``` r
library(tidyverse)

ap <- available.packages() %>% 
  as_tibble()

ap %>% 
  filter(grepl("CC BY-SA 4.0", License)) %>% 
  count(License, sort = TRUE)
#> # A tibble: 2 x 2
#>   License                         n
#>   <chr>                       <int>
#> 1 CC BY-SA 4.0                   20
#> 2 CC BY-SA 4.0 + file LICENSE     1

ap %>% 
  filter(grepl("CC BY-SA 4.0", License)) %>% 
  pull(Package) %>% 
  unique()
#>  [1] "agridat"       "alakazam"      "anyLib"        "apercu"       
#>  [5] "arnie"         "cetcolor"      "diverse"       "ds4psy"       
#>  [9] "igraphdata"    "inspectr"      "install.load"  "piecepackr"   
#> [13] "rabhit"        "rdi"           "scoper"        "shazam"       
#> [17] "stackoverflow" "stationery"    "tigger"        "unikn"        
#> [21] "webex"
```

<sup>Created on 2019-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

`use_ccby_license()` was added by @njtierney a few months back, in case he wants to comment.

**Comment by kiernann** [comment]
I checked out the [`LICENSE`](https://github.com/PsyTeachR/webex/blob/master/LICENSE) file from the [webex package](https://github.com/PsyTeachR/webex). They use "CC BY-SA 4.0" rather than "CCBY-4.0." I made that change manually and my empty package passed `devtools::check`!

```r
usethis::use_ccby_license(name = "Kiernan Nicholls")

read_lines("DESCRIPTION") %>% 
  str_replace(
    pattern = "License: CCBY-4.0", 
    replacement = "License: CC BY-SA 4.0"
  ) %>% 
  write_lines("DESCRIPTION")

devtools::check()
```

```
── R CMD check results ── issue 0.0.0.9001 ──
Duration: 3s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```

I don't know if there's a meaningful difference in those two strings, but I can open a PR with that change, if needed.

**Comment by jennybc** [comment]
@kiernann Looks like you have identified the likely problem. A PR would be welcome.
