### ISSUE TITLE
testthat: R CMD check should be OK if testthat is not installed

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/usethis#9]
AFAIK packages are expected to `R CMD check` cleanly if suggeted packages, like `testthat` are not installed.

The `testthat.R` template could check if `testthat` is installed, and maybe give a message (if that is supported at all) if not.

**Comment by hadley** [comment]
So something like this:

```R
if (require(testthat)) {
  library({{{ name }}})
  test_check("{{{ name }}}")
}
```

?

**Comment by gaborcsardi** [comment]
Oh, no, I changed my mind on this. It should fail if `testthat` is not available.
