### ISSUE TITLE
use_test() should not assume working directory = top-level

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#90]
If wd is a subdirectory, e.g. `R/` or `vignettes/`, `usethis::use_test()` dutifully creates testing infrastructure right there vs. finding top-level directory first.

**Comment by hadley** [comment]
Presumably I should use `here::here()` everywhere.

I wonder it makes sense to get rid of `base_path()` altogether and assume some function in here that can manually override for testing.
