### ISSUE TITLE
use_pkgdown_travis() should nudge re: GitHub Pages settings

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#907]
Issue reminder to check repo settings:

  * GitHub Pages source should be `gh-pages` branch
  * Any custom domain needs to be entered here as well

**Comment by hadley** [comment]
I think this is probably low value since we're likely to be moving off this workflow in the not-too-distant future.

**Comment by jennybc** [comment]
Are we going to stop using GitHub Pages? Because that's the aspect that has to be done manually. I think this is going to still apply even if we're using GitHub Actions build the site.

**Comment by hadley** [comment]
Oh good point, I did read too quickly — but the custom domain is automated (set `url` in `_pkgdown.yml`), and isn't gh-pages the default?

**Comment by jennybc** [comment]
I think "turning on" GitHub Pages is still something beyond the reach of the API. You have to do it in the browser last time I checked.

**Comment by jennybc** [comment]
Well, that used to be true.

Looks like there are some preview features we could use:

https://developer.github.com/v3/repos/pages/#enable-a-pages-site
