### ISSUE TITLE
Updates to use_cran_comments() template

### ISSUE THREAD

**Issue by dchiu911** [r-lib/usethis#908]
Some suggested updates to `use_cran_comments()`:
1. It appears that the default Travis distribution is now Ubuntu Xenial 16.04
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
Should the template check `.travis.yml` for `dist: trusty` so the ubuntu version is 14.04, or 16.04  otherwise? I see the previous change was 2 years ago so this doesn't happen very often.
2. Change the default "local OS X install" field to "local macOS install" since most builds are post 2016, or detect using something like `sessioninfo::os_name()`?
3. Change default "win-builder (devel and release)" field to "win-builder (devel)" since `devtools::release()` only asks "Have you checked on win-builder (with `check_win_devel()`)?"?

**Comment by hadley** [comment]
The hope is that you'll modify this as necessary for your process, so I did the minimal set of changes that you suggested.
