### ISSUE TITLE
Reduce friction around using roxygen2 + markdown

### ISSUE THREAD

**Issue by batpigandme** [r-lib/usethis#911]
i.e. have `use_roxygen_md()` insert `Roxygen: list(markdown = TRUE)` at the bottom of DESCRIPTION without having to run `roxygen2md::roxygen2md()`

**Comment by jennybc** [comment]
Or was the suggestion to (also) just put this in our default `DESCRIPTION`? @hadley

**Comment by hadley** [comment]
Yeah we should turn it on by default and polish the other function a bit
