### ISSUE TITLE
Feature request: extend use_dev_package() beyond github.com

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#918]
As far as I can tell, right now, `use_dev_package()` assumes that the remote is located at github.com, and it constructs a Remotes entry based on that assumption, e.g. `r-lib/usethis`.

To extend to other situations, could `use_dev_package()` be an additional argument, `remote` with a default of `NULL`? Of course, the default behavior would be the current behavior. A non-NULL `remote` provided to the function could become the entry in Remotes.

I would not think this useful for direct interactive use; my use case is to write a wrapper function for institutional use, for example:

```r
use_package_acme <- function(package) {

  remote <- get_acme_remote(package) # Acme's responsibility

  usethis::use_dev_package(package, remote = remote)
}
```

If you think this worthwhile, I'd be happy to make a PR. Thanks!

**Comment by cderv** [comment]
@ijlyttle I am just curious and hijacking this issue for a question: 
`use_dev_package` adds a depency as Remotes in description. 
How do you add a _acme remote_ using this `Remotes` field ? Can you add a Github Package in the remote field for a package from you GHE server ?

**Comment by ijlyttle** [comment]
The idea would be to use a URL remote - along the lines described in r-lib/remotes#448. Not as powerful as the "standard" GitHub approach, but I think it would get the job done for me :)

**Comment by jennybc** [comment]
Yeah, making a non-github.com remote possibles sounds reasonable to me. Yes, a PR would be welcome.

**Comment by hadley** [comment]
Also related to #970
