### ISSUE TITLE
Add to release checklist: check that README.md and index.md are up-to-date

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#923]

**Comment by hadley** [comment]
Maybe we should have a usethis helper for this too? It would run render `README.Rmd` and `index.Rmd` in a clean session; and then the release bullet would just say to run that function.

**Comment by hadley** [comment]
I've done a PR to devtools to add a more general tool for building Rmds; but I think `build_readme()` covers the most common 95% of cases
