### ISSUE TITLE
Feature: Use badges from shield.io in `use_badges_*` functions

### ISSUE THREAD

**Issue by pat-s** [r-lib/usethis#925]
- Contain the logo of the CI system which makes badges easier to differentiate 
- Contain the OS system which was used for building (only for Circle and Appveyor since Travis provides multiple ones)
- point by default to the master branch

# Preview

[![Travis build status](https://img.shields.io/travis/r-lib/usethis/master?logo=travis)](https://travis-ci.org/r-lib/usethis)
[![AppVeyor build status](https://img.shields.io/appveyor/ci/r-lib/usethis?label=Windows&logo=appveyor)](https://ci.appveyor.com/project/r-lib/usethis)
[![CircleCI build status](https://img.shields.io/circleci/build/gh/r-lib/usethis/master?label=Linux&logo=circle&logoColor=green)](https://circleci.com/gh/r-lib/usethis)

**Comment by hadley** [comment]
See discussion in PR
