### ISSUE TITLE
use_github() can't be used right after create_package()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#93]
I was trying to improve my answer to this, based on feedback from @jimhester:

https://community.rstudio.com/t/procedure-to-create-a-project-for-a-package-destined-for-github/2054/4

But noticed that you can't really do `usethis::create_package()` and then, immediately, in the new package, do `use_github()`.

The yesno about checking Title and Description and the restart of RStudio interfere with each other. The result is that `use_git()` is called but the github repo is never created.

<img width="929" alt="screen shot 2017-10-17 at 1 14 37 pm" src="https://user-images.githubusercontent.com/599454/31687469-2f730cb2-b33e-11e7-967d-e70f05a3e732.png">

**Comment by hadley** [comment]
I've fixed this pretty trivially - now you need to call `use_git()` first.

(Also if you update you'll get a nicer message for `use_github()`)

**Comment by jennybc** [comment]
Yay! Have we ever talked about doing `browseURL("https://github.com/user/repo")` at the end? I don't see a downside, yet feels like we would have done it by now if it was a good idea.
