### ISSUE TITLE
Export render_template()

### ISSUE THREAD

**Issue by GregorDeCillia** [r-lib/usethis#930]
I am currently working on several packages that are somewhat similar to usethis in the sense that they use a lot of parameterized templates. To render those templates, I usually invoke `use_template()` but there are cases where I want to render the templates in the R memory. The reason being that the rendered templates are sent to some REST APIs.

My current workaround is to either

* reimplement `render_template()` based on `whisker::whisker.render()` or
* combine `use_template()` with `readLines()`.

It would be very handy if usethis could add `render_template()` to the exports. It seems to me the API of this function is fairly stable and it could be easily documented alongside `use_template()`

**Comment by hadley** [comment]
I think it's simple enough that it's better for you to reimplement yourself; if anything the function should be exported by whisker, not usethis.
