### ISSUE TITLE
Use better method for hiding build-time dependencies

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#934]
e.g. from @gaborcsardi 

```R
fix_check <- function() {
  R6::R6Class()
}
```

**Comment by jimhester** [comment]
It doesn't even have to be a call, it can just be `R6::R6Class` in any function.

**Comment by hadley** [comment]
I wish I remembered how this related to usethis

**Comment by hadley** [comment]
e.g.

```
  use_dependency("lifecycle", "imports")
  # silence R CMD check NOTE
  roxygen_ns_append("@importFrom lifecycle deprecate_soft")
```

But we now have the tooling for managing namespace declarations in the package doc file, so I don't think implementing this is going to be worth it.
