### ISSUE TITLE
Doc suggestion: link PR vignette from PR helpers manual page

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#938]
I was reading https://usethis.r-lib.org/reference/pr_init.html which unless I missed it doesn't mention https://usethis.r-lib.org/articles/articles/pr-functions.html which I nearly missed, so I'd suggest adding a link.

**Comment by jennybc** [comment]
Good idea! The `pr_*()` helpers (and their docs) were created well before the article was contributed.
