### ISSUE TITLE
Allow vector input in use_package

### ISSUE THREAD

**Issue by smingerson** [r-lib/usethis#949]
Using 1.5.1, I receive the following error:
```
> usethis::use_package(c("tidyselect", "rlang", "Rcpp", "purrr"))
Error in use_dependency(package, type, min_version = min_version) : 
  is_string(package) is not TRUE
# Expected behavior was to add all to Description as Imports.
```
Seems reasonable to either allow a vector input or add a plural variant. Happy to submit a PR for either if desired.

**Comment by cderv** [comment]
Duplicate of #904

It seems from this answer https://github.com/r-lib/usethis/issues/904#issuecomment-542815616 that this function is aim and interactive use when you need to need a new package, one by one.

**Comment by smingerson** [comment]
Thanks for pointing out the previous issue, seems like I did a poor job searching.
