### ISSUE TITLE
FR: Add `browse_file()` to open files in the remote repo

### ISSUE THREAD

**Issue by pat-s** [r-lib/usethis#951]
(or a similar name)

I would like to be able to browse the currently active Rscript of a package on its remote instead of having to open/search for it it manually via the browser.

Maybe _rstudioapi_ has a function to get the current open file? This could be used to glue a url in combination with `browse_github()`.

**Comment by jennybc** [comment]
> Maybe rstudioapi has a function to get the current open file?

Yeah we have already built things out around such functionality with `use_r()`/`use_test()`.

**Comment by pat-s** [comment]
Thanks for the pointer. Maybe you find the approach in #951 useful.

**Comment by tmastny** [comment]
Hey @pat-s! Checkout my R package browse: https://github.com/tmastny/browse. It comes with an RStudio addin and also supports Gitlab and Bitbucket.

**Comment by hadley** [comment]
I'm not 100% sure that this code should live in usethis. As well as @tmastny's package, there's already a button in RStudio:

<img width="252" alt="Screenshot 2020-03-14 at 9 10 24 AM" src="https://user-images.githubusercontent.com/4196/76683631-a640f080-65d3-11ea-8b39-d16646973ff5.png">

**Comment by hadley** [comment]
I'm closing since there are already two existing ways.
