### ISSUE TITLE
use_article("pkg.name") should create vignettes/pkg.name.Rmd (not *-name.Rmd)

### ISSUE THREAD

**Issue by maurolepore** [r-lib/usethis#952]
As a developer of the pkg.name package I would like pkgdown to build the _Get started_ article from vignettes/pkg.name.Rmd.

I expect to create such an article with `usethis::use_article("pkg.name")`. 

But instead I get vignettes/pkg-name.Rmd (__"-" instead of "."__) so pkgdown places my article in _Articles_ not _Get started_.

![image](https://user-images.githubusercontent.com/5856545/70241868-6a290480-1735-11ea-95ad-86316b7c82ff.png)

**Comment by hadley** [comment]
This is a deliberate choice because [R-exts](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-package-vignettes) says:

> To ensure that they can be accessed from a browser (as an HTML index is provided), the file names should start with an ASCII letter and be comprised entirely of ASCII letters or digits or hyphen or underscore.

**Comment by maurolepore** [comment]
Thanks for educating me!
