### ISSUE TITLE
Better error message for malformed usethis.description

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#961]
Might be worthwhile to save to a file and attempt to parse? 

It's also particularly problematic because it causes `create_package()` to fail part way through, leaving you in a malformed state that you just have to blow away.

**Comment by jennybc** [comment]
Any specifics on the nature of this malformed description?

**Comment by hadley** [comment]
Two mistakes so far: 

* Forgetting a closing parenthesis, so `person(...` doesn't parse
* Not using the correct indentation so that one line of `Authors@R` is interpreted as a new field

**Comment by hadley** [comment]
We could also improve the situation by allowing a direct call to `person()` here, rather than being forced to wrap it in a string; `format(person(), style = "R")` generates the code we need.

**Comment by hadley** [comment]
Reprex:

``` r
library(usethis)

options(usethis.description = list("Authors@R" = "person('Hadley', 'Wickham'"))
create_package(tempfile())
#> ✔ Creating '/tmp/RtmpjerEGN/file12f3050812b9d/'
#> ✔ Setting active project to '/private/tmp/RtmpjerEGN/file12f3050812b9d'
#> ✔ Creating 'R/'
#> Error in fmt[[1]]: subscript out of bounds
#> ✔ Setting active project to '<no active project>'
```

<sup>Created on 2020-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
