### ISSUE TITLE
Should check() run document on first call?

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#963]
Currently, if you create a package and then immediately check it, it does not automatically run `document()`. But once you've run `document()` once, `check()` will automatically run it for you. This seems mildly confusing and worth reconsidering.

Probably related to #927

**Comment by jennybc** [comment]
This feels more like a devtools issue.

**Comment by hadley** [comment]
It's really to do with how `usethis::create_package()` initialises the package so I think it belongs here.

**Comment by condwanaland** [comment]
This trips me up all the time when first creating a package - would strongly be in favor of `check()` running it on first call
