### ISSUE TITLE
Conclude (as in "remove") the use_azure_pipelines() experiment

### ISSUE THREAD

**Issue by okhoma** [r-lib/usethis#964]
Running `use_azure_pipelines()` fails if the "project does not have a GitHub remote configured". This should not be a requirement for azure_pipelines. The code might as well be from Azure DevOps or any other repo, just use Azure Pipelines for CI/CD.

**Comment by jennybc** [comment]
Any thoughts @jimhester? Was that sort of just ... mirroring your usage and experience?

I also note that, since we've decided to concentrate more on GitHub Actions, the Azure stuff here ... may very well sort of stall (?).

**Comment by jimhester** [comment]
I think we should remove the azure pipelines code from usethis.

As to checking for GitHub I was following the conventions used in the travis and all other CI code currently in usethis, e.g. https://github.com/r-lib/usethis/blob/b2e894eb6d1d7f3312a783db3bb03a7cc309ba61/R/ci.R#L25

**Comment by jennybc** [comment]
Thanks @jimhester.

> I think we should remove the azure pipelines code from usethis.

This confirms what I suspected.

**Comment by hadley** [comment]
These seem to have been removed already.

**Comment by jimhester** [comment]
Removed in https://github.com/r-lib/usethis/pull/1036 for future reference
