### ISSUE TITLE
Don't install README pre-commit hook if R package precommit is installed by default

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/usethis#965]
`usethis::use_readme_rmd()` initialises a bare git pre-commit hook (i.e. write a simple script to .git/hooks/pre-commit) when git is used. However, users who use the pre-commit framework (e.g. via https://github.com/lorenzwalthert/precommit) at the same time may not want this hook to be initlized because they want to use the pre-commit framework exclusively for managing hooks to avoid friction.

Hence, I propose that `usethis::use_readme_rmd()` exposes an argument `add_git_hook` defaulting to `!rlang::is_installed("precommit")`. This way, the hook only get's initiated if {precommit} is not installed. The assumption here is that people who create a new README and have precommit installed most likely want to use equivalent of usethis' precommit hook from the {precommit} package. If that's not the case, the can still override the default argument and set `add_git_hook` to `TRUE`.  

This proposal alleviates problems mentioned in your [previous statement ](https://github.com/r-lib/usethis/issues/849#issuecomment-514266345) that the existing hook is already a source of complaint and friction and hook management is generally out of the scope of {usethis}. Would you be open to review a PR that implements this?

**Comment by jennybc** [comment]
I don't want to tether usethis's logic to the installation status of precommit, which is a cool package but, I think, not widely used. But I would take a PR that just adds an argument to control the addition of the git hook. That gives us another place to hang to some documentation around this issue and, perhaps, we could even consider an interactive question, the way we often do for git commits.

**Comment by hadley** [comment]
Closing since we'd accept a PR along the lines outlined by @jennybc, but we're not planning to implement ourselves.
