### ISSUE TITLE
usethis::use_pkgdown_travis() calling usethis::use_travis()?

### ISSUE THREAD

**Issue by jrosen48** [r-lib/usethis#966]
Thanks for such a, well, useful package.

Using the latest development version, I ran `usethis::use_pkgdown_travis()`, which worked, and provided code to paste to a `.travis.yml` file. I had not run `usethis::use_travis()` first, and so this file wasn't yet existant. Would it make sense to provide a warning/note about the need to:

- run `usethis::use_travis()` before running `usethis::use_pkgdown_travis()`
- create the file `.travis.yml`?

Thanks!

**Comment by hadley** [comment]
We're moving away from `use_pkgdown_travis()` in favour of github actions, so this is no longer relevant.
