### ISSUE TITLE
use_directory should return a directory that I can use

### ISSUE THREAD

**Issue by slyrus** [r-lib/usethis#967]
The docs for use_directory state: "use_directory()` creates a directory (if it does not already exist) in the project's top-level directory."

It would be great if I could do something like:

```
my_dir <- usethis::use_directory("data")
write.csv(file = file.path(my_dir, "somefile.csv"))
```
And have the file appear in "the right place". By the right place I mean the data directory at the top level of my package, whether I'm using devtools::load_all, devtools::install, R CMD INSTALL, etc....

In particular, I want this to work from code that is called via a .onLoad function.

Maybe there's a better way to do this, but I haven't found it yet.

**Comment by jennybc** [comment]
I would avoid creating a load-time dependency on usethis, which is really meant to be a package to aid your *development* of a package.

I really like [`fs::path_package()`](https://fs.r-lib.org/reference/path_package.html) for building paths that work with installed and dev versions of a package..fs is a much more suitable package for you to put in Imports anyway.

**Comment by slyrus** [comment]
Oh, thanks for the tip. I'll check that out. Just curious but how is _my development_ of a package different from others use of a package? Or, why the distinction? Did I miss a warning about not using usethis in user-focused code? Sorry for the annoying question but I sense a recurring theme in exploring the R universe that goes like "hey, this looks useful!" "Oh, sure, but you're not really supposed to use/do that." Thanks again!

**Comment by jennybc** [comment]
I use usethis to help me get the right files, in the right places, etc. as I develop a package. Or to help me manage pull request workflows. All interactive, development tasks.

But for the most part, would not use usethis in the actual package code.

Unless, of course, I'm working on a package with similar goals, in which case it makes total sense to Import usethis. Some people/orgs do this when they want to create an internal variant of usethis, to promote consistent practices across all the packages, analyses, apps etc. developed within an organization.

**Comment by slyrus** [comment]
Perhaps I'm misusing fs::path_package (and 1) perhaps this is the wrong forum for this and 2) perhaps this is just a fundamentally broken idea) but I'm trying to use fs::path_package to give me a filename that I can write to at package load time. The various approaches I've tried all fail for various reasons but the fs::path_package approach fails with an error that the file does not exist. Yeah, that's the whole point :) Let me know if you have any suggestions and/or if we should take this discussion elsewhere.

**Comment by jennybc** [comment]
This is better suited to https://community.rstudio.com.

But yeah, writing into the directory of the installed package at load time, if I understand you correctly, seems sort of 😬. Is there no other location that seems suitable? Like session temp dir or something determined with the help of <https://cran.r-project.org/web/packages/rappdirs/index.html>?

I think `fs::path_package()` should work, though, so it might be worth creating a reprex for the problem you are seeing.
