### ISSUE TITLE
`use_dev_package` should handle more remote types

### ISSUE THREAD

**Issue by antoine-sachet** [r-lib/usethis#970]
`use_dev_package` can only handle dev packages installed from github remotes. 

A simple change to the `package_remote` function would make `use_dev_package` work with any remote type that has a `Remotes` field of the form `{RemoteType}::{RemoteUsername}/{RemoteRepo}`.

In particular, this would cover package dependencies from `GitLab` and `Bitbucket`.

Something like this:

```R
package_remote <- function(package) {
  desc <- desc::desc(package = package)
  remote_info <- desc$get(c("RemoteType", "RemoteUsername", "RemoteRepo"))
  
  supported_remotes <- c("github", "gitlab", "bitbucket")
  is_valid_remote <- 
    rlang::is_string(remote_info[["RemoteType"]]) && 
    remote_info[["RemoteType"]] %in% supported_remotes
  
  if (!is_valid_remote) {
    ui_stop("{ui_value(package)} was not installed from a supported remote type.")
  }
  
  glue::glue_data(as.list(remote_info), "{RemoteType}::{RemoteUsername}/{RemoteRepo}")
}
```

I don't really see a reason to restrict the remotes to github, gitlab and bitbucket though. I would just check that `RemoteType`, `RemoteUsername` and `RemoteRepo` are not `NA`.

The code above would add an explicit `github::` prefix to github remotes but this could obviously be avoided. IMO `usethis` is github-centric enough as it is, so I would leave the prefix for clarity.

This is related to #293 to the extent that it is about extending the functionalities beyond github, but this is a simpler (and probably more common) use case.

**Comment by hadley** [comment]
Do you want to do a PR for this?

**Comment by antoine-sachet** [comment]
@hadley Sure, done.
