### ISSUE TITLE
FR: export functions to facilitate tests

### ISSUE THREAD

**Issue by aaronpeikert** [r-lib/usethis#973]
I am using the `usethis` package as a basis for [another package](https://www.github.com/aaronpeikert/repro) (it is btw a great and remarkably easy to extend `usethis`). However as I started to write tests that involve testing whether files are created etc., I had to copy the test helper from usethis [(tests/testthat/helper.R)](https://github.com/r-lib/usethis/blob/b2e894eb6d1d7f3312a783db3bb03a7cc309ba61/tests/testthat/helper.R) into my package. It would be great if you could export them as functions as they are really useful for extending `usethis`.

**Comment by aaronpeikert** [comment]
https://github.com/r-lib/usethis/issues/308#issuecomment-372152249

**Comment by jennybc** [comment]
Are you talking about `scoped_temporary_thing()` and friends?

**Comment by aaronpeikert** [comment]
Yes exactly. Just `scoped_temporary_thing()` actually --- I should have been more clear here.

**Comment by jennybc** [comment]
It’s hard to know what to do here. I understand your point but also don’t want to agree to some contract about such an internal function. You inlining a version of this In your package might actually be the right answer.

**Comment by aaronpeikert** [comment]
Yeah, it's tricky. Maybe one could consider putting them into the R/ directory without exporting them (afaik CRAN Checks do not check if the testing code uses unexported functions, so I could still use them). That way, I do not need to inline your functions, and you do not have to export them.
However, I can certainly live with inlining them so feel free to close.

**Comment by jennybc** [comment]
We could certainly define nontrivial test helpers below `R/` and sequester in a single file. That would support `:::` use by others and/or inlining that whole file. I can't think of a downside.

**Comment by hadley** [comment]
I don't think we should be exporting these functions yet. If you want to use them in your own package, just copy and paste them.
