### ISSUE TITLE
pr_pause() should have some way to override check

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#975]
So that if you've accidentally made some changes in the wrong branch (but haven't committed them), you can switch to the correct branch without using the command line.

**Comment by jennybc** [comment]
Yeah related to what I say here https://github.com/r-lib/usethis/issues/950#issuecomment-565554459:

> I think (several of?) the checkers in the PR flow should probably present a "Proceed? Y/N" choice when they encounter a non-default situation, instead of erroring unconditionally.
