### ISSUE TITLE
Additional configuration file setup: edit_ bash*, edit_odbc_ini, edit_netrc

### ISSUE THREAD

**Issue by overdodactyl** [r-lib/usethis#978]
Would additional edit_* functions for configuration files be in scope for `usethis`?

I have in mind:

* `edit_odbc_ini()`

* `edit_bash_profile()`

* `edit_bashrc()`

* `edit_netrc()`

I'm happy to contribute the changes if they are.

**Comment by hadley** [comment]
These seem a bit too general for usethis, sorry.
