### ISSUE TITLE
Make docs more clear that use_description() works in a non-package project

### ISSUE THREAD

**Issue by JohnCoene** [r-lib/usethis#979]
So I recently learned that one can include a [DESCRIPTION file outside of packages](https://twitter.com/bradleyboehmke/status/1215703648384225281), it's something I perceive as good practice.

![image](https://user-images.githubusercontent.com/7833796/72242007-95cac480-35e8-11ea-9417-00ed19194fa5.png)

However, to the best of my knowledge, usethis does not currently support that.

```r
r$> usethis::use_description()                                                                                
Error: Path '/my/current/directory/' does not appear to be inside a project or package.
In addition: Warning message:
In path_file(base_path) : restarting interrupted promise evaluation
```

**Comment by TylerGrantSmith** [comment]
I had the same concern.  Check out the development version `remotes::install_github("r-lib/usethis")`, it has been fixed with `usethis::use_description(check_name = F)`

**Comment by jennybc** [comment]
Yup 👆 is true.

It would be good to make this use case (not an R package) more clear in the `use_description()` docs and in the NEWS entry describing the addition of `check_name`. I'm going to leave this open and flag it as a good first contribution for tidyverse dev day.

Remember to change the docs in the oxygen comment and to run `document()` after, so the `.Rd` file is updated.
