### ISSUE TITLE
question: import UQ/UQS/!!/!!! in tidy_eval.R template?

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#98]
I have been using the tidyeval framework in some of my packages and I have found it useful to import the unquoting operators, for internal package use,  something like this:

```
#' @importFrom rlang UQ !!
#' @importFrom rlang UQS !!!
```

As usual, I don't _really_ know what I'm doing - but could this be useful for the `tidy_eval.R` template?

If so, happy to make a PR.

**Comment by hadley** [comment]
You should import `UQ` and `UQS` to avoid R CMD warnings. A PR would be great!
