### ISSUE TITLE
Add a type in use_package to remove a dependency

### ISSUE THREAD

**Issue by jplecavalier** [r-lib/usethis#980]
This is a very minor possible enhancement for the `use_package` function.

In the first release of my package, I had an external dependency on the `igraph` package, so I could easily add this dependency with
```
usethis::use_package("igraph")
```
Since I always try to minimize the number of external packages I'm relying on, I was able to replace the dependency to `igraph` with a very tiny function inside my own package (I do not export it, users won't need it). Since I don't need the dependency on the `igraph` package again, it is best practice to remove it in the `DESCRIPTION` file of my package. I know it's extremely easy to just remove the line that states the dependency to `igraph`, but I was wondering if we should include this possibility in `usethis`. We could implement it as
```
usethis::use_package("igraph", type=NULL)
``` 
or
```
usethis::use_package("igraph", type=FALSE)
``` 
or
```
usethis::use_package("igraph", type="None")
```

What do you think?

**Comment by jennybc** [comment]
My initial reaction is "seems unnecessary". I think the value proposition for usethis functions that add/modify setup is that they look after fiddly details that are annoying to remember. According to that mentality, I'm not sure removing a dependency qualifies, because you just delete a line in DESCRIPTION. (Or removal is more complicated, but then we couldn't address that with `use_package()` anyway.)

**Comment by jplecavalier** [comment]
@jennybc - No problem, it was only a suggestion. Feel free to close the issue!

**Comment by asadow** [comment]
> I looked for something like this, because I didn't know that I only needed to delete a line in the DESCRIPTION file. Therefore I thought I could break something. Adding an option to remove the dependency would've made me feel safe. But maybe the process of figuring this out is wanted?

Me too.

**Comment by jennybc** [comment]
I added a sentence to the docs.

> But maybe the process of figuring this out is wanted?

But, basically, I think the answer to that is "yes". `use_package()` is a convenience helper, but I would hope that folks still develop an understanding of the `DESCRIPTION` file.
