### ISSUE TITLE
Revisit the name cat_line()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#981]
Now that messaging routes through `rlang::inform()`, the function name `cat_line()` is somewhat misleading. This is an internal matter, but it's something anyone developing in usethis might encounter.

**Comment by jennybc** [comment]
Address this TODO at the same time:

https://github.com/r-lib/usethis/blob/0a0d98ddce00e9bf38f86b2c0ad5557cb688bf1f/R/ui.R#L275-L280

**Comment by hadley** [comment]
Maybe just `ui_inform()` now?

I also wonder if `ui_yeah()`/`ui_nope()` should just use `inform()` directly. Otherwise when `options(usethis.quiet = TRUE)` you get the prompt for action, but you don't know what it's for.
