### ISSUE TITLE
use_dependency() should check for existing imports

### ISSUE THREAD

**Issue by jeroen** [r-lib/usethis#99]
E.g. when using:

```r
use_dependency("roxygen2", "Suggests")
```

on a package that already imports/depends `roxygen2` it will give a check error:

```
Package listed in more than one of Depends, Imports, Suggests, Enhances:
  ‘roxygen2’
```

**Comment by hadley** [comment]
What should it do? I think maybe it would ignore with a warning if a "downgrade", otherwise it would upgrade (i.e. existing imports -> suggests gives warning and does nothing; suggests -> imports removes from suggests and adds to imports).

**Comment by jeroen** [comment]
Yes that is what I would expect. Maybe just a message with *Package `roxygen` already imported, DESCRIPTION file unchanged.*
