### ISSUE TITLE
`check_is_package` says git repos are R projects, which is confusing

### ISSUE THREAD

**Issue by erindb** [r-lib/usethis#992]
The function `check_is_package` inside `R/proj.R` assumes that anything that's a git repo is also an R project (specifically, line 168 in `R/proj.R`). And it doesn't explain to the user what it found that makes it think it's an R project. So it was telling me a directory was an R project, I was looking for a `.Rproj` file and not finding one, and being really confused.

I'm all for warning people about making projects where there's already a `.git`, but can we have a message explaining what's happening? Can it say specifically what it found? <3 Thank you!!

**Comment by hadley** [comment]
This is already documented in `proj_get()`, and unfortunately I don't think it's worth being noisier about how it finds the root because most of the time it works the way you expect. I think unfortunately this is just something you might need to learn through experience.

**Comment by jennybc** [comment]
For @erindb and anyone else who might come by, `here::dr_here()` is a chatty way to understand why a particular directory is being recognized as a project by rprojroot (which is what powers the more user-friendly package here and all the project-recognizing machinery in usethis).

``` r
> here::dr_here()
here() starts at /Users/jenny/rrr/usethis, because it contains a file matching `[.]Rproj$` with contents matching `^Version: ` in the first line
```
