### ISSUE TITLE
use_github_action fails due to malformed URLs of example workflows

### ISSUE THREAD

**Issue by fabian-s** [r-lib/usethis#993]
```r
usethis::use_github_action("pkgdown")
## Error in file(con, "r") : 
##  cannot open the connection to 'https://raw.githubusercontent.com/r-lib/actions/master/examples/pkgdown'
```

Bug is at:

https://github.com/r-lib/usethis/blob/4194fd69179ab654b73ab5e2e165963bed5ad877/R/github-actions.R#L63

This needs to be:

`glue("https://raw.githubusercontent.com/r-lib/actions/master/examples/{name}.yaml")`  
not  
`glue("https://raw.githubusercontent.com/r-lib/actions/master/examples/{name}")`

**Comment by hadley** [comment]
Looks like `use_github_action()` has been refactored and the bug fixed, since you filed this issue.
